force-app/main/default/objects/Account_Plan_Status_Code__c/Account_Plan_Status_Code__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Error,Warning message handler for Account Plan</description>
    <label>Account Plan Status Code</label>
</CustomObject>

force-app/main/default/objects/AcctPlan_Questionnaire_Template__c/AcctPlan_Questionnaire_Template__c.object-meta.xml
<CustomObject>
    <label>AcctPlan Questionnaire Template</label>
    <nameField>
        <displayFormat>QT-{000000}</displayFormat>
        <label>AcctPlan Questionnaire Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctPlan Questionnaire Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlan_Questionnaire_Template__c/fields/Answer_Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Answer_Field_Type__c</fullName>
    <label>Answer Field Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes or No</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctPlan_Questionnaire_Template__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Opportunity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctPlan_Questionnaire_Template__c/fields/Product_Label__c.field-meta.xml
<CustomField>
    <fullName>Product_Label__c</fullName>
    <label>Product Label</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Business Click</fullName>
            </value>
            <value>
                <fullName>Liquidity Management</fullName>
            </value>
            <value>
                <fullName>L/G transaction with Government sector</fullName>
            </value>
            <value>
                <fullName>L/G issuing : Aval/Acceptance</fullName>
            </value>
            <value>
                <fullName>L/G issuing : International bank guarantee or Standby L/C</fullName>
            </value>
            <value>
                <fullName>L/G issuing : Shipping guarantee</fullName>
            </value>
            <value>
                <fullName>Request L/G from Buyer</fullName>
            </value>
            <value>
                <fullName>Normal business transaction : Credit risk protection</fullName>
            </value>
            <value>
                <fullName>Normal business transaction : Other revenue/ expenditure</fullName>
            </value>
            <value>
                <fullName>Insurance : Credit life insurance</fullName>
            </value>
            <value>
                <fullName>Insurance : Non credit life insurance</fullName>
            </value>
            <value>
                <fullName>Insurance : Non life insurance</fullName>
            </value>
            <value>
                <fullName>Balance sheet management : Liability management</fullName>
            </value>
            <value>
                <fullName>Balance sheet management : Investment &amp; Capital expenditure plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctPlan_Questionnaire_Template__c/fields/SEQ__c.field-meta.xml
<CustomField>
    <fullName>SEQ__c</fullName>
    <label>SEQ</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AcctPlan_Questionnaire_Template__c/fields/Sub_Domain__c.field-meta.xml
<CustomField>
    <fullName>Sub_Domain__c</fullName>
    <label>Sub Domain</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Contingent Liability</fullName>
            </value>
            <value>
                <fullName>Hedging</fullName>
            </value>
            <value>
                <fullName>Internet Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctPlan_Questionnaire_Template__c/fields/Sub_Segment_SEQ__c.field-meta.xml
<CustomField>
    <fullName>Sub_Segment_SEQ__c</fullName>
    <label>Sub Segment SEQ</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AcctPlanQuestionnaire__c/AcctPlanQuestionnaire__c.object-meta.xml
<CustomObject>
    <label>Account Plan Questionnaire</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Account Plan Questionnaire Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Questionnaire</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanQuestionnaire__c/fields/AcctPlanWallet__c.field-meta.xml
<CustomField>
    <fullName>AcctPlanWallet__c</fullName>
    <label>Account Plan Wallet</label>
    <referenceTo>AcctPlanWallet__c</referenceTo>
    <relationshipLabel>Account Plan Questionnaire</relationshipLabel>
    <relationshipName>Account_Plan_Questionnaire</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctPlanQuestionnaire__c/fields/Answer_Type__c.field-meta.xml
<CustomField>
    <fullName>Answer_Type__c</fullName>
    <label>Answer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes or No</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctPlanQuestionnaire__c/fields/isStandard__c.field-meta.xml
<CustomField>
    <fullName>isStandard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isStandard</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AcctPlanQuestionnaire__c/fields/Product_Label__c.field-meta.xml
<CustomField>
    <fullName>Product_Label__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctPlanQuestionnaire__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Question</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AcctPlanQuestionnaire__c/fields/Question_TH__c.field-meta.xml
<CustomField>
    <fullName>Question_TH__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Question TH</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AcctPlanQuestionnaire__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Collection Method</fullName>
            </value>
            <value>
                <fullName>Export Collection Method</fullName>
            </value>
            <value>
                <fullName>Collection Questionnaire</fullName>
            </value>
            <value>
                <fullName>Payment Questionnaire</fullName>
            </value>
            <value>
                <fullName>Domestic Payment Method</fullName>
            </value>
            <value>
                <fullName>Payment Method Import</fullName>
            </value>
            <value>
                <fullName>Liquidity Management</fullName>
            </value>
            <value>
                <fullName>L/G issuing</fullName>
            </value>
            <value>
                <fullName>L/G Project</fullName>
            </value>
            <value>
                <fullName>AVAL &amp; Acceptance</fullName>
            </value>
            <value>
                <fullName>International bank section1</fullName>
            </value>
            <value>
                <fullName>International bank section2</fullName>
            </value>
            <value>
                <fullName>Shipping guarantee</fullName>
            </value>
            <value>
                <fullName>Request L/G</fullName>
            </value>
            <value>
                <fullName>FX Hedging Behavior</fullName>
            </value>
            <value>
                <fullName>FX Hedging experience</fullName>
            </value>
            <value>
                <fullName>Credit protection risk</fullName>
            </value>
            <value>
                <fullName>Non credit life insurance</fullName>
            </value>
            <value>
                <fullName>Non Life insurance</fullName>
            </value>
            <value>
                <fullName>Insurance Internet Banking</fullName>
            </value>
            <value>
                <fullName>Credit life insurance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctPlanQuestionnaire__c/fields/Sub_Domain__c.field-meta.xml
<CustomField>
    <fullName>Sub_Domain__c</fullName>
    <description>ใช้สำหรับ Step4</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ใช้สำหรับ Step4</inlineHelpText>
    <label>Sub Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctPlanQuestionnaire__c/fields/Sub_Segment_SEQ__c.field-meta.xml
<CustomField>
    <fullName>Sub_Segment_SEQ__c</fullName>
    <label>Sub Segment SEQ</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AcctPlanWallet__c/AcctPlanWallet__c.object-meta.xml
<CustomObject>
    <label>Account Plan Wallet</label>
    <nameField>
        <displayFormat>Wallet-{000000}</displayFormat>
        <label>Account Plan Wallet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Wallet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Question ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DomainIVQuestionnaireEdittableCtrl.cls
public class DomainIVQuestionnaireEdittableCtrl extends EditableList {
    
    public String walletId {get;set;}
    public String typeofFX {get;set;}
    public String TypeofQuestionnaire {get;set;}
    public boolean isBehavior {get;set;}
    public boolean isEXP {get;set;}
    public boolean isRisk {get;set;}
    public List<AcctPlan_Questionnaire_Template__c> InitiateQ {get;set;}
    public Map<String,List<AcctPlanQuestionnaire__c>> QuestionnaireMap {get;set;}
    public List<AcctPlanQuestionnaire__c> QuestionnaireList {get;set;}
    public List<AcctPlan_Questionnaire_Template__c> QTemplateList {get;set;}
    public Map<String,List<AcctPlan_Questionnaire_Template__c>> QTemplateMap;
    public DomainIVQuestionnaireEdittableCtrl(ApexPages.StandardController stdController) {
    super(stdController);
    walletId = ApexPages.currentPage().getParameters().get('walletid');
    typeofFX = ApexPages.currentPage().getParameters().get('type');
        isBehavior =false;
         isRisk =false;
         isEXP =false;
        
        if(typeofFX=='behavior'){
            isBehavior = true;
           TypeofQuestionnaire = 'FX Hedging Behavior';
        }else if(typeofFX=='exp'){
            isEXP = true;
           TypeofQuestionnaire = 'FX Hedging experience';
        }else if (typeofFX=='risk'){
            isRisk = true;
            TypeofQuestionnaire = 'Credit protection risk';
        }
        
        if(walletid !=null){
                QuestionnaireList = AccountPlanUtilities.QueryQuestionnaireByWalletID(walletid);
                //Collection all Questionnaires
                     for(AcctPlanQuestionnaire__c question : QuestionnaireList){
                         if(question.Segment__c ==TypeofQuestionnaire){
                           this.childList.add(question); 
                           
                         }
                     }
        
        
        //FX Hedging Behavior Questionnaire - Initiate
             
                
                  if(this.childList.size()==0){
                       QTemplateList = AccountPlanWalletUtilities.queryQuestionnaireTemplate('Domain IV');
                        QuestionnaireMap = new Map<String,List<AcctPlanQuestionnaire__c>>();
                        QTemplateMap = new Map<String,List< AcctPlan_Questionnaire_Template__c> >();
                      
                      
                         for(AcctPlan_Questionnaire_Template__c QT : QTemplateList){
                                 String Segment = QT.Segment__c;
                                 if(QTemplateMap.containsKey(Segment)){
                                     QTemplateMap.get(Segment).add(qt);
                                 }else{
                                    List< AcctPlan_Questionnaire_Template__c>  QTList = new List< AcctPlan_Questionnaire_Template__c>();
                                     QTList.add(qt);
                                     QTemplateMap.put(Segment,QTList);
                                     
                                 }
                                 
                             }
                      for(AcctPlan_Questionnaire_Template__c qt : QTemplateMap.get(TypeofQuestionnaire)){
                          AcctPlanQuestionnaire__c question = new AcctPlanQuestionnaire__c ();
                          question.SEQ__c = qt.SEQ__c;
                          question.Question_TH__c = qt.Question_TH__C;
                          question.Question__c = qt.Question__c;
                          question.isStandard__c = true;
                          question.Opportunity__c = qt.Opportunity__c;
                          question.Segment__c = TypeofQuestionnaire;
                          question.AcctPlanWallet__c = walletid;
                          question.Product_Label__c = qt.Product_Label__c;
                          question.Sub_Domain__c = qt.Sub_Domain__c;
                          question.Sub_Segment_SEQ__c = qt.Sub_Segment_SEQ__c;
                          question.Answer_Type__c = qt.Answer_Field_Type__c;
                             
                          this.childList.add(question);
                         
                      }
                      
                  }

        }        
      
        
  }
  
  
    /*
   * This method is necessary for reference on the Visualforce page, 
   * in order to reference non-standard fields.
   */
  public List<AcctPlanQuestionnaire__c > getChildren()
  {

    return (List<AcctPlanQuestionnaire__c >)childList;
  }

  public override sObject initChildRecord()
  {
    AcctPlanQuestionnaire__c  child = new AcctPlanQuestionnaire__c ();
    // Can either use mysObject or acct here
    
    child.Segment__c = TypeofQuestionnaire;
    child.AcctPlanWallet__c = walletid;
    child.SEQ__c = getChildren().size()+1;
    return child;
  }
    
    
    public  void checkportion(){

        try{
       
            super.save();
              //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Save Successful.'));
            ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.CONFIRM ,Account_Plan_Status_Code__c.GetValues('9001').Status_Message__c));
        
        }catch(Exception e){
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        } 
        
    }
    // Fix Refresh
    public override  void  refresh(){
          removeChildList.clear();
          childList.clear();
         
             QuestionnaireList = AccountPlanUtilities.QueryQuestionnaireByWalletID(walletid);
            for(AcctPlanQuestionnaire__c question : QuestionnaireList){
                if(question.Segment__c == TypeofQuestionnaire){
                        this.childList.add(question);  
                      }
            }

    }
    

}