force-app/main/default/objects/Campaign/fields/RTL_Campaign_Code_10_digits__c.field-meta.xml
<CustomField>
    <fullName>RTL_Campaign_Code_10_digits__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Campaign Code (10-digits)</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/RTL_Campaign_Code_9_digits__c.field-meta.xml
<CustomField>
    <fullName>RTL_Campaign_Code_9_digits__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Campaign Code (9-digits)</label>
    <length>9</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/RTL_Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>RTL_Campaign_Type__c</fullName>
    <label>Campaign Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exclusive</fullName>
            </value>
            <value>
                <fullName>Local Exclusive</fullName>
            </value>
            <value>
                <fullName>Mass</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Exclusive_Campaign.recordType-meta.xml
<RecordType>
    <fullName>Exclusive_Campaign</fullName>
    <active>true</active>
    <description>Exclusive campaign in child level</description>
    <label>Exclusive Campaign</label>
</RecordType>

force-app/main/default/objects/Campaign/recordTypes/Master_Campaign.recordType-meta.xml
<RecordType>
    <fullName>Master_Campaign</fullName>
    <active>true</active>
    <description>Master campaign for Retail campaign (must create the master first)</description>
    <label>Master Campaign</label>
</RecordType>

force-app/main/default/classes/CampaignReportControllerTest.cls
@isTest
public class CampaignReportControllerTest {
	@isTest
    static void test(){
        TestUtils.createAppConfig();
        String master = [SELECT Id, Name From recordtype where developername = 'Master_Campaign' LIMIT 1].Id;
        String exclusive = [SELECT Id, Name From recordtype where developername = 'Exclusive_Campaign' LIMIT 1].Id;
        Campaign c1 = new Campaign();
        c1.RTL_Campaign_Type__c = 'Mass';
        c1.Name = 'This is a Campaign';
        c1.RecordTypeId = master;
        c1.RTL_Campaign_Code_9_digits__c = 'M11111111';
        insert c1;
        /*
         Campaign c2 = new Campaign();
        c2.RTL_Campaign_Type__c = 'Mass';
        c2.Name = 'This is a Campaign';
        c2.RecordTypeId = master;
        c2.RTL_Campaign_Code_10_digits__c = '1234567890';
        insert c;
*/
        CampaignReportController.getCampaignList();
    }
    
}