force-app/main/default/objects/Case/fields/Call_Log_ID__c.field-meta.xml
<CustomField>
    <fullName>Call_Log_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Call Log ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Call_Number__c.field-meta.xml
<CustomField>
    <fullName>Call_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Call Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Call_Start_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Call_Start_Datetime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Call Start Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <label>Journey</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Interest / Inquiry</fullName>
            </value>
            <value>
                <fullName>Apply / Approve</fullName>
            </value>
            <value>
                <fullName>After Used</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Problem_Type__c.field-meta.xml
<CustomField>
    <fullName>Problem_Type__c</fullName>
    <label>Problem Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Failure - ไม่ได้รับบริการในสิ่งที่ลูกค้าต้องการ</fullName>
            </value>
            <value>
                <fullName>Delay - ได้รับบริการ แต่ช้า</fullName>
            </value>
            <value>
                <fullName>Quality/Suitability - ได้รับบริการ แต่ลูกค้าขอให้ตรวจสอบ</fullName>
            </value>
            <value>
                <fullName>Quality/Suitability - ได้รับบริการ แต่ลูกค้าไม่พอใจ</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SMS_Code_Resolution_1__c.field-meta.xml
<CustomField>
    <fullName>SMS_Code_Resolution_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SMS Code Resolution 1</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SMS_Code_Resolution_2__c.field-meta.xml
<CustomField>
    <fullName>SMS_Code_Resolution_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SMS Code Resolution 2</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SMS_Code_Resolved__c.field-meta.xml
<CustomField>
    <fullName>SMS_Code_Resolved__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SMS Code (Resolved)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/Service_Type_Matrix__c.object-meta.xml
<CustomObject>
    <label>Service Type Matrix</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Service Type Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Type Matrixs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Journey</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Problem_Type__c.field-meta.xml
<CustomField>
    <fullName>Problem_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Problem Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Resolution_1__c.field-meta.xml
<CustomField>
    <fullName>Resolution_1__c</fullName>
    <label>Resolution 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IT ดำเนินการแก้ไขระบบ</fullName>
            </value>
            <value>
                <fullName>ปรับปรุงการ Set Up ให้ถูกต้อง</fullName>
            </value>
            <value>
                <fullName>ชีแจงข้อมูลที่ถูกต้องให้ลูกค้ารับทราบ</fullName>
            </value>
            <value>
                <fullName>เจ้าหน้าที่แก้ไขรายการให้ถูกต้อง</fullName>
            </value>
            <value>
                <fullName>ปรับปรุง/แก้ไขรายการให้ลูกค้า</fullName>
            </value>
            <value>
                <fullName>แนะนำให้ลูกค้ารับทราบ</fullName>
            </value>
            <value>
                <fullName>ปรับปรุงเงินคืน</fullName>
            </value>
            <value>
                <fullName>ปรับปรุงคะแนนคืน</fullName>
            </value>
            <value>
                <fullName>ยืนยันรายการปกติ</fullName>
            </value>
            <value>
                <fullName>ดำเนินการตามที่ลูกค้าร้องขอ</fullName>
            </value>
            <value>
                <fullName>แก้ไขปัญหาแล้ว ติดต่อลูกค้าไม่ได้ ส่ง SMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Resolution_2__c.field-meta.xml
<CustomField>
    <fullName>Resolution_2__c</fullName>
    <label>Resolution 2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IT ดำเนินการแก้ไขระบบ</fullName>
            </value>
            <value>
                <fullName>ปรับปรุงการ Set Up ให้ถูกต้อง</fullName>
            </value>
            <value>
                <fullName>ชีแจงข้อมูลที่ถูกต้องให้ลูกค้ารับทราบ</fullName>
            </value>
            <value>
                <fullName>เจ้าหน้าที่แก้ไขรายการให้ถูกต้อง</fullName>
            </value>
            <value>
                <fullName>ปรับปรุง/แก้ไขรายการให้ลูกค้า</fullName>
            </value>
            <value>
                <fullName>แนะนำให้ลูกค้ารับทราบ</fullName>
            </value>
            <value>
                <fullName>ปรับปรุงเงินคืน</fullName>
            </value>
            <value>
                <fullName>ปรับปรุงคะแนนคืน</fullName>
            </value>
            <value>
                <fullName>ยืนยันรายการปกติ</fullName>
            </value>
            <value>
                <fullName>ดำเนินการตามที่ลูกค้าร้องขอ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>PTA Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RBG</fullName>
            </value>
            <value>
                <fullName>SBG</fullName>
            </value>
            <value>
                <fullName>WBG</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Service_Level1__c.field-meta.xml
<CustomField>
    <fullName>Service_Level1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Level1</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Service_Level2__c.field-meta.xml
<CustomField>
    <fullName>Service_Level2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Level2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Service_Level3__c.field-meta.xml
<CustomField>
    <fullName>Service_Level3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Level3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Service_Level4__c.field-meta.xml
<CustomField>
    <fullName>Service_Level4__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Level4</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Service_Template__c.field-meta.xml
<CustomField>
    <fullName>Service_Template__c</fullName>
    <label>Service Template</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>CardProduct</fullName>
            </value>
            <value>
                <fullName>DepositWithdraw</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>MoneyTransfer</fullName>
            </value>
            <value>
                <fullName>CheckInvalidTransfer</fullName>
            </value>
            <value>
                <fullName>BillPayTopup</fullName>
            </value>
            <value>
                <fullName>CreditService</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>KYCReview</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/SMS_Code_Resolution_1__c.field-meta.xml
<CustomField>
    <fullName>SMS_Code_Resolution_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SMS Code Resolution 1</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/SMS_Code_Resolution_2__c.field-meta.xml
<CustomField>
    <fullName>SMS_Code_Resolution_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SMS Code Resolution 2</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/SMS_Code_Resolved__c.field-meta.xml
<CustomField>
    <fullName>SMS_Code_Resolved__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SMS Code (Resolved)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Validate_Code__c.field-meta.xml
<CustomField>
    <fullName>Validate_Code__c</fullName>
    <description>This field for define code to validate in case validation rule</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>This field for define service code to use in validation rule, report, back end integration.</inlineHelpText>
    <label>Service Type Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Create_Case_Inquiry_Controller.cls
global without sharing class Create_Case_Inquiry_Controller {
    
    global class PicklistWrapper{
        @AuraEnabled
        global Set<String> keyPTASegment{get;set;}
        @AuraEnabled
        global Map<String,Set<PicklistOption>> mapSVTMlvl1{get;set;}
        @AuraEnabled
        global Map<String,Set<PicklistOption>> mapSVTMlvl2{get;set;}
        @AuraEnabled
        global Map<String,Set<PicklistOption>> mapSVTMlvl3{get;set;}
        @AuraEnabled
        global Map<String,Set<PicklistOption>> mapSVTMlvl4{get;set;}
        @AuraEnabled
        global Map<String,Service_Type_Matrix__c> mapSVTM{get;set;}
    }

    public class PicklistOption{
        @AuraEnabled
        public String value{get;set;}
        @AuraEnabled
        public String label{get;set;}
    }

    @AuraEnabled
    public static PicklistWrapper getServiceTypeMatrix (){
        PicklistWrapper wrapper = new PicklistWrapper();
        List<Service_Type_Matrix__c> stm = new List<Service_Type_Matrix__c>([SELECT Id, Segment__c, 
        Service_Level1__c, Service_Level2__c, Service_Level3__c, Service_Level4__c,SMS_Code_Resolution_1__c, SMS_Code_Resolution_2__c,
        SMS_Code_Resolved__c, Service_Template__c, Resolution_2__c, Resolution_1__c,Journey__c,Validate_Code__c,Problem_Type__c 
        FROM Service_Type_Matrix__c WHERE Service_Level1__c = 'Inquiry' AND Active__c = true order by Service_Level1__c asc,Service_Level2__c asc,Service_Level3__c asc, Service_Level4__c asc]);
        Set<String> keySegment = new Set<String>();
        Map<String,PicklistOption> mapSegment = new Map<String,PicklistOption>();
        Map<String,Set<PicklistOption>> keySVTMlvl1 = new Map<String,Set<PicklistOption>>();
        Map<String,Set<PicklistOption>> keySVTMlvl2 = new Map<String,Set<PicklistOption>>();
        Map<String,Set<PicklistOption>> keySVTMlvl3 = new Map<String,Set<PicklistOption>>();
        Map<String,Set<PicklistOption>> keySVTMlvl4 = new Map<String,Set<PicklistOption>>();
        Map<String,Service_Type_Matrix__c> SVTM = new Map<String,Service_Type_Matrix__c>();
        for(Service_Type_Matrix__c m : stm){
            if (keySVTMlvl1.containsKey(m.Segment__c)){
                Boolean isExisting = false; // check have no in set
                Set<PicklistOption> tmpSet = keySVTMlvl1.get(m.Segment__c);
                for (PicklistOption picklist : tmpSet){
                    if (picklist.value == m.Service_Level1__c){
                        isExisting = true;
                        break;
                    }
                }
                if (!isExisting){
                    PicklistOption pl = new PicklistOption();
                    pl.value = m.Service_Level1__c;
                    pl.label = m.Service_Level1__c;
                    tmpSet.add(pl);
                }
            }else {
                Set<PicklistOption> tmpSet = new Set<PicklistOption>();
                PicklistOption pl = new PicklistOption();
                pl.value = m.Service_Level1__c;
                pl.label = m.Service_Level1__c;
                tmpSet.add(pl);
                keySVTMlvl1.put(m.Segment__c,tmpSet);

                keySegment.add(m.Segment__c);
            }
            if (keySVTMlvl2.containsKey(m.Service_Level1__c+':'+m.Segment__c)){
                Boolean isExisting = false; // check have no in set
                Set<PicklistOption> tmpSet = keySVTMlvl2.get(m.Service_Level1__c+':'+m.Segment__c);
                for (PicklistOption picklist : tmpSet){
                    if (picklist.value == m.Service_Level2__c){
                        isExisting = true;
                        break;
                    }
                }
                if (!isExisting){
                    PicklistOption pl = new PicklistOption();
                    pl.value = m.Service_Level2__c;
                    pl.label = m.Service_Level2__c;
                    tmpSet.add(pl);
                }
            }else {
                Set<PicklistOption> tmpSet = new Set<PicklistOption>();
                PicklistOption pl = new PicklistOption();
                pl.value = m.Service_Level2__c;
                pl.label = m.Service_Level2__c;
                tmpSet.add(pl);
                keySVTMlvl2.put(m.Service_Level1__c+':'+m.Segment__c,tmpSet);
            }
            if (keySVTMlvl3.containsKey(m.Service_Level2__c+':'+m.Service_Level1__c+':'+m.Segment__c)){
                Boolean isExisting = false; // check have no in set
                Set<PicklistOption> tmpSet = keySVTMlvl3.get(m.Service_Level2__c+':'+m.Service_Level1__c+':'+m.Segment__c);
                for (PicklistOption picklist : tmpSet){
                    if (picklist.value == m.Service_Level3__c){
                        isExisting = true;
                        break;
                    }
                }
                if (!isExisting){
                    PicklistOption pl = new PicklistOption();
                    pl.value = m.Service_Level3__c;
                    pl.label = m.Service_Level3__c;
                    tmpSet.add(pl);
                }
            }else {
                Set<PicklistOption> tmpSet = new Set<PicklistOption>();
                PicklistOption pl = new PicklistOption();
                pl.value = m.Service_Level3__c;
                pl.label = m.Service_Level3__c;
                tmpSet.add(pl);
                keySVTMlvl3.put(m.Service_Level2__c+':'+m.Service_Level1__c+':'+m.Segment__c,tmpSet);
            }
            if (keySVTMlvl4.containsKey(m.Service_Level3__c+':'+m.Service_Level2__c+':'+m.Service_Level1__c+':'+m.Segment__c)){
                Boolean isExisting = false; // check have no in set
                Set<PicklistOption> tmpSet = keySVTMlvl4.get(m.Service_Level3__c+':'+m.Service_Level2__c+':'+m.Service_Level1__c+':'+m.Segment__c);
                for (PicklistOption picklist : tmpSet){
                    if (picklist.value == m.Service_Level3__c){
                        isExisting = true;
                        break;
                    }
                }
                if (!isExisting){
                    PicklistOption pl = new PicklistOption();
                    pl.value = m.Service_Level4__c;
                    pl.label = m.Service_Level4__c;
                    tmpSet.add(pl);
                }
            }else {
                Set<PicklistOption> tmpSet = new Set<PicklistOption>();
                PicklistOption pl = new PicklistOption();
                pl.value = m.Service_Level4__c;
                pl.label = m.Service_Level4__c;
                tmpSet.add(pl);
                keySVTMlvl4.put(m.Service_Level3__c+':'+m.Service_Level2__c+':'+m.Service_Level1__c+':'+m.Segment__c,tmpSet);
            }
            SVTM.put(m.Service_Level4__c+':'+m.Service_Level3__c+':'+m.Service_Level2__c+':'+m.Service_Level1__c+':'+m.Segment__c,m);
        }

        wrapper.keyPTASegment = keySegment;
        wrapper.mapSVTMlvl1 = keySVTMlvl1;
        wrapper.mapSVTMlvl2 = keySVTMlvl2;
        wrapper.mapSVTMlvl3 = keySVTMlvl3;
        wrapper.mapSVTMlvl4 = keySVTMlvl4;
        wrapper.mapSVTM = SVTM;
        return wrapper;
    }

    @AuraEnabled
    public static List<Case> saveRecord(List<Case> caseList,Task taskObj){
        try {
            System.Debug('caseList: '+caseList);
            System.Debug('taskObj: '+taskObj);
            insert caseList;
            
            List<Task> updateTask = new List<Task>();
            if(taskObj != null)
            {
                if(taskObj.WhatId == null && taskObj.Id != null)
                {   
                    Task newTask = new Task();
                    newTask.Id = taskObj.Id;
                    newTask.WhatId = caseList.size() > 0? caseList[0].AccountId : null;
                    updateTask.add(newTask);
                }
            }
            if(updateTask.size() > 0)
            {
                update updateTask;
            }
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
        return caseList;
    }
    @AuraEnabled
    public static Task mappingCallLog() {
        Task callTask = new Task();
        try {
            User currentUser = [Select ID, Employee_ID__c from User where username = : userinfo.getUserName() limit 1];
            String userName = UserInfo.getUserName();
            String userId = currentUser.Employee_ID__c;
            List<Task> callTaskList =  [select ID, Call_Agent_Id__c, Call_Log_ID__c, Call_Start_Datetime__c, Call_Number__c,
                            recordtypeID, CreatedDate from Task WHERE Call_Agent_Id__c = :userId
                            AND CreatedDate >= : Datetime.now().addHours(-1)
                            AND RecordType.Name  = 'Call Log Record Type' AND Call_Log_ID__c != null
                            ORDER BY CreatedDate DESC LIMIT 1 ];
            System.Debug('callTaskList:'+callTaskList);
            if (callTaskList.size() > 0){
                callTask = callTaskList[0];
            }
            else {
                System.Debug('IS NULL');
            }
            return callTask;

        } catch (exception e) {
            System.debug(e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
}