force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Category</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Closed_By_BU__c.field-meta.xml
<CustomField>
    <fullName>Closed_By_BU__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Closed By BU</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_Person_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Person Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Person Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_Person_Phone_2__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Phone_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Person Phone 2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_Person_Phone__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Person Phone 1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Resolution_LIst__c.field-meta.xml
<CustomField>
    <fullName>Resolution_LIst__c</fullName>
    <label>Resolution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IT ดำเนินการแก้ไขระบบ</fullName>
            </value>
            <value>
                <fullName>ชีแจงข้อมูลที่ถูกต้องให้ลูกค้ารับทราบ</fullName>
            </value>
            <value>
                <fullName>ดำเนินการตามที่ลูกค้าร้องขอ</fullName>
            </value>
            <value>
                <fullName>ปรับปรุง/แก้ไขรายการให้ลูกค้า</fullName>
            </value>
            <value>
                <fullName>ปรับปรุงการ Set Up ให้ถูกต้อง</fullName>
            </value>
            <value>
                <fullName>ปรับปรุงคะแนนคืน</fullName>
            </value>
            <value>
                <fullName>ปรับปรุงเงินคืน</fullName>
            </value>
            <value>
                <fullName>ยืนยันรายการปกติ</fullName>
            </value>
            <value>
                <fullName>เจ้าหน้าที่แก้ไขรายการให้ถูกต้อง</fullName>
            </value>
            <value>
                <fullName>แนะนำให้ลูกค้ารับทราบ</fullName>
            </value>
            <value>
                <fullName>ลูกค้ายอมยุติข้อร้องเรียน</fullName>
            </value>
            <value>
                <fullName>ธนาคารชดเชยให้ลูกค้า</fullName>
            </value>
            <value>
                <fullName>ส่งบัตร/เอกสารให้ลูกค้าแล้ว</fullName>
            </value>
            <value>
                <fullName>ติดต่อลูกค้าไม่ได้</fullName>
            </value>
            <value>
                <fullName>ลูกค้าไม่ให้ความร่วมมือ</fullName>
            </value>
            <value>
                <fullName>Compliance ได้รับเรื่องเรียบร้อยแล้ว</fullName>
            </value>
            <value>
                <fullName>แก้ไขปัญหาแล้ว ติดต่อลูกค้าไม่ได้ ส่ง SMS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>A</fullName>
                <isActive>false</isActive>
                <label>A</label>
            </value>
            <value>
                <fullName>B</fullName>
                <isActive>false</isActive>
                <label>B</label>
            </value>
            <value>
                <fullName>ลูกค้าไม่รับสาย/ติดต่อลูกค้าไม่ได้</fullName>
                <isActive>false</isActive>
                <label>ลูกค้าไม่รับสาย/ติดต่อลูกค้าไม่ได้</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Root_Cause_List__c.field-meta.xml
<CustomField>
    <fullName>Root_Cause_List__c</fullName>
    <label>Issue Cause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ttb_Application Error เช่น ttb touch / Internet Banking</fullName>
            </value>
            <value>
                <fullName>ttb_Set Up ข้อมูลไม่ถูกต้อง</fullName>
            </value>
            <value>
                <fullName>ttb_ข้อมูลผลิตภัณฑ์ / Compaign ไม่ชัดเจน</fullName>
            </value>
            <value>
                <fullName>ttb_ข้อมูลในระบบไม่ถูกต้อง</fullName>
            </value>
            <value>
                <fullName>ttb_ปัญหาอื่นๆ จากกระบวนการภายใน</fullName>
            </value>
            <value>
                <fullName>ttb_ปัญหาเกิดจากพนักงาน</fullName>
            </value>
            <value>
                <fullName>ttb_ผลิตภัณฑ์และบริการไม่ตรงตามความต้องการลูกค้า</fullName>
            </value>
            <value>
                <fullName>ttb_ฟังก์ชั่นการทำงานของเครื่อง ATM/ADM ขัดข้อง</fullName>
            </value>
            <value>
                <fullName>ttb_ระบบงานภายในขัดข้อง เช่น F2F /SD /SCS</fullName>
            </value>
            <value>
                <fullName>ttb_ระบบภายในปิดปรับปรุง</fullName>
            </value>
            <value>
                <fullName>ttb_ลูกค้าไม่ยอมรับนโยบายและหลักการปฏิบัติของธนาคาร</fullName>
            </value>
            <value>
                <fullName>ttb_เครือข่ายภายในขัดข้อง Host Down / Time out</fullName>
            </value>
            <value>
                <fullName>ttb_เจ้าหน้าที่ดำเนินการล่าช้า</fullName>
            </value>
            <value>
                <fullName>ttb_เจ้าหน้าที่ทำรายการไม่ถูกต้อง</fullName>
            </value>
            <value>
                <fullName>ttb_เจ้าหน้าที่สอนการใช้งานระบบให้ลูกค้าไม่ครบถ้วน</fullName>
            </value>
            <value>
                <fullName>ttb_เจ้าหน้าที่ให้ข้อมูลลูกค้าไม่ถูกต้อง</fullName>
            </value>
            <value>
                <fullName>ttb_ไม่มี Process รองรับความต้องการลูกค้า</fullName>
            </value>
            <value>
                <fullName>Customer_ลูกค้าร้องขอบริการ</fullName>
            </value>
            <value>
                <fullName>Customer_เกิดจากลูกค้าเข้าใจผิด</fullName>
            </value>
            <value>
                <fullName>Third Party_ATM/ ADM ต่างธนาคารขัดข้อง (Timeout)</fullName>
            </value>
            <value>
                <fullName>Third Party_ATM Timeout</fullName>
            </value>
            <value>
                <fullName>Third Party_Hardware_Machine_Error</fullName>
            </value>
            <value>
                <fullName>Third Party_Network ขัดข้อง</fullName>
            </value>
            <value>
                <fullName>Third Party_การดำเนินการ / การติดต่อที่ไม่ถูกต้อง</fullName>
            </value>
            <value>
                <fullName>Third Party_ปิดระบบ / Network ขัดข้อง</fullName>
            </value>
            <value>
                <fullName>Third Party_ระบบงานภายนอกขัดข้อง</fullName>
            </value>
            <value>
                <fullName>Third Party_ระบบภายนอกปิดปรับปรุง</fullName>
            </value>
            <value>
                <fullName>Third Party_ระบบเครื่อข่ายภายนอกขัดข้อง</fullName>
            </value>
            <value>
                <fullName>Third Party_ระบบเครื่อข่ายภายนอกขัดข้อง_ไฟฟ้าดับ</fullName>
            </value>
            <value>
                <fullName>Third Party_อยู่ระหว่างตรวจสอบ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Type_Matrix_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Type_Matrix_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Type Matrix Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SMS_Code_Resolution_1__c.field-meta.xml
<CustomField>
    <fullName>SMS_Code_Resolution_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SMS Code Resolution 1</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SMS_Code_Resolution_2__c.field-meta.xml
<CustomField>
    <fullName>SMS_Code_Resolution_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SMS Code Resolution 2</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SMS_Resolution_1__c.field-meta.xml
<CustomField>
    <fullName>SMS_Resolution_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SMS Resolution 1</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SMS_Resolution_2__c.field-meta.xml
<CustomField>
    <fullName>SMS_Resolution_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SMS Resolution 2</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/To_Ext_1__c.field-meta.xml
<CustomField>
    <fullName>To_Ext_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>To / Ext 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/To_Ext_2__c.field-meta.xml
<CustomField>
    <fullName>To_Ext_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>To / Ext 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClosedCaseLayoutExtensionTest.cls
@isTest
public class ClosedCaseLayoutExtensionTest {
    static{
        TestUtils.createAppConfig();
    }

    public static testmethod void CaseUpdate(){
        Test.startTest();
        Case testCase = new Case();
        testCase.Status = 'New';
        testCase.Resolution_List__c = 'ปรับปรุงเงินคืน';
        testCase.Contact_Person_Name__c = 'TEST TEST';
        testCase.Contact_Person_Phone__c ='0800000000';
        testCase.Contact_Person_Phone_2__c ='0800000000';
        testCase.To_Ext_1__c ='401 ,403';
        testCase.To_Ext_2__c ='401 ,(403)- 1';

        testCase.Contact_Person_Email__c = 'test@gmail.com';
        testCase.Closed_By_BU__c = 'TEST';
        testCase.Subject = 'TEST Case';
        testCase.Service_Type_Matrix_Code__c = 'V0012';
        testCase.SMS_Resolution_1__c = 'ปรับปรุงเงินคืน';
        testCase.SMS_Resolution_2__c = 'ยืนยันรายการปกติ';
        testCase.SMS_Code_Resolution_1__c = 'CRMRBG_012';
        testCase.SMS_Code_Resolution_2__c = 'CRMRBG_001';
        testCase.Root_Cause_List__c = 'Customer_ลูกค้าร้องขอบริการ';
        testCase.Category__c = 'Complaint';
        ApexPages.StandardController sc1 = new ApexPages.StandardController(testCase);
        ClosedCaseLayoutExtension Case1 = new ClosedCaseLayoutExtension(sc1);
        Case1.checkedStatusNew = null;
        Case1.validateCase();
        Case1.oldStatus = 'Completed';
        Case1.validateCase();
        Case1.cancelCase();
        
        Test.stopTest();

    }



}