force-app/main/default/objects/Case/fields/FCR__c.field-meta.xml
<CustomField>
    <fullName>FCR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FCR?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Root_Cause__c.field-meta.xml
<CustomField>
    <fullName>Root_Cause__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Issue Cause Detail</label>
    <length>3500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/Social_Post__c.object-meta.xml
<CustomObject>
    <label>Warroom Social Post</label>
    <nameField>
        <displayFormat>SP-{yyyy}{mm}-{00000}</displayFormat>
        <label>Social Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warroom Social Posts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Post__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Warroom Social Posts</relationshipLabel>
    <relationshipName>Custom_Social_Posts_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Default_Social_Account__c.field-meta.xml
<CustomField>
    <fullName>Default_Social_Account__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Default Social Account</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/End_DateTime__c.field-meta.xml
<CustomField>
    <fullName>End_DateTime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/External_Link__c.field-meta.xml
<CustomField>
    <fullName>External_Link__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>External Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
                <default>true</default>
                <label>Inbound</label>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_Author_Type__c.field-meta.xml
<CustomField>
    <fullName>Post_Author_Type__c</fullName>
    <label>Post Author Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_Body__c.field-meta.xml
<CustomField>
    <fullName>Post_Body__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Post Body</label>
    <length>3200</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Post_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Post Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_ID__c.field-meta.xml
<CustomField>
    <fullName>Post_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Post ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_Identity_ID__c.field-meta.xml
<CustomField>
    <fullName>Post_Identity_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Post Identity ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_Type__c.field-meta.xml
<CustomField>
    <fullName>Post_Type__c</fullName>
    <label>Post Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>post</fullName>
            </value>
            <value>
                <fullName>comment</fullName>
            </value>
            <value>
                <fullName>Tweet</fullName>
            </value>
            <value>
                <fullName>Inbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Reject_Comment__c.field-meta.xml
<CustomField>
    <fullName>Reject_Comment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reject Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Reject_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Reason__c</fullName>
    <label>Reject Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ไม่เกี่ยวข้อง</fullName>
            </value>
            <value>
                <fullName>โฆษณาแฝง</fullName>
            </value>
            <value>
                <fullName>อื่นๆ</fullName>
            </value>
            <value>
                <fullName>Sticker</fullName>
            </value>
            <value>
                <fullName>ลูกค้าถามซ้ำ</fullName>
            </value>
            <value>
                <fullName>Facebook ดึงเคสย้อนหลัง</fullName>
            </value>
            <value>
                <fullName>Crisis touch และมีการโพสต์อัพเดทสถานะว่ากลับมาใช้งานได้แล้ว</fullName>
            </value>
            <value>
                <fullName>ลูกค้าบ่นทั่วไป(ไม่พอใจนโยบายสมัครทัช) ทั้งนี้เคลียร์ทาง inbox แล้ว</fullName>
            </value>
            <value>
                <fullName>ttb touch ขัดข้อง</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Reply_Social_ID__c.field-meta.xml
<CustomField>
    <fullName>Reply_Social_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reply Social ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Reply_to_Social_Post__c.field-meta.xml
<CustomField>
    <fullName>Reply_to_Social_Post__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reply to Social Post</label>
    <referenceTo>Social_Post__c</referenceTo>
    <relationshipName>Social_Posts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Social_Post_Author__c.field-meta.xml
<CustomField>
    <fullName>Social_Post_Author__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Social Post Author</label>
    <referenceTo>Social_Post_Author__c</referenceTo>
    <relationshipName>Custom_Social_Posts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Source_Channel__c.field-meta.xml
<CustomField>
    <fullName>Source_Channel__c</fullName>
    <label>Source Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Facebook Inbox</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>LINE</fullName>
            </value>
            <value>
                <fullName>LINE Account Connect</fullName>
            </value>
            <value>
                <fullName>Pantip</fullName>
            </value>
            <value>
                <fullName>Pantip Inbox</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>Twitter Inbox</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Google Business Review</fullName>
            </value>
            <value>
                <fullName>Google Business QA</fullName>
            </value>
            <value>
                <fullName>Warroom Connect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Post Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Subject_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Subject Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Thread_ID__c.field-meta.xml
<CustomField>
    <fullName>Thread_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Thread ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Thread_Identity_ID__c.field-meta.xml
<CustomField>
    <fullName>Thread_Identity_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Thread Identity ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Thread_Type__c.field-meta.xml
<CustomField>
    <fullName>Thread_Type__c</fullName>
    <label>Thread Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>LINE</fullName>
            </value>
            <value>
                <fullName>Pantip</fullName>
            </value>
            <value>
                <fullName>PantipInbox</fullName>
            </value>
            <value>
                <fullName>Tweet</fullName>
            </value>
            <value>
                <fullName>TwitterInbox</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>GoogleBusinessReview</fullName>
            </value>
            <value>
                <fullName>GoogleBusinessQA</fullName>
            </value>
            <value>
                <fullName>WarroomConnect</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Topic_Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Topic_Profile_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Topic Profile Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SocialPostMainComponentController.cls
public without sharing class SocialPostMainComponentController {
    
    @AuraEnabled
    public static List<Object> getAccountList(String recordId) {
        List<Object> rtnValue = new List<Object>();

        List<Social_Post__c> thisPost = [
            SELECT Id, Thread_Type__c
            FROM Social_Post__c
            WHERE Id = :recordId
        ];

        Datetime startTime = System.now();
        String requestBody;
        String responseBody;
        Boolean isSuccess = false;
        String userName = UserInfo.getName();
        try {
            String token = SocialPostMainComponentController.getToken();
            String threadType = thisPost.get(0).Thread_Type__c;
            HttpRequest req = new HttpRequest();
            req.setEndpoint('callout:Get_Social_Account_List/' + threadType);
            req.setMethod('GET');
            req.setHeader('Authorization', 'Bearer ' + token);
            Http http = new Http();
            requestBody = req.getBody();
            HTTPResponse res = http.send(req);
            // System.debug('token: ' + token);
            // System.debug('threadType: ' + threadType);
            // System.debug('resBody: ' + res.getBody());
            Map<String, Object> jsonMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
            List<Object> accounts = (List<Object>) jsonMap.get('accounts');
            responseBody = res.getBody();
            System.debug('responseBody: ' + responseBody);
            for (Object acc : accounts) {
                Map<String, Object> accountDetails = (Map<String, Object>) acc;
                // System.debug('accountDetails: ' + accountDetails);
                Map<String, Object> account = new Map<String, Object>();
                account.put('id', String.valueOf(accountDetails.get('social_id')));
                // account.put('id', String.valueOf(accountDetails.get('id')));
                account.put('name', String.valueOf(accountDetails.get('name')));
                rtnValue.add(account);
            }
            isSuccess = true;
            OnlineServiceLogUtils.saveToOnlineLog(isSuccess , '',  '',  '' ,  userName, '' ,  'Get_Social_Account_List' , requestBody , responseBody, null, startTime,  System.now(),  '');
        } catch (Exception e) {
            isSuccess = false;
            System.debug(e.getLineNumber() + ': ' + e.getMessage());
            OnlineServiceLogUtils.saveToOnlineLog(isSuccess , '',  e.getMessage(),  '' ,  userName, '' ,  'Get_Social_Account_List' , requestBody , responseBody, null, startTime,  System.now(),  '');
        }
        if (!isSuccess) {
            throw new AuraHandledException('');
        }
        return rtnValue;
    }

    @AuraEnabled
    public static Map<String, Object> getPostInfo(String recordId) {
        Social_Post__c thisPost = [
            SELECT Id, Post_Body__c, Status__c, OwnerId, Message_Type__c, Reply_to_Social_Post__r.Post_Body__c, Reply_to_Social_Post__c, Reply_to_Social_Post__r.Reply_Social_ID__c, Default_Social_Account__c
            FROM Social_Post__c
            WHERE Id = :recordId
        ];
        Map<String, Object> rtnValue = new Map<String, Object>();
        rtnValue.put('message', thisPost.Post_Body__c);
        Boolean isDisableInput = thisPost.Message_Type__c != 'Inbound' ? true : false;
        if (thisPost.Status__c == 'Close' || thisPost.Status__c == 'Reject') {
            isDisableInput = true;
        } else if (thisPost.OwnerId != UserInfo.getUserId()) {
            isDisableInput = true;
        }

        rtnValue.put('messageType', isDisableInput);
        String replyMsg;
        String replyId;
        if (thisPost.Reply_to_Social_Post__c != null) {
            replyMsg = thisPost.Reply_to_Social_Post__r.Post_Body__c;
            replyId = thisPost.Reply_to_Social_Post__r.Reply_Social_ID__c;
        }
        rtnValue.put('replyMessage', replyMsg);
        rtnValue.put('replyId', replyId);
        rtnValue.put('rejectList', getPicklistValues());
        rtnValue.put('default_acc', thisPost.Default_Social_Account__c);
        return rtnValue;
    }

    @AuraEnabled
    public static Map<String, Object> getThreadIdentity(String recordId) {
        Map<String, Object> rtnValue = new Map<String, Object>();
        // String rtnValue;

        List<Social_Post__c> thisPost = [
            SELECT Id, Thread_ID__c, Thread_Identity_ID__c
            FROM Social_Post__c
            WHERE Id = :recordId
        ];
        System.debug('recordId: ' + recordId);

        Datetime startTime = System.now();
        String requestBody;
        String responseBody;
        Boolean isSuccess = false;
        String userName = UserInfo.getName();
        try {
            String token = WarroomPageController.getWarroomToken();
            System.debug('token: ' + token);
            String threadId = thisPost.get(0).Thread_ID__c;
            System.debug('threadId: ' + threadId);
            HttpRequest req = new HttpRequest();
            req.setEndpoint('callout:Get_Thread_Identity/' + threadId);
            req.setMethod('GET');
            req.setHeader('Authorization', 'Bearer ' + token);
            Http http = new Http();
            requestBody = req.getBody();
            HTTPResponse res = http.send(req);
            Map<String, Object> jsonMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
            System.debug('resBody: ' + res.getBody());
            responseBody = res.getBody();
            rtnValue = jsonMap;
            isSuccess = true;
            OnlineServiceLogUtils.saveToOnlineLog(isSuccess , '',  '',  '' ,  userName, '' ,  'Get_Thread_Identity' , requestBody , responseBody, null, startTime,  System.now(),  '');
        } catch (Exception e) {
            isSuccess = false;
            System.debug('err: ' + e.getMessage());
            OnlineServiceLogUtils.saveToOnlineLog(isSuccess , '',  e.getMessage(),  '' ,  userName, '' ,  'Get_Thread_Identity' , requestBody , responseBody, null, startTime,  System.now(),  '');
        }
        if (!isSuccess) {
            throw new AuraHandledException('');
        }
        return rtnValue;
    }

    @AuraEnabled
    public static String replyMessage(String recordId, String threadIdentityId, String socialId, String messageBody) {
        String rtnValue;

        List<Social_Post__c> thisPost = [
            SELECT
                Id,
                Post_ID__c,
                Thread_ID__c,
                Thread_Identity_ID__c,
                Post_Identity_ID__c,
                Source_Channel__c,
                External_Link__c,
                Thread_Type__c,
                Social_Post_Author__c,
                Case__c,
                Subject_Name__c,
                Status__c,
                Reply_to_Social_Post__c,
                End_DateTime__c,
                Topic_Profile_Name__c
            FROM Social_Post__c
            WHERE Id = :recordId
        ];
        System.debug('recordId: ' + recordId);
        Map<String, Object> jsonMap = new Map<String, Object>();

        Datetime startTime = System.now();
        String requestBody;
        String responseBody;
        Boolean isSuccess = false;
        String userName = UserInfo.getName();
        try {
            String token = WarroomPageController.getWarroomToken();
            HttpRequest req = new HttpRequest();
            req.setEndpoint('callout:Reply_Message');
            req.setMethod('POST');
            req.setHeader('Content-Type', 'application/json;Charset="UTF-8"');
            req.setHeader('Authorization', 'Bearer ' + token);

            // create reqBody
            Map<String, Object> reqBody = new Map<String, Object>();
            reqBody.put('sna_id', socialId);
            reqBody.put('post_identity_id', thisPost.get(0).Post_Identity_ID__c);

            // message
            Map<String, Object> msgPayload = new Map<String, Object>();
            msgPayload.put('type', 'text');
            msgPayload.put('text', messageBody);
            List<Object> finalPayload = new List<Object>();
            finalPayload.add(msgPayload);
            reqBody.put('message_payload', finalPayload);

            reqBody.put('thread_type', thisPost.get(0).Thread_Type__c);
            reqBody.put('website', thisPost.get(0).Thread_Type__c);
            reqBody.put('thread_id', thisPost.get(0).Thread_ID__c);
            // reqBody.put('thread_identity_id', thisPost.get(0).Thread_Identity_ID__c);
            reqBody.put('thread_identity_id', threadIdentityId);
            req.setBody(JSON.serializePretty(reqBody));
            Http http = new Http();
            requestBody = req.getBody();
            System.debug('reqBody' + JSON.serializePretty(reqBody));
            HTTPResponse res = http.send(req);
            // Map<String, Object> jsonMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
            jsonMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
            System.debug('resBody: ' + res.getBody());
            responseBody = res.getBody();
            String status = String.valueOf(jsonMap.get('status'));
            if (status == 'success') {
                isSuccess = true;
                OnlineServiceLogUtils.saveToOnlineLog(isSuccess , '',  '',  '' ,  userName, '' ,  'Reply_Message' , requestBody , responseBody, null, startTime,  System.now(),  '');
                // insert new post
                Social_Post__c replyPost = new Social_Post__c();
                replyPost.Source_Channel__c = thisPost.get(0).Source_Channel__c;
                replyPost.Post_Author_Type__c = 'Agent';
                replyPost.External_Link__c = thisPost.get(0).External_Link__c;
                replyPost.Post_ID__c = String.valueOf(thisPost.get(0).Post_ID__c) + 'R';
                replyPost.Post_Body__c = messageBody;
                replyPost.Post_Type__c = 'comment';
                replyPost.Post_Date__c = System.now();
                replyPost.Status__c = 'Close';
                replyPost.Thread_ID__c = thisPost.get(0).Thread_ID__c;
                replyPost.Thread_Type__c = thisPost.get(0).Thread_Type__c;
                replyPost.Social_Post_Author__c = thisPost.get(0).Social_Post_Author__c;
                replyPost.Reply_Social_ID__c = socialId;
                replyPost.Case__c = thisPost.get(0).Case__c;
                replyPost.Message_Type__c = 'Outbound';
                replyPost.Post_Identity_ID__c = String.valueOf(jsonMap.get('id'));
                replyPost.Subject_Name__c = thisPost.get(0).Subject_Name__c;
                replyPost.Topic_Profile_Name__c = thisPost.get(0).Topic_Profile_Name__c;
                System.debug('replyPost: ' + JSON.serializePretty(replyPost));
                insert replyPost;
                
                thisPost.get(0).Reply_to_Social_Post__c = replyPost.Id;
                thisPost.get(0).End_DateTime__c = System.now();
                thisPost.get(0).Status__c = 'Close';
                update thisPost;
            } else {
                isSuccess = false;
                Map<String, Object> error = (Map<String, Object>) jsonMap.get('error');
                String errMsg = String.valueOf(error.get('message'));
                System.debug('error: ' + errMsg);
                OnlineServiceLogUtils.saveToOnlineLog(isSuccess , '',  errMsg,  '' ,  userName, '' ,  'Reply_Message' , requestBody , responseBody, null, startTime,  System.now(),  '');
            }
        } catch (Exception e) {
            isSuccess = false;
            System.debug('err: ' + e.getMessage());
            OnlineServiceLogUtils.saveToOnlineLog(isSuccess , '',  e.getMessage(),  '' ,  userName, '' ,  'Reply_Message' , requestBody , responseBody, null, startTime,  System.now(),  '');
        }
        if (!isSuccess) {
            throw new AuraHandledException('');
        }
        return rtnValue;
    }

    @AuraEnabled
    public static void rejectPost(String recordId, String rejectReason, String rejectComment) {
        List<Social_Post__c> thisPost = [SELECT Id, Status__c, End_DateTime__c, Case__c, Reject_Reason__c, Reject_Comment__c FROM Social_Post__c WHERE Id = :recordId];
        try {
            Case thisCase = [SELECT Id, FCR__c, Root_Cause__c, Root_Cause_List__c, Resolution__c, Resolution_List__c FROM Case WHERE Id = :thisPost.get(0).Case__c LIMIT 1];
            thisCase.FCR__c = true;
            thisCase.Root_Cause_List__c = 'Other';
            thisCase.Resolution_LIst__c = 'Other';
            thisCase.Root_Cause__c = 'Reject Post';
            thisCase.Resolution__c = 'Reject Post';
            update thisCase;
        } catch (Exception e) {
            System.debug('Case not found');
        }
        
        thisPost.get(0).End_DateTime__c = System.now();
        thisPost.get(0).Status__c = 'Reject';
        thisPost.get(0).Reject_Reason__c = rejectReason;
        thisPost.get(0).Reject_Comment__c = rejectComment;
        update thisPost;
    }

    @AuraEnabled
    public static void clearTransfer(String recordId) {
        List<Social_Post__c> thisPost = [SELECT Id, Status__c, LastTransferUser__c FROM Social_Post__c WHERE Id = :recordId];
        thisPost.get(0).LastTransferUser__c = null;
        update thisPost;
    }

    public static String getToken() {
        String token;
        String jsonBody =  '{"username": "{!$Credential.Username}",'+
                           '"password": "{!$Credential.Password}",'+
                           '"expire": 900}';

        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('callout:Warroom_Get_Token_2');
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setBody(jsonBody);

        HttpResponse response;
        if (!Test.isRunningTest()) {
            response = http.send(request);
        } else {
            String body = '{"status":"success","data":"xxx"}';
            response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody(body);
            response.setStatusCode(200);
        }
 
        System.debug('Get Token status code --->' + response.getStatusCode());
        System.debug('Get response' + response.getBody());

        if (response.getStatusCode() == 200) 
        {
            Map<String, Object> getTokenMap = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
            //token = JSON.serialize(getTokenMap.get('api_token'));
            token = getTokenMap.containsKey('data') ? getTokenMap.get('data').ToString() : null;
            System.debug('token:'+getTokenMap.get('data'));
        } else {
            System.debug('Get Token status body --->' + response.getStatusCode() + ' ' + response.getBody());
        }
       
        return token;
    }

    public static List<String> getPicklistValues() {
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = Social_Post__c.Reject_Reason__c.getDescribe();
        List<Schema.PicklistEntry> picklistEntries = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry entry : picklistEntries) {
            options.add(entry.getValue());
        }
        return options;
    }
}