force-app/main/default/objects/RTL_Household__c/RTL_Household__c.object-meta.xml
<CustomObject>
    <label>Household</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Household__c/fields/RTL_Benefit_Package__c.field-meta.xml
<CustomField>
    <fullName>RTL_Benefit_Package__c</fullName>
    <description>Benefit Package the Primary Household Member is entitled to</description>
    <label>Benefit Package</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wealth Package 1</fullName>
            </value>
            <value>
                <fullName>Wealth Package 2</fullName>
            </value>
            <value>
                <fullName>Wealth Package 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/RTL_Household_History_and_Approval__c.object-meta.xml
<CustomObject>
    <label>Household History and Approval</label>
    <nameField>
        <displayFormat>HH-{00000000}</displayFormat>
        <label>Household History and Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Household History and Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Household__c.field-meta.xml
<CustomField>
    <fullName>RTL_Household__c</fullName>
    <description>Household which this History record belongs to</description>
    <label>Household</label>
    <referenceTo>RTL_Household__c</referenceTo>
    <relationshipLabel>Household History and Approvals</relationshipLabel>
    <relationshipName>Household_History_and_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Outcome__c.field-meta.xml
<CustomField>
    <fullName>RTL_Outcome__c</fullName>
    <description>Outcome of this Household History</description>
    <label>Outcome</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RTL_HouseholdEditExtensionTest.cls
@isTest
public class RTL_HouseholdEditExtensionTest {
    
    static User rmUser;
    static User rmManager;
    static List<Account> acctList;
    static List<RTL_Household__c> householdList;
    static List<RTL_Household_History_And_Approval__c> historyList;
   
    static{
        
        TestUtils.createAppConfig();
        rmUser = RTL_TestUtility.createRetailTestUserWithBranch(true);
        rmManager = RTL_TestUtility.createRetailTestUser(true);
        acctList = RTL_TestUtility.createAccounts(2,true);
        householdList = RTL_TestUtility2.createHouseholdwithPrimaryMember(1,true,rmUser,acctList[0]);
        rmUser.ManagerId = rmManager.id;
        update rmUser;     
    }
	testmethod static void testEditHousehold(){
        Test.startTest();
        	historyList = [SELECT ID,Name FROM RTL_Household_History_And_Approval__c];
			historyList[0].RTL_Outcome__c = 'Approved';
        	update historyList;
        
        	RTL_HouseholdHistoryTriggerHandler.historyTrigger = false;
			Test.setCurrentPage(Page.RTL_HouseHold_Detail);
        	ApexPages.StandardController std = new ApexPages.StandardController(householdList[0]);
        	RTL_HouseHoldEditExtension ext = new RTL_HouseHoldEditExtension(std);
        	Integer historyCount = historyList.size();
        	ext.household.RTL_Benefit_Package__c = 'Wealth Package 3';
        	ext.save();
        	
        	historyList = [SELECT ID,Name FROM RTL_Household_History_And_Approval__c];
        	System.assertEquals(historyCount+1, historyList.size());
		Test.stopTest();  
    }
    
    testmethod static void testFailEditHousehold(){
        Test.startTest();
			Test.setCurrentPage(Page.RTL_HouseHold_Detail);
        	ApexPages.StandardController std = new ApexPages.StandardController(householdList[0]);
        	RTL_HouseHoldEditExtension ext = new RTL_HouseHoldEditExtension(std);
        	ext.household.RTL_Benefit_Package__c = 'Wealth Package';
        	ext.save();
        	
        	List<Apexpages.Message> msgs = ApexPages.getMessages();
			boolean b = false;
			for(Apexpages.Message msg:msgs){
    			if (msg.getDetail().contains('picklist')) b = true;
			}
			system.assert(b);
		Test.stopTest();  
    }
}