force-app/main/default/objects/RTL_Household__c/RTL_Household__c.object-meta.xml
<CustomObject>
    <label>Household</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Household__c/fields/RTL_Approver_UserName__c.field-meta.xml
<CustomField>
    <fullName>RTL_Approver_UserName__c</fullName>
    <description>Username of Approver</description>
    <formula>RTL_RM__r.Manager.FirstName + &quot; &quot; + RTL_RM__r.Manager.LastName</formula>
    <label>Approver</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Household__c/fields/RTL_Benefit_Package__c.field-meta.xml
<CustomField>
    <fullName>RTL_Benefit_Package__c</fullName>
    <description>Benefit Package the Primary Household Member is entitled to</description>
    <label>Benefit Package</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wealth Package 1</fullName>
            </value>
            <value>
                <fullName>Wealth Package 2</fullName>
            </value>
            <value>
                <fullName>Wealth Package 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Household__c/fields/RTL_Number_of_Members__c.field-meta.xml
<CustomField>
    <fullName>RTL_Number_of_Members__c</fullName>
    <description>Number of Members in this Household</description>
    <label>Number of Members</label>
    <summaryFilterItems>
        <field>RTL_Household_Member__c.RTL_Status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>RTL_Household_Member__c.RTL_Household__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/RTL_Household__c/fields/RTL_Remarks__c.field-meta.xml
<CustomField>
    <fullName>RTL_Remarks__c</fullName>
    <description>Remarks for this Household</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Remarks</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RTL_Household__c/fields/RTL_RM__c.field-meta.xml
<CustomField>
    <fullName>RTL_RM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship Manager for this Household</description>
    <label>RM/BM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Households</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Household__c/fields/RTL_Sent_to_Approval__c.field-meta.xml
<CustomField>
    <fullName>RTL_Sent_to_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent to Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Household__c/fields/RTL_Status__c.field-meta.xml
<CustomField>
    <fullName>RTL_Status__c</fullName>
    <description>Status of this Household</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>To Delete</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
                <isActive>false</isActive>
                <label>Delete</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Revisit</fullName>
                <isActive>false</isActive>
                <label>Revisit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Household__c/fields/RTL_To_Delete__c.field-meta.xml
<CustomField>
    <fullName>RTL_To_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Soft delete</description>
    <label>Delete Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/RTL_Household_History_and_Approval__c.object-meta.xml
<CustomObject>
    <label>Household History and Approval</label>
    <nameField>
        <displayFormat>HH-{00000000}</displayFormat>
        <label>Household History and Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Household History and Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Approval_Submit_User__c.field-meta.xml
<CustomField>
    <fullName>RTL_Approval_Submit_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that submits the approval request that is the intended recipient for the email response.</description>
    <label>Approval Submit User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Household_History_and_Approvals3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Date_Approved__c.field-meta.xml
<CustomField>
    <fullName>RTL_Date_Approved__c</fullName>
    <description>Date this change was Approved</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Date_Requested__c.field-meta.xml
<CustomField>
    <fullName>RTL_Date_Requested__c</fullName>
    <description>Date change was requested</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Requested Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Field_Changed__c.field-meta.xml
<CustomField>
    <fullName>RTL_Field_Changed__c</fullName>
    <description>Field to be changed</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Changed Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Field_Label__c.field-meta.xml
<CustomField>
    <fullName>RTL_Field_Label__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Household__c.field-meta.xml
<CustomField>
    <fullName>RTL_Household__c</fullName>
    <description>Household which this History record belongs to</description>
    <label>Household</label>
    <referenceTo>RTL_Household__c</referenceTo>
    <relationshipLabel>Household History and Approvals</relationshipLabel>
    <relationshipName>Household_History_and_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Household_Member__c.field-meta.xml
<CustomField>
    <fullName>RTL_Household_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Household member which this change is related to</description>
    <label>Household Member</label>
    <referenceTo>RTL_Household_Member__c</referenceTo>
    <relationshipLabel>Household History and Approvals</relationshipLabel>
    <relationshipName>Household_History_and_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Member_Lookup_Account__c.field-meta.xml
<CustomField>
    <fullName>RTL_Member_Lookup_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Account field to retain Household Membership data.</description>
    <label>Household Member</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Household History and Approvals</relationshipLabel>
    <relationshipName>Household_History_and_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_New_Value__c.field-meta.xml
<CustomField>
    <fullName>RTL_New_Value__c</fullName>
    <description>New value to be set</description>
    <encryptionScheme>None</encryptionScheme>
    <label>New Value</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Outcome__c.field-meta.xml
<CustomField>
    <fullName>RTL_Outcome__c</fullName>
    <description>Outcome of this Household History</description>
    <label>Outcome</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Prev_Value__c.field-meta.xml
<CustomField>
    <fullName>RTL_Prev_Value__c</fullName>
    <description>Old value of this change</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Old Value</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Section__c.field-meta.xml
<CustomField>
    <fullName>RTL_Section__c</fullName>
    <formula>IF(CONTAINS(RTL_Field_Label__c,&apos;Household&apos;),&apos;Household&apos;, $Label.RTL_Member )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Section</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Sent_to_Approval__c.field-meta.xml
<CustomField>
    <fullName>RTL_Sent_to_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to track if record is sent to approval</description>
    <label>Sent to Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_User_Requesting__c.field-meta.xml
<CustomField>
    <fullName>RTL_User_Requesting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User requesting for the change</description>
    <label>Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Household_History_and_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/RTL_Household_Member__c.object-meta.xml
<CustomObject>
    <label>Household Membership</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Household Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_Household__c.field-meta.xml
<CustomField>
    <fullName>RTL_Household__c</fullName>
    <description>Household that this member record belongs to</description>
    <label>Household</label>
    <referenceTo>RTL_Household__c</referenceTo>
    <relationshipName>Household_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_Household_Member_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_Household_Member_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of this Household Member</description>
    <label>Household Member Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Household_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_Status__c.field-meta.xml
<CustomField>
    <fullName>RTL_Status__c</fullName>
    <description>Status of this member in this Household</description>
    <label>Member Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
            <value>
                <fullName>To Delete</fullName>
            </value>
            <value>
                <fullName>Household Deleted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
                <isActive>false</isActive>
                <label>Delete</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_To_Delete__c.field-meta.xml
<CustomField>
    <fullName>RTL_To_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Soft Delete</description>
    <label>Delete Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Household_Pagination__c/RTL_Household_Pagination__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Household Pagination</label>
</CustomObject>

force-app/main/default/objects/RTL_Household_Pagination__c/fields/Page_Max_Size__c.field-meta.xml
<CustomField>
    <fullName>Page_Max_Size__c</fullName>
    <label>Page Max Size</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RTL_HouseHoldDetailExtension.cls
public class RTL_HouseHoldDetailExtension {

    public RTL_HouseHold__c household {get;set;}
    public List<RTL_Household_History_and_Approval__c > historyList {get;set;}
    public List<RTL_Household_Member__c> memberList {get;set;}
    public List<RTL_Household_History_and_Approval__c > approvalList {get;set;}
    public List<RTL_Household_History_and_Approval__c> notNotifiedHistoryList{get;set;}
    public Map<String,RTL_Household_History_Type__mdt> historyTypeMap{get;set;}
    public List<RTL_Household__c> householdList {get;set;} /*use this list to check whether household is still in the system after any history change*/
    public String membId {get;set;}
    public String histId {get;set;}
    public Boolean hasError{get;set;}
    
    private RTL_Household_Member__c primaryMember;
    private String acctId;
    private String templateId;
    private String responseTemplateId;
    public String primaryMemberId {get;set;}
    private Map<Id,RTL_Household_Member__c> memberMap;
    private PageReference householdDetailPage;
    private PageReference customerDetailPage;
    
    public Integer pageSize {get;set;}
    public Integer counter{get;set;}
    public Integer totalSize {
        get
        {
            if(totalSize == null){
                totalSize = 0;
            }
        return totalSize;
        }set;}
    
    public RTL_HouseHoldDetailExtension(ApexPages.StandardController std){ 
        household = (RTL_HouseHold__c)std.getRecord();
        templateId = [select id, name from EmailTemplate where developername = : 'RTL_Household_Approval_Mail_Template'].id;
        responseTemplateId = [select id, name from EmailTemplate where developername = : 'RTL_Household_Approval_Response_Template'].id;
        memberList = new List<RTL_HouseHold_Member__c>();
        approvalList = new List<RTL_Household_History_and_Approval__c >();
        householdDetailPage = new PageReference('/apex/RTL_Household_Detail?id='+household.id);
        householdDetailPage.setRedirect(true);
        historyTypeMap = getHistoryTypeMdt();
     
        if(null != household.id ){
            counter = 0;
            pageSize = Integer.ValueOf(RTL_Household_Pagination__c.getValues('Record Per Page').Page_Max_Size__c);
            household = queryHouseHold();
            historyList = queryHistoryList();
            memberMap = queryMember();
            primaryMember = getPrimaryMember(memberMap);
            primaryMemberId = String.ValueOf(primaryMember.RTL_Household_Member_Name__c).left(15);
            memberList = generateMemberList();
            approvalList = queryApprovalList();
            notNotifiedHistoryList = RTL_HouseholdApprovalResponseEmail.queryNotSentToRequestorHistoryList(household.id);
            customerDetailPage = new PageReference('/'+primaryMemberId);
            customerDetailPage.setRedirect(true);
            
        }
        
    }
    
     
    public PageReference submitForApproval(){
        hasError = false;
        try{
            if(household.RTL_RM__c == null || household.RTL_Approver_UserName__c == null){
                return showErrorMessage(System.Label.RTL_Household_ERR03);
            }
            
            Set<ID> memberIdSet = new Set<ID>();
            Map<Id,RTL_Household_Member__c> memberToUpdate = new Map<Id,RTL_Household_Member__c>();
            List<RTL_Household_History_and_Approval__c> historyToUpdate = new List<RTL_Household_History_and_Approval__c>();
            
            approvalList = queryApprovalList();
            for(RTL_Household_History_and_Approval__c history : approvalList){
                //if History Status = New
                if(history.RTL_Outcome__c == 'New'){       
                    history.RTL_Outcome__c = 'Pending';
                    history.RTL_Approval_Submit_User__c = UserInfo.getUserId();
                    history.RTL_User_Requesting__c = UserInfo.getUserId();
                    historyToUpdate.add(history);
                    //Keep Member Record to be locked
                    if(history.RTL_Household_Member__c != null ){
                        memberIdSet.add(history.RTL_Household_Member__c);               
                    }
                
                }     
            }
            
            if(historyToUpdate.size() > 0){
                update historyToUpdate;        
            }
            
            if(household.RTL_Status__c == 'New'){
                household.RTL_Status__c = 'Awaiting Approval';
            }
            
            update household;
            
            //Start Locking Records
            Approval.LockResult[] lrList = Approval.lock(memberList, false);

            // Iterate through each returned result
            for(Approval.LockResult lr : lrList) {
                if (lr.isSuccess()) {
                    // Operation was successful, so get the ID of the record that was processed
                }
                else {
                    // Operation failed, so get all errors                
                    for(Database.Error err : lr.getErrors()) {
                    }
                }
            }
        
            Approval.LockResult result = Approval.lock(household, false);
                if (result.isSuccess()) {
                    // Operation was successful, so get the ID of the record that was processe
                }
                else {
                    // Operation failed, so get all errors                
                    for(Database.Error err : result.getErrors()) {
                    }
                }
            System.debug('Household data ;:: '+household);
        
            //Start Sending Approval Email
            RTL_HouseholdApprovalEmail.SendEmail(household.Id);
        
            return householdDetailPage;
            
        }catch(DMLException e){
            return showErrorMessage(e.getDmlMessage(0));
        }
        catch(Exception e){
            return showErrorMessage(e.getMessage());
        }
    }
    
    public PageReference notifyRequestor(){
        RTL_HouseholdApprovalResponseEmail.SendEmail(household.Id);
        return householdDetailPage;
    }
    
    public PageReference updateHistory(List<RTL_Household_History_and_Approval__c> historyToDelete){
        hasError = false;
        try{
            
            if(historyToDelete.size() > 0){
                delete historyToDelete;
            }
            
            update approvalList;
            
        }catch(DMLException e){
            resetHistoryList();
            return showErrorMessage(e.getDmlMessage(0));
            
        }
        catch(Exception e){
            resetHistoryList();
            return showErrorMessage(e.getMessage());
        }
        //Check if household is still exists
        householdList = getHouseholdList();
        
        return null;
    }
    
    //Approve All Pending History
    public PageReference approveAll(){
        Set<Id> historyIdSet = new Set<Id>();
        Set<Id> memberIdSet = new Set<Id>();
        List<RTL_Household_History_and_Approval__c> historyToDelete = new List<RTL_Household_History_and_Approval__c>();
        for(RTL_Household_History_and_Approval__c history : approvalList){
            if(history.RTL_Outcome__c == 'Pending'){
                history.RTL_Outcome__c = 'Approved';
                
                if(history.RTL_Field_Label__c == 'Delete Member' && history.RTL_New_Value__c == 'true' && history.RTL_Household_Member__c != null){
                    historyIdSet.add(history.id);
                    memberIdSet.add(history.RTL_Household_Member__c);
                    
                }
            
            }
    
        }
        historyToDelete = [SELECT ID,Name FROM RTL_Household_History_and_Approval__c 
                                            WHERE (RTL_Outcome__c = 'New' OR RTL_Outcome__c = 'Pending') 
                                            AND ID NOT IN:historyIdSet
                                            AND RTL_Household_Member__c IN:historyIdSet];
        
        return updateHistory(historyToDelete);
        
    }
    
    //Reject All Pending History
     public PageReference rejectAll(){
        for(RTL_Household_History_and_Approval__c history : approvalList){
            if(history.RTL_Outcome__c == 'Pending'){
                history.RTL_Outcome__c = 'Rejected';
            }
            
        }
        return updateHistory(new List<RTL_Household_History_and_Approval__c>());
        
    }
    
    public Boolean getIsHouseholdEditable(){
        if(UserInfo.getUserId() == household.RTL_RM__r.ManagerId){
            return false;
        }
        if(household.RTL_Status__c == 'Deleted'){
            return false;
        }
        if(approvalList.size() > 0 ){
            if(UserInfo.getUserId() == approvalList[0].CreatedById || UserInfo.getUserId() == household.RTL_RM__c){
                return true;
            }
            return false;
        }
         return true;
    }
    
    public PageReference requestDelete(){
        approvalList = queryApprovalList();
        if(approvalList.size() >0 ){
            return showErrorMessage(System.Label.RTL_Household_ERR08);
        }
        household.RTL_To_Delete__c = true;
        update household;
        
        historyList = queryHistoryList();
        approvalList = queryApprovalList();
        return submitForApproval();
        
    }
    
    public PageReference requestDeleteMember(){
        RTL_Household_Member__c membToDelete = memberMap.get(membId);
        membToDelete.RTL_To_Delete__c = true;
        update membToDelete;
        return HouseholdDetailPage;
    }
    
    public PageReference deleteHistory(){
        hasError = false;
        try{  
            RTL_Household_History_and_Approval__c histToDelete;
            for(RTL_Household_History_and_Approval__c hist : approvalList){
                if(hist.id == histId){
                    histToDelete = hist;
                }
            }
            
            delete histToDelete;
            householdList = getHouseholdList();
        }catch(DMLException e){
            resetHistoryList();
            return showErrorMessage(e.getDmlMessage(0));
            
        }
        catch(Exception e){
            resetHistoryList();
            return showErrorMessage(e.getMessage());
        }
        //List<RTL_Household__c> householdList = [SELECT ID,Name FROM RTL_Household__c WHERE ID IN:householdIdSet];
        //if(householdList.size() == 0){
            //return CustomerDetailPage;
        //}
        return null;
        //return HouseholdDetailPage;
    }
    
    public Boolean getIsHouseholdRecordLocked(){
        return Approval.isLocked(household.id);
    }
    
    public void resetHistoryList(){
        historyList = queryHistoryList();
    }
    
    public RTL_HouseHold__c queryHouseHold(){
        RTL_HouseHold__c hh;
        hh =  [SELECT Name,RTL_RM__c,RTL_RM__r.ManagerId,RTL_Benefit_Package__c,
                      RTL_Approver_UserName__c,RTL_Status__c,RTL_Number_of_Members__c,RTL_Remarks__c,
                      RTL_Sent_To_Approval__c,CreatedById,RTL_RM__r.Name,
               (SELECT ID FROM Household_History_and_Approvals__r WHERE RTL_Outcome__c = 'New') 
               FROM RTL_HouseHold__C 
               WHERE ID=:household.id];
        return hh;
    }
    
    public List<RTL_Household_History_and_Approval__c> queryHistoryList(){
        List<RTL_Household_History_and_Approval__c> history;
        System.debug('COUNTER : '+counter);
        history = [SELECT ID,Name,RTL_Field_Changed__c,RTL_Field_Label__c,RTL_User_Requesting__c ,RTL_Prev_Value__c ,
                       RTL_New_Value__c ,RTL_Outcome__c,RTL_Date_Requested__c ,RTL_Date_Approved__c,RTL_Household_Member__c,
                        RTL_Household__c,RTL_Household__r.Name,RTL_Household_Member__r.Name,RTL_Sent_To_Approval__c,
                        RTL_Section__c,RTL_Sent_to_Requestor__c,RTL_User_Requesting__r.Name, 
                       RTL_Approver_Link__c, RTL_Approver_Link__r.Name,RTL_Member_Lookup_Account__c,RTL_Member_Lookup_Account__r.Name
                   FROM RTL_Household_History_and_Approval__c  
                   WHERE RTL_Household__c =: household.id LIMIT :pageSize OFFSET :counter];
        totalSize = [SELECT count() FROM RTL_Household_History_and_Approval__c WHERE RTL_Household__c =: household.id];
        return history;
    }
    
    public Map<Id,RTL_Household_Member__c> queryMember(){
        Map<Id,RTL_Household_Member__c> member;
        member = new Map<Id,RTL_Household_Member__c>([SELECT ID,Name,RTL_Household_Member_Name__c,RTL_TMB_Customer_ID_PE__c,
                                                      RTL_Primary__c,RTL_Benefit__c,RTL_Relationship__c,RTL_Status__c,RTL_Is_Approved__c,
                                                      RTL_To_Delete__c,RTL_Household_Member_Name__r.Name
                                                      FROM RTL_Household_Member__c  
                                                      WHERE RTL_Household__c =: household.id ORDER BY RTL_Primary__c DESC]);
        return member;
    }
    
    //put member into list  
    public List<RTL_Household_Member__c> generateMemberList(){
        List<RTL_Household_Member__c> membList = new List<RTL_HouseHold_Member__c>();
        for(RTL_Household_Member__c member : memberMap.values()){
            if(member.RTL_Is_Approved__c == true){
                membList.add(member);
            }
        }
        return membList;
    }
    
    public RTL_Household_Member__c getPrimaryMember(Map<Id,RTL_Household_Member__c> membMap){
        RTL_Household_Member__c primaryMemb;
        for(RTL_Household_Member__c memb : membMap.values()){
            if(memb.RTL_Primary__c == true){
                primaryMemb = memb;
            }
        }
        return primaryMemb;
    }
    
    public List<RTL_Household_History_and_Approval__c> queryApprovalList(){
        List<RTL_Household_History_and_Approval__c> apprvList;
        apprvList = [SELECT ID,Name,RTL_Field_Changed__c,RTL_Field_Label__c,RTL_User_Requesting__c ,RTL_Prev_Value__c ,
                       RTL_New_Value__c ,RTL_Outcome__c,RTL_Date_Requested__c ,RTL_Date_Approved__c,RTL_Household_Member__c,
                        RTL_Household__c,RTL_Household__r.Name,RTL_Household_Member__r.Name,RTL_Sent_To_Approval__c,
                        RTL_Section__c,RTL_Sent_to_Requestor__c,RTL_User_Requesting__r.Name,RTL_Approver_Link__c,
                        CreatedById,RTL_Member_Lookup_Account__c,RTL_Member_Lookup_Account__r.Name
                   FROM RTL_Household_History_and_Approval__c  
                   WHERE RTL_Outcome__c != 'Approved' AND RTL_Outcome__c != 'Rejected' 
                   AND RTL_Household__c =: household.id];
        return apprvList;
    }
    
    public PageReference showErrorMessage(String errMsg){
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,errMsg));
        hasError = true;
        return null;
    }
    
    public PageReference Previous() { //user clicked previous button
      counter -= pageSize;
      historyList = queryHistoryList();
      return null;
   }
    
    public PageReference  Next() { //user clicked next button
      counter += pageSize;
      historyList = queryHistoryList();
      return null;
   }
    
    public PageReference First(){
        counter = 0;
        historyList = queryHistoryList();
        return null;
    }
    
    public PageReference Last(){
        Decimal page = ((Decimal)totalSize/(Decimal)pageSize);
        Integer LastPage = Integer.ValueOf(page.round(System.RoundingMode.CEILING));
        counter = (LastPage-1) * pageSize;
        historyList = queryHistoryList();
        return null;
    }
    
    public boolean  getDisableNext() { //user clicked next button   
        if((counter + pageSize) >= totalSize) {
            return true;
        }else{
            return false;
        }
   }
    
    public boolean  getDisablePrevious() { //user clicked next button     
        if(counter == 0) {
            return true;
        }else{
            return false;
        }
    }
    
    //This method used to check if the Household is still exists in the database
    public List<RTL_Household__c> getHouseholdList(){
        Set<Id> householdIdSet = new Set<Id>{household.id};
        List<RTL_Household__c> householdList = new List<RTL_Household__c>();
        householdList = [SELECT ID,Name FROM RTL_Household__c WHERE ID IN:householdIdSet];
        return householdList;
    }
    
    public Map <String,RTL_Household_History_Type__mdt > getHistoryTypeMdt(){
        Map <String,RTL_Household_History_Type__mdt > historyTypeMap = new Map <String,RTL_Household_History_Type__mdt >();
        
        for(RTL_Household_History_Type__mdt historyType : [SELECT Id,MasterLabel ,DeveloperName ,RTL_English_Value__c , RTL_Thai_Value__c FROM RTL_Household_History_Type__mdt ]){
            historyTypeMap.put(historyType.RTL_English_Value__c,historyType);
            historyTypeMap.put(historyType.RTL_Thai_Value__c,historyType);
        }
        return historyTypeMap;
    }

}