force-app/main/default/objects/RTL_Household__c/RTL_Household__c.object-meta.xml
<CustomObject>
    <label>Household</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Household__c/fields/RTL_Sent_to_Approval__c.field-meta.xml
<CustomField>
    <fullName>RTL_Sent_to_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sent to Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Household__c/fields/RTL_Status__c.field-meta.xml
<CustomField>
    <fullName>RTL_Status__c</fullName>
    <description>Status of this Household</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>To Delete</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
                <isActive>false</isActive>
                <label>Delete</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Revisit</fullName>
                <isActive>false</isActive>
                <label>Revisit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Household__c/fields/RTL_To_Delete__c.field-meta.xml
<CustomField>
    <fullName>RTL_To_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Soft delete</description>
    <label>Delete Household</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/RTL_Household_History_and_Approval__c.object-meta.xml
<CustomObject>
    <label>Household History and Approval</label>
    <nameField>
        <displayFormat>HH-{00000000}</displayFormat>
        <label>Household History and Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Household History and Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Date_Approved__c.field-meta.xml
<CustomField>
    <fullName>RTL_Date_Approved__c</fullName>
    <description>Date this change was Approved</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Date_Requested__c.field-meta.xml
<CustomField>
    <fullName>RTL_Date_Requested__c</fullName>
    <description>Date change was requested</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Requested Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Field_Changed__c.field-meta.xml
<CustomField>
    <fullName>RTL_Field_Changed__c</fullName>
    <description>Field to be changed</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Changed Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Field_Label__c.field-meta.xml
<CustomField>
    <fullName>RTL_Field_Label__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Household__c.field-meta.xml
<CustomField>
    <fullName>RTL_Household__c</fullName>
    <description>Household which this History record belongs to</description>
    <label>Household</label>
    <referenceTo>RTL_Household__c</referenceTo>
    <relationshipLabel>Household History and Approvals</relationshipLabel>
    <relationshipName>Household_History_and_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Household_Member__c.field-meta.xml
<CustomField>
    <fullName>RTL_Household_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Household member which this change is related to</description>
    <label>Household Member</label>
    <referenceTo>RTL_Household_Member__c</referenceTo>
    <relationshipLabel>Household History and Approvals</relationshipLabel>
    <relationshipName>Household_History_and_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_New_Value__c.field-meta.xml
<CustomField>
    <fullName>RTL_New_Value__c</fullName>
    <description>New value to be set</description>
    <encryptionScheme>None</encryptionScheme>
    <label>New Value</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Outcome__c.field-meta.xml
<CustomField>
    <fullName>RTL_Outcome__c</fullName>
    <description>Outcome of this Household History</description>
    <label>Outcome</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Prev_Value__c.field-meta.xml
<CustomField>
    <fullName>RTL_Prev_Value__c</fullName>
    <description>Old value of this change</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Old Value</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Sent_to_Approval__c.field-meta.xml
<CustomField>
    <fullName>RTL_Sent_to_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to track if record is sent to approval</description>
    <label>Sent to Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_User_Requesting__c.field-meta.xml
<CustomField>
    <fullName>RTL_User_Requesting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User requesting for the change</description>
    <label>Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Household_History_and_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/RTL_Household_Member__c.object-meta.xml
<CustomObject>
    <label>Household Membership</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Household Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_Benefit__c.field-meta.xml
<CustomField>
    <fullName>RTL_Benefit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Member is entitled to Household Benefit</description>
    <label>Benefit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_Household__c.field-meta.xml
<CustomField>
    <fullName>RTL_Household__c</fullName>
    <description>Household that this member record belongs to</description>
    <label>Household</label>
    <referenceTo>RTL_Household__c</referenceTo>
    <relationshipName>Household_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_Household_Member_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_Household_Member_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of this Household Member</description>
    <label>Household Member Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Household_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_Primary__c.field-meta.xml
<CustomField>
    <fullName>RTL_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates this member is the Primary member of this Household</description>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_Relationship__c.field-meta.xml
<CustomField>
    <fullName>RTL_Relationship__c</fullName>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>คู่สมรส</fullName>
            </value>
            <value>
                <fullName>บิดา/มารดา</fullName>
            </value>
            <value>
                <fullName>บุตร</fullName>
            </value>
            <value>
                <fullName>พี่น้อง</fullName>
            </value>
            <value>
                <fullName>ปู่/ย่า/ตา/ยาย</fullName>
            </value>
            <value>
                <fullName>หลาน</fullName>
            </value>
            <value>
                <fullName>ญาติ</fullName>
            </value>
            <value>
                <fullName>อื่นๆ</fullName>
            </value>
            <value>
                <fullName>Child of</fullName>
                <isActive>false</isActive>
                <label>Child of</label>
            </value>
            <value>
                <fullName>Grandchild of</fullName>
                <isActive>false</isActive>
                <label>Grandchild of</label>
            </value>
            <value>
                <fullName>Grandparent of</fullName>
                <isActive>false</isActive>
                <label>Grandparent of</label>
            </value>
            <value>
                <fullName>Others of</fullName>
                <isActive>false</isActive>
                <label>Others of</label>
            </value>
            <value>
                <fullName>Parent of</fullName>
                <isActive>false</isActive>
                <label>Parent of</label>
            </value>
            <value>
                <fullName>Relative of</fullName>
                <isActive>false</isActive>
                <label>Relative of</label>
            </value>
            <value>
                <fullName>Sibling of</fullName>
                <isActive>false</isActive>
                <label>Sibling of</label>
            </value>
            <value>
                <fullName>Spouse of</fullName>
                <isActive>false</isActive>
                <label>Spouse of</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_Status__c.field-meta.xml
<CustomField>
    <fullName>RTL_Status__c</fullName>
    <description>Status of this member in this Household</description>
    <label>Member Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
            <value>
                <fullName>To Delete</fullName>
            </value>
            <value>
                <fullName>Household Deleted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
                <isActive>false</isActive>
                <label>Delete</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_TMB_Customer_ID_PE__c.field-meta.xml
<CustomField>
    <fullName>RTL_TMB_Customer_ID_PE__c</fullName>
    <description>TMB Customer ID for Integration purposes</description>
    <formula>RTL_Household_Member_Name__r.TMB_Customer_ID_PE__c</formula>
    <label>TMB Customer ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_To_Delete__c.field-meta.xml
<CustomField>
    <fullName>RTL_To_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Soft Delete</description>
    <label>Delete Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RTL_HouseholdHistoryTriggerHandlerTest.cls
@isTest
public class RTL_HouseholdHistoryTriggerHandlerTest {
    
    static User rmUser;
    static User rmManager;
    static List<Account> acctList;
    static List<RTL_Household__c> householdList;
    static List<RTL_Household_Member__c> memberList;
    static List<RTL_Household_History_And_Approval__c> historyList;
    
    static{
        TestUtils.createAppConfig();
        rmUser = RTL_TestUtility.createRetailTestUserWithBranch(true);
        rmManager = RTL_TestUtility.createRetailTestUser(true);
        acctList = RTL_TestUtility.createAccounts(2,true);
        householdList = RTL_TestUtility2.createHouseholdwithPrimaryMember(1,true,rmUser,acctList[0]);
        
    }
    static testmethod void testApproveInsertHousehold(){
        Test.startTest();
            historyList = getHistoryList();
            
            for(RTL_Household_History_and_Approval__c history : historyList){
                history.RTL_Outcome__c = 'Approved';
            }
            
            update historyList;
        
            //Check Result : Verify that history outcome set to Approved;
            historyList = [SELECT Id,Name,RTL_Outcome__c FROM RTL_Household_History_and_Approval__c WHERE ID IN:historyList];
            System.assertEquals('Approved', historyList[0].RTL_Outcome__c);
            householdList = [SELECT ID,Name,RTL_Status__c FROM RTL_Household__c ];
            System.assertEquals('Approved', householdList[0].RTL_Status__c);    
            
            
        Test.stopTest();
        
    }
    
    static testmethod void testApproveInsertMember(){
        RTL_Household_Member__c member = RTL_TestUtility2.createHouseholdMember(true, householdList[0].id, acctList[1]);
        Test.startTest();
            historyList = getHistoryList();
            
            for(RTL_Household_History_and_Approval__c history : historyList){
                history.RTL_Outcome__c = 'Approved';
            }
            
            update historyList;
        
            //Check Result : Verify that history outcome set to Approved;
            historyList = [SELECT Id,Name,RTL_Outcome__c FROM RTL_Household_History_and_Approval__c WHERE ID IN:historyList];
            System.assertEquals('Approved', historyList[0].RTL_Outcome__c);
            System.assertEquals('Approved', historyList[1].RTL_Outcome__c);
            
            
        Test.stopTest();
        
    }
    
    static testmethod void testRejectInsertHousehold(){
        Test.startTest();
            historyList = getHistoryList();
            
            for(RTL_Household_History_and_Approval__c history : historyList){
                history.RTL_Outcome__c = 'Rejected';
            }
            
            update historyList;
        
            //Check Result : Verify that history outcome set to Approved;
            historyList = [SELECT Id,Name,RTL_Outcome__c FROM RTL_Household_History_and_Approval__c WHERE ID IN:historyList];
            System.assertEquals(0, historyList.size());
            
            
        Test.stopTest();
        
    }
    
    static testmethod void testRMCancelInsertHousehold(){
        Test.startTest();
            historyList = getHistoryList();         
            delete historyList;
        
            //Check Result : Verify that history outcome set to Approved;
            historyList = [SELECT Id,Name,RTL_Outcome__c FROM RTL_Household_History_and_Approval__c WHERE ID IN:historyList];
            System.assertEquals(0, historyList.size());
            
            
        Test.stopTest();
        
    }
    
    static testmethod void testRejectInsertMember(){
        RTL_Household_Member__c member = RTL_TestUtility2.createHouseholdMember(true, householdList[0].id, acctList[1]);
        Test.startTest();
            historyList = getHistoryList();
            
            historyList[0].RTL_Outcome__c = 'Approved';
            historyList[1].RTL_Outcome__c = 'Rejected';
            
            update historyList;
        
            //Check Result : Verify that history outcome set to Approved;
            historyList = [SELECT Id,Name,RTL_Outcome__c FROM RTL_Household_History_and_Approval__c WHERE ID IN:historyList];
            System.debug('MEMBER HISTORY :: '+historyList[1]);
            System.assertEquals('Approved', historyList[0].RTL_Outcome__c);
            System.assertEquals('Rejected', historyList[1].RTL_Outcome__c);
            
            
        Test.stopTest();
        
    }
    
    static testmethod void testApprovedUpdateMember(){
        Test.startTest();
            RTL_Household_Member__c member = RTL_TestUtility2.createHouseholdMember(true, householdList[0].id, acctList[1]);
            historyList = getHistoryList();
            
            for(RTL_Household_History_and_Approval__c history : historyList){
                history.RTL_Outcome__c = 'Approved';
            }
            
            update historyList;
            
            RTL_HouseholdHistoryTriggerHandler.historyTrigger = false;
            member.RTL_Benefit__c = true;
            member.RTL_Relationship__c = 'ปู่/ย่า/ตา/ยาย';
            member.RTL_status__c = 'Approved';
            update member;
        
            //Check Result : Verify that history outcome set to Approved;
            historyList = [SELECT Id,Name,RTL_Outcome__c FROM RTL_Household_History_and_Approval__c WHERE ID IN:historyList];
            System.assertEquals('Approved', historyList[0].RTL_Outcome__c);
            System.assertEquals('Approved', historyList[1].RTL_Outcome__c);
        
            historyList = getHistoryList();
            System.assertEquals(4, historyList.size());
            
            for(RTL_Household_History_and_Approval__c history : historyList){
                history.RTL_Outcome__c = 'Approved';
            }
            update historyList;
            
        Test.stopTest();
        
    }
    
    
    
    static testmethod void testApproveHouseholdDeletion(){
        Test.startTest();
            historyList = getHistoryList();
            historyList[0].RTL_Outcome__c = 'Approved';
            
            update historyList;
        

            RTL_HouseholdHistoryTriggerHandler.historyTrigger = false;
            householdList = [SELECT ID,Name,RTL_Status__c FROM RTL_Household__c ];
            //Update household status to To Delete in order to delete the household
            householdList[0].RTL_To_Delete__c = true;
            update householdList;
        
            //Approved to Delete
            historyList = getHistoryList();
            historyList[1].RTL_Outcome__c = 'Approved';
            update historyList;
            
            //Check Result : Verify that house hold status is changed to Delete
            RTL_Household__c household = [SELECT ID,Name,RTL_Status__c FROM RTL_Household__c WHERE Id =:householdList[0].id ];
            System.assertEquals('Deleted', household.RTL_Status__c);
        
            
        Test.stopTest();
        
    }
    
    static testmethod void testApproveHouseholdMemberDeletion(){
        RTL_Household_Member__c member = RTL_TestUtility2.createHouseholdMember(true, householdList[0].id, acctList[1]);
        Test.startTest();
            historyList = getHistoryList();
            historyList[0].RTL_Outcome__c = 'Approved';
            historyList[1].RTL_Outcome__c = 'Approved';
            update historyList;
        
            RTL_HouseholdHistoryTriggerHandler.historyTrigger = false;
            memberList = getMember();
            //Check Result : there must be 2 member in the system.
            System.assertEquals(2, memberList.size());
            memberList[1].RTL_To_Delete__c = true;
            update memberList;
            
            historyList = getHistoryList();
            historyList[2].RTL_Outcome__c = 'Approved';
            update historyList;
            memberList = getMember();
            //Check Result : Verify that member was deleted;
            System.assertEquals(1, memberList.size());
            
            
        Test.stopTest();
        
    }
    
    static testmethod void testRejectHouseholdDeletion(){
        Test.startTest();
            historyList = getHistoryList();
            historyList[0].RTL_Outcome__c = 'Approved';
            
            update historyList;
            
            RTL_HouseholdHistoryTriggerHandler.historyTrigger = false;
            householdList = [SELECT ID,Name,RTL_Status__c FROM RTL_Household__c ];
            System.debug('HH'+householdList);
            //Update household status to To Delete in order to delete the household
            householdList[0].RTL_To_Delete__c = true;
            update householdList;
        
            //Approved to Delete
            historyList = getHistoryList();
            System.debug('HISTORY LIST '+historyList);
            historyList[1].RTL_Outcome__c = 'Rejected';
            update historyList;
            
            //Check Result : Verify that house hold status is changed to Delete
            RTL_Household__c household = [SELECT ID,Name,RTL_Status__c FROM RTL_Household__c WHERE Id =:householdList[0].id ];
            System.assertEquals('Approved', household.RTL_Status__c);
        
            
        Test.stopTest();
        
    }
    
    static testmethod void testRejectHouseholdMemberDeletion(){
        RTL_Household_Member__c member = RTL_TestUtility2.createHouseholdMember(true, householdList[0].id, acctList[1]);
        Test.startTest();
            historyList = getHistoryList();
            historyList[0].RTL_Outcome__c = 'Approved';
            historyList[1].RTL_Outcome__c = 'Approved';
            update historyList;
        
            RTL_HouseholdHistoryTriggerHandler.historyTrigger = false;
            memberList = getMember();
            //Check Result : there must be 2 member in the system.
            System.assertEquals(2, memberList.size());
            memberList[1].RTL_To_Delete__c = true;
            update memberList;
            
            historyList = getHistoryList();
            historyList[2].RTL_Outcome__c = 'Rejected';
            update historyList;
            memberList = getMember();
            //Check Result : Verify that member was deleted;
            System.assertEquals(2, memberList.size());
            
            
        Test.stopTest();
        
    }

    
    static testmethod void testCancelHouseholdMemberDeletion(){
       RTL_Household_Member__c member = RTL_TestUtility2.createHouseholdMember(true, householdList[0].id, acctList[1]);
        Test.startTest();
            historyList = getHistoryList();
            historyList[0].RTL_Outcome__c = 'Approved';
            historyList[1].RTL_Outcome__c = 'Approved';
            update historyList;
            
            RTL_HouseholdHistoryTriggerHandler.historyTrigger = false;
            member.RTL_To_Delete__c = true;
            member.RTL_Status__c = 'Approved';
            update member;
            
            historyList = getHistoryList();
            delete historyList[2];
        
            //Check Result : Verify that history outcome set to Approved;
            member = [SELECT ID,RTL_To_Delete__c FROM RTL_Household_Member__c WHERE Id=:member.id];
        	System.assertEquals(false, member.RTL_To_Delete__c);
            
        Test.stopTest();
        
    }
    
    static testmethod void testCancelInsertMember(){
       RTL_Household_Member__c member = RTL_TestUtility2.createHouseholdMember(true, householdList[0].id, acctList[1]);
        Test.startTest();
            historyList = getHistoryList();
            delete HistoryList[1];
        
            //Check Result : Verify that history outcome set to Approved;
            historyList = [SELECT Id,Name,RTL_Outcome__c FROM RTL_Household_History_and_Approval__c WHERE ID IN:historyList];
            memberList = getMember();
            System.assertEquals(1, historyList.size());
            System.assertEquals(1, memberList.size());
            
        Test.stopTest();
        
    }

    
    public static List<RTL_Household_Member__c> getMember(){
        List<RTL_Household_Member__c> memberToReturn;
        memberToReturn = [SELECT ID,Name,RTL_Household_Member_Name__c,RTL_TMB_Customer_ID_PE__c,
                                 RTL_Primary__c,RTL_Benefit__c,RTL_Relationship__c,RTL_Status__c 
                                 FROM RTL_Household_Member__c ];
        return memberToReturn;
    }
    
    public static List<RTL_Household_History_and_Approval__c> getHistoryList(){
        List<RTL_Household_History_and_Approval__c> historyToReturn;
        
        historyToReturn = [SELECT ID,Name,RTL_Field_Changed__c,RTL_Field_Label__c,RTL_User_Requesting__c ,RTL_Prev_Value__c ,
                            RTL_New_Value__c ,RTL_Outcome__c,RTL_Date_Requested__c ,RTL_Date_Approved__c,RTL_Household_Member__c,
                            RTL_Household__c,RTL_Household__r.Name,RTL_Household_Member__r.Name,RTL_Sent_To_Approval__c
                            FROM RTL_Household_History_and_Approval__c];
        
        return historyToReturn;
    }
    
    
}