force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/RTL_Lead_Assignment_Rule__c.object-meta.xml
<CustomObject>
    <description>For setup condition for assign owner to Lead when created.</description>
    <label>Lead Assignment</label>
    <nameField>
        <displayFormat>RTLLA-{000000}</displayFormat>
        <label>Lead Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Active_Flag__c.field-meta.xml
<CustomField>
    <fullName>RTL_Active_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Assigned_User_field__c.field-meta.xml
<CustomField>
    <fullName>RTL_Assigned_User_field__c</fullName>
    <label>2.2 Assigned User field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OwnerId</fullName>
            </value>
            <value>
                <fullName>Referred_Staff__c</fullName>
            </value>
            <value>
                <fullName>RTL_Employee_ID__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Integration_Type__c.field-meta.xml
<CustomField>
    <fullName>RTL_Integration_Type__c</fullName>
    <description>Values: &quot;Cisco&quot;, &quot;Avaya&quot;</description>
    <label>Integration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Avaya</fullName>
                <isActive>false</isActive>
                <label>Avaya</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_IsAssign_Campaign__c.field-meta.xml
<CustomField>
    <fullName>RTL_IsAssign_Campaign__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Update to field RTL_IsAssign_Campaign__c in object Lead.</description>
    <label>Is Assign Campaign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_IsInsertProduct__c.field-meta.xml
<CustomField>
    <fullName>RTL_IsInsertProduct__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Use this flag to clarify is auto create interested product</description>
    <inlineHelpText>Use product from lead field RTL_Product_name</inlineHelpText>
    <label>Is Create Interested Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Lead_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>RTL_Lead_Record_Type__c</fullName>
    <label>Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial Account</fullName>
            </value>
            <value>
                <fullName>Commercial Completed</fullName>
            </value>
            <value>
                <fullName>Commercial Lead</fullName>
            </value>
            <value>
                <fullName>Retail Banking</fullName>
                <default>true</default>
                <label>Retail Banking</label>
            </value>
            <value>
                <fullName>Retail Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Priority__c.field-meta.xml
<CustomField>
    <fullName>RTL_Priority__c</fullName>
    <label>Priority</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CallMeNowLeadBatchTest.cls
@isTest
public class CallMeNowLeadBatchTest {
    static{
        TestUtils.createAppConfig();

        RTL_Lead_Assignment_Rule__c leadAssignmentrule = new RTL_Lead_Assignment_Rule__c ();
        leadAssignmentrule.RTL_Active_Flag__c = true;
        leadAssignmentrule.RTL_Priority__c = 0;
        leadAssignmentrule.RTL_IsInsertProduct__c = true;
        leadAssignmentrule.RTL_Assigned_User_field__c = 'OwnerId';
        leadAssignmentrule.RTL_IsAssign_Campaign__c = true;
        leadAssignmentrule.RTL_Lead_Record_Type__c = 'Retail Banking';
        leadAssignmentrule.RTL_Integration_Type__c = 'Cisco';

        insert leadAssignmentrule;

        RTL_TestUtility.enableWebToLeadAutoAssign(true);
        RTL_TestUtility.createCampaignAssignmentRule();
    }
    
    @isTest 
    static void CallMeNowLeadBatchTest() {
        RTL_TestUtility.createRetailMasterProducts(true);
        List<lead> leadList = RTL_TestUtility.createLeads(1,false);
        leadList.get(0).RTL_Web_Unique_ID_c__c = '989988712';
        leadList.get(0).RTL_Call_Back_Date_time__c = Datetime.now();
        leadList.get(0).RTL_TMB_Campaign_Source__c = 'Web';
        leadList.get(0).RTL_Contact_Method__c = 'Call Me Later';
        leadList.get(0).RTL_AL_Leasing_Condition__c = 'LeasingTest';
        leadList.get(0).RTL_AL_Car_Status__c = 'TestCarStatus';
        
        Test.startTest();
        insert leadList;
        Datetime nextBH = CallMeNowLeadBatch.getNextnBSDate();
        // RTL_TestUtility.createInterestedProducts(leadList, true);
        Test.stopTest();
    }
}