force-app/main/default/objects/S2O_Code_Mapping__c/S2O_Code_Mapping__c.object-meta.xml
<CustomObject>
    <label>S2O Code Mapping</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>S2O Code Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>S2O Code Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/S2O_Code_Mapping__c/fields/CRM_Task_Key__c.field-meta.xml
<CustomField>
    <fullName>CRM_Task_Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>CRM Task Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/S2O_Code_Mapping__c/fields/EWM_Service_EN_Type_Desc__c.field-meta.xml
<CustomField>
    <fullName>EWM_Service_EN_Type_Desc__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>EWM Service EN Type Desc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S2O_Code_Mapping__c/fields/EWM_Service_TH_Type_Desc__c.field-meta.xml
<CustomField>
    <fullName>EWM_Service_TH_Type_Desc__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>EWM Service TH Type Desc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S2O_Code_Mapping__c/fields/EWM_Service_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>EWM_Service_Type_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>EWM Service Type Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/S2OUtil.cls
public without sharing class S2OUtil {
	
	public static Map<String,S2O_Code_Mapping__c> getAllS2OCodeMap() {
		Map<String,S2O_Code_Mapping__c> s20Map = new Map<String,S2O_Code_Mapping__c>();

		List<S2O_Code_Mapping__c> s2oCodeList = [SELECT Id
													   ,CRM_Task_Key__c
													   ,EWM_Service_Type_Code__c
														,EWM_Service_EN_Type_Desc__c
														,EWM_Service_TH_Type_Desc__c
												FROM S2O_Code_Mapping__c 
												WHERE isActive__c = true
												];

		for (S2O_Code_Mapping__c codeMapping : s2oCodeList) {
			s20Map.put(codeMapping.CRM_Task_Key__c.toLowerCase().replace(' ',''),codeMapping);
		}

		return s20Map;
	}
}