force-app/main/default/objects/Skill_Master__c/Skill_Master__c.object-meta.xml
<CustomObject>
    <label>Skill Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Skill Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skill Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Master__c/fields/Assign_to_Queue__c.field-meta.xml
<CustomField>
    <fullName>Assign_to_Queue__c</fullName>
    <description>Assign to Queue</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Assign to Queue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/Social_Post__c.object-meta.xml
<CustomObject>
    <label>Warroom Social Post</label>
    <nameField>
        <displayFormat>SP-{yyyy}{mm}-{00000}</displayFormat>
        <label>Social Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warroom Social Posts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Post__c/fields/LastTransferUser__c.field-meta.xml
<CustomField>
    <fullName>LastTransferUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Streaming API subscribe filter</description>
    <label>LastTransferUser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Warroom_Social_Posts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Source_Channel__c.field-meta.xml
<CustomField>
    <fullName>Source_Channel__c</fullName>
    <label>Source Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Facebook Inbox</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>LINE</fullName>
            </value>
            <value>
                <fullName>LINE Account Connect</fullName>
            </value>
            <value>
                <fullName>Pantip</fullName>
            </value>
            <value>
                <fullName>Pantip Inbox</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>Twitter Inbox</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Google Business Review</fullName>
            </value>
            <value>
                <fullName>Google Business QA</fullName>
            </value>
            <value>
                <fullName>Warroom Connect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Post Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post_Transfer_log__c/Social_Post_Transfer_log__c.object-meta.xml
<CustomObject>
    <description>Logging for transfer post</description>
    <label>Social Post Transfer log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Social Post Transfer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Post Transfer logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Post_Transfer_log__c/fields/Transfer_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Datetime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Transfer Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Social_Post_Transfer_log__c/fields/Transfer_From__c.field-meta.xml
<CustomField>
    <fullName>Transfer_From__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Transfer From</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post_Transfer_log__c/fields/Transfer_To__c.field-meta.xml
<CustomField>
    <fullName>Transfer_To__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Transfer To</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/transferAgentController.cls
public without sharing class transferAgentController {
    public virtual class BaseException extends Exception {
    }
    public class OtherException extends BaseException {
    }
    @AuraEnabled
    public static String changeOwner(Id recordId, Id ownerId, String type) {
        Social_Post__c selectedPost = [SELECT Id, Name, OwnerId, Owner.Name, LastTransferUser__c, Status__c FROM Social_Post__c WHERE Id = :recordId LIMIT 1];
        if (selectedPost.OwnerId == ownerId) {
            throw new OtherException('Owner cannot be duplicated.');
        } else {
            // Social_Post_Transfer_log__c changelog = new Social_Post_Transfer_log__c();
            //changelog.Social_Post__c = recordId; comment for change SocialPost to Social_Post__c object
            // changelog.Transfer_Datetime__c = Datetime.now();
            // changelog.Transfer_From__c = selectedPost.Owner.Name;
            // if (type == 'user') {
                // changelog.Transfer_To__c = [SELECT Id, Name FROM User WHERE Id = :ownerId LIMIT 1].Name;
            // } else if (type == 'queue') {
                // changelog.Transfer_To__c = [SELECT Id, Name FROM Group WHERE Id = :ownerId LIMIT 1].Name;
            // }
            // insert changelog;
            // selectedPost.OwnerId = ownerId;
            // update selectedPost;
            ServiceChannel chatServiceChannel = [SELECT Id FROM ServiceChannel WHERE relatedEntity = :'Social_Post__c' WITH SECURITY_ENFORCED LIMIT 1];
            if (type == 'user') {
                PendingServiceRouting psr = new PendingServiceRouting();
                psr.workItemId = recordId;
                psr.RoutingType = 'SkillsBased';
                psr.RoutingPriority = 1;
                psr.CapacityWeight = 0;
                // psr.ServiceChannelId = '0N90l0000008P2SCAU';
                psr.ServiceChannelId = chatServiceChannel.Id;
                psr.RoutingModel = 'MostAvailable';
                psr.IsReadyForRouting = true;
                psr.preferredUserId = ownerId;
                psr.CustomRequestedDateTime = System.now();
                psr.PushTimeout = 120;
                insert psr;
            } else {
                selectedPost.OwnerId = ownerId;
            }
            // selectedPost.LastTransferUser__c = UserInfo.getUserId();
            selectedPost.LastTransferUser__c = null;
            selectedPost.Status__c = 'Transfer';
            update selectedPost;
            return selectedPost.Name;
        }
    }
    @AuraEnabled
    public static List<String> queueCondition(Id recordId) {
        // Social_Post__c selectedPost = [SELECT Id, OwnerId, Provider FROM Social_Post__c WHERE Id =: recordId LIMIT 1];
        Social_Post__c selectedPost = [
            SELECT Id, OwnerId, Source_Channel__c
            FROM Social_Post__c
            WHERE Id = :recordId
            LIMIT 1
        ];
        List<String> returnValue = new List<String>();
        id currentuserId = Userinfo.getUserId();
        if (selectedPost.OwnerId == currentuserId) {
            // String socialNetwork = selectedPost.Provider;
            String socialNetwork = selectedPost.Source_Channel__c;
            List<Skill_Master__c> skillList = [
                SELECT Id, Assign_to_Queue__c
                FROM Skill_Master__c
                WHERE Assign_to_Queue__c LIKE 'Post%'
            ];
            for (Skill_Master__c skill : skillList) {
                returnValue.add('\'' + skill.Assign_to_Queue__c + '\'');
            }
            // if (socialNetwork == 'Facebook') {
            //     returnValue.add('\'Post_TTB_Advisory\'');
            //     returnValue.add('\'Post_TTB_Bank\'');
            //     returnValue.add('\'Post_TTB_Drive\'');
            //     returnValue.add('\'Post_KOL\'');
            //     returnValue.add('\'Post_BOT\'');
            // } else if (socialNetwork == 'Other') {
            //     returnValue.add('\'Post_Pantip\'');
            // } else {
            //     returnValue.add('\'Post_Twitter\'');
            // }
        } else {
            throw new OtherException('You must be owner of this post.');
        }
        return returnValue;
    }
}