force-app/main/default/objects/FX_Order__c/FX_Order__c.object-meta.xml
<CustomObject>
    <label>FX Order</label>
    <nameField>
        <displayFormat>FX-{YYMMDD}-{000}</displayFormat>
        <label>FX Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FX Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FX_Order__c/fields/FXO_BuySell__c.field-meta.xml
<CustomField>
    <fullName>FXO_BuySell__c</fullName>
    <label>Bank Buy/Bank Sell</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_Currency__c.field-meta.xml
<CustomField>
    <fullName>FXO_Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>CNH</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>DKK</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>IDR</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>LAK</fullName>
            </value>
            <value>
                <fullName>MYR</fullName>
            </value>
            <value>
                <fullName>NOK</fullName>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
            <value>
                <fullName>RUB</fullName>
            </value>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>TWD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_CurrencyPair__c.field-meta.xml
<CustomField>
    <fullName>FXO_CurrencyPair__c</fullName>
    <label>Currency Pair</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FXO_Currency__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>USD/THB</fullName>
            </value>
            <value>
                <fullName>CAD/THB</fullName>
            </value>
            <value>
                <fullName>AUD/THB</fullName>
            </value>
            <value>
                <fullName>AED/THB</fullName>
            </value>
            <value>
                <fullName>CHF/THB</fullName>
            </value>
            <value>
                <fullName>CNH/THB</fullName>
            </value>
            <value>
                <fullName>CNY/THB</fullName>
            </value>
            <value>
                <fullName>DKK/THB</fullName>
            </value>
            <value>
                <fullName>EUR/THB</fullName>
            </value>
            <value>
                <fullName>GBP/THB</fullName>
            </value>
            <value>
                <fullName>HKD/THB</fullName>
            </value>
            <value>
                <fullName>IDR/THB</fullName>
            </value>
            <value>
                <fullName>JPY/THB</fullName>
            </value>
            <value>
                <fullName>LAK/THB</fullName>
            </value>
            <value>
                <fullName>MYR/THB</fullName>
            </value>
            <value>
                <fullName>NOK/THB</fullName>
            </value>
            <value>
                <fullName>NZD/THB</fullName>
            </value>
            <value>
                <fullName>RUB/THB</fullName>
            </value>
            <value>
                <fullName>SEK/THB</fullName>
            </value>
            <value>
                <fullName>SGD/THB</fullName>
            </value>
            <value>
                <fullName>TWD/THB</fullName>
            </value>
            <value>
                <fullName>AUD/JPY</fullName>
            </value>
            <value>
                <fullName>AUD/USD</fullName>
            </value>
            <value>
                <fullName>EUR/AUD</fullName>
            </value>
            <value>
                <fullName>EUR/CHF</fullName>
            </value>
            <value>
                <fullName>EUR/GBP</fullName>
            </value>
            <value>
                <fullName>EUR/JPY</fullName>
            </value>
            <value>
                <fullName>EUR/USD</fullName>
            </value>
            <value>
                <fullName>GBP/JPY</fullName>
            </value>
            <value>
                <fullName>GBP/USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_Customer__c.field-meta.xml
<CustomField>
    <fullName>FXO_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FX Order</relationshipLabel>
    <relationshipName>FX_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_CustomerRate__c.field-meta.xml
<CustomField>
    <fullName>FXO_CustomerRate__c</fullName>
    <label>Customer Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>FXO_Expiration_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_FillAmount__c.field-meta.xml
<CustomField>
    <fullName>FXO_FillAmount__c</fullName>
    <label>Fill Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_GTC__c.field-meta.xml
<CustomField>
    <fullName>FXO_GTC__c</fullName>
    <defaultValue>true</defaultValue>
    <label>GTC (Good &apos;Til Cancelled)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_InterbankRate__c.field-meta.xml
<CustomField>
    <fullName>FXO_InterbankRate__c</fullName>
    <label>Interbank Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>FXO_OrderStatus__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Acknowledge</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Not Allocated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_RequestAmount__c.field-meta.xml
<CustomField>
    <fullName>FXO_RequestAmount__c</fullName>
    <label>Request Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>FXO_Submitted_By__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Submitted By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_Submitted_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>FXO_Submitted_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Submitted Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/Owner_s_Segment__c.field-meta.xml
<CustomField>
    <fullName>Owner_s_Segment__c</fullName>
    <formula>Owner:User.Reporting_Segment__c</formula>
    <label>Owner&apos;s Segment (Formula)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/Owner_s_Segment_stamp__c.field-meta.xml
<CustomField>
    <fullName>Owner_s_Segment_stamp__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Owner&apos;s Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FXOrderSubmitToTraderController_Test.cls
@isTest
private class FXOrderSubmitToTraderController_Test {
	
	@TestSetup static void setup() {
		FX_Order__c fxor = new FX_Order__c();
		fxor.FXO_OrderStatus__c = FXOrderTriggerHandler.NEW_STATUS;
		fxor.FXO_BuySell__c = 'Sell';
		fxor.FXO_Currency__c = 'JPY';
		fxor.FXO_CurrencyPair__c = 'JPY/THB';
		fxor.FXO_CustomerRate__c = 0.225;
		fxor.FXO_RequestAmount__c = 50000000;
		fxor.Owner_s_Segment_stamp__c = 'SE';
		fxor.FXO_GTC__c = false;
		Integer hours = now.hour();
		fxor.FXO_Expiration_Date__c = DateTime.newInstance(now.year(), now.month(), now.day(), hours + 1, 0, 0) ;
		// fxor.FXO_Expiration_Date__c = now.addHours(1);
		insert fxor;

		FX_Order__c fxor1 = new FX_Order__c();
		fxor1.FXO_OrderStatus__c = FXOrderTriggerHandler.SUBMIT_STATUS;
		fxor1.FXO_BuySell__c = 'Buy';
		fxor1.FXO_Currency__c = 'JPY';
		fxor1.FXO_CurrencyPair__c = 'JPY/THB';
		fxor1.FXO_CustomerRate__c = 0.225;
		fxor1.FXO_RequestAmount__c = 10000000;
		fxor1.Owner_s_Segment_stamp__c = 'BB';
		// fxor1.FXO_Expiration_Date__c = System.now().addDays(-2);
		insert fxor1;

		FX_Order__c fxor2 = new FX_Order__c();
		fxor2.FXO_OrderStatus__c = FXOrderTriggerHandler.DONE_STATUS;
		fxor2.FXO_BuySell__c = 'Buy';
		fxor2.FXO_Currency__c = 'JPY';
		fxor2.FXO_CurrencyPair__c = 'JPY/THB';
		fxor2.FXO_CustomerRate__c = 0.245;
		fxor2.FXO_RequestAmount__c = 20000000;
		fxor2.Owner_s_Segment_stamp__c = 'MB';
		insert fxor2;
	}

	@isTest static void test_getFXO() {
		// setup();
		FX_Order__c fxo = [ 
			SELECT id,Name,FXO_Submitted_Date_Time__c,FXO_Customer__c, OwnerId, Owner_s_Segment__c, 
				FXO_BuySell__c,FXO_CurrencyPair__c,FXO_CustomerRate__c,FXO_RequestAmount__c,
				FXO_OrderStatus__c,FXO_Expiration_Date__c,FXO_GTC__c,FXO_Submitted_By__c,
				FXO_InterbankRate__c,FXO_FillAmount__c 
			FROM FX_Order__c
			LIMIT 1
		];
		FXOrderSubmitToTraderController.getFXO(fxo.id);
		fxo.FXO_OrderStatus__c = FXOrderTriggerHandler.DONE_STATUS;
		update fxo;
		FXOrderSubmitToTraderController.getFXO(fxo.id);
	}

	//  -----------------------------------------------
	//  now     : getter/setter to have testemthod-driven different values for now; see also today
	//  -----------------------------------------------
	public static DateTime now {
		get {
			return now == null ? DateTime.now() : now;
		} 
		set;
	}

	//  -----------------------------------------------
	//  today : getter/setter to have testemthod-driven different values for today; see also now
	//  -----------------------------------------------
	public static Date today {
		get {
			return today == null ? Date.today() : today;
		} 
		set;
	}
	
	@isTest static void test_submitFromQuickAction() {
		// setup();
		FX_Order__c o = [ 
			SELECT id,Name,FXO_Submitted_Date_Time__c,FXO_Customer__c, OwnerId, Owner_s_Segment__c, 
				FXO_BuySell__c,FXO_CurrencyPair__c,FXO_CustomerRate__c,FXO_RequestAmount__c,
				FXO_OrderStatus__c,FXO_Expiration_Date__c,FXO_GTC__c,FXO_Submitted_By__c,
				FXO_InterbankRate__c,FXO_FillAmount__c 
			FROM FX_Order__c
			LIMIT 1
		];

		Test.startTest();
		FXOrderSubmitToTraderController.submitFromQuickAction(o);
		
		// DateTime.now().addYears(-1);
		// FXOrderSubmitToTraderController.submitFromQuickAction(o);
		Test.stopTest();
	}

	@isTest static void test_FXOrderSubmitToTraderController(){
		// setup();
		List<FX_Order__c> fxo_list = [ 
			SELECT id,Name,FXO_Submitted_Date_Time__c,FXO_Customer__c, OwnerId, Owner_s_Segment__c, 
				FXO_BuySell__c,FXO_CurrencyPair__c,FXO_CustomerRate__c,FXO_RequestAmount__c,
				FXO_OrderStatus__c,FXO_Expiration_Date__c,FXO_GTC__c,FXO_Submitted_By__c,
				FXO_InterbankRate__c,FXO_FillAmount__c 
			FROM FX_Order__c
		];
		
		// fxo_list[1].FXO_GTC__c = false;
		// fxo_list[1].FXO_Expiration_Date__c = System.now().addSeconds(5);
		fxo_list[2].FXO_OrderStatus__c = FXOrderTriggerHandler.DONE_STATUS;
		update fxo_list;
		// Integer start = System.Now().second();
        // while(System.Now().second() < start + 10){ 
        // }

		Test.startTest();
		Test.setCurrentPage(Page.FXOrderSubmitToTrader);
		ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(fxo_list);
		stdSetController.setSelected(fxo_list);
		FXOrderSubmitToTraderController ext = new FXOrderSubmitToTraderController(stdSetController);
		ext.submitToTrader();
		fxo_list[1].FXO_OrderStatus__c = FXOrderTriggerHandler.DONE_STATUS;
		update fxo_list;
		ext.submitToTrader();
		ext.cancel();
		Test.stopTest();
	}


	@isTest static void test_FXOrderItemSubmitToTraderController(){
		List<FX_Order__c> fxo_list = new List<FX_Order__c>{};
		
		FX_Order__c fxor = new FX_Order__c();
		fxor.FXO_OrderStatus__c = FXOrderTriggerHandler.NEW_STATUS;
		fxor.FXO_BuySell__c = 'Sell';
		fxor.FXO_Currency__c = 'JPY';
		fxor.FXO_CurrencyPair__c = 'JPY/THB';
		fxor.FXO_CustomerRate__c = 0.225;
		fxor.FXO_RequestAmount__c = 50000000;
		fxor.Owner_s_Segment_stamp__c = 'SE';

		fxo_list.add(fxor);
        insert fxo_list;

		Test.startTest();
		Test.setCurrentPage(Page.FXOrderItemSubmitToTrader);
		ApexPages.StandardController sc = new ApexPages.StandardController(fxo_list[0]);
		FXOrderItemSubmitToTraderController ext = new FXOrderItemSubmitToTraderController(sc);
		PageReference pageRef = Page.FXOrderItemSubmitToTrader;
        pageRef.getParameters().put('id', String.valueOf(fxor.Id));
		ext.doForward();
		Test.stopTest();
	}
	
}