force-app/main/default/objects/FX_Order__c/FX_Order__c.object-meta.xml
<CustomObject>
    <label>FX Order</label>
    <nameField>
        <displayFormat>FX-{YYMMDD}-{000}</displayFormat>
        <label>FX Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FX Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FX_Order__c/fields/FXO_BuySell__c.field-meta.xml
<CustomField>
    <fullName>FXO_BuySell__c</fullName>
    <label>Bank Buy/Bank Sell</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_Cancelled_Order_By_Stamp__c.field-meta.xml
<CustomField>
    <fullName>FXO_Cancelled_Order_By_Stamp__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cancelled Order By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_Cancelled_Order_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>FXO_Cancelled_Order_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cancelled Order Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_Currency__c.field-meta.xml
<CustomField>
    <fullName>FXO_Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>CNH</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>DKK</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>IDR</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>LAK</fullName>
            </value>
            <value>
                <fullName>MYR</fullName>
            </value>
            <value>
                <fullName>NOK</fullName>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
            <value>
                <fullName>RUB</fullName>
            </value>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>TWD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_CurrencyPair__c.field-meta.xml
<CustomField>
    <fullName>FXO_CurrencyPair__c</fullName>
    <label>Currency Pair</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FXO_Currency__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>USD/THB</fullName>
            </value>
            <value>
                <fullName>CAD/THB</fullName>
            </value>
            <value>
                <fullName>AUD/THB</fullName>
            </value>
            <value>
                <fullName>AED/THB</fullName>
            </value>
            <value>
                <fullName>CHF/THB</fullName>
            </value>
            <value>
                <fullName>CNH/THB</fullName>
            </value>
            <value>
                <fullName>CNY/THB</fullName>
            </value>
            <value>
                <fullName>DKK/THB</fullName>
            </value>
            <value>
                <fullName>EUR/THB</fullName>
            </value>
            <value>
                <fullName>GBP/THB</fullName>
            </value>
            <value>
                <fullName>HKD/THB</fullName>
            </value>
            <value>
                <fullName>IDR/THB</fullName>
            </value>
            <value>
                <fullName>JPY/THB</fullName>
            </value>
            <value>
                <fullName>LAK/THB</fullName>
            </value>
            <value>
                <fullName>MYR/THB</fullName>
            </value>
            <value>
                <fullName>NOK/THB</fullName>
            </value>
            <value>
                <fullName>NZD/THB</fullName>
            </value>
            <value>
                <fullName>RUB/THB</fullName>
            </value>
            <value>
                <fullName>SEK/THB</fullName>
            </value>
            <value>
                <fullName>SGD/THB</fullName>
            </value>
            <value>
                <fullName>TWD/THB</fullName>
            </value>
            <value>
                <fullName>AUD/JPY</fullName>
            </value>
            <value>
                <fullName>AUD/USD</fullName>
            </value>
            <value>
                <fullName>EUR/AUD</fullName>
            </value>
            <value>
                <fullName>EUR/CHF</fullName>
            </value>
            <value>
                <fullName>EUR/GBP</fullName>
            </value>
            <value>
                <fullName>EUR/JPY</fullName>
            </value>
            <value>
                <fullName>EUR/USD</fullName>
            </value>
            <value>
                <fullName>GBP/JPY</fullName>
            </value>
            <value>
                <fullName>GBP/USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_Customer__c.field-meta.xml
<CustomField>
    <fullName>FXO_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FX Order</relationshipLabel>
    <relationshipName>FX_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_CustomerRate__c.field-meta.xml
<CustomField>
    <fullName>FXO_CustomerRate__c</fullName>
    <label>Customer Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>FXO_Expiration_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_From_Import_Flag__c.field-meta.xml
<CustomField>
    <fullName>FXO_From_Import_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>From Import</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_FXOrderSummary__c.field-meta.xml
<CustomField>
    <fullName>FXO_FXOrderSummary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Order Summary</label>
    <referenceTo>FX_Order_Summary__c</referenceTo>
    <relationshipLabel>FX Order</relationshipLabel>
    <relationshipName>FX_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_GTC__c.field-meta.xml
<CustomField>
    <fullName>FXO_GTC__c</fullName>
    <defaultValue>true</defaultValue>
    <label>GTC (Good &apos;Til Cancelled)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>FXO_OrderStatus__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Acknowledge</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Not Allocated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/FXO_RequestAmount__c.field-meta.xml
<CustomField>
    <fullName>FXO_RequestAmount__c</fullName>
    <label>Request Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/Owner_s_Segment__c.field-meta.xml
<CustomField>
    <fullName>Owner_s_Segment__c</fullName>
    <formula>Owner:User.Reporting_Segment__c</formula>
    <label>Owner&apos;s Segment (Formula)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FX_Order__c/fields/Owner_s_Segment_stamp__c.field-meta.xml
<CustomField>
    <fullName>Owner_s_Segment_stamp__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Owner&apos;s Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FX_Order_Summary__c/FX_Order_Summary__c.object-meta.xml
<CustomObject>
    <label>FX Order Summary</label>
    <nameField>
        <displayFormat>FXS-{YYMMDD}-{000}</displayFormat>
        <label>FX Order Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FX Order Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FX_Order_Summary__c/fields/FXS_Status__c.field-meta.xml
<CustomField>
    <fullName>FXS_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Partially Completed</fullName>
            </value>
            <value>
                <fullName>Fully Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FXOrderCancelController_Test.cls
@isTest
private class FXOrderCancelController_Test {

	public static final Id RTL_BRANCH_SALES_PROFILE_ID = [SELECT Id FROM Profile WHERE Name = 'TMB Retail Channel Sales' LIMIT 1].Id;  
	
	@testSetup static void setup() {
		FX_Order__c fxor = new FX_Order__c();
		fxor.FXO_OrderStatus__c = FXOrderTriggerHandler.NEW_STATUS;
		fxor.FXO_BuySell__c = 'Sell';
		fxor.FXO_Currency__c = 'JPY';
		fxor.FXO_CurrencyPair__c = 'JPY/THB';
		fxor.FXO_CustomerRate__c = 0.225;
		fxor.FXO_RequestAmount__c = 50000000;
		fxor.Owner_s_Segment_stamp__c = 'SE';
		fxor.FXO_From_Import_Flag__c = true;
		insert fxor;

		FX_Order__c fxor1 = new FX_Order__c();
		fxor1.FXO_OrderStatus__c = FXOrderTriggerHandler.SUBMIT_STATUS;
		fxor1.FXO_BuySell__c = 'Buy';
		fxor1.FXO_Currency__c = 'JPY';
		fxor1.FXO_CurrencyPair__c = 'JPY/THB';
		fxor1.FXO_CustomerRate__c = 0.225;
		fxor1.FXO_RequestAmount__c = 10000000;
		fxor1.Owner_s_Segment_stamp__c = 'BB';
		fxor1.FXO_From_Import_Flag__c = true;
		insert fxor1;

		FX_Order__c fxor2 = new FX_Order__c();
		fxor2.FXO_OrderStatus__c = FXOrderTriggerHandler.DONE_STATUS;
		fxor2.FXO_BuySell__c = 'Buy';
		fxor2.FXO_Currency__c = 'JPY';
		fxor2.FXO_CurrencyPair__c = 'JPY/THB';
		fxor2.FXO_CustomerRate__c = 0.245;
		fxor2.FXO_RequestAmount__c = 20000000;
		fxor2.Owner_s_Segment_stamp__c = 'MB';
		fxor2.FXO_From_Import_Flag__c = true;
		insert fxor2;



		User fxblotterUser = new User(FirstName='fxblotter', LastName='test fxblotter',
                                UserName='fxblotter_testuser@tmb.com',
                                Email='fxblotter_testuser@tmbbank.com', Alias='RTLUser', Segment__c ='SE',
                                LocaleSidKey='en_US', LanguageLocaleKey='en_US', EmailEncodingKey='ISO-8859-1', 
                                ProfileId = RTL_BRANCH_SALES_PROFILE_ID, TimeZoneSidKey='America/New_York',isActive = true,
                                RTL_Branch_Code__c='001', Region_Code__c = '002', Zone_Code__c = '003',
                                Employee_ID__c='RTL01', RTL_Branch__c='RTLQ_001 (001)');
		insert fxblotterUser;
	}

	@isTest static void test_cancelFromQuickAction() {
		// setup();
		FX_Order__c o = [ SELECT id, Name, FXO_Customer__c, OwnerId, Owner_s_Segment__c,
                                FXO_BuySell__c, FXO_CurrencyPair__c, FXO_CustomerRate__c, FXO_RequestAmount__c,
                                FXO_OrderStatus__c, FXO_Expiration_Date__c, FXO_GTC__c, 
                                FXO_Cancelled_Order_By_Stamp__c,FXO_Cancelled_Order_Date_Time__c
                        FROM FX_Order__c
						LIMIT 1
		];
		FXOrderCancelController.cancelFromQuickAction(o);
	}
	
	@isTest static void test_getFXO() {
		// setup();
		FX_Order__c o = [ SELECT id, Name, FXO_Customer__c, OwnerId, Owner_s_Segment__c,
                                FXO_BuySell__c, FXO_CurrencyPair__c, FXO_CustomerRate__c, FXO_RequestAmount__c,
                                FXO_OrderStatus__c, FXO_Expiration_Date__c, FXO_GTC__c, 
                                FXO_Cancelled_Order_By_Stamp__c,FXO_Cancelled_Order_Date_Time__c
                FROM FX_Order__c 
				LIMIT 1
		];
		User u = FXOrderCancelController.getUserData();
		
		Test.startTest();
		FXOrderCancelController.getFXO(o.id);
		User user_fxblotter = [SELECT Id FROM User WHERE UserName = 'fxblotter_testuser@tmb.com' LIMIT 1];
		// o.OwnerId = user_fxblotter.Id;
		// update o;
		System.runAS(user_fxblotter){
			FXOrderCancelController.getFXO(o.id);
		}
		
		Test.stopTest();
	}

	@isTest static void test_FXOrderCancelController() {
		// setup();
		List<FX_Order__c> fxo_list = [
			SELECT id, Name, FXO_Customer__c, OwnerId, Owner_s_Segment__c,
				FXO_BuySell__c, FXO_CurrencyPair__c, FXO_CustomerRate__c, FXO_RequestAmount__c,
				FXO_OrderStatus__c, FXO_Expiration_Date__c, FXO_GTC__c, 
				FXO_Cancelled_Order_By_Stamp__c,FXO_Cancelled_Order_Date_Time__c
			FROM FX_Order__c
		];
		

		// fxo_list[1].OwnerId = user_fxblotter.Id;
		fxo_list[2].FXO_OrderStatus__c = FXOrderTriggerHandler.DONE_STATUS;
		update fxo_list;
		
		User user_fxblotter = [SELECT Id FROM User WHERE UserName = 'fxblotter_testuser@tmb.com' LIMIT 1];
		Test.startTest();
		System.runAS(user_fxblotter){
			
		
			Test.setCurrentPage(Page.FXOrderCancel);
			// User u = FXOrderCancelController.getUserData();
			// u.Segment__c = 'BB';
			// update u;
			ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(fxo_list);
			stdSetController.setSelected(fxo_list);
			FXOrderCancelController ext = new FXOrderCancelController(stdSetController);
			ext.cancelOrderConfirm();
			// FXOrderAcknowledgeController.acknowledgeFromQuickAction(fxo_list[2]);
			// fxo_list[2].FXO_OrderStatus__c = FXOrderTriggerHandler.ACKNOWLEDGE_STATUS;
			// update fxo_list;
			//ext.cancelOrderConfirm();
			ext.cancel();

		}
		Test.stopTest();
	}

	//@isTest static void test_FXOrderCancelFailedController() {
	//	// setup();
	//	List<FX_Order__c> fxo_list = [
	//		SELECT id, Name, FXO_Customer__c, OwnerId, Owner_s_Segment__c,
	//			FXO_BuySell__c, FXO_CurrencyPair__c, FXO_CustomerRate__c, FXO_RequestAmount__c,
	//			FXO_OrderStatus__c, FXO_Expiration_Date__c, FXO_GTC__c, 
	//			FXO_Cancelled_Order_By_Stamp__c,FXO_Cancelled_Order_Date_Time__c
	//		FROM FX_Order__c
	//	];
		

	//	// fxo_list[1].OwnerId = user_fxblotter.Id;

		
	//	User user_fxblotter = [SELECT Id FROM User WHERE UserName = 'fxblotter_testuser@tmb.com' LIMIT 1];
	//	Test.startTest();
	//	System.runAS(user_fxblotter){
			
		
	//		Test.setCurrentPage(Page.FXOrderCancel);
	//		// User u = FXOrderCancelController.getUserData();
	//		// u.Segment__c = 'BB';
	//		// update u;
	//		ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(fxo_list);
	//		stdSetController.setSelected(fxo_list);
	//		FXOrderCancelController ext = new FXOrderCancelController(stdSetController);

	//		//ext.cancelOrderConfirm();

	//		//FXOrderAcknowledgeController.acknowledgeFromQuickAction(fxo_list[2]);


	
	//	//fxo_list[2].FXO_OrderStatus__c = FXOrderTriggerHandler.ACKNOWLEDGE_STATUS;
	//	//update fxo_list2[2];

	//	//	FXOrderAcknowledgeController.acknowledgeFromQuickAction(fxo_list[2]);

	//	List<FX_Order__c> fxo_list2 = [
	//		SELECT id, Name, FXO_Customer__c, OwnerId, Owner_s_Segment__c,
	//			FXO_BuySell__c, FXO_CurrencyPair__c, FXO_CustomerRate__c, FXO_RequestAmount__c,
	//			FXO_OrderStatus__c, FXO_Expiration_Date__c, FXO_GTC__c, 
	//			FXO_Cancelled_Order_By_Stamp__c,FXO_Cancelled_Order_Date_Time__c,
	//			FXO_FXOrderSummary__c
	//		FROM FX_Order__c
	//	];

	//	system.debug('Gade:' + fxo_list2);

	//		List<FX_Order_Summary__c> fxslist = [select id,FXS_Status__c from FX_Order_Summary__c where id = :fxo_list2[2].FXO_FXOrderSummary__c ];
	//	system.debug('Gade2:' + fxslist);			
	//		//ext.cancelOrderConfirm();
	//		//ext.cancel();

	//	}
	//	Test.stopTest();
	//}
}