force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <label>Visit Plan / Report</label>
    <nameField>
        <displayFormat>Visit-{0000}</displayFormat>
        <label>Visit Report No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Plan / Reports</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report__c/fields/Check_in_Location__c.field-meta.xml
<CustomField>
    <fullName>Check_in_Location__c</fullName>
    <description>Check-in Location</description>
    <label>Check-in Location</label>
    <scale>0</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Is_Last_Checkin_Location__c.field-meta.xml
<CustomField>
    <fullName>Is_Last_Checkin_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Showing if the location info is updated from Google Map API or not 
This will be trigger from Is Checkin Location Changed workflow</description>
    <label>Is Last Checkin Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Is_Retry_for_GoogleMap__c.field-meta.xml
<CustomField>
    <fullName>Is_Retry_for_GoogleMap__c</fullName>
    <formula>IF(AND(OR(ISNULL(Retry_Google_Map__c),Retry_Google_Map__c &lt;= 2),Is_Geolocation_Exist__c=True, Is_Last_Checkin_Location__c =False), True, False)</formula>
    <label>Is Retry for GoogleMap</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Retry_Google_Map__c.field-meta.xml
<CustomField>
    <fullName>Retry_Google_Map__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Retry Google Map</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GoogleMapAPISchedulable.cls
global class GoogleMapAPISchedulable implements Schedulable  {
    global void execute(SchedulableContext sc) {
    	Id jobId = sc.getTriggerId();
    	System.abortJob(jobId);

    	String query = 'SELECT Id,Check_in_Location__c,Retry_Google_Map__c FROM Call_Report__c Where Is_Retry_for_GoogleMap__c = true '
                       +' and Is_Last_Checkin_Location__c = false ORDER BY LastModifiedDate ASC LIMIT 200';
        
    	GoogleExternalAPI batchGoogleMap = new GoogleExternalAPI(query);
    	Id BatchProcessId = Database.ExecuteBatch(batchGoogleMap,50);

    	Integer GoogleMAPInMinute = 60;
        try{
            List<App_Config__mdt> GoogleMapAPIMetaData 
                = [SELECT Value__c FROM App_Config__mdt WHERE MasterLabel = 'GoogleMAPInMinute'];

            if (GoogleMapAPIMetaData != null && GoogleMapAPIMetaData.size() > 0) {
                GoogleMAPInMinute = Integer.valueOf(GoogleMapAPIMetaData.get(0).Value__c);
            }      
        }catch( Exception e ){
            System.debug(e);
        }

    	Datetime currenttime = System.now();
    	Datetime nextRuntime = currenttime.addMinutes(GoogleMAPInMinute);

    	String day = string.valueOf(nextRuntime.day());
        String month = string.valueOf(nextRuntime.month());
        String hour = string.valueOf(nextRuntime.hour());
        String minute = string.valueOf(nextRuntime.minute());
        String second = string.valueOf(nextRuntime.second());
        String year = string.valueOf(nextRuntime.year());

        String strJobName = 'Job-GoogleMapAPISchedulable_' + second + '_' + minute + '_' + hour + '_' + day + '_' + month + '_' + year;
        String strSchedule = '0 ' + minute + ' ' + hour + ' ' + day + ' ' + month + ' ?' + ' ' + year;
        System.schedule(strJobName, strSchedule, new GoogleMapAPISchedulable());
    }

}