force-app/main/default/objects/Currency__c/Currency__c.object-meta.xml
<CustomObject>
    <description>Currency</description>
    <label>Currency</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currency</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Currency__c/fields/Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>Exchange_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exchange Rate</label>
    <referenceTo>Exchange_Rate_Of_Thai_FCY__c</referenceTo>
    <relationshipLabel>Currency</relationshipLabel>
    <relationshipName>Currency</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Currency__c/fields/ShortName__c.field-meta.xml
<CustomField>
    <fullName>ShortName__c</fullName>
    <description>Short Name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Short Name</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Exchange_Rate_Of_Thai_FCY__c/Exchange_Rate_Of_Thai_FCY__c.object-meta.xml
<CustomObject>
    <description>อัตรแลกเปลี่ยนรายปีของ TMB</description>
    <label>Exchange Rate Of Thai FCY</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Rate Of Thai FCYs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Rate_Of_Thai_FCY__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Currency Short Name</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExchangeRateExtension.cls
public class ExchangeRateExtension {
    
    public ExchangeRateExtension()
    {
    
    }
    
    public static void afterInsert(list<Exchange_Rate_Of_Thai_FCY__c> listData)
    {
        list<Currency__c> insertData = new list<Currency__c>();
        List<Currency__c> UpdateData = new list<Currency__c>();        
        Map<String , Currency__c> currencyData = new Map<String , Currency__c>();                
        for (Currency__c a : [select Id, name from currency__c])
        {
            currencyData.put(a.name,a);
        }
        for (Exchange_Rate_Of_Thai_FCY__c a: listData)
        {
            // Insert Case
            if (!currencyData.containsKey(a.Name__c)){
                currency__c newData = new currency__c();
                newData.Name = a.Name__c;
                newData.ShortName__c = a.Name__c;
                newData.Exchange_Rate__c = a.id;
                insertData.add(newData);
            }
            // Update Case
            else{
                 Currency__c newData = new Currency__c();
                 newData.Id = (Id)currencyData.get(a.Name__c).Id;
                 newData.Exchange_Rate__c  = a.id;
                 UpdateData.add(newData);
            }
        }
        system.debug(insertData);
        insert insertData;
        update UpdateData;
    }


}