force-app/main/default/objects/RTL_Upload_Campaign_Member__mdt/RTL_Upload_Campaign_Member__mdt.object-meta.xml
<CustomObject>
    <label>Upload Campaign Member</label>
    <pluralLabel>Upload Campaign Member</pluralLabel>
</CustomObject>

force-app/main/default/objects/RTL_Upload_Campaign_Member__mdt/fields/RTL_Line_Save_Per_Batch__c.field-meta.xml
<CustomField>
    <fullName>RTL_Line_Save_Per_Batch__c</fullName>
    <label>Line Save Per Batch</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTL_Upload_Campaign_Member_Batch__c/RTL_Upload_Campaign_Member_Batch__c.object-meta.xml
<CustomObject>
    <label>Upload Campaign Member Batch</label>
    <nameField>
        <displayFormat>UCMB-{000000}</displayFormat>
        <label>Upload Campaign Member Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTL Upload Campaign Member Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Upload_Campaign_Member_Batch__c/fields/RTL_Status__c.field-meta.xml
<CustomField>
    <fullName>RTL_Status__c</fullName>
    <label>RTL Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Upload_Campaign_Member_Batch__c/fields/RTL_Upload_Campaign_Member_Logs__c.field-meta.xml
<CustomField>
    <fullName>RTL_Upload_Campaign_Member_Logs__c</fullName>
    <label>RTL Upload Campaign Member Logs</label>
    <referenceTo>RTL_Upload_Campaign_Member_Logs__c</referenceTo>
    <relationshipName>Upload_Campaign_Member_Batches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTL_Upload_Campaign_Member_Logs__c/RTL_Upload_Campaign_Member_Logs__c.object-meta.xml
<CustomObject>
    <label>Upload Campaign Member Log</label>
    <nameField>
        <displayFormat>UCML-{00000000}</displayFormat>
        <label>Upload Campaign Member Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Upload Campaign Member Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Upload_Campaign_Member_Logs__c/fields/RTL_UploadStatus__c.field-meta.xml
<CustomField>
    <fullName>RTL_UploadStatus__c</fullName>
    <label>RTL UploadStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Starting</fullName>
            </value>
            <value>
                <fullName>In Progress - Split File</fullName>
            </value>
            <value>
                <fullName>In Progress - Import Batch</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>In Progress - Import Member to Batch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Upload_Campaign_Members__c/RTL_Upload_Campaign_Members__c.object-meta.xml
<CustomObject>
    <label>Upload Campaign Member</label>
    <nameField>
        <displayFormat>UCM-{0000000}</displayFormat>
        <label>Upload Campaign Members Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTL Upload Campaign Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Upload_Campaign_Members__c/fields/RTL_Upload_Campaign_Member_Batch__c.field-meta.xml
<CustomField>
    <fullName>RTL_Upload_Campaign_Member_Batch__c</fullName>
    <label>RTL Upload Campaign Member Batch</label>
    <referenceTo>RTL_Upload_Campaign_Member_Batch__c</referenceTo>
    <relationshipName>Upload_Campaign_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTL_Upload_Campaign_Members__c/fields/RTL_Upload_Campaign_Member_Logs__c.field-meta.xml
<CustomField>
    <fullName>RTL_Upload_Campaign_Member_Logs__c</fullName>
    <label>RTL Upload Campaign Member Logs</label>
    <referenceTo>RTL_Upload_Campaign_Member_Logs__c</referenceTo>
    <relationshipName>Upload_Campaign_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RTL_UploadCampaignMemberImportError.cls
public class RTL_UploadCampaignMemberImportError implements Queueable {

	List<RTL_Upload_Campaign_Members__c> errorList;
	RTL_Upload_Campaign_Member_Batch__c ucmb;
	RTL_Upload_Campaign_Member_Logs__c ucml;

	private Integer itemPerSaveMember {
    	get{
                if(itemPerSaveMember==null){
                 RTL_Upload_Campaign_Member__mdt ucmMeta = [select id,RTL_Line_Save_Per_Batch__c
                   from RTL_Upload_Campaign_Member__mdt 
                   where DeveloperName = 'RTL_Upload_Campaign_Member_Setting'];

                   itemPerSaveMember = integer.valueOf(ucmMeta.RTL_Line_Save_Per_Batch__c);
            }
            return itemPerSaveMember;
        }
    	set;
    }

	public RTL_UploadCampaignMemberImportError(RTL_Upload_Campaign_Member_Logs__c logObject,RTL_Upload_Campaign_Member_Batch__c batchOjbect,List<RTL_Upload_Campaign_Members__c> ucmList)
	{
		errorList = ucmList;
		ucmb = batchOjbect;
		ucml = logObject;
	}

	public void execute(QueueableContext context) {

		// Insert error record from parent chianed class
        Database.SaveResult[] ucmResultList = Database.insert(errorList,false);
	
		ucmb.RTL_Status__c ='Completed';
		update ucmb;

        ucmL.RTL_UploadStatus__c = 'In Progress - Import Batch';
        update ucmL;

        // Call Import campaign member from CSV to temp
		RTL_UploadCampaignMemberBatch ucmBatch = new RTL_UploadCampaignMemberBatch(ucmL,ucmb);
		Database.executeBatch(ucmBatch ,itemPerSaveMember);
	}
}