force-app/main/default/objects/Maintenance_Message__c/Maintenance_Message__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Message for system maintenance page</description>
    <label>Maintenance Message</label>
</CustomObject>

force-app/main/default/objects/Maintenance_Message__c/fields/Body_Message__c.field-meta.xml
<CustomField>
    <fullName>Body_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Body Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Maintenance_Message__c/fields/Header_Message__c.field-meta.xml
<CustomField>
    <fullName>Header_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Header Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Maintenance_Message__c/fields/Title_Message__c.field-meta.xml
<CustomField>
    <fullName>Title_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Title Message</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TMBMaintenanceTestClass.cls
@isTest 
private class TMBMaintenanceTestClass {
    static testMethod void TMBMaintenanceTest() {
        TMBMaintenanceController ctrl1 = new TMBMaintenanceController();
        
        Maintenance_Message__c msg = new Maintenance_Message__c();
        msg.Name = 'Test Msg';
        msg.Title_Message__c = 'Test Title';
        msg.Header_Message__c= 'Test Header';
        msg.Body_Message__c= 'Test Body';
        insert msg;
        
        TMBMaintenanceController ctrl2 = new TMBMaintenanceController();
    }
}