force-app/main/default/objects/CXM_Survey__c/CXM_Survey__c.object-meta.xml
<CustomObject>
    <label>CXM Survey</label>
    <nameField>
        <displayFormat>CXM-{000000}</displayFormat>
        <label>CXM Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CXM Survey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CXM_Survey__c/fields/ActivityDesc__c.field-meta.xml
<CustomField>
    <fullName>ActivityDesc__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ActivityDesc</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CXM_Survey__c/fields/ComplaintIssue__c.field-meta.xml
<CustomField>
    <fullName>ComplaintIssue__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ComplaintIssue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CXM_Survey__c/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CXM_Survey__c/fields/parentBusinessOutcome__c.field-meta.xml
<CustomField>
    <fullName>parentBusinessOutcome__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>parentBusinessOutcome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CXM_Survey__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Source</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CXM_Survey__c/fields/Survey_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Survey_Datetime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Survey Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CXM_Survey__c/fields/Survey_Score__c.field-meta.xml
<CustomField>
    <fullName>Survey_Score__c</fullName>
    <label>Survey Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/Service_Type_Matrix__c.object-meta.xml
<CustomObject>
    <label>Service Type Matrix</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Service Type Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Type Matrixs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Closed_By_BU__c.field-meta.xml
<CustomField>
    <fullName>Closed_By_BU__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Closed By BU</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Responsible_BU__c.field-meta.xml
<CustomField>
    <fullName>Responsible_BU__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>1. If assign to specific user, input user id.
ex. 34506, 2395

2. If assign dynamic user related to customer in put formula field.
ex. Customer_Owner_ID__c
Customer_BRC_User__c
Customer_Wealth_RM_BM__c

3. If assign to bu name in put BU Name.</inlineHelpText>
    <label>Responsible BU (Hop 1)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Responsible_BU_Hop_2__c.field-meta.xml
<CustomField>
    <fullName>Responsible_BU_Hop_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Responsible BU (Hop 2)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Responsible_BU_Hop_3__c.field-meta.xml
<CustomField>
    <fullName>Responsible_BU_Hop_3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Responsible BU (Hop 3)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>PTA Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RBG</fullName>
            </value>
            <value>
                <fullName>SBG</fullName>
            </value>
            <value>
                <fullName>WBG</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Service_issue_EN__c.field-meta.xml
<CustomField>
    <fullName>Service_issue_EN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service issue EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Service_Level1__c.field-meta.xml
<CustomField>
    <fullName>Service_Level1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Level1</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Service_Level2__c.field-meta.xml
<CustomField>
    <fullName>Service_Level2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Level2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Service_Level3__c.field-meta.xml
<CustomField>
    <fullName>Service_Level3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Level3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Service_Level4__c.field-meta.xml
<CustomField>
    <fullName>Service_Level4__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Level4</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Service_Template__c.field-meta.xml
<CustomField>
    <fullName>Service_Template__c</fullName>
    <label>Service Template</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>CardProduct</fullName>
            </value>
            <value>
                <fullName>DepositWithdraw</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>MoneyTransfer</fullName>
            </value>
            <value>
                <fullName>CheckInvalidTransfer</fullName>
            </value>
            <value>
                <fullName>BillPayTopup</fullName>
            </value>
            <value>
                <fullName>CreditService</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>KYCReview</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <label>SLA</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/SLA_Closed_By_BU_Day__c.field-meta.xml
<CustomField>
    <fullName>SLA_Closed_By_BU_Day__c</fullName>
    <label>SLA Closed By BU (Day)</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/SLA_Hop_1_Day__c.field-meta.xml
<CustomField>
    <fullName>SLA_Hop_1_Day__c</fullName>
    <label>SLA Hop 1 (Day)</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/SLA_Hop_2_Day__c.field-meta.xml
<CustomField>
    <fullName>SLA_Hop_2_Day__c</fullName>
    <label>SLA Hop 2 (Day)</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/SLA_Hop_3_Day__c.field-meta.xml
<CustomField>
    <fullName>SLA_Hop_3_Day__c</fullName>
    <label>SLA Hop 3 (Day)</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Type_Matrix__c/fields/Validate_Code__c.field-meta.xml
<CustomField>
    <fullName>Validate_Code__c</fullName>
    <description>This field for define code to validate in case validation rule</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>This field for define service code to use in validation rule, report, back end integration.</inlineHelpText>
    <label>Service Type Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Survey_Score__c/Survey_Score__c.object-meta.xml
<CustomObject>
    <label>Survey Score</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Survey Score Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Score</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CXMSurveyTest.cls
@isTest
public class CXMSurveyTest {
    
    static testMethod void runTestClass() { 
        Test.startTest();
            Service_Type_Matrix__c serviceType = New Service_Type_Matrix__c();
            serviceType.Segment__c = 'SBG';
            serviceType.Service_Level1__c = 'Service Level1';
            serviceType.Service_Level2__c = 'Service level2';
            serviceType.Service_Level3__c = 'Service level3';
            serviceType.Service_Level4__c = 'Service level4';
            serviceType.SLA__c = 7;
            serviceType.Severity__c = '1';
            serviceType.Responsible_BU__c = 'Test_Queue_SE';
            serviceType.active__c = true;
            serviceType.Service_issue_EN__c = 'english version';
            serviceType.Validate_Code__c = 'xxxx1';
            serviceType.Responsible_BU_Hop_2__c = 'RMC';
            serviceType.Responsible_BU_Hop_3__c ='test queue';
            serviceType.Closed_By_BU__c = 'REGISTER';
            serviceType.SLA_Hop_1_Day__c = 1;
            serviceType.SLA_Hop_2_Day__c = 1;
            serviceType.SLA_Hop_3_Day__c = 1;
            serviceType.SLA_Closed_By_BU_Day__c = 1;
            serviceType.Service_Template__c = 'CreditService';
            insert serviceType;

            List<CXM_Survey__c> cxmList = New List<CXM_Survey__c>();

            CXM_Survey__c cxmsurvey1 = new CXM_Survey__c();
            cxmsurvey1.Customer_ID__c = '001100000001102200000006823105';
            cxmsurvey1.Source__c = 'CRM-CCRP';
            cxmsurvey1.Survey_Score__c = 51;
            cxmsurvey1.Survey_Datetime__c = system.now();
            cxmsurvey1.ComplaintIssue__c = 'xxxx1';        
            cxmList.add(cxmsurvey1);

            CXM_Survey__c cxmsurvey2 = new CXM_Survey__c();
            cxmsurvey2.Customer_ID__c = '001100000001102200000006823105';
            cxmsurvey2.Source__c = 'Finesse';
            cxmsurvey2.Survey_Score__c = 61;
            cxmsurvey2.Survey_Datetime__c = system.now();
            cxmsurvey2.ActivityDesc__c = 'test comment';        
            cxmList.add(cxmsurvey2);

            CXM_Survey__c cxmsurvey3 = new CXM_Survey__c();
            cxmsurvey3.Customer_ID__c = '001100000001102200000006823105';
            cxmsurvey3.Source__c = 'Finesse';
            cxmsurvey3.Survey_Score__c = 81;
            cxmsurvey3.Survey_Datetime__c = system.now();
            cxmsurvey3.parentBusinessOutcome__c = 'test comment';        
            cxmList.add(cxmsurvey3);

            insert cxmList;
        Test.stopTest();

    }

}