force-app/main/default/objects/Branch_and_Zone__c/Branch_and_Zone__c.object-meta.xml
<CustomObject>
    <label>Branch and Zone</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch and Zone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch_and_Zone__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Branch Code</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Branch_and_Zone__c/fields/RMC_User__c.field-meta.xml
<CustomField>
    <fullName>RMC_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMC User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Branch_and_Zone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branch_and_Zone__c/fields/RTL_Region_Code__c.field-meta.xml
<CustomField>
    <fullName>RTL_Region_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Region Code (Retail)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch_and_Zone__c/fields/RTL_Zone_Code__c.field-meta.xml
<CustomField>
    <fullName>RTL_Zone_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zone Code (Retail)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch_and_Zone__c/fields/SE_Queue_Name__c.field-meta.xml
<CustomField>
    <fullName>SE_Queue_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SE Queue Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RTL_Priority_Product__c.field-meta.xml
<CustomField>
    <fullName>RTL_Priority_Product__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Priority Product</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/RTL_Lead_Assignment_Rule__c.object-meta.xml
<CustomObject>
    <description>For setup condition for assign owner to Lead when created.</description>
    <label>Lead Assignment</label>
    <nameField>
        <displayFormat>RTLLA-{000000}</displayFormat>
        <label>Lead Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Active_Flag__c.field-meta.xml
<CustomField>
    <fullName>RTL_Active_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Assigned_Apex__c.field-meta.xml
<CustomField>
    <fullName>RTL_Assigned_Apex__c</fullName>
    <label>1.1 Assign by Apex function</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RTL_AssignmentCriteriaService</fullName>
            </value>
            <value>
                <fullName>RTL_ReferAssignmentService</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Assigned_Queue_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_Assigned_Queue_Name__c</fullName>
    <description>Developer Queue Name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Use developer name for assigned to Queue.</inlineHelpText>
    <label>3.1 Assigned Queue Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>RTL_Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2.1 Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assigned_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Assigned_User_field__c.field-meta.xml
<CustomField>
    <fullName>RTL_Assigned_User_field__c</fullName>
    <label>2.2 Assigned User field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OwnerId</fullName>
            </value>
            <value>
                <fullName>Referred_Staff__c</fullName>
            </value>
            <value>
                <fullName>RTL_Employee_ID__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Branch_and_Zone_Queue_User_field__c.field-meta.xml
<CustomField>
    <fullName>RTL_Branch_and_Zone_Queue_User_field__c</fullName>
    <description>Check from field RTL_Branch_Name</description>
    <inlineHelpText>Get the value from RTL_Branch_Name__c.</inlineHelpText>
    <label>3.2 Branch and Zone Queue/User field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BB_Queue_Name__c</fullName>
            </value>
            <value>
                <fullName>SE_Queue_Name__c</fullName>
            </value>
            <value>
                <fullName>Branch_Queue_Name__c</fullName>
            </value>
            <value>
                <fullName>RMC_User__c</fullName>
            </value>
            <value>
                <fullName>RTL_Wealth_RM_User__c</fullName>
            </value>
            <value>
                <fullName>RTL_Branch_Manager_User__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Default_Queue_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_Default_Queue_Name__c</fullName>
    <description>Developer Queue Name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Use developer name for assigned to Queue.</inlineHelpText>
    <label>4.1 Default Queue Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Default_User__c.field-meta.xml
<CustomField>
    <fullName>RTL_Default_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>4.2 Default User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Default_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_IsAssign_Campaign__c.field-meta.xml
<CustomField>
    <fullName>RTL_IsAssign_Campaign__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Update to field RTL_IsAssign_Campaign__c in object Lead.</description>
    <label>Is Assign Campaign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_IsInsertProduct__c.field-meta.xml
<CustomField>
    <fullName>RTL_IsInsertProduct__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Use this flag to clarify is auto create interested product</description>
    <inlineHelpText>Use product from lead field RTL_Product_name</inlineHelpText>
    <label>Is Create Interested Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Lead_Field_Criteria_1__c.field-meta.xml
<CustomField>
    <fullName>RTL_Lead_Field_Criteria_1__c</fullName>
    <label>Lead Field Criteria 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RTL_Contact_Method__c</fullName>
            </value>
            <value>
                <fullName>LeadSource</fullName>
            </value>
            <value>
                <fullName>RTL_TMB_Campaign_Source__c</fullName>
            </value>
            <value>
                <fullName>RTL_TMB_Campaign_Reference__c</fullName>
            </value>
            <value>
                <fullName>RTL_Customer_Segment__c</fullName>
            </value>
            <value>
                <fullName>RTL_Owner_Type__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Lead_Field_Value_1__c.field-meta.xml
<CustomField>
    <fullName>RTL_Lead_Field_Value_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Possible value for this field are
1) Is null
2) Is not null
3) Field Value (always using &apos;=&apos; operator)
4) TRUE /FALSE for checkbox field</inlineHelpText>
    <label>Lead Field Value 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Lead_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>RTL_Lead_Record_Type__c</fullName>
    <label>Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial Account</fullName>
            </value>
            <value>
                <fullName>Commercial Completed</fullName>
            </value>
            <value>
                <fullName>Commercial Lead</fullName>
            </value>
            <value>
                <fullName>Retail Banking</fullName>
                <default>true</default>
                <label>Retail Banking</label>
            </value>
            <value>
                <fullName>Retail Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Lead_Assignment_Rule__c/fields/RTL_Priority__c.field-meta.xml
<CustomField>
    <fullName>RTL_Priority__c</fullName>
    <label>Priority</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTL_Messenger_Cover_Area__c/RTL_Messenger_Cover_Area__c.object-meta.xml
<CustomObject>
    <description>To keep if the Zip Code is covered by Messenger or Not , using in Retail Lead Assignment</description>
    <label>Messenger Cover Area</label>
    <nameField>
        <displayFormat>MCA{0000}</displayFormat>
        <label>Messenger Cover Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messenger Cover Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Messenger_Cover_Area__c/fields/RTL_Area__c.field-meta.xml
<CustomField>
    <fullName>RTL_Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cover</fullName>
            </value>
            <value>
                <fullName>Not Cover</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Messenger_Cover_Area__c/fields/RTL_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>RTL_Zip_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Zip Code</label>
    <length>5</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTL_product_master__c/RTL_product_master__c.object-meta.xml
<CustomObject>
    <description>To store list of products for Retail banking only.</description>
    <label>Retail Product Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Retail Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_product_master__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Show only products marked as Active in interested products &amp; opportunity .</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_product_master__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_product_master__c/fields/Product_Sub_group__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_group__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Sub group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadAssignmentUtilTest.cls
@isTest
public class LeadAssignmentUtilTest {
    static User adminUser{
        get
        {
            if(adminUser == null){
                adminUser = [SELECT Id, Name FROM User WHERE IsActive = true AND ProfileId =: TestUtils.SYSADMIN_PROFILE_ID LIMIT 1];
            }
            return adminUser;
        }
        set;
    }

    static {
        System.runAs(adminUser){
                
            TestUtils.createAppConfig();

            Branch_and_zone__c bz = new Branch_and_zone__c();
            bz.Branch_Code__c = '001';
            bz.Name = '001';
            bz.RMC_User__c = adminUser.Id;
            bz.SE_Queue_Name__c = 'test_queue';
            bz.isActive__c = true;
            insert bz;

            Group queue = new Group();
            queue.Name = 'Email - TMB';
            queue.DeveloperName = 'test_queue';
            queue.type = 'Queue';
            insert queue;
            
            QueuesObject qsObject = new QueueSObject();
            qsObject.QueueId = queue.Id;
            qsObject.SobjectType = 'Lead';
            insert qsObject;
            
            RTL_TestUtility.enableWebToLeadAutoAssign(true);
            RTL_TestUtility.createCampaignAssignmentRule();
        }
    }

    @isTest
    public static void testCreateLeadCommercialAssignUserField(){
        RTL_Lead_Assignment_Rule__c leadAssignmentrule = new RTL_Lead_Assignment_Rule__c ();
        leadAssignmentrule.RTL_Active_Flag__c = true;
        leadAssignmentrule.RTL_Priority__c = 1;
        leadAssignmentrule.RTL_IsInsertProduct__c = true;
        leadAssignmentrule.RTL_Assigned_User_field__c = 'OwnerId';
        leadAssignmentrule.RTL_IsAssign_Campaign__c = false;
        leadAssignmentrule.RTL_Lead_Record_Type__c = 'Commercial Lead';
        insert leadAssignmentrule;

        Test.startTest();
        Lead led = new Lead();
        led.RecordTypeId = Schema.Sobjecttype.Lead.getRecordTypeInfosByName().get('Commercial Lead').getRecordTypeId();
        led.Company = 'Company';
        led.LastName = 'LastName';
        insert led;
        Test.stopTest();
    }

    @isTest
    public static void testCreateLeadCommercialAssignUser(){
        RTL_Lead_Assignment_Rule__c leadAssignmentrule = new RTL_Lead_Assignment_Rule__c ();
        leadAssignmentrule.RTL_Active_Flag__c = true;
        leadAssignmentrule.RTL_Priority__c = 1;
        leadAssignmentrule.RTL_IsInsertProduct__c = true;
        leadAssignmentrule.RTL_Assigned_User__c = userinfo.getUserId();
        leadAssignmentrule.RTL_IsAssign_Campaign__c = false;
        leadAssignmentrule.RTL_Lead_Record_Type__c = 'Commercial Lead';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'LeadSource';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Web';
        insert leadAssignmentrule;

        RTL_Lead_Assignment_Rule__c leadAssignmentrule2 = new RTL_Lead_Assignment_Rule__c ();
        leadAssignmentrule2.RTL_Active_Flag__c = true;
        leadAssignmentrule2.RTL_Priority__c = 0;
        leadAssignmentrule2.RTL_IsInsertProduct__c = true;
        leadAssignmentrule2.RTL_Assigned_User_field__c = 'OwnerId';
        leadAssignmentrule2.RTL_IsAssign_Campaign__c = false;
        leadAssignmentrule2.RTL_Lead_Record_Type__c = 'Commercial Lead';
        leadAssignmentrule2.RTL_Lead_Field_Criteria_1__c = 'LeadSource';
        leadAssignmentrule2.RTL_Lead_Field_Value_1__c = 'Web2';
        insert leadAssignmentrule2;

        Test.startTest();
        Lead led = new Lead();
        led.RecordTypeId = Schema.Sobjecttype.Lead.getRecordTypeInfosByName().get('Commercial Lead').getRecordTypeId();
        led.Company = 'Company';
        led.LastName = 'LastName';
        led.LeadSource = 'Web';
        insert led;
        Test.stopTest();
    }

    @isTest
    public static void testCreateLeadCommercialAssignQueueName(){
        RTL_Lead_Assignment_Rule__c leadAssignmentrule = new RTL_Lead_Assignment_Rule__c ();
        leadAssignmentrule.RTL_Active_Flag__c = true;
        leadAssignmentrule.RTL_Priority__c = 1;
        leadAssignmentrule.RTL_IsInsertProduct__c = true;
        leadAssignmentrule.RTL_Assigned_Queue_Name__c = 'test_queue';
        leadAssignmentrule.RTL_IsAssign_Campaign__c = false;
        leadAssignmentrule.RTL_Lead_Record_Type__c = 'Commercial Lead';
        insert leadAssignmentrule;

        Test.startTest();
        Lead led = new Lead();
        led.RecordTypeId = Schema.Sobjecttype.Lead.getRecordTypeInfosByName().get('Commercial Lead').getRecordTypeId();
        led.Company = 'Company';
        led.LastName = 'LastName';
        insert led;
        Test.stopTest();
    }

    @isTest
    public static void testCreateLeadCommercialAssignBranchZoneUserField(){
        RTL_Lead_Assignment_Rule__c leadAssignmentrule = new RTL_Lead_Assignment_Rule__c ();
        leadAssignmentrule.RTL_Active_Flag__c = true;
        leadAssignmentrule.RTL_Priority__c = 1;
        leadAssignmentrule.RTL_IsInsertProduct__c = true;
        leadAssignmentrule.RTL_Branch_and_Zone_Queue_User_field__c = 'SE_Queue_Name__c';
        leadAssignmentrule.RTL_IsAssign_Campaign__c = false;
        leadAssignmentrule.RTL_Lead_Record_Type__c = 'Commercial Lead';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'LeadSource';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Q';
        insert leadAssignmentrule;

        leadAssignmentrule = new RTL_Lead_Assignment_Rule__c ();
        leadAssignmentrule.RTL_Active_Flag__c = true;
        leadAssignmentrule.RTL_Priority__c = 2;
        leadAssignmentrule.RTL_IsInsertProduct__c = true;
        leadAssignmentrule.RTL_Branch_and_Zone_Queue_User_field__c = 'RMC_User__c';
        leadAssignmentrule.RTL_IsAssign_Campaign__c = false;
        leadAssignmentrule.RTL_Lead_Record_Type__c = 'Commercial Lead';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'LeadSource';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'User';
        insert leadAssignmentrule;

        Test.startTest();
        Lead led = new Lead();
        led.RecordTypeId = Schema.Sobjecttype.Lead.getRecordTypeInfosByName().get('Commercial Lead').getRecordTypeId();
        led.Company = 'Company';
        led.LastName = 'LastName';
        led.LeadSource = 'Q';
        led.RTL_Branch_Name__c = '001';
        insert led;

        Lead led2 = new Lead();
        led2.RecordTypeId = Schema.Sobjecttype.Lead.getRecordTypeInfosByName().get('Commercial Lead').getRecordTypeId();
        led2.Company = 'Company';
        led2.LastName = 'LastName';
        led2.LeadSource = 'User';
        led2.RTL_Branch_Name__c = '001';
        insert led2;
        
        led2 = new Lead();
        led2.RecordTypeId = Schema.Sobjecttype.Lead.getRecordTypeInfosByName().get('Commercial Lead').getRecordTypeId();
        led2.Company = 'Company';
        led2.LastName = 'LastName';
        led2.LeadSource = 'User';
        led2.RTL_Branch_Name__c = '111';
        insert led2;
        Test.stopTest();
    }

    @isTest
    public static void testCreateLeadCommercialAssignDefult(){
        RTL_Lead_Assignment_Rule__c leadAssignmentrule = new RTL_Lead_Assignment_Rule__c ();
        leadAssignmentrule.RTL_Active_Flag__c = true;
        leadAssignmentrule.RTL_Priority__c = 1;
        leadAssignmentrule.RTL_IsInsertProduct__c = true;
        leadAssignmentrule.RTL_Default_Queue_Name__c = 'test_queue';
        leadAssignmentrule.RTL_IsAssign_Campaign__c = false;
        leadAssignmentrule.RTL_Lead_Record_Type__c = 'Commercial Lead';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'LeadSource';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Q';
        insert leadAssignmentrule;

        leadAssignmentrule = new RTL_Lead_Assignment_Rule__c ();
        leadAssignmentrule.RTL_Active_Flag__c = true;
        leadAssignmentrule.RTL_Priority__c = 2;
        leadAssignmentrule.RTL_IsInsertProduct__c = true;
        leadAssignmentrule.RTL_Default_User__c = adminUser.Id;
        leadAssignmentrule.RTL_IsAssign_Campaign__c = false;
        leadAssignmentrule.RTL_Lead_Record_Type__c = 'Commercial Lead';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'LeadSource';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'User';
        insert leadAssignmentrule;

        Test.startTest();
        Lead led = new Lead();
        led.RecordTypeId = Schema.Sobjecttype.Lead.getRecordTypeInfosByName().get('Commercial Lead').getRecordTypeId();
        led.Company = 'Company';
        led.LastName = 'LastName';
        led.LeadSource = 'Q';
        insert led;

        Lead led2 = new Lead();
        led2.RecordTypeId = Schema.Sobjecttype.Lead.getRecordTypeInfosByName().get('Commercial Lead').getRecordTypeId();
        led2.Company = 'Company';
        led2.LastName = 'LastName';
        led2.LeadSource = 'User';
        insert led2;
        Test.stopTest();
    }
    @isTest
    public static void testCreateLeadNoMultiCover(){
        RTL_Lead_Assignment_Rule__c leadAssignmentrule = new RTL_Lead_Assignment_Rule__c ();
        leadAssignmentrule.RTL_Active_Flag__c = true;
        leadAssignmentrule.RTL_Priority__c = 40;
        leadAssignmentrule.RTL_IsInsertProduct__c = true;
        leadAssignmentrule.RTL_IsAssign_Campaign__c = true;
        leadAssignmentrule.RTL_Lead_Record_Type__c = 'Retail Banking';
        leadAssignmentrule.RTL_Assigned_Apex__c = 'RTL_ReferAssignmentService';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'RTL_Contact_Method__c';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Normal Request';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'LeadSource';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Referral';
        insert leadAssignmentrule;

        RTL_Messenger_Cover_Area__c coverarea = new RTL_Messenger_Cover_Area__c();
        coverarea.RTL_Area__c  ='Cover';
        coverarea.RTL_Zip_Code__c  ='18000';
        insert coverarea;

        RTL_TestUtility.createLeadAssignCriteriasGBH(true);
        Test.startTest();
        Lead led = new Lead();
        led.Company = 'Company';
        led.RecordTypeId = '01290000000iZYK';
        led.FirstName = 'Test';
        led.LastName = 'Test';
        led.RTL_Web_Unique_ID_c__c = 'WEB000000123001';
        led.RTL_Mobile_Number__c= '0946528664';
        led.RTL_Multiple_Interested_Product_s__c= false;
        led.RTL_Product_Name__c = 'GBHCC';
        led.RTL_Contact_Method__c = 'Normal Request';
        led.LeadSource = 'Referral';
        led.RTL_BranchW2L_Area__c = '18000';
        led.RTL_Branch_Name__c = '444';
        led.RTL_Priority_Product__c = '';
        insert led;

        Test.stopTest();
    }

    @isTest
    public static void testCreateLeadNoMultiNoCover(){
        RTL_Lead_Assignment_Rule__c leadAssignmentrule = new RTL_Lead_Assignment_Rule__c ();
        leadAssignmentrule.RTL_Active_Flag__c = true;
        leadAssignmentrule.RTL_Priority__c = 40;
        leadAssignmentrule.RTL_IsInsertProduct__c = true;
        leadAssignmentrule.RTL_IsAssign_Campaign__c = true;
        leadAssignmentrule.RTL_Lead_Record_Type__c = 'Retail Banking';
        leadAssignmentrule.RTL_Assigned_Apex__c = 'RTL_ReferAssignmentService';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'RTL_Contact_Method__c';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Normal Request';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'LeadSource';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Referral';
        insert leadAssignmentrule;

        RTL_Messenger_Cover_Area__c coverarea = new RTL_Messenger_Cover_Area__c();
        coverarea.RTL_Area__c  ='Not Cover';
        coverarea.RTL_Zip_Code__c  ='18000';
        insert coverarea;

        RTL_TestUtility.createLeadAssignCriteriasGBH(true);
        Test.startTest();
        Lead led = new Lead();
        led.Company = 'Company';
        led.RecordTypeId = '01290000000iZYK';
        led.FirstName = 'Test';
        led.LastName = 'Test';
        led.RTL_Web_Unique_ID_c__c = 'WEB000000123001';
        led.RTL_Mobile_Number__c= '0946528664';
        led.RTL_Multiple_Interested_Product_s__c= false;
        led.RTL_Product_Name__c = 'GBHCC';
        led.RTL_Contact_Method__c = 'Normal Request';
        led.LeadSource = 'Referral';
        led.RTL_BranchW2L_Area__c = '18000';
        led.RTL_Branch_Name__c = '444';
        led.RTL_Priority_Product__c = '';
        insert led;

        Test.stopTest();
    }
    @isTest
    public static void testCreateLeadMultiCover(){
        RTL_Lead_Assignment_Rule__c leadAssignmentrule = new RTL_Lead_Assignment_Rule__c ();
        leadAssignmentrule.RTL_Active_Flag__c = true;
        leadAssignmentrule.RTL_Priority__c = 40;
        leadAssignmentrule.RTL_IsInsertProduct__c = true;
        leadAssignmentrule.RTL_IsAssign_Campaign__c = true;
        leadAssignmentrule.RTL_Lead_Record_Type__c = 'Retail Banking';
        leadAssignmentrule.RTL_Assigned_Apex__c = 'RTL_ReferAssignmentService';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'RTL_Contact_Method__c';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Normal Request';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'LeadSource';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Referral';
        insert leadAssignmentrule;

        RTL_Messenger_Cover_Area__c coverarea = new RTL_Messenger_Cover_Area__c();
        coverarea.RTL_Area__c  ='Cover';
        coverarea.RTL_Zip_Code__c  ='18000';
        insert coverarea;

        RTL_TestUtility.createLeadAssignCriteriasGBH(true);
        Test.startTest();
        Lead led1 = new Lead();
        led1.Company = 'Company1';
        led1.RecordTypeId = '01290000000iZYK';
        led1.FirstName = 'multiple3';
        led1.LastName = 'Test3';
        led1.RTL_Web_Unique_ID_c__c = 'WEBtestclass123002';
        led1.RTL_Mobile_Number__c= '0946527648';
        led1.RTL_Multiple_Interested_Product_s__c= true;
        led1.RTL_Product_Name__c = 'GBHCC;GBHFC';
        led1.RTL_Contact_Method__c = 'Normal Request';
        led1.LeadSource = 'Referral';
        led1.RTL_BranchW2L_Area__c = '18000';
        led1.RTL_Branch_Name__c = '444';
        led1.RTL_Priority_Product__c = 'GBHCC';
        insert led1;

        Test.stopTest();
    }
    @isTest
    public static void testCreateLeadMultiNotCover(){
        RTL_Lead_Assignment_Rule__c leadAssignmentrule = new RTL_Lead_Assignment_Rule__c ();
        leadAssignmentrule.RTL_Active_Flag__c = true;
        leadAssignmentrule.RTL_Priority__c = 40;
        leadAssignmentrule.RTL_IsInsertProduct__c = true;
        leadAssignmentrule.RTL_IsAssign_Campaign__c = true;
        leadAssignmentrule.RTL_Lead_Record_Type__c = 'Retail Banking';
        leadAssignmentrule.RTL_Assigned_Apex__c = 'RTL_ReferAssignmentService';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'RTL_Contact_Method__c';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Normal Request';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'LeadSource';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Referral';
        insert leadAssignmentrule;

        RTL_Messenger_Cover_Area__c coverarea = new RTL_Messenger_Cover_Area__c();
        coverarea.RTL_Area__c  ='Not Cover';
        coverarea.RTL_Zip_Code__c  ='18000';
        insert coverarea;

        RTL_TestUtility.createLeadAssignCriteriasGBH(true);
        Test.startTest();
        Lead led1 = new Lead();
        led1.Company = 'Company1';
        led1.RecordTypeId = '01290000000iZYK';
        led1.FirstName = 'multiple3';
        led1.LastName = 'Test3';
        led1.RTL_Web_Unique_ID_c__c = 'WEBtestclass123002';
        led1.RTL_Mobile_Number__c= '0946527648';
        led1.RTL_Multiple_Interested_Product_s__c= true;
        led1.RTL_Product_Name__c = 'GBHCC;GBHFC';
        led1.RTL_Contact_Method__c = 'Normal Request';
        led1.LeadSource = 'Referral';
        led1.RTL_BranchW2L_Area__c = '18000';
        led1.RTL_Branch_Name__c = '444';
        led1.RTL_Priority_Product__c = 'GBHCC';
        insert led1;

        Test.stopTest();
    }
    @isTest
    public static void testCreateLeadnoProductNobranch(){
        RTL_Lead_Assignment_Rule__c leadAssignmentrule = new RTL_Lead_Assignment_Rule__c ();
        leadAssignmentrule.RTL_Active_Flag__c = true;
        leadAssignmentrule.RTL_Priority__c = 40;
        leadAssignmentrule.RTL_IsInsertProduct__c = true;
        leadAssignmentrule.RTL_IsAssign_Campaign__c = true;
        leadAssignmentrule.RTL_Lead_Record_Type__c = 'Retail Banking';
        leadAssignmentrule.RTL_Assigned_Apex__c = 'RTL_ReferAssignmentService';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'RTL_Contact_Method__c';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Normal Request';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'LeadSource';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Referral';
        insert leadAssignmentrule;

        RTL_Messenger_Cover_Area__c coverarea = new RTL_Messenger_Cover_Area__c();
        coverarea.RTL_Area__c  ='Cover';
        coverarea.RTL_Zip_Code__c  ='18000';
        insert coverarea;

        RTL_TestUtility.createLeadAssignCriteriasGBH(true);

        List<RTL_product_master__c> productList = new List<RTL_product_master__c>();
        RTL_product_master__c product = new RTL_product_master__c(Name='Test', Product_Group__c='Credit Card', Product_Sub_group__c='Credit Card',Active__c=true);
        insert productList;



        Test.startTest();
        Lead led1 = new Lead();
        led1.Company = 'Company1';
        led1.RecordTypeId = '01290000000iZYK';
        led1.FirstName = 'multiple3';
        led1.LastName = 'Test3';
        led1.RTL_Web_Unique_ID_c__c = 'WEBtestclass123002';
        led1.RTL_Mobile_Number__c= '0946527648';
        led1.RTL_Multiple_Interested_Product_s__c= false;
        led1.RTL_Product_Name__c = 'test';
        led1.RTL_Contact_Method__c = 'Normal Request';
        led1.LeadSource = 'Referral';
        led1.RTL_BranchW2L_Area__c = '18000';
        led1.RTL_Branch_Name__c = '';
        led1.RTL_Priority_Product__c = '';
        insert led1;

        Test.stopTest();
    }
    // @isTest
    // public static void testCreateLeadnoProduct(){
    //     RTL_Lead_Assignment_Rule__c leadAssignmentrule = new RTL_Lead_Assignment_Rule__c ();
    //     leadAssignmentrule.RTL_Active_Flag__c = true;
    //     leadAssignmentrule.RTL_Priority__c = 40;
    //     leadAssignmentrule.RTL_IsInsertProduct__c = true;
    //     leadAssignmentrule.RTL_IsAssign_Campaign__c = true;
    //     leadAssignmentrule.RTL_Lead_Record_Type__c = 'Retail Banking';
    //     leadAssignmentrule.RTL_Assigned_Apex__c = 'RTL_ReferAssignmentService';
    //     leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'RTL_Contact_Method__c';
    //     leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Normal Request';
    //     leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'LeadSource';
    //     leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Referral';
    //     insert leadAssignmentrule;

    //     RTL_Messenger_Cover_Area__c coverarea = new RTL_Messenger_Cover_Area__c();
    //     coverarea.RTL_Area__c  ='Cover';
    //     coverarea.RTL_Zip_Code__c  ='18000';
    //     insert coverarea;

    //     RTL_TestUtility.createLeadAssignCriteriasGBH(true);

    //     List<RTL_product_master__c> productList = new List<RTL_product_master__c>();
    //     RTL_product_master__c product = new RTL_product_master__c(Name='Test', Product_Group__c='Credit Card', Product_Sub_group__c='Credit Card',Active__c=true);
    //     insert productList;

    //     Group newgroup = new Group();
    //     newgroup.Name = 'Test_444';
    //     newgroup.DeveloperName = 'Test_444';
    //     newgroup.Type = 'Queue';
    //     insert newgroup;

    //     Branch_and_Zone__c newBranch = new Branch_and_Zone__c ();
    //     newBranch.Name = 'Test';
    //     newBranch.Branch_Code__c = '444';
    //     newBranch.RTL_Region_Code__c = '444';
    //     newBranch.RTL_Zone_Code__c = '444';
    //     newBranch.IsActive__c = true;
    //     insert newBranch;

    //     Test.startTest();
    //     Lead led1 = new Lead();
    //     led1.Company = 'Company1';
    //     led1.RecordTypeId = '01290000000iZYK';
    //     led1.FirstName = 'multiple3';
    //     led1.LastName = 'Test3';
    //     led1.RTL_Web_Unique_ID_c__c = 'WEBtestclass123002';
    //     led1.RTL_Mobile_Number__c= '0946527648';
    //     led1.RTL_Multiple_Interested_Product_s__c= false;
    //     led1.RTL_Product_Name__c = 'test';
    //     led1.RTL_Contact_Method__c = 'Normal Request';
    //     led1.LeadSource = 'Referral';
    //     led1.RTL_BranchW2L_Area__c = '18000';
    //     led1.RTL_Branch_Name__c = '444';
    //     led1.RTL_Priority_Product__c = '';
    //     insert led1;

    //     Test.stopTest();
    // }
    @isTest
    public static void testCreateLeadnoProductbranchnovalid(){
        RTL_Lead_Assignment_Rule__c leadAssignmentrule = new RTL_Lead_Assignment_Rule__c ();
        leadAssignmentrule.RTL_Active_Flag__c = true;
        leadAssignmentrule.RTL_Priority__c = 40;
        leadAssignmentrule.RTL_IsInsertProduct__c = true;
        leadAssignmentrule.RTL_IsAssign_Campaign__c = true;
        leadAssignmentrule.RTL_Lead_Record_Type__c = 'Retail Banking';
        leadAssignmentrule.RTL_Assigned_Apex__c = 'RTL_ReferAssignmentService';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'RTL_Contact_Method__c';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Normal Request';
        leadAssignmentrule.RTL_Lead_Field_Criteria_1__c = 'LeadSource';
        leadAssignmentrule.RTL_Lead_Field_Value_1__c = 'Referral';
        insert leadAssignmentrule;

        RTL_Messenger_Cover_Area__c coverarea = new RTL_Messenger_Cover_Area__c();
        coverarea.RTL_Area__c  ='Cover';
        coverarea.RTL_Zip_Code__c  ='18000';
        insert coverarea;

        RTL_TestUtility.createLeadAssignCriteriasGBH(true);

        List<RTL_product_master__c> productList = new List<RTL_product_master__c>();
        RTL_product_master__c product = new RTL_product_master__c(Name='Test', Product_Group__c='Credit Card', Product_Sub_group__c='Credit Card',Active__c=true);
        insert productList;

        Group newgroup = new Group();
        newgroup.Name = 'Test_444';
        newgroup.DeveloperName = 'Test_444';
        newgroup.Type = 'Queue';
        insert newgroup;

        Test.startTest();
        Lead led1 = new Lead();
        led1.Company = 'Company1';
        led1.RecordTypeId = '01290000000iZYK';
        led1.FirstName = 'multiple3';
        led1.LastName = 'Test3';
        led1.RTL_Web_Unique_ID_c__c = 'WEBtestclass123002';
        led1.RTL_Mobile_Number__c= '0946527648';
        led1.RTL_Multiple_Interested_Product_s__c= false;
        led1.RTL_Product_Name__c = 'test';
        led1.RTL_Contact_Method__c = 'Normal Request';
        led1.LeadSource = 'Referral';
        led1.RTL_BranchW2L_Area__c = '18000';
        led1.RTL_Branch_Name__c = '444';
        led1.RTL_Priority_Product__c = '';
        insert led1;

        Test.stopTest();
    }
}