force-app/main/default/objects/Survey_Question__c/Survey_Question__c.object-meta.xml
<CustomObject>
    <label>Survey Question</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Question</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question__c/fields/Choice_Render_Type__c.field-meta.xml
<CustomField>
    <fullName>Choice_Render_Type__c</fullName>
    <label>Choice Render Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Choice Render Below</fullName>
            </value>
            <value>
                <fullName>Choice Render On Right</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Question_Grid_Size__c.field-meta.xml
<CustomField>
    <fullName>Question_Grid_Size__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Question Grid Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SurveyQuestionWrapperTest.cls
@isTest
private class SurveyQuestionWrapperTest {
	
	@isTest static void test_method_one() {
		// Implement test code
		SurveyQuestionWrapper sc = new SurveyQuestionWrapper();
		sc.getSubQuestionList();
		sc.genTitleGridStyleClass();
		sc.genChoiceGridStyleClass();

		Survey_Question__c question = new Survey_Question__c();
		question.Choice_Render_Type__c = 'Choice Render On Right';
		question.Question_Grid_Size__c = 2;

		sc.question = question;

		List<SurveyManagerController.choiceWrapper> choiceList = sc.choiceList;
		List<SurveyQuestionWrapper> subQuestionList = sc.subQuestionList;
		String gridTitleStyleClass = sc.gridTitleStyleClass;
		String gridChoiceStyleClass = sc.gridChoiceStyleClass;
		List<SurveyManagerController.choiceWrapper> getChoice = sc.getChoiceList();
		List<SurveyQuestionWrapper> getSubQuestion = sc.getSubQuestionList();
		sc.genTitleGridStyleClass();
		sc.genChoiceGridStyleClass();
	}

	
}