force-app/main/default/objects/FNA_Activity__c/FNA_Activity__c.object-meta.xml
<CustomObject>
    <label>FNA Activity</label>
    <nameField>
        <displayFormat>FNA-{0000000000}</displayFormat>
        <label>FNA Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FNA Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNA_Activity__c/fields/OTP_Code__c.field-meta.xml
<CustomField>
    <fullName>OTP_Code__c</fullName>
    <formula>SMS_OTP__r.OTP_Code__c</formula>
    <label>SMS OTP Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OTP__c/OTP__c.object-meta.xml
<CustomObject>
    <label>OTP</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>OTP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OTP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OTP__c/fields/IsExpired__c.field-meta.xml
<CustomField>
    <fullName>IsExpired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsExpired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OTP__c/fields/IsUsed__c.field-meta.xml
<CustomField>
    <fullName>IsUsed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsUsed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OTP__c/fields/OTP_Code__c.field-meta.xml
<CustomField>
    <fullName>OTP_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>OTP_Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OTP__c/fields/OTP_Master__c.field-meta.xml
<CustomField>
    <fullName>OTP_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OTP_Master</label>
    <referenceTo>OTP_Master__c</referenceTo>
    <relationshipLabel>OTP</relationshipLabel>
    <relationshipName>OTP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OTP_Master__c/OTP_Master__c.object-meta.xml
<CustomObject>
    <label>OTP Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>OTP_Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OTP_Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OTP_Master__c/fields/FNA_Activity__c.field-meta.xml
<CustomField>
    <fullName>FNA_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FNA Activity</label>
    <referenceTo>FNA_Activity__c</referenceTo>
    <relationshipName>OTP_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OTP_Master__c/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Secret_Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/fnaGenerateOTPCtrl_Test.cls
@isTest
public without sharing class fnaGenerateOTPCtrl_Test {

    @isTest
    private static void Test_fnGenerateOTP() {
        List<FNA_Activity__c> listFnaAct = new List<FNA_Activity__c>();
        FNA_Activity__c fnaActivity = new FNA_Activity__c();
        listFnaAct.add(fnaActivity);
        insert listFnaAct;

        List<OTP_Master__c> listOTPMaster = new List<OTP_Master__c>();
        OTP_Master__c OTPMaster = new OTP_Master__c();
        OTPMaster.FNA_Activity__c = listFnaAct[0].Id;
        OTPMaster.Secret_Key__c = 'RFDSYEPQYBF5OYCFSWTUIHU3YMY6UK37';
        OTPMaster.Counter__c = 1;
        listOTPMaster.add(OTPMaster);
        insert listOTPMaster;

        // OTP_Master__c OTPMaster_2 = new OTP_Master__c();
        // OTPMaster_2.FNA_Activity__c = listFnaAct[1].Id;
        // OTPMaster_2.Secret_Key__c = 'RFDSYEPQYBF5OYCFSWTUIHU3YMY6UK37';
        // OTPMaster_2.Counter__c = 1;
        // listOTPMaster.add(OTPMaster_2);
        // insert listOTPMaster;

        // List<OTP__c> listOTP = new List<OTP__c>();
        // OTP__c OTP = new OTP__c();
        // OTP.OTP_Master__c = listOTPMaster[1].Id;
        // OTP.IsUsed__c = true;
        // listOTP.add(OTP);
        // insert listOTP;

        fnaGenerateOTPCtrl.fnGenerateOTP(listFnaAct[0].Id);
    }

    @isTest
    private static void Test_fnVerifyOTP() {
        List<FNA_Activity__c> listFnaAct = new List<FNA_Activity__c>();
        FNA_Activity__c fnaActivity = new FNA_Activity__c();
        listFnaAct.add(fnaActivity);
        insert listFnaAct;

        String FNAId = listFnaAct[0].Id;
        String otpCode = '123456';
        fnaGenerateOTPCtrl.fnVerifyOTP(FNAId, otpCode);
    }

    @isTest
    private static void Test_fnVerifyOTP_2() {

        List<FNA_Activity__c> listFnaAct = new List<FNA_Activity__c>();
        FNA_Activity__c fnaActivity = new FNA_Activity__c();
        listFnaAct.add(fnaActivity);
        insert listFnaAct;
        
        // fnaGenerateOTPCtrl.FNA_ACTIVITY_PREFIX = (String)listFnaAct[0].Id;

        List<OTP_Master__c> listOTPMaster = new List<OTP_Master__c>();
        OTP_Master__c OTPMaster = new OTP_Master__c();
        OTPMaster.FNA_Activity__c = listFnaAct[0].Id;
        OTPMaster.Secret_Key__c = 'RFDSYEPQYBF5OYCFSWTUIHU3YMY6UK37';
        OTPMaster.Counter__c = 0;
        listOTPMaster.add(OTPMaster);
        insert listOTPMaster;

        List<OTP__c> listOTP = new List<OTP__c>();
        OTP__c OTP = new OTP__c();
        OTP.OTP_Master__c = listOTPMaster[0].Id;
        OTP.IsUsed__c = true;
        OTP.OTP_Code__c = '006415';
        listOTP.add(OTP);
        insert listOTP;

        String FNAId = listFnaAct[0].Id;
        String otpCode = '006415';
        fnaGenerateOTPCtrl.fnVerifyOTP(FNAId, otpCode);

        OTP_Master__c OTPMaster_2 = new OTP_Master__c();
        OTPMaster_2 = fnaGenerateOTPCtrl.increaseCounter(listOTPMaster[0]);
    }

    @isTest
    private static void Test_requestOTP() {
        List<FNA_Activity__c> listFnaAct = new List<FNA_Activity__c>();
        FNA_Activity__c fnaActivity = new FNA_Activity__c();
        listFnaAct.add(fnaActivity);
        insert listFnaAct;


        List<OTP_Master__c> listOTPMaster = new List<OTP_Master__c>();
        OTP_Master__c OTPMaster = new OTP_Master__c();
        OTPMaster.FNA_Activity__c = listFnaAct[0].Id;
        OTPMaster.Secret_Key__c = 'RFDSYEPQYBF5OYCFSWTUIHU3YMY6UK37';
        OTPMaster.Counter__c = 0;
        listOTPMaster.add(OTPMaster);
        insert listOTPMaster;

        List<OTP__c> listOTP = new List<OTP__c>();
        OTP__c OTP = new OTP__c();
        OTP.OTP_Master__c = listOTPMaster[0].Id;
        OTP.IsUsed__c = true;
        OTP.IsExpired__c = true;
        OTP.OTP_Code__c = '006415';
        listOTP.add(OTP);
        insert listOTP;

        String FNAId = listFnaAct[0].Id;

        fnaGenerateOTPCtrl.fnGenerateOTP(FNAId);

        // fnaGenerateOTPCtrl.requestOTP(FNAId);
    }
}