force-app/main/default/objects/E_Client_Suitability__c/E_Client_Suitability__c.object-meta.xml
<CustomObject>
    <label>E-Client Suitability</label>
    <nameField>
        <displayFormat>CS-{YYMMDD}-{000}</displayFormat>
        <label>E-Client Suitability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>E-Client Suitability</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/E_Client_Suitability__c/fields/CS_Basic_Flag__c.field-meta.xml
<CustomField>
    <fullName>CS_Basic_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Basic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/E_Client_Suitability__c/fields/CS_Customer__c.field-meta.xml
<CustomField>
    <fullName>CS_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>E-Client Suitability</relationshipLabel>
    <relationshipName>E_client_Suitability_Review</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/E_Client_Suitability__c/fields/CS_Customer_Survey_A__c.field-meta.xml
<CustomField>
    <fullName>CS_Customer_Survey_A__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CS Customer Survey A</label>
    <referenceTo>Survey_Sheet__c</referenceTo>
    <relationshipLabel>E-Client Suitability</relationshipLabel>
    <relationshipName>E_Client_Suitability</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/E_Client_Suitability__c/fields/CS_Customer_Survey_B__c.field-meta.xml
<CustomField>
    <fullName>CS_Customer_Survey_B__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CS Customer Survey B</label>
    <referenceTo>Survey_Sheet__c</referenceTo>
    <relationshipLabel>E-Client Suitability (CS Customer Survey B)</relationshipLabel>
    <relationshipName>E_Client_Suitability1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/E_Client_Suitability__c/fields/CS_Expiry_Date_Next__c.field-meta.xml
<CustomField>
    <fullName>CS_Expiry_Date_Next__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CS Expiry Date (Next)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/E_Client_Suitability__c/fields/CS_RM__c.field-meta.xml
<CustomField>
    <fullName>CS_RM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>E_Client_Suitability2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/E_Client_Suitability__c/fields/CS_Sales_Owner__c.field-meta.xml
<CustomField>
    <fullName>CS_Sales_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales (Owner)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>E_Client_Suitability</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/E_Client_Suitability__c/fields/CS_Status__c.field-meta.xml
<CustomField>
    <fullName>CS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Review</fullName>
                <default>true</default>
                <label>Pending Review</label>
            </value>
            <value>
                <fullName>Reviewing</fullName>
            </value>
            <value>
                <fullName>Pending RM TH</fullName>
            </value>
            <value>
                <fullName>RM TH Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Sales</fullName>
            </value>
            <value>
                <fullName>Pending Sales TH</fullName>
            </value>
            <value>
                <fullName>Sales TH Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Pending Customer</fullName>
                <isActive>false</isActive>
                <label>Pending Customer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Manager__c/Survey_Manager__c.object-meta.xml
<CustomObject>
    <description>Survey Master for each survey form</description>
    <label>Survey Manager</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Manager</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Manager__c/fields/Survey_Version__c.field-meta.xml
<CustomField>
    <fullName>Survey_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Version</label>
    <referenceTo>Survey_Version__c</referenceTo>
    <relationshipLabel>Survey Manager</relationshipLabel>
    <relationshipName>FX_Survey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Sheet__c/Survey_Sheet__c.object-meta.xml
<CustomObject>
    <label>Survey Sheet</label>
    <nameField>
        <displayFormat>SS-{0000}</displayFormat>
        <label>Survey Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Sheet</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Sheet__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Customer (In case survey&apos;s linked object related to customer )</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Survey Sheet</relationshipLabel>
    <relationshipName>Customer_Survey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Sheet__c/fields/Info_1__c.field-meta.xml
<CustomField>
    <fullName>Info_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Form Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Sheet__c/fields/Survey_Type__c.field-meta.xml
<CustomField>
    <fullName>Survey_Type__c</fullName>
    <label>Survey Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>E-Client Suitability</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Sheet__c/fields/Survey_Version__c.field-meta.xml
<CustomField>
    <fullName>Survey_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Version</label>
    <referenceTo>Survey_Version__c</referenceTo>
    <relationshipName>Customer_Survey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Version__c/Survey_Version__c.object-meta.xml
<CustomObject>
    <label>Survey Version</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Survey Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Version</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Version__c/fields/Survey_Manager__c.field-meta.xml
<CustomField>
    <fullName>Survey_Manager__c</fullName>
    <label>Survey Manager</label>
    <referenceTo>Survey_Manager__c</referenceTo>
    <relationshipLabel>Survey Version</relationshipLabel>
    <relationshipName>Survey_Version</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CSChangeRMSaleController.cls
public without sharing class CSChangeRMSaleController {
	public CSChangeRMSaleController() {
		
	}
	public static String SURVEY_TYPE = 'E-Client Suitability';
	public static String E_CLIENT_STATUS_COMPLETE = 'Completed';
	public static String E_CLIENT_STATUS_PENDING_RM = 'Pending RM TH';
	public static String E_CLIENT_STATUS_PENDING_SALES = 'Pending Sales TH';
	public static String E_CLIENT_STATUS_SUSPENDED = 'Suspended';

	
	@AuraEnabled
	public static LIst<E_Client_Suitability__c> getCurrentEclient(List<Id> eclientId)
	{
		try 
		{
			List<String> statusNotAvailableToChangeRM = new List<String>();
			statusNotAvailableToChangeRM.add(E_CLIENT_STATUS_COMPLETE);
			statusNotAvailableToChangeRM.add(E_CLIENT_STATUS_PENDING_RM);
			statusNotAvailableToChangeRM.add(E_CLIENT_STATUS_PENDING_SALES);
			statusNotAvailableToChangeRM.add(E_CLIENT_STATUS_SUSPENDED);

			List<E_Client_Suitability__c> eClient = [SELECT Id,Name,CS_Status__c,CS_Basic_Flag__c,
					CS_RM__c,CS_Sales_Owner__c,OwnerId,CS_Expiry_Date_Next__c,CS_Customer__c,
					CS_Customer_Survey_A__c,CS_Customer_Survey_B__c,
					CS_Sales_Owner__r.Name,CS_RM__r.Name
					From E_Client_Suitability__c
					 WHERE Id = : eclientId
					 AND CS_Status__c not in :statusNotAvailableToChangeRM
					];

			return eClient;

		} 
		catch(Exception e) 
		{
			System.debug(e.getMessage());
			return null;
			
		}
		
	}

	@AuraEnabled
	public static List<E_Client_Suitability__c> confirmEclientListView( List<E_Client_Suitability__c> eClient )
    {
		update eClient;

    	String errorMessage = '';

    	Set<Id> surveySheetIdset = new Set<Id>();
		List<String> ecIdList = new List<String>();
		String userId;
    	for(E_Client_Suitability__c ec : eClient)
    	{
    		surveySheetIdset.add(ec.CS_Customer_Survey_A__c);
    		surveySheetIdset.add(ec.CS_Customer_Survey_B__c);
    	}

    	//system.debug('surveySheetIdset: ' + surveySheetIdset);

    	Map<ID,Survey_Sheet__c> surveySheetIdMap = new Map<ID,Survey_Sheet__c>( [SELECT Id,OwnerId FROM Survey_Sheet__c WHERE id in :surveySheetIdset ] );

		try{
			
			List<Survey_Sheet__c> shList = new List<Survey_Sheet__c>();

			for(E_Client_Suitability__c ec : eClient)
			{				
				if( surveySheetIdMap.containsKey( ec.CS_Customer_Survey_A__c ) )
				{
					Survey_Sheet__c formA = surveySheetIdMap.get(ec.CS_Customer_Survey_A__c);
					formA.OwnerId =  ec.CS_RM__c;
					shList.add(formA);
				}

				if( surveySheetIdMap.containsKey( ec.CS_Customer_Survey_B__c ) )
				{
					Survey_Sheet__c formB = surveySheetIdMap.get(ec.CS_Customer_Survey_B__c);
					formB.OwnerId =  ec.CS_Sales_Owner__c;
					shList.add(formB);
				}

				ecIdList.add(ec.Id);

				userId = ec.CS_RM__c;
			}

			if( shList.size() > 0 )
			{
				update shList;
			}

			if(ecIdList.size() > 0)
			{
				CSEClientController.setManualShareRead(ecIdList,userId);
			}

			return eClient;
		}
		catch(Exception e) 
		{
			errorMessage = e.getMessage();
    		System.debug(e.getMessage() + e.getLineNumber() );
    		
		}

		throw new AuraHandledException( errorMessage );
		return null;
	}

	@AuraEnabled
	public static Survey_Sheet__c insertSurveySheet( Survey_Manager__c sm , String  eCustomerId ,String ownerNameId )
    {
		try
		{
			Survey_Sheet__c sh = new Survey_Sheet__c();
			sh.Survey_Version__c = sm.Survey_Version__c;
			sh.Info_1__c = sm.name;
			sh.Customer__c = eCustomerId;
			sh.OwnerId = ownerNameId;
			sh.Survey_Type__c = SURVEY_TYPE;
			
			return sh;
		}
		catch(Exception e) 
		{
    		System.debug(e.getMessage() + e.getLineNumber() );
    		return null;
		}
	}

	@AuraEnabled
	public static E_Client_Suitability__c updateCurrentEclient(E_Client_Suitability__c eClient)
	{

		try 
		{
			update eClient;
			return eClient;
		}
		catch(Exception e) 
		{
			System.debug(e.getMessage());
			return null;
			
		}
	}

	@AuraEnabled 
    public static User getCurrentUser(){
     // query current user information  
      User oUser = [Select Id,Name,Username,Country,Email,FirstName,LastName,IsActive,Profile.Name 
                 FROM User Where Id =: userInfo.getUserId() AND isActive=true];
        return oUser;
    }


	@AuraEnabled
   	public static void setManualShareRead(List<E_Client_Suitability__c> eClient )
	{
		try
		{	
			List<String> ecIdList = new List<String>();
			String userId;

			for(E_Client_Suitability__c ec : eClient)
			{								
				ecIdList.add(ec.Id);

				userId = ec.CS_RM__c;
			}

			if(ecIdList.size() > 0)
			{
				CSEClientController.setManualShareRead(ecIdList,userId);
			}
					
		}
		catch(Exception e) {
   			System.debug(e.getMessage() );
   		}
	}

}