force-app/main/default/objects/BA_Insurance_Company__c/BA_Insurance_Company__c.object-meta.xml
<CustomObject>
    <description>Because the source system does not have the insurance company’s details, a Custom object will
be created in SFDC to store the details. The Insurance Company details will be maintained by
TMB manually</description>
    <label>BA Insurance Company</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA Insurance Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BA_Insurance_Company__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Insurance Company
Address</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/BA_Insurance_Company__c/fields/ContactNo1__c.field-meta.xml
<CustomField>
    <fullName>ContactNo1__c</fullName>
    <description>Insurance Company
Contact Number #1</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Number #1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BA_Insurance_Company__c/fields/ContactNo2__c.field-meta.xml
<CustomField>
    <fullName>ContactNo2__c</fullName>
    <description>Insurance Company
Contact Number #2</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Number #2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BAInsuranceCompanySelector.cls
public class BAInsuranceCompanySelector { 
/*----------------------------------------------------------------------------------
	  Author:        Keattisak Chinburarat
	  Company:       I&I Consulting 
	  Description:   Selector for BA_Insurance_Company__c
	  Inputs:        None
	  Test Class:    TestBAInsuranceCompanySelector
	  History
	  <Date>      <Authors Name>     <Brief Description of Change>
	  ----------------------------------------------------------------------------------*/
	private static string selectAll() {
		return 'SELECT Id,Name,Address__c,ContactNo1__c,ContactNo2__c  FROM BA_Insurance_Company__c ';
	}
	public static List<BA_Insurance_Company__c> getAllBAInsuranceCompanies() {
		List<BA_Insurance_Company__c> ret;
		string sql = selectAll();
		System.Debug('TMB: -> SOQL : ' + sql);
		try
		{
			ret = (List<BA_Insurance_Company__c>) Database.query(sql);
		}
		catch(Exception ex)
		{
			throw new RetailProductSelectorException('There is some error when query BA_Insurance_Company__c', ex);
		}
		return ret;
	}
	public class RetailProductSelectorException extends Exception {
	}

}