force-app/main/default/objects/RTL_Upload_Campaign_Member_Batch__c/RTL_Upload_Campaign_Member_Batch__c.object-meta.xml
<CustomObject>
    <label>Upload Campaign Member Batch</label>
    <nameField>
        <displayFormat>UCMB-{000000}</displayFormat>
        <label>Upload Campaign Member Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTL Upload Campaign Member Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Upload_Campaign_Member_Batch__c/fields/RTL_Upload_Campaign_Member_Logs__c.field-meta.xml
<CustomField>
    <fullName>RTL_Upload_Campaign_Member_Logs__c</fullName>
    <label>RTL Upload Campaign Member Logs</label>
    <referenceTo>RTL_Upload_Campaign_Member_Logs__c</referenceTo>
    <relationshipName>Upload_Campaign_Member_Batches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTL_Upload_Campaign_Member_Logs__c/RTL_Upload_Campaign_Member_Logs__c.object-meta.xml
<CustomObject>
    <label>Upload Campaign Member Log</label>
    <nameField>
        <displayFormat>UCML-{00000000}</displayFormat>
        <label>Upload Campaign Member Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Upload Campaign Member Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Upload_Campaign_Members__c/RTL_Upload_Campaign_Members__c.object-meta.xml
<CustomObject>
    <label>Upload Campaign Member</label>
    <nameField>
        <displayFormat>UCM-{0000000}</displayFormat>
        <label>Upload Campaign Members Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTL Upload Campaign Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Upload_Campaign_Members__c/fields/RTL_Upload_Campaign_Member_Batch__c.field-meta.xml
<CustomField>
    <fullName>RTL_Upload_Campaign_Member_Batch__c</fullName>
    <label>RTL Upload Campaign Member Batch</label>
    <referenceTo>RTL_Upload_Campaign_Member_Batch__c</referenceTo>
    <relationshipName>Upload_Campaign_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTL_Upload_Campaign_Members__c/fields/RTL_Upload_Campaign_Member_Logs__c.field-meta.xml
<CustomField>
    <fullName>RTL_Upload_Campaign_Member_Logs__c</fullName>
    <label>RTL Upload Campaign Member Logs</label>
    <referenceTo>RTL_Upload_Campaign_Member_Logs__c</referenceTo>
    <relationshipName>Upload_Campaign_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RTL_UploadCampaignMemberDelete.cls
global class RTL_UploadCampaignMemberDelete implements Database.Batchable<sObject> {
	
	private String query;
	private String id;
	
	global RTL_UploadCampaignMemberDelete(String ucmlID) {
		id = ucmlID;
		query =  'SELECT ID FROM RTL_Upload_Campaign_Members__c WHERE RTL_Upload_Campaign_Member_Logs__r.id = :id';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<RTL_Upload_Campaign_Members__c> scope) {
		delete scope;
	}
	
	global void finish(Database.BatchableContext BC) {

		List<RTL_Upload_Campaign_Member_Batch__c> uploadMemberBatchResults = [
			SELECT ID 
			FROM RTL_Upload_Campaign_Member_Batch__c
			WHERE RTL_Upload_Campaign_Member_Logs__r.id = :id
            ];

        delete uploadMemberBatchResults;
		
	}
	
}