force-app/main/default/objects/PostChannel2Queue__mdt/PostChannel2Queue__mdt.object-meta.xml
<CustomObject>
    <label>Post Channel to Queue</label>
    <pluralLabel>Post Channel to Queue</pluralLabel>
</CustomObject>

force-app/main/default/objects/PostChannel2Queue__mdt/fields/Social_ID__c.field-meta.xml
<CustomField>
    <fullName>Social_ID__c</fullName>
    <label>Social ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostChannel2Queue__mdt/fields/Topic_Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Topic_Profile_Name__c</fullName>
    <label>Topic Profile Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostChannel2Queue__mdt/fields/Warroom_Channel__c.field-meta.xml
<CustomField>
    <fullName>Warroom_Channel__c</fullName>
    <label>Warroom Channel</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Skill_Master__c/Skill_Master__c.object-meta.xml
<CustomObject>
    <label>Skill Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Skill Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skill Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Master__c/fields/Assign_to_Queue__c.field-meta.xml
<CustomField>
    <fullName>Assign_to_Queue__c</fullName>
    <description>Assign to Queue</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Assign to Queue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Problem_Type__c.field-meta.xml
<CustomField>
    <fullName>Problem_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Problem Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Segment</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Service_Level1__c.field-meta.xml
<CustomField>
    <fullName>Service_Level1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Level1</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Service_Level2__c.field-meta.xml
<CustomField>
    <fullName>Service_Level2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Level2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Service_Level3__c.field-meta.xml
<CustomField>
    <fullName>Service_Level3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Level3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Social_Network__c.field-meta.xml
<CustomField>
    <fullName>Social_Network__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Social Network</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Topic</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Topic_Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Topic_Profile_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Topic Profile Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SLA_Config__mdt/SLA_Config__mdt.object-meta.xml
<CustomObject>
    <label>SLA Information Config</label>
    <pluralLabel>SLA Information Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/SLA_Config__mdt/fields/Time_Sec__c.field-meta.xml
<CustomField>
    <fullName>Time_Sec__c</fullName>
    <label>Time(Sec)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Social_Persona_Negative__c/Social_Persona_Negative__c.object-meta.xml
<CustomObject>
    <label>Social Persona Negative</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Social Persona Negative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Persona Negatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Persona_Negative__c/fields/Real_Name__c.field-meta.xml
<CustomField>
    <fullName>Real_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Real Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Persona_Negative__c/fields/Social_Persona_ID__c.field-meta.xml
<CustomField>
    <fullName>Social_Persona_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Social Persona ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Social_Post__c/Social_Post__c.object-meta.xml
<CustomObject>
    <label>Warroom Social Post</label>
    <nameField>
        <displayFormat>SP-{yyyy}{mm}-{00000}</displayFormat>
        <label>Social Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warroom Social Posts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Post__c/fields/Default_Social_Account__c.field-meta.xml
<CustomField>
    <fullName>Default_Social_Account__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Default Social Account</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Intention__c.field-meta.xml
<CustomField>
    <fullName>Intention__c</fullName>
    <label>Intention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Defame</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
                <default>true</default>
                <label>Inbound</label>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_Body__c.field-meta.xml
<CustomField>
    <fullName>Post_Body__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Post Body</label>
    <length>3200</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Post_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Post Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_ID__c.field-meta.xml
<CustomField>
    <fullName>Post_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Post ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_Identity_ID__c.field-meta.xml
<CustomField>
    <fullName>Post_Identity_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Post Identity ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Sentiment__c.field-meta.xml
<CustomField>
    <fullName>Sentiment__c</fullName>
    <label>Sentiment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>positive</fullName>
            </value>
            <value>
                <fullName>neutral</fullName>
            </value>
            <value>
                <fullName>negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <label>SLA</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Social_Post_Author__c.field-meta.xml
<CustomField>
    <fullName>Social_Post_Author__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Social Post Author</label>
    <referenceTo>Social_Post_Author__c</referenceTo>
    <relationshipName>Custom_Social_Posts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Source_Channel__c.field-meta.xml
<CustomField>
    <fullName>Source_Channel__c</fullName>
    <label>Source Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Facebook Inbox</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>LINE</fullName>
            </value>
            <value>
                <fullName>LINE Account Connect</fullName>
            </value>
            <value>
                <fullName>Pantip</fullName>
            </value>
            <value>
                <fullName>Pantip Inbox</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>Twitter Inbox</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Google Business Review</fullName>
            </value>
            <value>
                <fullName>Google Business QA</fullName>
            </value>
            <value>
                <fullName>Warroom Connect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Subject_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Subject Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Thread_ID__c.field-meta.xml
<CustomField>
    <fullName>Thread_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Thread ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Topic_Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Topic_Profile_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Topic Profile Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post_Author__c/Social_Post_Author__c.object-meta.xml
<CustomObject>
    <label>Social Post Author</label>
    <nameField>
        <displayFormat>SA-{YYYY}{MM}{0000}</displayFormat>
        <label>Social Post Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Post Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Post_Author__c/fields/Post_Author_Name__c.field-meta.xml
<CustomField>
    <fullName>Post_Author_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Social Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post_Negative__c/Social_Post_Negative__c.object-meta.xml
<CustomObject>
    <label>Social Post Negative</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Social Post Negative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Post Negatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Post_Negative__c/fields/Post_Channel__c.field-meta.xml
<CustomField>
    <fullName>Post_Channel__c</fullName>
    <label>Post Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post_Negative__c/fields/Posted_Date__c.field-meta.xml
<CustomField>
    <fullName>Posted_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Posted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Social_Post_Negative__c/fields/Sentiment__c.field-meta.xml
<CustomField>
    <fullName>Sentiment__c</fullName>
    <label>Sentiment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Negative</fullName>
            </value>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post_Negative__c/fields/Social_Persona_Negative__c.field-meta.xml
<CustomField>
    <fullName>Social_Persona_Negative__c</fullName>
    <label>Social Persona Negative</label>
    <referenceTo>Social_Persona_Negative__c</referenceTo>
    <relationshipLabel>Social Post Negatives</relationshipLabel>
    <relationshipName>Social_Post_Negatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Social_Post_Negative__c/fields/Social_Post_ID__c.field-meta.xml
<CustomField>
    <fullName>Social_Post_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Social Post ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SocialPostTriggerHandler.cls
public without sharing class SocialPostTriggerHandler {
    private static final Integer sla {
        get {
            // 120000 ms
            if(sla == null){
                List<SLA_Config__mdt> postSLA = [SELECT Time_Sec__c FROM SLA_Config__mdt WHERE DeveloperName = 'Post'];

                return postSLA != null && postSLA.size() > 0 ? Integer.valueOf(postSLA.get(0).Time_Sec__c) : 0;
            }
            return sla;
        }
        set;
    }

    public static Map<String,PostChannel2Queue__mdt> channelQueueMap {
        get{
            Map<String,PostChannel2Queue__mdt> channelQueueMap = new Map<String,PostChannel2Queue__mdt>();        
                for(PostChannel2Queue__mdt postChannel2Queue : [select id, Topic_Profile_Name__c, Warroom_Channel__c, Social_ID__c  from PostChannel2Queue__mdt] ){
                    channelQueueMap.put(postChannel2Queue.Warroom_Channel__c ,postChannel2Queue);
                }           
            return new Map<String,PostChannel2Queue__mdt>(channelQueueMap);
        }set;
    }

    public static void beforeInsert(List<Social_Post__c> newSocialPostList) {
        /* Find Queue name list */
        List<String> queueNameList = new List<String>();
        Map<String, Id> queueMap = new Map<String, Id>();
        Map<String, Social_Post__c> chkDupMap = new Map<String, Social_Post__c>();

        // Prepare Skill master map
        Map<String, Skill_Master__c> skillMasterMap = new Map<String, Skill_Master__c>();
        for (Skill_Master__c skillMaster : [SELECT id, Topic__c, Source__c, Segment__c, Assign_to_Queue__c, Service_Level1__c, Service_Level2__c, Service_Level3__c, Problem_Type__c, Social_Network__c, Topic_Profile_Name__c 
                                                FROM Skill_Master__c 
                                                WHERE Assign_to_Queue__c like 'Post%']) {

            skillMasterMap.put(skillMaster.Topic_Profile_Name__c, skillMaster);
            queueNameList.add(skillMaster.Assign_to_Queue__c);
        }

        // Prepare Queue map
        for (Group queue : [SELECT Id, Name, Type FROM Group WHERE Type='Queue' AND Name in :queueNameList]) {
            queueMap.put(queue.Name, queue.Id);
        }

        for (Social_Post__c socialPost : newSocialPostList) {
            System.debug('socialPost.Message_Type__c -->' + socialPost.Message_Type__c);
            if ( !'Outbound'.equals(socialPost.Message_Type__c) ) {
                /* Assign SLA */
                System.debug('sla -->' + sla);
                socialPost.SLA__c = sla;

                /* Assign to queue */
                PostChannel2Queue__mdt channelQueue = channelQueueMap.get(socialPost.Subject_Name__c);
                System.debug('channelQueue -->' + channelQueue);
                System.debug('Post_Body__c -->' + socialPost.Post_Body__c);
    
                if (queueMap != null) {
                    try {
                        Skill_Master__c skillMaster = skillMasterMap.get(channelQueue.Topic_Profile_Name__c);
                        System.debug('skillMaster -->' + skillMaster);
                        ID channelQueueId = queueMap.get(skillMaster.Assign_to_Queue__c);
                        System.debug('channelQueueId -->' + channelQueueId);
                        socialPost.OwnerId = channelQueueId;
                    } catch (Exception e) {
                        e.setMessage('Invalid subject name :: ' + socialPost.Subject_Name__c);
                        throw e;
                    }
                }

                if (channelQueue != null) {
                    socialPost.Topic_Profile_Name__c = channelQueue.Topic_Profile_Name__c;
                    socialPost.Default_Social_Account__c = channelQueue.Social_ID__c;
                }

                chkDupMap.put(socialPost.Post_Identity_ID__c, socialPost);
            }
        }

        List<Social_Post__c> updateSocialPostList = new List<Social_Post__c>();
        Set<String> socialPostToRemove = new Set<String>();
        for (Social_Post__c existingSocialPost : [SELECT id, Thread_ID__c, Post_ID__c, Post_Identity_ID__c from social_post__c where Post_Identity_ID__c in :chkDupMap.keySet()]) {
            Social_Post__c mapSocialPost = chkDupMap.get(existingSocialPost.Post_Identity_ID__c);
            if (mapSocialPost != null) {
                System.debug('existingSocialPost ID -->' + mapSocialPost.id);
                System.debug('mapSocialPost.Post_ID__c -->' + mapSocialPost.Post_ID__c);
                existingSocialPost.Post_ID__c = mapSocialPost.Post_ID__c;
    
    
                socialPostToRemove.add(existingSocialPost.Post_Identity_ID__c);
                updateSocialPostList.add(existingSocialPost);
            }
        }

        update updateSocialPostList;

        for (Social_Post__c socialPost : newSocialPostList) {
            if (socialPostToRemove.contains(socialPost.Post_Identity_ID__c)) {
                System.debug('Duplicate record -->' + socialPost.Post_Identity_ID__c);
                socialPost.addError('Duplicate record');
            }
        }

        System.debug('End beforeInsert');
    }

    public static void afterUpdate(List<Social_Post__c> newSocialPostList, Map<Id,Social_Post__c> oldMap) {
        
        /* Create negative post record */
        List<Social_Post__c> negativeList = new List<Social_Post__c>();
        for (Social_Post__c socialPost : newSocialPostList) {
            System.debug('Update social post Id -->' + socialPost.id);
            Social_Post__c oldSocialPost = oldMap.get(socialPost.id);
            if (socialPost.Intention__c == 'Defame' && oldSocialPost.Intention__c != 'Defame') {
                negativeList.add(socialPost);
            }
        }
        if (!negativeList.isEmpty()) {
            SocialPostTriggerHandler.negativePost(negativeList);
        }

    }

    private static void negativePost(List<Social_Post__c> newSocialPostList) {
       
        List<Social_Post_Negative__c> negativePostList = new List<Social_Post_Negative__c>();
        Map<String, Social_Persona_Negative__c> personaNegativeMap = new Map<String, Social_Persona_Negative__c>();

        Social_Post_Negative__c negativePost = null;
        Social_Persona_Negative__c personaNegative = null;
        List<String> personaIds = new List<String>(); 

        for (Social_Post__c socialPost : newSocialPostList) {
            personaIds.add(socialPost.Social_Post_Author__c);
        }
 
        for (Social_Post_Author__c socialPersona : [SELECT id, Name, Post_Author_Name__c from Social_Post_Author__c where id in :personaIds ]) {
            personaNegative = new Social_Persona_Negative__c();
            personaNegative.Real_Name__c = socialPersona.Post_Author_Name__c;
            personaNegative.Social_Persona_ID__c = socialPersona.id;
            personaNegative.name = socialPersona.name;
            personaNegativeMap.put(socialPersona.id, personaNegative);
        }

        upsert personaNegativeMap.values() Social_Persona_ID__c;
         
        for (Social_Post__c socialPost : newSocialPostList) {
                  
            negativePost = new Social_Post_Negative__c();
            negativePost.Social_Persona_Negative__c = personaNegativeMap.get(socialPost.Social_Post_Author__c).id;
            negativePost.Posted_Date__c = socialPost.Post_Date__c;
            negativePost.Sentiment__c = socialPost.Sentiment__c;
            negativePost.Post_Channel__c = socialPost.Source_Channel__c;
            negativePost.Intention__c = socialPost.Intention__c;
            negativePost.Message__c = socialPost.Post_Body__c;
            negativePost.Social_Post_ID__c = socialPost.Id;
            System.debug('    negativePost --> ' + negativePost);
            
            negativePostList.add(negativePost);
        }

        insert negativePostList;
        
    }

    private class InvalidSubjectException extends Exception{}
}