force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Customer Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Qualified Prospect</fullName>
            </value>
            <value>
                <fullName>Disqualified Prospect</fullName>
            </value>
            <value>
                <fullName>Existing Customer</fullName>
            </value>
            <value>
                <fullName>Retail Customer</fullName>
            </value>
            <value>
                <fullName>Retail Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>ประเภทลูกค้าว่าเป็น  บุคคล หรือ บริษัท</description>
    <inlineHelpText>ประเภทลูกค้าว่าเป็น  บุคคล หรือ บริษัท</inlineHelpText>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
                <default>true</default>
                <label>Individual</label>
            </value>
            <value>
                <fullName>Juristic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/First_name_PE__c.field-meta.xml
<CustomField>
    <fullName>First_name_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>First Name TH</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_name_PE__c.field-meta.xml
<CustomField>
    <fullName>Last_name_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Last Name TH</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RTL_RM_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_RM_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>EMP/BR CODE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Branch_Manager_Title__c/RTL_Branch_Manager_Title__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Branch Manager Title</label>
</CustomObject>

force-app/main/default/objects/RTL_Branch_Manager_Title__c/fields/RTL_Value__c.field-meta.xml
<CustomField>
    <fullName>RTL_Value__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Household__c/RTL_Household__c.object-meta.xml
<CustomObject>
    <label>Household</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Household__c/fields/RTL_Benefit_Package__c.field-meta.xml
<CustomField>
    <fullName>RTL_Benefit_Package__c</fullName>
    <description>Benefit Package the Primary Household Member is entitled to</description>
    <label>Benefit Package</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wealth Package 1</fullName>
            </value>
            <value>
                <fullName>Wealth Package 2</fullName>
            </value>
            <value>
                <fullName>Wealth Package 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/RTL_Household_Member__c.object-meta.xml
<CustomObject>
    <label>Household Membership</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Household Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_Benefit__c.field-meta.xml
<CustomField>
    <fullName>RTL_Benefit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Member is entitled to Household Benefit</description>
    <label>Benefit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_Household__c.field-meta.xml
<CustomField>
    <fullName>RTL_Household__c</fullName>
    <description>Household that this member record belongs to</description>
    <label>Household</label>
    <referenceTo>RTL_Household__c</referenceTo>
    <relationshipName>Household_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_Household_Member_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_Household_Member_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of this Household Member</description>
    <label>Household Member Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Household_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_Primary__c.field-meta.xml
<CustomField>
    <fullName>RTL_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates this member is the Primary member of this Household</description>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RTL_HouseholdExtensionTest.cls
@isTest
public class RTL_HouseholdExtensionTest {
	
    static User rmUser;
    static User rmManager;
    static List<Account> acctList;
    static List<RTL_Household__c> householdList;
    
    static{
       	TestUtils.createAppConfig();
        rmUser = RTL_TestUtility.createRetailTestUserWithBranch(true);
        rmManager = RTL_TestUtility.createRetailTestUser(true);
        acctList = RTL_TestUtility.createAccounts(2,true);
    }
    static testmethod void testInsertHouseholdSuccessCase(){
        rmUser.Employee_ID__c = '11111';
       	update rmUser;
        acctList[0].RTL_RM_Name__c = '11111';
        update acctList;
        Test.startTest();
        	
        	List<RTL_HouseHold__c> hhList = null;
        	hhList = [SELECT Id,Name FROM RTL_Household__c];
        	//check if system doesn't have any household data
        	System.assertEquals(0, hhList.size());
        	
        	Test.setCurrentPage(Page.RTL_HouseHold_Creation);
        	ApexPages.currentPage().getParameters().put('acctId',acctList[0].id);
        	ApexPages.StandardController std = new ApexPages.StandardController(acctList[0]);
        	RTL_HouseHoldExtension ext = new RTL_HouseHoldExtension(std);
        	ext.household.RTL_Benefit_Package__c = 'Wealth Package 1';
        	//save to insert household
        	ext.save();
        	hhList = [SELECT Id,Name,(SELECT ID,Name,RTL_Primary__c,RTL_Benefit__c FROM Household_Members__r) FROM RTL_Household__c];
        	//Check Result : Household was created in the system
        	System.assertEquals(1,hhList.size());
        	//Check Result : Household was created with one member
        	System.assertEquals(1,hhList[0].Household_Members__r.size());
        	//Check Result : Household Member is Primary
        	System.assertEquals(true,hhList[0].Household_Members__r[0].RTL_Primary__c);
        Test.stopTest();
        
    }
    
     static testmethod void testInsertHouseholdFromBranchSuccessCase(){
        RTL_Branch_Manager_Title__c branchTitle = new RTL_Branch_Manager_Title__c(Name='Branch Manager',RTL_Value__c ='Branch');
      	insert branchTitle;
        rmUser.RTL_Branch_Code__c = '111';
        rmUser.title = 'Branch';
       	update rmUser;
        acctList[0].RTL_RM_Name__c = '00111';
        update acctList;
        Test.startTest();
        	
        	List<RTL_HouseHold__c> hhList = null;
        	hhList = [SELECT Id,Name FROM RTL_Household__c];
        	//check if system doesn't have any household data
        	System.assertEquals(0, hhList.size());
        	
        	Test.setCurrentPage(Page.RTL_HouseHold_Creation);
        	ApexPages.currentPage().getParameters().put('acctId',acctList[0].id);
        	ApexPages.StandardController std = new ApexPages.StandardController(acctList[0]);
        	RTL_HouseHoldExtension ext = new RTL_HouseHoldExtension(std);
        	ext.household.RTL_Benefit_Package__c = 'Wealth Package 1';
        	//save to insert household
        	ext.save();
        	hhList = [SELECT Id,Name,(SELECT ID,Name,RTL_Primary__c,RTL_Benefit__c FROM Household_Members__r) FROM RTL_Household__c];
        	//Check Result : Household was created in the system
        	System.assertEquals(1,hhList.size());
        	//Check Result : Household was created with one member
        	System.assertEquals(1,hhList[0].Household_Members__r.size());
        	//Check Result : Household Member is Primary
        	System.assertEquals(true,hhList[0].Household_Members__r[0].RTL_Primary__c);
        Test.stopTest();
        
    }
    
    static testmethod void testDuplicateHouseholdNameCase(){
        Test.startTest();
        	//Insert Household to let the system have exist household record
        	householdList = RTL_TestUtility2.createHouseholdwithPrimaryMember(1,true,rmUser,acctList[0]);
        	acctList = [SELECT ID,Name,First_Name_PE__c,Last_Name_PE__c,Account_Type__c,Customer_Type__c FROM Account];
        	//update existing household name to account name
        	householdList[0].Name = acctList[0].Last_Name_PE__c+' '+acctList[0].First_Name_PE__c;
        	update householdList;
            System.debug('ACCT ::: '+acctList[0]);
        	Test.setCurrentPage(Page.RTL_HouseHold_Creation);
        	ApexPages.currentPage().getParameters().put('acctId',acctList[0].id);
        	ApexPages.StandardController std = new ApexPages.StandardController(acctList[0]);
        	RTL_HouseHoldExtension ext = new RTL_HouseHoldExtension(std); 
        	ext.household.RTL_Benefit_Package__c = 'Wealth Package 1';
        	//Insert Household
        	ext.save();
        	
        	//Check Result : Inserted Household must named as account name + sequence
        	System.debug('ACCT ::: '+acctList[0].Last_Name_PE__c +acctList[0].First_Name_PE__c );
            System.debug('ACCT ::: HOUSEHOLD NAME :: '+ext.household.Name);
        	System.assertEquals(acctList[0].Last_Name_PE__c+' '+acctList[0].First_Name_PE__c+' 001', ext.household.Name);
        	ext.cancel();
        Test.stopTest();
        
    }
    static testmethod void testInsertHouseholdFailedCase(){
        Test.startTest();
        	List<RTL_HouseHold__c> hhList = null;
        	hhList = [SELECT Id,Name FROM RTL_Household__c];
        	//check if system doesn't have any household data
        	System.assertEquals(0, hhList.size());
        
        	Test.setCurrentPage(Page.RTL_HouseHold_Creation);
        	ApexPages.currentPage().getParameters().put('acctId',acctList[0].id);
        	ApexPages.StandardController std = new ApexPages.StandardController(acctList[0]);
        	RTL_HouseHoldExtension ext = new RTL_HouseHoldExtension(std);
        	
        	ext.save();
        
        	hhList = [SELECT Id,Name FROM RTL_Household__c];
        	//Check Result : Sytem should not have any household data due to insertion failed.
        	System.assertEquals(0, hhList.size());
        	
        	ext.cancel();
        Test.stopTest();
        
    }
}