force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Customer Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Qualified Prospect</fullName>
            </value>
            <value>
                <fullName>Disqualified Prospect</fullName>
            </value>
            <value>
                <fullName>Existing Customer</fullName>
            </value>
            <value>
                <fullName>Retail Customer</fullName>
            </value>
            <value>
                <fullName>Retail Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Number_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Number_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>เลขที่เอกสารสำคัญของลูกค้า</inlineHelpText>
    <label>ID Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Type_PE__c</fullName>
    <description>Identification Type Ex. Citizen ID, BRN ID, Passport ID, Alien ID, Work permit</description>
    <inlineHelpText>ประเภทเอกสารสำคัญของลูกค้า</inlineHelpText>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Customer_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BRN ID</fullName>
            </value>
            <value>
                <fullName>Citizen ID</fullName>
            </value>
            <value>
                <fullName>Passport ID</fullName>
            </value>
            <value>
                <fullName>Work permit ID</fullName>
            </value>
            <value>
                <fullName>Alien ID</fullName>
            </value>
            <value>
                <fullName>Tax ID</fullName>
            </value>
            <value>
                <fullName>Other ID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Plan_Fiscal_Year__c/Account_Plan_Fiscal_Year__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Account Plan Fiscal Year</label>
</CustomObject>

force-app/main/default/objects/Account_Plan_Fiscal_Year__c/fields/AD_Year__c.field-meta.xml
<CustomField>
    <fullName>AD_Year__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AD Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Plan_Fiscal_Year__c/fields/BE_Year__c.field-meta.xml
<CustomField>
    <fullName>BE_Year__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>BE Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Host_Product_Mapping__c/Host_Product_Mapping__c.object-meta.xml
<CustomObject>
    <description>Master table to map host products to SF product table</description>
    <label>Host Product Mapping</label>
    <nameField>
        <displayFormat>HP-{0000}</displayFormat>
        <label>Host Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Host Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Host_Product_Mapping__c/fields/Credit_Type_ID__c.field-meta.xml
<CustomField>
    <fullName>Credit_Type_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Credit Type ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Host_Product_Mapping__c/fields/Host_Name__c.field-meta.xml
<CustomField>
    <fullName>Host_Name__c</fullName>
    <inlineHelpText>ชื่อระบบขออนุมัติสินเชื่อ</inlineHelpText>
    <label>Host Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SLS</fullName>
            </value>
            <value>
                <fullName>EXCEL</fullName>
            </value>
            <value>
                <fullName>FSR</fullName>
                <isActive>false</isActive>
                <label>FSR</label>
            </value>
            <value>
                <fullName>TPT</fullName>
                <isActive>false</isActive>
                <label>TPT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Host_Product_Mapping__c/fields/Host_Prod_Name_Credit_Facility__c.field-meta.xml
<CustomField>
    <fullName>Host_Prod_Name_Credit_Facility__c</fullName>
    <inlineHelpText>ชื่อ Credit Facility (SLS)</inlineHelpText>
    <label>Host Prod Name/Credit Facility</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Program__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loan - Core WC</fullName>
            </value>
            <value>
                <fullName>Loan - Quick Loan 10%</fullName>
            </value>
            <value>
                <fullName>Loan - Quick Loan 15%</fullName>
            </value>
            <value>
                <fullName>Loan - Land</fullName>
            </value>
            <value>
                <fullName>Loan - Construction</fullName>
            </value>
            <value>
                <fullName>Loan - Machine</fullName>
            </value>
            <value>
                <fullName>OD</fullName>
            </value>
            <value>
                <fullName>L/G Utility</fullName>
            </value>
            <value>
                <fullName>L/G Lending Guarantee</fullName>
            </value>
            <value>
                <fullName>L/G Credit Purchasing Guarantee</fullName>
            </value>
            <value>
                <fullName>L/G Performance Guarantee</fullName>
            </value>
            <value>
                <fullName>L/G Advance Payment Guarantee</fullName>
            </value>
            <value>
                <fullName>L/G Retention Guarantee</fullName>
            </value>
            <value>
                <fullName>L/G Tax/Duty Guarantee</fullName>
            </value>
            <value>
                <fullName>L/G Tender Guarantee/Bid Bond</fullName>
            </value>
            <value>
                <fullName>L/G Other</fullName>
            </value>
            <value>
                <fullName>AVAL</fullName>
            </value>
            <value>
                <fullName>ACCEPTANCE</fullName>
            </value>
            <value>
                <fullName>F/X - FORWARD</fullName>
            </value>
            <value>
                <fullName>L/C Loan one time</fullName>
            </value>
            <value>
                <fullName>Fleet Card</fullName>
            </value>
            <value>
                <fullName>OBOD</fullName>
            </value>
            <value>
                <fullName>Excel Test</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL LOANS</fullName>
            </value>
            <value>
                <fullName>OD for Floating Charge</fullName>
            </value>
            <value>
                <fullName>Loan - General</fullName>
            </value>
            <value>
                <fullName>Loan - Special (GSB)</fullName>
            </value>
            <value>
                <fullName>Top-up for Refinance cost</fullName>
            </value>
            <value>
                <fullName>OD for Growth</fullName>
            </value>
            <value>
                <fullName>UNSECURED LOAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Host_Product_Mapping__c/fields/Host_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Host_Product_Group__c</fullName>
    <inlineHelpText>ชื่อ Product Group (SLS)</inlineHelpText>
    <label>Host Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Host_Name__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TMB SME SmartBiz</fullName>
            </value>
            <value>
                <fullName>F-Cash</fullName>
            </value>
            <value>
                <fullName>NEW IFC</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>Excel Test</fullName>
            </value>
            <value>
                <fullName>OD No Asset</fullName>
            </value>
            <value>
                <fullName>Quick Loan</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Non Product Program</fullName>
                <isActive>false</isActive>
                <label>Non Product Program</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Host_Product_Mapping__c/fields/Product_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Group_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Group ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Host_Product_Mapping__c/fields/Product_Program__c.field-meta.xml
<CustomField>
    <fullName>Product_Program__c</fullName>
    <inlineHelpText>ชื่อ Product Program (SLS)</inlineHelpText>
    <label>Host Product Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Host_Product_Group__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SmartBiz for Construction</fullName>
            </value>
            <value>
                <fullName>OD No Asset</fullName>
            </value>
            <value>
                <fullName>Retention Pre Approve</fullName>
            </value>
            <value>
                <fullName>Retention Non Pre Approve</fullName>
            </value>
            <value>
                <fullName>Quick Loan</fullName>
            </value>
            <value>
                <fullName>NEW IFC</fullName>
            </value>
            <value>
                <fullName>Excel Test</fullName>
            </value>
            <value>
                <fullName>TMB SME SmartBiz</fullName>
            </value>
            <value>
                <fullName>Top Up Bancassurance</fullName>
            </value>
            <value>
                <fullName>F-Cash</fullName>
            </value>
            <value>
                <fullName>ODB</fullName>
            </value>
            <value>
                <fullName>Factoring</fullName>
            </value>
            <value>
                <fullName>SmartBiz E-Commerce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Host_Product_Mapping__c/fields/Product_Program_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Program_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Program ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price_book_access__c/Price_book_access__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Using for Price book assignment when create the opportunity
[Support Mobility limitation]</description>
    <label>PriceBookAccess</label>
</CustomObject>

force-app/main/default/objects/Price_book_access__c/fields/PricebookItem__c.field-meta.xml
<CustomField>
    <fullName>PricebookItem__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PricebookItem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status_Code__c/Status_Code__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Error,Warning message handler</description>
    <label>Status Code</label>
</CustomObject>

force-app/main/default/objects/Status_Code__c/fields/Status_Message__c.field-meta.xml
<CustomField>
    <fullName>Status_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SLOSContextTest.cls
@istest
public class SLOSContextTest {
  
    static {
        TestUtils.createIdType();
        TestUtils.createAppConfig();
        TestUtils.createStatusCode();
        TestUtils.createDisqualifiedReason();
        //TestUtils.CreateTriggerMsg();
        TestInit.createCustomSettingStageApproval();
        
    }
    
    public static Id pb1 {get{return Test.getStandardPricebookId();}set;}
    public static pricebook2 pb2 {get;set;}
    public static product2 prod {get;set;}
    public static pricebookentry pbe {get;set;}
    public static account acct {get;set;}
    public static opportunity oppt {get;set;} 
    public static host_product_mapping__c hostmap {get;set;}
    
    public static void setInitial()
    {
        insert new status_code__c(name = '8041', Status_Message__c = 'test');
        insert new status_code__c(name = '8043', Status_Message__c = 'test');
        insert new status_code__c(name = '8037', Status_Message__c = 'test');
        insert new status_code__c(name = '8038', Status_Message__c = 'test');
        insert new status_code__c(name = '8039', Status_Message__c = 'test');
        insert new status_code__c(name = '8023', Status_Message__c = 'test');
        insert new status_code__c(name = '8040', Status_Message__c = 'test');
        insert new AppConfig__c(name = 'runtrigger', value__c = 'TRUE');
        insert new AppConfig__c(name = 'FilterPrimaryProvince', value__c = 'จ.|จังหวัด');
        insert new AppConfig__c(name = 'FilterPrimaryDistrict', value__c = 'อ.|อำเภอ|เขต');
        insert new AppConfig__c(name = 'FilterPrimarySubDistrict', value__c = 'ต.|ตำบล|แขวง');
        insert new AppConfig__c(name = 'FilterRetailSegment	', value__c = '5|6|7|8|9');
        insert new Trigger_Msg__c(name = 'Permission_Create_Opportunity', Description__c   = 'description');
        insert new Account_Plan_Fiscal_Year__c(name='2',ad_year__c='2015',be_year__c='2558');
        user u = [select segment__c from user where id =: userinfo.getUserId()];
        if (u.segment__c != null){ 
            insert new Price_book_access__c(name=u.segment__c,PricebookItem__c='test');
        }
        else insert new Price_book_access__c(name='MB',PricebookItem__c='test');
        insert new Price_book_access__c(name='Default',PricebookItem__c='test');
        
        pb2 = new pricebook2(name='test',isActive=true,TMB_Pricebook__c='test');
        insert pb2;
        prod = new product2(name='test',isactive=true,Product_Domain__c='Risk');
        insert prod;
        pbe = new pricebookentry(isactive=true,unitprice=1.00,product2id=prod.id,pricebook2id=pb1,usestandardprice=false);
        insert pbe;
        
        acct = testutils.createAccounts(1, 'fname', 'Individual', false).get(0);
        acct.Account_Type__c = 'Existing Customer';
        acct.ID_Type_PE__c =null;
        acct.ID_Number_PE__c =null;
        insert acct;
        oppt = new opportunity(Pricebook2Id=pb1,accountid = acct.id, name='test', ownerid = acct.ownerid,
                               Expected_submit_date__c = date.today(), closedate = date.today(),
                               Host_Product_Group__c = 'TMB SME SmartBiz',
                               stagename = 'Analysis');
        insert oppt;
		
        hostmap = new Host_Product_Mapping__c(Active_Flag__c=true,Host_Name__c='SLS',
                                              Host_Product_Group__c='TMB SME SmartBiz',
                                             Product_Program__c='TMB SME SmartBiz',Credit_Type_ID__c='102',
                                             Host_Prod_Name_Credit_Facility__c ='OD for Floating Charge',Product_Group_ID__c='1',
                                             Product_Program_ID__c='1',Salesforce_Product__c=prod.id);
     	insert hostmap;  
    }
    public static testmethod void myPositiveUnitTest(){
        
                Test.startTest();
        
        setInitial();
        
        opportunitylineitem opptline = new opportunitylineitem(opportunityid = oppt.id, quantity = 1.00, pricebookentryid = pbe.id,unitprice=1.00
                                                               ,RevisedStartMonth__c='Dec',RevisedStartYear__c=string.valueof(system.today()).substring(0,4)
                                                               ,RevisedStartMonthFee__c='Dec',RevisedStartYearFee__c=string.valueof(system.today()).substring(0,4)
                                                               ,Type_Of_Reference__c='NIIc',Type_Of_Reference_Fee__c='AS Fee'
                                                               ,host_product_mapping__c=hostmap.id
                                                              );
          insert opptline;

        
        
        List<OpportunityLineItem> lines = new List<OpportunityLineItem>();
        lines.add(opptline);
        SLOSContext context = new SLOSContext();
        SLOSContext.SLOSRequest request = new SLOSContext.SLOSRequest(oppt ,lines);
        
        Test.stopTest();
        
    }

}