force-app/main/default/objects/Account/fields/As_of_date_Wallet__c.field-meta.xml
<CustomField>
    <fullName>As_of_date_Wallet__c</fullName>
    <formula>TEXT(DAY(Income_as_of_Wallet__c)) &amp; &quot; &quot;&amp; CASE(MONTH( Income_as_of_Wallet__c), 1, &quot;Jan&quot;, 2, &quot;Feb&quot;, 3, &quot;Mar&quot;, 4, &quot;Apr&quot;, 5, &quot;May&quot;, 6, &quot;Jun&quot;, 7, &quot;Jul&quot;, 8, &quot;Aug&quot;, 9, &quot;Sep&quot;, 10, &quot;Oct&quot;, 11, &quot;Nov&quot;, &quot;Dec&quot;) &amp; &quot;, &quot;&amp; TEXT(YEAR(Income_as_of_Wallet__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>As of date (Wallet)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fee_Actual__c.field-meta.xml
<CustomField>
    <fullName>Fee_Actual__c</fullName>
    <label>Fee (Actual NI) Core Bank</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fee_Plan__c.field-meta.xml
<CustomField>
    <fullName>Fee_Plan__c</fullName>
    <label>Fee (Expected NI) Account Plan</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fee_SoW__c.field-meta.xml
<CustomField>
    <fullName>Fee_SoW__c</fullName>
    <formula>IF(Fee_Wallet__c=0,0,(( Fee_Actual__c  / (MONTH( Income_as_of_Wallet__c)))*12)/  Fee_Wallet__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fee (SoW) Core Bank</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fee_Wallet__c.field-meta.xml
<CustomField>
    <fullName>Fee_Wallet__c</fullName>
    <label>Fee (Wallet) Core Bank</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gross_Profit__c.field-meta.xml
<CustomField>
    <fullName>Gross_Profit__c</fullName>
    <label>Gross Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Loan_Classification__c.field-meta.xml
<CustomField>
    <fullName>Loan_Classification__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Loan Classification</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Net_Profit_Baht__c.field-meta.xml
<CustomField>
    <fullName>Net_Profit_Baht__c</fullName>
    <label>Net Profit (Baht)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/NI_Actual__c.field-meta.xml
<CustomField>
    <fullName>NI_Actual__c</fullName>
    <label>NI (Actual NI) Core Bank</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/NI_Plan__c.field-meta.xml
<CustomField>
    <fullName>NI_Plan__c</fullName>
    <label>NI (Expected NI) Account Plan</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/NI_SoW__c.field-meta.xml
<CustomField>
    <fullName>NI_SoW__c</fullName>
    <formula>if(NI_Wallet__c=0,0,(
(
( NIIc_Actual__c + NIId_Actual__c +  Fee_Actual__c + Supply_Chain_Actual__c ) / MONTH( Income_as_of_Wallet__c )
)*12
)/ NI_Wallet__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NI (SoW) Core Bank</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/NI_Wallet__c.field-meta.xml
<CustomField>
    <fullName>NI_Wallet__c</fullName>
    <label>NI (Wallet) Core Bank</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/NIIc_Actual__c.field-meta.xml
<CustomField>
    <fullName>NIIc_Actual__c</fullName>
    <label>NIIc (Actual NI) Core Bank</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/NIIc_Plan__c.field-meta.xml
<CustomField>
    <fullName>NIIc_Plan__c</fullName>
    <label>NIIc (Expected NI) Account Plan</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/NIIc_SoW__c.field-meta.xml
<CustomField>
    <fullName>NIIc_SoW__c</fullName>
    <formula>if (NIIc_Wallet__c = 0,0,((NIIc_Actual__c / (MONTH( Income_as_of_Wallet__c)))*12)/ NIIc_Wallet__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NIIc (SoW) Core Bank</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/NIIc_Wallet__c.field-meta.xml
<CustomField>
    <fullName>NIIc_Wallet__c</fullName>
    <label>NIIc (Wallet) Core Bank</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/NIId_Actual__c.field-meta.xml
<CustomField>
    <fullName>NIId_Actual__c</fullName>
    <label>NIId (Actual NI) Core Bank</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/NIId_Plan__c.field-meta.xml
<CustomField>
    <fullName>NIId_Plan__c</fullName>
    <label>NIId (Expected NI) Account Plan</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/NIId_SoW__c.field-meta.xml
<CustomField>
    <fullName>NIId_SoW__c</fullName>
    <formula>IF(NIId_Wallet__c=0,0,(( NIId_Actual__c  / (MONTH( Income_as_of_Wallet__c)))*12)/   NIId_Wallet__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NIId (SoW) Core Bank</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/NIId_Wallet__c.field-meta.xml
<CustomField>
    <fullName>NIId_Wallet__c</fullName>
    <label>NIId (Wallet) Core Bank</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/No_of_Open_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>No_of_Open_Opportunities__c</fullName>
    <label>No. of Open Opportunities</label>
    <summaryFilterItems>
        <field>Opportunity.IsClosed</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.RecordTypeId</field>
        <operation>notEqual</operation>
        <value>Retail Bancassurance, Retail Card and RDC, Retail Deposit, Retail Investment, Retail Loans, Retail Others, Retail Retentions</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/RTL_RM_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_RM_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>EMP/BR CODE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SCF_Score__c.field-meta.xml
<CustomField>
    <fullName>SCF_Score__c</fullName>
    <label>Credit Rate</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Supply_Chain_Actual__c.field-meta.xml
<CustomField>
    <fullName>Supply_Chain_Actual__c</fullName>
    <label>Supply Chain (Actual)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Revenue_Baht__c.field-meta.xml
<CustomField>
    <fullName>Total_Revenue_Baht__c</fullName>
    <label>Total Revenue (Data from Enlite system)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustSingleView__c/CustSingleView__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Customer Single View, Report name of Product on hand, Pipeline, etc..</description>
    <label>CustSingleView</label>
</CustomObject>

force-app/main/default/objects/CustSingleView__c/fields/ReportName__c.field-meta.xml
<CustomField>
    <fullName>ReportName__c</fullName>
    <description>ReportName</description>
    <encryptionScheme>None</encryptionScheme>
    <label>ReportName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CollateralProxyCtrl.cls
public class CollateralProxyCtrl {
    
private final ApexPages.StandardController std ;
    public Account tmpAcct {get;set;}
    private Account accts; 
    public boolean isAccountTeam {get;set;}
    public List<UserRecordAccess> accessList {get;set;}
    public id CollateralReportId {get;set;}
    public id CollateralReportId_Partition {get;set;}
    public String tabId {get;set;}
    
    public CollateralProxyCtrl(ApexPages.StandardController std){
        accts = (Account)std.getRecord();
        //std = controller;
        //accts = (account)std.getRecord();
        isAccountTeam = false;

        string accid = apexpages.currentpage().getparameters().get('acctId');

        tmpAcct = [select Loan_Classification__c, SCF_Score__c
                           ,NI_Plan__c,NIIc_Plan__c,NIId_Plan__c,Fee_Plan__c
                           , NI_Wallet__c, NIIc_Wallet__c, NIId_Wallet__c, Fee_Wallet__c
                           ,NI_Actual__c, NIIc_Actual__c, NIId_Actual__c, Fee_Actual__c
                           , NI_SoW__c, NIIc_SoW__c, NIId_SoW__c, Fee_SoW__c
                           , Total_Revenue_Baht__c, Gross_Profit__c, Net_Profit_Baht__c
                           , Last_Activity_Date__c,Supply_Chain_Actual__c,As_of_date_Wallet__c
                           ,No_of_Open_Opportunities__c
                           , owner.UserRoleId
                           from Account where id =: accid]; 

        accessList = [SELECT RecordId, 
            HasAllAccess,HasEditAccess, HasReadAccess  
            FROM UserRecordAccess 
            WHERE UserId =: Userinfo.getUserId()
            AND RecordId =: tmpAcct.id
           ];
        system.debug('accessList : '+accessList.size());
        
         try{
            CustSingleView__c CustSingleView7 = CustSingleView__c.GetValues('CollateralReport');
            String collateral = CustSingleView7.ReportName__c;
            CollateralReportId = [SELECT id FROM report where name = : collateral ].Id;
             
            CustSingleView__c CustSingleView7_2 = CustSingleView__c.GetValues('CollateralReport_Partition');
            String collateral_Partition = CustSingleView7_2.ReportName__c;
            CollateralReportId_Partition = [SELECT id FROM report where name = : collateral_Partition ].Id;
         }catch(Exception Ex){
           	system.debug('::::::Exception Domain5Id::::::');
         }
        
    }
    // Desktop
    public PageReference redirectPage(){
        string accid = apexpages.currentpage().getparameters().get('acctId');
		//string CollateralReportId = apexpages.currentpage().getparameters().get('collateral');
        try{
        	tabId = apexpages.currentPage().getParameters().get('tabId');
        }catch(Exception e){
            tabId = '';
        }
        //string types = apexpages.currentpage().getparameters().get('type');
        system.debug('accid :'+accid);
        system.debug('CollateralReportId :'+CollateralReportId);
        /*
        tmpAcct = [select Loan_Classification__c, SCF_Score__c
                           ,NI_Plan__c,NIIc_Plan__c,NIId_Plan__c,Fee_Plan__c
                           , NI_Wallet__c, NIIc_Wallet__c, NIId_Wallet__c, Fee_Wallet__c
                           ,NI_Actual__c, NIIc_Actual__c, NIId_Actual__c, Fee_Actual__c
                           , NI_SoW__c, NIIc_SoW__c, NIId_SoW__c, Fee_SoW__c
                           , Total_Revenue_Baht__c, Gross_Profit__c, Net_Profit_Baht__c
                           , Last_Activity_Date__c,Supply_Chain_Actual__c,As_of_date_Wallet__c
                           ,No_of_Open_Opportunities__c
                           from Account where id =: accId];
        
       List<UserRecordAccess> accessList = 
           [SELECT RecordId, 
            HasAllAccess,HasEditAccess, HasReadAccess  
            FROM UserRecordAccess 
            WHERE UserId =: Userinfo.getUserId()
            AND RecordId =: tmpAcct.id
           ];
        system.debug('accessList : '+accessList.size());
        */
        
		//set<string> AccteamId = new set<String>();
  //      id currentuserId = Userinfo.getUserId();
  //      list<AccountTeamMember> accTeam = [select Id,AccountAccessLevel,AccountId,TeamMemberRole,UserId 
  //                                     from AccountTeamMember 
  //                                     where AccountId =:accId];
  //          if(accTeam.size() > 0) {
  //              for(AccountTeamMember acc : accTeam) {
  //                  AccteamId.add(acc.UserId);
  //              }
  //       	}
  //      if(AccteamId.contains(currentuserId)){
  //          isAccountTeam = true;
  //      }
        // Remove old logic and check only from data partition
		//if(accessList.size()>0){
            //if(checkAuthorize() || isAccountTeam == true){
                string url = '';
                if(checkAuthorizeMatrix()){
                    // url = '/'+CollateralReportId+'?pv0='+accid.left(15);
                    url = '/lightning/r/Report/'+CollateralReportId+'/view?fv0='+accid;
                }else{            
                    //url = '/'+CollateralReportId_Partition+'?pv0='+accid.left(15);
                	url = '/apex/DataPartitionDetail?id='+accid+'&type=8&isVisible=false&tabId='+tabId;
                }
            PageReference page = new PageReference(url); 
        	page.setRedirect(true); 
        	return page; 
        	//}
            //else{
         //   //string url2 = '/apex/DataPartitionDetail?id='+accid+'&type=8';
         //   string url2 = '/apex/DataPartitionDetail?id='+accid+'&type=8&isVisible=false&tabId='+tabId;
         //   PageReference page = new PageReference(url2); 
        	//page.setRedirect(true); 
        	//return page; 
        	//}
        //}
        //return null;
    }
    // Mobile
    public PageReference redirectMobile(){        
        string accid = apexpages.currentpage().getparameters().get('acctId');
		string CollateralReportId = apexpages.currentpage().getparameters().get('collateral');
        //string types = apexpages.currentpage().getparameters().get('type');
        system.debug('accid :'+accid);

        /*
        system.debug('CollateralReportId :'+CollateralReportId);
        tmpAcct = [select Loan_Classification__c, SCF_Score__c
                           ,NI_Plan__c,NIIc_Plan__c,NIId_Plan__c,Fee_Plan__c
                           , NI_Wallet__c, NIIc_Wallet__c, NIId_Wallet__c, Fee_Wallet__c
                           ,NI_Actual__c, NIIc_Actual__c, NIId_Actual__c, Fee_Actual__c
                           , NI_SoW__c, NIIc_SoW__c, NIId_SoW__c, Fee_SoW__c
                           , Total_Revenue_Baht__c, Gross_Profit__c, Net_Profit_Baht__c
                           , Last_Activity_Date__c,Supply_Chain_Actual__c,As_of_date_Wallet__c
                           ,No_of_Open_Opportunities__c
                           from Account where id =: accId]; 
         
       List<UserRecordAccess> accessList = 
           [SELECT RecordId, 
            HasAllAccess,HasEditAccess, HasReadAccess  
            FROM UserRecordAccess 
            WHERE UserId =: Userinfo.getUserId()
            AND RecordId =: tmpAcct.id
           ];
        system.debug('accessList : '+accessList.size());
        */

		//if(accessList.size()>0){
  //          if(checkAuthorize() || isAccountTeam == true){
                string url = '';
                if(checkAuthorizeMatrix()){
            		url = '/apex/Collateral_Report_Mobile?id='+accid+'&sfredirect=true';     
                }else{            
                    //url = '/apex/Collateral_Report_Mobile_Partition?id='+accid+'&sfredirect=true';
                	url = '/apex/DataPartitionDetail?id='+accid+'&type=8&isVisible=false';
                }
            PageReference page = new PageReference(url); 
        	page.setRedirect(true); 
        	return page;
                
        //	}else{
        //        string url2 = '/apex/DataPartitionDetail?id='+accid+'&type=8&isVisible=false';
        //    PageReference page = new PageReference(url2); 
        //	page.setRedirect(true); 
        //	return page; 
        //	}
        //}
        //return null;
    }


    public boolean checkAuthorize()
    {
        boolean validate = false;
        boolean continueVal = true;

        if (accessList.get(0).HasEditAccess) {
            validate = true;
        } else {
            user u = [select UserRoleId from user where id =: UserInfo.getUserId()];
            string accOwnerRole = tmpAcct.owner.UserRoleId;
            string currentUserRole = '';
            if (u != null) currentUserRole = u.UserRoleId;

            if (currentUserRole != '' && currentUserRole != null)
            {
                while (continueVal)
                {
                    if (accOwnerRole != '' && accOwnerRole != null) {
                        UserRole ur = [select ParentRoleId from UserRole where id =: accOwnerRole];
                        string accOwnerParentRole = '';
                        if (ur != null) accOwnerParentRole = ur.ParentRoleId;
                        
                        if (accOwnerParentRole != '' && accOwnerParentRole != null) {
                            if (accOwnerParentRole != currentUserRole) {
                                accOwnerRole = accOwnerParentRole;
                            } else {
                                validate = true;
                                continueVal = false;
                            }
                        } else {
                            continueVal = false;
                        }
                    } else {
                      continueVal = false;
                    }
                }
            }
        }

        return validate;
    }
    
            // --------------------------------------------------------------------------------------
    
    public String section {get;set;}
    public String section1 {get;set;}
    public String section2 {get;set;}
    public Boolean isLoading {get;set;}
    public Boolean isVisible {get;set;}
    public Boolean isVisible_product {get;set;}
    public Boolean isVisible_total {get;set;}
    public Boolean isLoadSuccess {get;set;}
    //public Account acct;

    public String hiddenText {
        get{
            if( hiddenText == null )
            {
                hiddenText = system.Label.Data_Condition_Hidden_Text;
            }
            return hiddenText;
        }
        set;
    }
	public String notAuthorizedMsg {
        get{
            if( notAuthorizedMsg == null )
            {
                notAuthorizedMsg = system.Label.Data_Condition_NotAuthorizedMsg; 
            }
            return notAuthorizedMsg;
        }
        set;
    }
    /*public AccountDataPartitionExtension(ApexPages.StandardController std){
        acct = (Account)std.getRecord();
        //isLoading = true; 
        //isLoadSuccess = false;
    }*/

    public boolean checkAuthorizeMatrix()
    {        
        try{
        	section = apexpages.currentPage().getParameters().get('sectionName');
        }catch(Exception e){
            this.section = section;
        }
        
        Account acctDetail = new Account();
        Profile userProfile = new Profile();

        try
        {
            acctDetail = [SELECT id,recordType.name,RTL_RM_Name__c,OwnerId FROM Account WHERE id = :tmpAcct.id ];
            userProfile = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];
        }
        catch (Exception e)
        { 
            //exception here
        }
        
        isVisible = RTL_AccountUtility.verifyFieldSecurity(section,userProfile.name, acctDetail.id);
            system.debug('isVisible = '+isVisible+ '/'+ tmpAcct.id);
        
        return isVisible;
    }

    
}