force-app/main/default/objects/Account/fields/BIZ_FLAG__c.field-meta.xml
<CustomField>
    <fullName>BIZ_FLAG__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>BIZ_FLAG</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch_and_Zone__c.field-meta.xml
<CustomField>
    <fullName>Branch_and_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preferred Branch</label>
    <referenceTo>Branch_and_Zone__c</referenceTo>
    <relationshipLabel>Accounts (Branch and Zone)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>ประเภทลูกค้าว่าเป็น  บุคคล หรือ บริษัท</description>
    <inlineHelpText>ประเภทลูกค้าว่าเป็น  บุคคล หรือ บริษัท</inlineHelpText>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
                <default>true</default>
                <label>Individual</label>
            </value>
            <value>
                <fullName>Juristic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WOW_FLAG__c.field-meta.xml
<CustomField>
    <fullName>WOW_FLAG__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>WOW_FLAG</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Existing_Customer.recordType-meta.xml
<RecordType>
    <fullName>Existing_Customer</fullName>
    <active>true</active>
    <label>Existing Customer</label>
</RecordType>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Using for RMC allows to create opportunity on other&apos;s existing customer.</description>
    <label>Create Opportunity Privilege</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch_and_Zone__c/Branch_and_Zone__c.object-meta.xml
<CustomObject>
    <label>Branch and Zone</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch and Zone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch_and_Zone__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Branch Code</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product_Information_Detail__c/Product_Information_Detail__c.object-meta.xml
<CustomObject>
    <label>Product: Account Information</label>
    <nameField>
        <displayFormat>PRD-{0000}</displayFormat>
        <label>Product: Account Information No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product: Account Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Information_Detail__c/fields/ACC_S1B__c.field-meta.xml
<CustomField>
    <fullName>ACC_S1B__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ACC_S1B</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Information_Detail__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Product_Information_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information_Detail__c/fields/LATEST_MTH_TXN__c.field-meta.xml
<CustomField>
    <fullName>LATEST_MTH_TXN__c</fullName>
    <label>LATEST_MTH_TXN</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Information_Detail__c/fields/LATEST_SIXMTH_TXN__c.field-meta.xml
<CustomField>
    <fullName>LATEST_SIXMTH_TXN__c</fullName>
    <label>LATEST_SIXMTH_TXN</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Information_Detail__c/fields/Product_Domain__c.field-meta.xml
<CustomField>
    <fullName>Product_Domain__c</fullName>
    <formula>Product_Information__r.Product_Domain__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Information_Detail__c/fields/Product_Hierachy_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Hierachy_Code__c</fullName>
    <formula>Product_Information__r.Product_Hierachy_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Hierachy Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Information_Detail__c/fields/Product_Information__c.field-meta.xml
<CustomField>
    <fullName>Product_Information__c</fullName>
    <label>Product Information</label>
    <referenceTo>Product_Information_On_Hand__c</referenceTo>
    <relationshipLabel>Product: Account Information</relationshipLabel>
    <relationshipName>Product_Information_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Information_On_Hand__c/Product_Information_On_Hand__c.object-meta.xml
<CustomObject>
    <label>Product on Hand Summary</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Product on Hand Summary No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product on Hand Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Information_On_Hand__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product on Hand Summary</relationshipLabel>
    <relationshipName>Product_Holding_Credit</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Information_On_Hand__c/fields/Product_Domain__c.field-meta.xml
<CustomField>
    <fullName>Product_Domain__c</fullName>
    <formula>TEXT( Product_Hierachy_Code__r.Product_Domain__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Information_On_Hand__c/fields/Product_Hierachy_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Hierachy_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Hierarchy Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Products_Information_On_Hand</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Branch_Manager_Title__c/RTL_Branch_Manager_Title__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Branch Manager Title</label>
</CustomObject>

force-app/main/default/objects/RTL_Branch_Manager_Title__c/fields/RTL_Value__c.field-meta.xml
<CustomField>
    <fullName>RTL_Value__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PHIRecommendedAtionExtensions_Test.cls
@isTest
private class PHIRecommendedAtionExtensions_Test {
	public static final Id BDM_PROFILE_ID = [SELECT Id FROM Profile WHERE Name = 'TMB BDM Profile' LIMIT 1].Id;   
	@testSetup static void setup() {
		TestUtils.createAppConfig();

		List<AppConfig__c> mc = new List<AppConfig__c> ();
        mc.Add(new AppConfig__c(Name = 'runtrigger', Value__c = 'false'));
        insert mc;

		RTL_Branch_Manager_Title__c branchTitle = new RTL_Branch_Manager_Title__c(Name='Branch Manager',RTL_Value__c='Branch Manager');
		insert branchTitle;
		
		Branch_and_zone__c bz = new Branch_and_zone__c();
        bz.Branch_Code__c = '611';
        insert bz;

		User User01 = RTL_TestUtility.createUsers(1, 'TestMock', 'SmartBDM', 'smartbdm@tmb.com.test', false).get(0);
		User01.ProfileId = BDM_PROFILE_ID;
		User01.isActive = true;
		User01.title = 'Branch Manager';
		User01.RTL_Branch_Code__c = bz.Branch_Code__c;
		User01.Employee_ID__c = '123456';
		insert User01;

		RecordType Existing_Customer = [SELECT Id FROM RecordType WHERE developername='Existing_Customer' AND SobjectType = 'Account' and IsActive = true LIMIT 1];
		Account acc1 = TestUtils.createAccounts(1, 'test', 'CType', false).get(0);
		acc1.Customer_Type__c = 'Individual';
		acc1.OwnerID = User01.id;
		acc1.RecordType = Existing_Customer;
		acc1.RecordTypeId = Existing_Customer.Id;
		acc1.BIZ_FLAG__c = 'Y';
		acc1.WOW_FLAG__c = 'Y';
		insert acc1;

		Product2 prod2 = new Product2(Name = 'Deposit', Product_Domain__c ='Deposit & Investment', Family = 'Hardware', IsActive=true);
        insert prod2;
		Product_Information_On_Hand__c onhand2 = new Product_Information_On_Hand__c();
        onhand2.Account__c = acc1.Id;
        onhand2.Product_Hierachy_Code__c = String.valueOf(prod2.id);
        insert onhand2;
		Product_Information_Detail__c detail2 = new Product_Information_Detail__c();
        detail2.Product_Information__c = onhand2.id;
		detail2.Customer__c = acc1.Id;
		detail2.ACC_S1B__c = 'Y';
		// detail2.EDC_FLAG__c = 'Y';
		detail2.LATEST_MTH_TXN__c = 8;
		detail2.LATEST_SIXMTH_TXN__c = 8;
        insert detail2;
		Product_Information_Detail__c detail3 = new Product_Information_Detail__c();
        detail3.Product_Information__c = onhand2.id;
		detail3.Customer__c = acc1.Id;
		detail3.ACC_S1B__c = 'N';
		// detail3.EDC_FLAG__c = 'Y';
		detail3.LATEST_MTH_TXN__c = 9;
		detail3.LATEST_SIXMTH_TXN__c = 9;
        insert detail3;

		Product_Information_Detail__c detail4 = new Product_Information_Detail__c();
        detail4.Product_Information__c = onhand2.id;
		detail4.Customer__c = acc1.Id;
        insert detail4;
	}

	@isTest static void test_method_PHIRecommendedAtionExtensions() {
		User user = [SELECT Id, Name FROM User WHERE Email = 'smartbdm@tmb.com.test' AND ProfileId =: BDM_PROFILE_ID LIMIT 1];
		Id AcctId = [SELECT Id FROM Account WHERE Customer_Type__c = 'Individual' AND OwnerId =: user.id LIMIT 1].Id;
		List<Product_Information_Detail__c> dProtI = [SELECT Id FROM Product_Information_Detail__c WHERE Customer__c =: AcctId];
		
		// Positive Recommended Action
		Test.setCurrentPageReference(new PageReference('Page.ProductHoldingInfoRecommendedAtion'));
		ApexPages.StandardController sc = new ApexPages.StandardController(dProtI.get(0));
		PHIRecommendedAtionExtensions phir = new PHIRecommendedAtionExtensions(sc);
		phir.CallRecommendedAction();
		sc = new ApexPages.StandardController(dProtI.get(1));
		phir = new PHIRecommendedAtionExtensions(sc);
		phir.CallRecommendedAction();
		Boolean isSF1 = phir.isSF1;

		System.currentPageReference().getParameters().put('isdtp', 'p1');
		sc = new ApexPages.StandardController(dProtI.get(2));
		phir = new PHIRecommendedAtionExtensions(sc);
		phir.CallRecommendedAction();
		isSF1 = phir.isSF1;

		// Negative Call Recommended Action
		sc = new ApexPages.StandardController(new Product_Information_Detail__c());
		phir = new PHIRecommendedAtionExtensions(sc);
		phir.CallRecommendedAction();
		
	}
}