force-app/main/default/objects/Account/fields/Branch_and_Zone__c.field-meta.xml
<CustomField>
    <fullName>Branch_and_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preferred Branch</label>
    <referenceTo>Branch_and_Zone__c</referenceTo>
    <relationshipLabel>Accounts (Branch and Zone)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/RTL_RM_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_RM_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>EMP/BR CODE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Branch_Manager_Title__c/RTL_Branch_Manager_Title__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Branch Manager Title</label>
</CustomObject>

force-app/main/default/objects/RTL_Branch_Manager_Title__c/fields/RTL_Value__c.field-meta.xml
<CustomField>
    <fullName>RTL_Value__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/RTL_Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{YY}{MM}{DD}-{000}</displayFormat>
        <label>Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Mobile1__c.field-meta.xml
<CustomField>
    <fullName>RTL_Mobile1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mobile1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Preferred_Branch__c.field-meta.xml
<CustomField>
    <fullName>RTL_Preferred_Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>สาขาที่ไม่รับบริการคือ สาขา Flagship ได้แก่ ไอคอน สยาม (283) และ อาคารยูไนเต็ด เซ็นเตอร์ สีลม (252), ระบุ WAT เพื่อส่งให้ Investment Line, ระบุ DSA เพื่อส่งให้ Mortgage Sales</inlineHelpText>
    <label>Preferred Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Branch_and_Zone__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch_and_Zone__c</referenceTo>
    <relationshipLabel>Referral Layout</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>RTL_product_master__c.Product_Group__c</field>
            <operation>notEqual</operation>
            <value>Loan Retention</value>
        </filterItems>
        <filterItems>
            <field>RTL_product_master__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RTL_product_master__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Referral_Assignment__c.field-meta.xml
<CustomField>
    <fullName>RTL_Referral_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral Assignment</label>
    <referenceTo>RTL_Referral_Assignment__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_RM_Owner_Id__c.field-meta.xml
<CustomField>
    <fullName>RTL_RM_Owner_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RM Owner Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Sales_Amount_Per_Year__c.field-meta.xml
<CustomField>
    <fullName>RTL_Sales_Amount_Per_Year__c</fullName>
    <label>Sales Amount Per Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SE : &lt;100 MB</fullName>
            </value>
            <value>
                <fullName>BB : 100-1,000 MB</fullName>
            </value>
            <value>
                <fullName>CB : 1,001-5,000 MB</fullName>
            </value>
            <value>
                <fullName>MB : &gt;5,000 MB</fullName>
            </value>
            <value>
                <fullName>SBO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/recordTypes/Refer_to_Commercial.recordType-meta.xml
<RecordType>
    <fullName>Refer_to_Commercial</fullName>
    <active>true</active>
    <description>Refer ลูกค้าที่สนใจผลิตภัณฑ์เพื่อธุรกิจ ระหว่าง สาขา/Wealth กับ Commercial</description>
    <label>Refer to Commercial</label>
</RecordType>

force-app/main/default/objects/RTL_Referral_Assignment__c/RTL_Referral_Assignment__c.object-meta.xml
<CustomObject>
    <label>Referral Assignment</label>
    <nameField>
        <displayFormat>RTLRA-{000000}</displayFormat>
        <label>Referral Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Assignment</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Active_Flag__c.field-meta.xml
<CustomField>
    <fullName>RTL_Active_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Assigned_User_field__c.field-meta.xml
<CustomField>
    <fullName>RTL_Assigned_User_field__c</fullName>
    <label>1.2 Assigned User field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RTL_RM_Owner_Id__c</fullName>
            </value>
            <value>
                <fullName>RTL_Wealth_RM_Id__c</fullName>
            </value>
            <value>
                <fullName>RTL_Referred_By_ID__c</fullName>
            </value>
            <value>
                <fullName>RTL_Preferred_Staff__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Priority__c.field-meta.xml
<CustomField>
    <fullName>RTL_Priority__c</fullName>
    <label>Priority</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Reassign_Flag__c.field-meta.xml
<CustomField>
    <fullName>RTL_Reassign_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To identify whether this rule is applied in Reassign process or not</description>
    <label>Reassign Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Referral_Field_Criteria_1__c.field-meta.xml
<CustomField>
    <fullName>RTL_Referral_Field_Criteria_1__c</fullName>
    <label>Referral Field Criteria 1</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RTL_Preferred_Branch__c</fullName>
            </value>
            <value>
                <fullName>RTL_Is_BM__c</fullName>
            </value>
            <value>
                <fullName>RTL_Wealth_RM__c</fullName>
            </value>
            <value>
                <fullName>RTL_Account_Name__c</fullName>
            </value>
            <value>
                <fullName>RTL_Owner_Segment__c</fullName>
            </value>
            <value>
                <fullName>RTL_Owner_Zone__c</fullName>
            </value>
            <value>
                <fullName>RTL_Preferred_Branch_Name__c</fullName>
            </value>
            <value>
                <fullName>RTL_Segment__c</fullName>
            </value>
            <value>
                <fullName>RTL_Privilege__c</fullName>
            </value>
            <value>
                <fullName>RTL_Sales_Amount_Per_Year__c</fullName>
            </value>
            <value>
                <fullName>RTL_Interested_Product__c</fullName>
            </value>
            <value>
                <fullName>RTL_Product_Name_txt__c</fullName>
            </value>
            <value>
                <fullName>RTL_EMP_BR_Code__c</fullName>
            </value>
            <value>
                <fullName>RTL_RM_Owner__c</fullName>
            </value>
            <value>
                <fullName>RTL_Owner_Role__c</fullName>
            </value>
            <value>
                <fullName>RTL_Type__c</fullName>
            </value>
            <value>
                <fullName>RTL_Phone1__c</fullName>
            </value>
            <value>
                <fullName>RTL_Channel_Segment__c</fullName>
            </value>
            <value>
                <fullName>RTL_Campaign_Reference__c</fullName>
            </value>
            <value>
                <fullName>RTL_Preferred_Branch_Type__c</fullName>
            </value>
            <value>
                <fullName>RTL_Product_Group__c</fullName>
            </value>
            <value>
                <fullName>Is_Flagship__c</fullName>
            </value>
            <value>
                <fullName>RTL_Product_Name__c</fullName>
            </value>
            <value>
                <fullName>RTL_Refer_Branch_Name__c</fullName>
            </value>
            <value>
                <fullName>RTL_Product_Sub_Group__c</fullName>
            </value>
            <value>
                <fullName>RTL_Product_Name_Str__c</fullName>
            </value>
            <value>
                <fullName>Assigned_Pool__c</fullName>
            </value>
            <value>
                <fullName>FNA_Have_Loan_Product__c</fullName>
            </value>
            <value>
                <fullName>RTL_Purpose__c</fullName>
            </value>
            <value>
                <fullName>RTL_Customer_Segment__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Referral_Field_Value_1__c.field-meta.xml
<CustomField>
    <fullName>RTL_Referral_Field_Value_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Possible value for this field are 
1) Is null 
2) Is not null 
3) Field Value (always using &apos;=&apos; operator)
4) TRUE /FALSE for checkbox field</inlineHelpText>
    <label>Referral Field Value 1</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Referral_Type__c.field-meta.xml
<CustomField>
    <fullName>RTL_Referral_Type__c</fullName>
    <label>Referral Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refer_to_Retail</fullName>
            </value>
            <value>
                <fullName>Retail_Cross_Channel_Referral</fullName>
            </value>
            <value>
                <fullName>Refer_to_Commercial</fullName>
            </value>
            <value>
                <fullName>Refer_within_Commercial</fullName>
            </value>
            <value>
                <fullName>Retail_Order_Transaction</fullName>
            </value>
            <value>
                <fullName>Refer_from_Digital_Channel</fullName>
            </value>
            <value>
                <fullName>Refer to Commercial</fullName>
                <isActive>false</isActive>
                <label>Refer to Commercial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RTL_ReferralAssignUtility_Test.cls
@isTest
class RTL_ReferralAssignUtility_Test {
	static List<sObject> ls;
	static List<Account> acctList;
    static List<Lead> leadList;
    static Map<String, Group> queueMap;
    static List<Branch_And_Zone__c> branchAndZoneList;
    static List<RTL_Product_Master__c> retailProductMasterList;
    static List<RTL_Referral__c> referralList;
    static List<Opportunity> opportunityList;
    static User retailWithBranchUser;
    static User rmcUser;
    static User bdmUser;
    static User adminUser;
    static Id referToCommercialRecTypeId 
            = Schema.Sobjecttype.RTL_Referral__c.getRecordTypeInfosByName().get('Refer to Commercial').getRecordTypeId();

	static {
        TestUtils.createAppConfig();
        TestUtility_Referral.createAppConfigReferralAssignment();
        createAppConfigReferralAssignmentForSalesSegment();
        TestUtility_Referral.createAppConfigCallMeNowBH();
        branchAndZoneList = RTL_TestUtility.createBranchZone(9,true);
        retailProductMasterList = RTL_TestUtility.createRetailProducts(true);
        retailWithBranchUser = RTL_TestUtility.createRetailTestUserWithBranch(true);
        adminUser = TestUtils.createUsers(1,'USERADMIN','TESTCLASS','test_TMB@tmbbank.com',true)[0];
        acctList = RTL_TestUtility.createAccounts(2,true);
        // update acct[0] as wealth account
        acctList[0].RTL_RM_Name__c = '00001';
        update acctList[0];
        
        RTL_Branch_Manager_Title__c branchTitle 
        		= new RTL_Branch_Manager_Title__c(Name='Branch Manager'
                                                        ,RTL_Value__c='Branch Manager');
        insert branchTitle;
        //ls = Test.loadData(Branch_And_Zone__c.sObjectType, 'BranchAndZoneMaster');
        ID RMC_ROLE_ID = [SELECT Id FROM UserRole WHERE Name LIKE '%RMC%' LIMIT 1].id;
        System.debug('RMC ROLE ID '+RMC_ROLE_ID);
        
        queueMap = new Map<String, Group>();
        for(Group queue : [Select Id, Name, DeveloperName from Group where Type = 'Queue'])
            queueMap.put(queue.DeveloperName, queue);
        
        System.runAs(adminUser){
            //create rmc user for test
            rmcUser = TestUtility_Referral.createRMCTestUser(true);
            //create bdm user for test 
            bdmUser = TestUtility_Referral.createBDMTestUser(true);
        }
        
    }


    public static  testmethod  void reassignReferal_Test(){
        Test.startTest();
        
        System.runAs(retailWithBranchUser){
        	insert new PermissionSetAssignment(PermissionSetId=TestUtils.SetupPermissionSet().Id,AssigneeId=retailWithBranchUser.Id);
        }
        System.runAs(retailWithBranchUser){
            //Insert referral To commercial List
            TestUtility_Referral.createReferralAssignment();
            createReferralAssignmentForSalesSegment();
            referralList = createReferralToCommercial();
            RTL_Referral__c ref = referralList.get(0);
            //ref.RTL_RM_Owner_Id__c = rmcUser.Id;

            //update ref;

            ApexPages.StandardController stdController 
                            = new ApexPages.StandardController(ref);

            RTL_ReferralAssignUtility refUtility = new RTL_ReferralAssignUtility(stdController);

            RTL_ReferralAssignUtility.doReferralReassign(referralList[0].Id);
            RTL_ReferralAssignUtility.getReferralReassign(referralList[0].Id);

            RTL_ReferralAssignUtility.doReferralReassign(referralList[1].Id);
            RTL_ReferralAssignUtility.getReferralReassign(referralList[1].Id);
        }
        Test.stopTest();

    }
    public static  testmethod  void reassignReferal_Test2(){
        Test.startTest();
        
        System.runAs(retailWithBranchUser){
        	insert new PermissionSetAssignment(PermissionSetId=TestUtils.SetupPermissionSet().Id,AssigneeId=retailWithBranchUser.Id);
        }
        System.runAs(retailWithBranchUser){
            //Insert referral To commercial List
            TestUtility_Referral.createReferralAssignment();
            createReferralAssignmentForSalesSegment();
            referralList = createReferralToCommercial();
            RTL_Referral__c ref = referralList.get(0);
            //ref.RTL_RM_Owner_Id__c = rmcUser.Id;

            //update ref;

            ApexPages.StandardController stdController 
                            = new ApexPages.StandardController(ref);

            RTL_ReferralAssignUtility refUtility = new RTL_ReferralAssignUtility(stdController);

            RTL_ReferralAssignUtility.doReferralReassign(referralList[2].Id);
            RTL_ReferralAssignUtility.getReferralReassign(referralList[2].Id);
        }
        Test.stopTest();

    }
    
    public static  testmethod  void reassignReferalRuleForNull_Test(){
        Test.startTest();
        
        System.runAs(retailWithBranchUser){
        	insert new PermissionSetAssignment(PermissionSetId=TestUtils.SetupPermissionSet().Id,AssigneeId=retailWithBranchUser.Id);
        }
        System.runAs(retailWithBranchUser){
            //Insert referral To commercial List
            createReferralAssignmentForNullCriertia();
            referralList = createReferralToCommercial();

            RTL_Referral__c ref = referralList.get(0);

            ApexPages.StandardController stdController 
                            = new ApexPages.StandardController(ref);

            RTL_ReferralAssignUtility refUtility = new RTL_ReferralAssignUtility(stdController);

            referralList[0].RTL_Account_Name__c = null;

            update referralList[0];

            RTL_ReferralAssignUtility.doReferralReassign(referralList[0].Id);
            RTL_ReferralAssignUtility.getReferralReassign(referralList[0].Id);

            RTL_ReferralAssignUtility.doReferralReassign(referralList[1].Id);
            RTL_ReferralAssignUtility.getReferralReassign(referralList[1].Id);
            RTL_ReferralAssignUtility.getReferralOwnerName(UserInfo.getUserId());
        }
        Test.stopTest();

    }
    
    public static  testmethod  void testCheckCondition2(){     
        Test.startTest();
        	sObject data1 = new RTL_Referral__c();
        	data1.put('RTL_Sales_Amount_Per_Year__c','SE : <100 MB');
			RTL_ReferralAssignUtility.checkCondition2('RTL_Sales_Amount_Per_Year__c',data1,'SE : < 100MB');
        
        	sObject data2 = new RTL_Referral__c();
        	data2.put('RTL_Sales_Amount_Per_Year__c','BB : 100-1,000 MB');
			RTL_ReferralAssignUtility.checkCondition2('RTL_Sales_Amount_Per_Year__c',data2,'BB : 100-1,000 MB');
        
        	sObject data3 = new RTL_Referral__c();
        	data3.put('RTL_Sales_Amount_Per_Year__c','CB : 1,001-5,000 MB');
			RTL_ReferralAssignUtility.checkCondition2('RTL_Sales_Amount_Per_Year__c',data3,'CB : 1,001-5,000 MB');
        
        	sObject data4 = new RTL_Referral__c();
        	data4.put('RTL_Sales_Amount_Per_Year__c','MB : >5,000 MB');
			RTL_ReferralAssignUtility.checkCondition2('RTL_Sales_Amount_Per_Year__c',data4,'MB : >5,000 MB');
        Test.stopTest();

    }
    
    public static testmethod void testdoCallService(){
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseCallMeNow(200,'{"code":"1","message":"success"}'));
        Map<String,String> mockMapString = new Map<String,String>();
        mockMapString.put('3','test3');
        mockMapString.put('4','test4');
        mockMapString.put('5','test5');
        mockMapString.put('6','test6');

        Test.startTest();
        	RTL_ReferralAssignUtility.doCallService('00c03ds000sdcb', 'REF-170712-2326', 'Test', 'LastName', 'SmartBiz', '0987654664', 'callmenow_sme', '', 'Web', 'true','Refer to Commercial','',mockMapString);
        Test.stopTest();
    }

    private static List<RTL_Referral__c> createReferralToCommercial() {
        List<RTL_Referral__c> referralList = new List<RTL_Referral__c>();
        
        RTL_Referral__c referralForSE 
                                = new RTL_Referral__c
                                                      (RecordTypeId = referToCommercialRecTypeId,
                                                       RTL_Product_Name__c = retailProductMasterList[0].id,
                                                       RTL_Preferred_Branch__c = branchAndZoneList[0].id,
                                                       RTL_Mobile1__c = '1111111111',
                                                       RTL_Account_Name__c = acctList[0].id,
                                                       RTL_Sales_Amount_Per_Year__c = 'SE : <100 MB'
                                                       );

        RTL_Referral__c referralForCB 
                                = new RTL_Referral__c
                                                      (RecordTypeId = referToCommercialRecTypeId,
                                                       RTL_Product_Name__c = retailProductMasterList[0].id,
                                                       RTL_Preferred_Branch__c = branchAndZoneList[0].id,
                                                       RTL_Mobile1__c = '1111111111',
                                                       RTL_Account_Name__c = acctList[0].id,
                                                       RTL_Sales_Amount_Per_Year__c = 'CB : 1,001-5,000 MB'
                                                       );


        RTL_Referral__c referralForMB 
                                = new RTL_Referral__c
                                                      (RecordTypeId = referToCommercialRecTypeId,
                                                       RTL_Product_Name__c = retailProductMasterList[0].id,
                                                       RTL_Preferred_Branch__c = branchAndZoneList[0].id,
                                                       RTL_Mobile1__c = '1111111111',
                                                       RTL_Account_Name__c = acctList[0].id,
                                                       RTL_Sales_Amount_Per_Year__c = 'MB : >5,000 MB'
                                                       );

        RTL_Referral__c referralForBB 
                                = new RTL_Referral__c
                                                      (RecordTypeId = referToCommercialRecTypeId,
                                                       RTL_Product_Name__c = retailProductMasterList[0].id,
                                                       RTL_Preferred_Branch__c = branchAndZoneList[0].id,
                                                       RTL_Mobile1__c = '1111111111',
                                                       RTL_Account_Name__c = acctList[0].id,
                                                       RTL_Sales_Amount_Per_Year__c = 'BB : 100-1,000 MB'
                                                       );

        //eferralList.add(referralForSE);
        referralList.add(referralForCB);
        referralList.add(referralForMB);
        referralList.add(referralForBB);

        insert referralList;

        return referralList;
    }
    

    private static void createReferralAssignmentForNullCriertia(){
        List<RTL_Referral_Assignment__c> refAssignmentList = new List<RTL_Referral_Assignment__c>();

        RTL_Referral_Assignment__c refAssignment1= new RTL_Referral_Assignment__c();
        refAssignment1.RTL_Priority__c = 1;
        refAssignment1.RTL_Referral_Type__c = 'Refer_to_Commercial';
        refAssignment1.RTL_Referral_Field_Criteria_1__c = 'RTL_Account_Name__c';
        refAssignment1.RTL_Referral_Field_Value_1__c = 'IS NULL';
        refAssignment1.RTL_Reassign_Flag__c = True;
        refAssignment1.RTL_Active_Flag__c   = True;
        refAssignment1.RTL_Assigned_User_field__c = 'RTL_RM_Owner_Id__c';

        refAssignmentList.add(refAssignment1);
        insert refAssignmentList;
    }
    
    private static void createReferralAssignmentForSalesSegment(){
        List<RTL_Referral_Assignment__c> refAssignmentList = new List<RTL_Referral_Assignment__c>();

        RTL_Referral_Assignment__c refAssignment1= new RTL_Referral_Assignment__c();
        refAssignment1.RTL_Priority__c = 1;
        refAssignment1.RTL_Referral_Type__c = 'Refer_to_Commercial';
        refAssignment1.RTL_Referral_Field_Criteria_1__c = 'RTL_Account_Name__c';
        refAssignment1.RTL_Referral_Field_Value_1__c = 'IS NOT NULL';
        refAssignment1.RTL_Reassign_Flag__c = True;
        refAssignment1.RTL_Active_Flag__c   = True;
        refAssignment1.RTL_Assigned_User_field__c = 'RTL_RM_Owner_Id__c';

        RTL_Referral_Assignment__c refAssignment2 = new RTL_Referral_Assignment__c();
        refAssignment2.RTL_Priority__c = 2;
        refAssignment2.RTL_Referral_Type__c = 'Refer_to_Commercial';
        refAssignment2.RTL_Referral_Field_Criteria_1__c = 'RTL_Preferred_Branch__c';
        refAssignment2.RTL_Referral_Field_Value_1__c = 'IS NOT NULL';
        refAssignment2.RTL_Referral_Field_Criteria_2__c = 'RTL_Sales_Amount_Per_Year__c';
        refAssignment2.RTL_Referral_Field_Value_2__c = 'SE : <100 MB';
        refAssignment2.RTL_Default_Queue_Name__c     = 'SME_Sales_Management';
        refAssignment2.RTL_Reassign_Flag__c = True;
        refAssignment2.RTL_Active_Flag__c = True;
        refAssignment2.RTL_Branch_and_Zone_Queue_User_field__c = 'SE_Queue_Name__c';

        RTL_Referral_Assignment__c refAssignment3 = new RTL_Referral_Assignment__c();
        refAssignment3.RTL_Priority__c = 3;
        refAssignment3.RTL_Referral_Type__c = 'Refer_to_Commercial';
        refAssignment3.RTL_Referral_Field_Criteria_1__c = 'RTL_Preferred_Branch__c';
        refAssignment3.RTL_Referral_Field_Value_1__c = 'IS NOT NULL';
        refAssignment3.RTL_Referral_Field_Criteria_2__c = 'RTL_Sales_Amount_Per_Year__c';
        refAssignment3.RTL_Referral_Field_Value_2__c = 'BB : 100-1,000 MB';
        refAssignment3.RTL_Reassign_Flag__c = True;
        refAssignment3.RTL_Active_Flag__c = True;
        refAssignment3.RTL_Branch_and_Zone_Queue_User_field__c = 'BB_Queue_Name__c';
        refAssignment3.RTL_Default_Queue_Name__c     = 'BB_Sales_Management';

        RTL_Referral_Assignment__c refAssignment4 = new RTL_Referral_Assignment__c();
        refAssignment4.RTL_Priority__c = 4;
        refAssignment4.RTL_Referral_Type__c = 'Refer_to_Commercial';
        refAssignment4.RTL_Referral_Field_Criteria_1__c = 'RTL_Sales_Amount_Per_Year__c';
        refAssignment4.RTL_Referral_Field_Value_1__c = 'CB : 1,001-5,000 MB';
        refAssignment4.RTL_Reassign_Flag__c = True;
        refAssignment4.RTL_Active_Flag__c = True;
        refAssignment4.RTL_Assigned_Queue_Name__c = 'CB_Sales_Management';

        RTL_Referral_Assignment__c refAssignment5 = new RTL_Referral_Assignment__c();
        refAssignment5.RTL_Priority__c = 5;
        refAssignment5.RTL_Referral_Type__c = 'Refer_to_Commercial';
        refAssignment5.RTL_Referral_Field_Criteria_1__c = 'RTL_Sales_Amount_Per_Year__c';
        refAssignment5.RTL_Referral_Field_Value_1__c = 'MB : >5,000 MB';
        refAssignment5.RTL_Reassign_Flag__c = True;
        refAssignment5.RTL_Active_Flag__c = True;
        refAssignment5.RTL_Assigned_Queue_Name__c = 'MB_Sales_Management';

        refAssignmentList.add(refAssignment1);
        refAssignmentList.add(refAssignment2);

        refAssignmentList.add(refAssignment3);
        refAssignmentList.add(refAssignment4);
        refAssignmentList.add(refAssignment5); 

        insert refAssignmentList;
    }

    private static void createAppConfigReferralAssignmentForSalesSegment(){     
        
        List<AppConfig__c> apps = new  List<AppConfig__c>();
        AppConfig__c appConfig1 = new AppConfig__c();
        appConfig1.Name = 'RTL_Referral_Assignment_SE';
        appConfig1.Value__c = 'SE : <100 MB';
        apps.add(appConfig1);
        
        AppConfig__c appConfig2 = new AppConfig__c();
        appConfig2.Name = 'RTL_Referral_Assignment_CB';
        appConfig2.Value__c = 'CB : 1,001-5,000 MB';
        apps.add(appConfig2);

        AppConfig__c appConfig3 = new AppConfig__c();
        appConfig3.Name = 'RTL_Referral_Assignment_MB';
        appConfig3.Value__c = 'MB : >5,000 MB';
        apps.add(appConfig3);

        AppConfig__c appConfig4 = new AppConfig__c();
        appConfig4.Name = 'RTL_Referral_Assignment_BB';
        appConfig4.Value__c = 'BB : 100-1,000 MB';
        apps.add(appConfig4);
        insert apps;
    }
    
    @isTest
    private static void Test_getNextnBSDate() {
        RTL_ReferralAssignUtility.getNextnBSDate();
    }
    
}