force-app/main/default/objects/Account/fields/Branch_and_Zone__c.field-meta.xml
<CustomField>
    <fullName>Branch_and_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preferred Branch</label>
    <referenceTo>Branch_and_Zone__c</referenceTo>
    <relationshipLabel>Accounts (Branch and Zone)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TMB_Customer_ID_PE__c.field-meta.xml
<CustomField>
    <fullName>TMB_Customer_ID_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>TMB Customer ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch_and_Zone__c/Branch_and_Zone__c.object-meta.xml
<CustomObject>
    <label>Branch and Zone</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch and Zone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch_and_Zone__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Branch Code</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Branch_and_Zone__c/fields/RTL_Zone_Code__c.field-meta.xml
<CustomField>
    <fullName>RTL_Zone_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zone Code (Retail)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/RTL_Campaign_Code_10_digits__c.field-meta.xml
<CustomField>
    <fullName>RTL_Campaign_Code_10_digits__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Campaign Code (10-digits)</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/RTL_Fulfillment_Type__c.field-meta.xml
<CustomField>
    <fullName>RTL_Fulfillment_Type__c</fullName>
    <label>Fulfillment Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cashback</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Point</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Dummy_Campaign.recordType-meta.xml
<RecordType>
    <fullName>Dummy_Campaign</fullName>
    <active>true</active>
    <label>Dummy Campaign</label>
</RecordType>

force-app/main/default/objects/CampaignMember/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Oldest_Closed_Date_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Oldest_Closed_Date_Opportunity__c</fullName>
    <formula>IF( 
AND( 
ISBLANK(RTL_RelatedOpportunity_1__r.Closed_Won_Date__c), 
ISBLANK(RTL_RelatedOpportunity_2__r.Closed_Won_Date__c), 
ISBLANK(RTL_RelatedOpportunity_3__r.Closed_Won_Date__c), 
ISBLANK(RTL_RelatedOpportunity_4__r.Closed_Won_Date__c), 
ISBLANK(RTL_RelatedOpportunity_5__r.Closed_Won_Date__c) 
), 
NULL, 
DATE(2998,1,1) - MAX( 
DATE(2998,1,1) - BLANKVALUE(RTL_RelatedOpportunity_1__r.Closed_Won_Date__c , DATE(2998,1,1)), 
DATE(2998,1,1) - BLANKVALUE(RTL_RelatedOpportunity_2__r.Closed_Won_Date__c, DATE(2998,1,1)), 
DATE(2998,1,1) - BLANKVALUE(RTL_RelatedOpportunity_3__r.Closed_Won_Date__c ,DATE(2998,1,1)), 
DATE(2998,1,1) - BLANKVALUE(RTL_RelatedOpportunity_4__r.Closed_Won_Date__c, DATE(2998,1,1)), 
DATE(2998,1,1) - BLANKVALUE(RTL_RelatedOpportunity_5__r.Closed_Won_Date__c, DATE(2998,1,1)) 
) 
)</formula>
    <label>Oldest Closed Date Opportunity</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_RelatedOpportunity_1__c.field-meta.xml
<CustomField>
    <fullName>RTL_RelatedOpportunity_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related to Opportunity-1</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_RelatedOpportunity_2__c.field-meta.xml
<CustomField>
    <fullName>RTL_RelatedOpportunity_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related to Opportunity-2</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Campaign Members (Related to Opportunity-2)</relationshipLabel>
    <relationshipName>Campaign_Members1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_RelatedOpportunity_3__c.field-meta.xml
<CustomField>
    <fullName>RTL_RelatedOpportunity_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related to Opportunity-3</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Campaign Members (Related to Opportunity-3)</relationshipLabel>
    <relationshipName>Campaign_Members2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_RelatedOpportunity_4__c.field-meta.xml
<CustomField>
    <fullName>RTL_RelatedOpportunity_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related to Opportunity-4</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Campaign Members (Related to Opportunity-4)</relationshipLabel>
    <relationshipName>Campaign_Members3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_RelatedOpportunity_5__c.field-meta.xml
<CustomField>
    <fullName>RTL_RelatedOpportunity_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related to Opportunity-5</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Campaign Members (Related to Opportunity-5)</relationshipLabel>
    <relationshipName>Campaign_Members4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>CR Migrate Contact WBG : use this field for migrate contact from dwh Rcordtype Core Back only.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Migration_Info__c/Migration_Info__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Migration Info</label>
</CustomObject>

force-app/main/default/objects/Migration_Info__c/fields/Migrated_Field_1__c.field-meta.xml
<CustomField>
    <fullName>Migrated_Field_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Migrated Field 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Migration_Info__c/fields/Migrated_Field_2__c.field-meta.xml
<CustomField>
    <fullName>Migrated_Field_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Migrated Field 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Migration_Info__c/fields/Migrated_Field__c.field-meta.xml
<CustomField>
    <fullName>Migrated_Field__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Migrated Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Migration_Info__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ObjectName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Migration_Info__c/fields/SQL1__c.field-meta.xml
<CustomField>
    <fullName>SQL1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SQL1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Migration_Info__c/fields/SQL2__c.field-meta.xml
<CustomField>
    <fullName>SQL2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SQL2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Migration_Info__c/fields/SQL3__c.field-meta.xml
<CustomField>
    <fullName>SQL3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SQL3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Migration_Info__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Fulfillment__c/RTL_Fulfillment__c.object-meta.xml
<CustomObject>
    <description>Keep information of campaign fulfillment to customer</description>
    <label>Fulfillment</label>
    <nameField>
        <displayFormat>FF-{0000}</displayFormat>
        <label>Fulfillment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Fulfillment__c/fields/RTL_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>RTL_Account_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Fulfillment__c/fields/RTL_Amount__c.field-meta.xml
<CustomField>
    <fullName>RTL_Amount__c</fullName>
    <description>Fulfillment Amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RTL_Fulfillment__c/fields/RTL_Campaign__c.field-meta.xml
<CustomField>
    <fullName>RTL_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Fulfillment</relationshipLabel>
    <relationshipName>Fulfillment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Fulfillment__c/fields/RTL_Customer__c.field-meta.xml
<CustomField>
    <fullName>RTL_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fulfillment</relationshipLabel>
    <relationshipName>Fulfillment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Fulfillment__c/fields/RTL_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>RTL_Delivery_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTL_Fulfillment__c/fields/RTL_Fulfillment_ID__c.field-meta.xml
<CustomField>
    <fullName>RTL_Fulfillment_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Fulfillment ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTL_Fulfillment__c/fields/RTL_Fulfillment_Status__c.field-meta.xml
<CustomField>
    <fullName>RTL_Fulfillment_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fulfillment Status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Fulfillment__c/fields/RTL_Fulfillment_Type__c.field-meta.xml
<CustomField>
    <fullName>RTL_Fulfillment_Type__c</fullName>
    <description>FF Type</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Fulfillment Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_Report_Config__c/Schedule_Report_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Schedule Report Config</label>
</CustomObject>

force-app/main/default/objects/Schedule_Report_Config__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Schedule_Report_Config__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This field for setting file name when sending to recipient</inlineHelpText>
    <label>File Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_Report_Config__c/fields/Report_Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Report_Unique_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Report Unique Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RTL_SchedulerEmailErrorLogTest.cls
@isTest
public class RTL_SchedulerEmailErrorLogTest {
    @testSetup static void setupmethod() {
        TestUtils.createAppConfig();
        RTL_TestUtility.createEmailConfig();
    }
    //use createddate to test since it's not able to change lastmodifieddate
    public static testMethod void scheduleEmailErrorLogTest(){
        //create retail online service log
        RTL_TestUtility.createOnlineServiceLog(100,true);
        List<Account> accList = RTL_TestUtility.createAccountDataQualityNA(true);
        List<Opportunity> oppListUpdate = TestForUtility.createOpportunities(accList.get(0),1,true);
        List<Campaign> commCampList = TestForUtility.createCampaign(1,'SE',true);
        TestForUtility.createCommLead(1, true,commCampList.get(0).Id);
        
        for (Opportunity opp:oppListUpdate) {
            opp.RTL_IsLock__c = false;
            opp.StageName = 'Closed Won (Deposit)';
        }

        update oppListUpdate;

        for (Opportunity opp:oppListUpdate) {
            opp.RTL_Lock_Opp_Date__c = Date.today().addDays(-1);
        }
        update oppListUpdate;

        List<AppConfig__c> apps = new  List<AppConfig__c>();
        AppConfig__c Aconfig = new AppConfig__c();
        Aconfig.Name = 'On_Demand_Expired_Opportunity';
        Aconfig.Value__c = String.valueOf(Date.today());  

        AppConfig__c Aconfig2 = new AppConfig__c();
        Aconfig2.Name = 'On_Demand_Expired_Opportunity_N_DAYS';
        Aconfig2.Value__c = '0';

        apps.add(Aconfig);
        apps.add(Aconfig2);

        AppConfig__c Aconfig3 = new AppConfig__c();
        Aconfig3.Name = 'Inactive_User_Batch';
        Aconfig3.Value__c = 'true';

        AppConfig__c Aconfig4 = new AppConfig__c();
        Aconfig4.Name = 'Report_Export';
        Aconfig4.Value__c = 'true';

        apps.add(Aconfig3);
        apps.add(Aconfig4);

        insert apps;
        
        
        Schedule_Report_Config__c schReport = new Schedule_Report_Config__c();
        schReport.Name = 'Report1';
        schReport.Email__c = 'test@tmbbank.com';
        schReport.File_Name__c = 'test report';
        schReport.Report_Unique_Name__c = 'SampleReportTopAccounts';
        insert schReport;
        

        List<Migration_Info__c> migtLst = new List<Migration_Info__c>();
        migtLst.add(new Migration_Info__c(
            Name = 'Migrate_Branch_And_Zone',
            Email__c = 'aa@aa.com;bb@bb.com',
            IsActive__c = true,
            Migrated_Field__c = '',
            Migrated_Field_1__c = '',
            Migrated_Field_2__c = '',
            ObjectName__c = 'Branch_and_Zone__c',
            SQL1__c = 'Id,Name,Branch_Code__c',
            SQL2__c = 'Where RTL_Zone_Code__c in (\'6480\',\'6490\')',
            SQL3__c = '',
            Type__c = 'MIGRATE_INFO'
        ));
        migtLst.add(new Migration_Info__c(
            Name = 'CampaignMember_Closed_Won_Report',
            Email__c = 'aa@aa.com;bb@bb.com',
            IsActive__c = true,
            Migrated_Field__c = 'RTL_RelatedOpportunity_2__r.Closed_Won_Emp__c,RTL_RelatedOpportunity_2__r.Closed_Won_Date__c,RTL_RelatedOpportunity_3__r.Closed_Won_Emp__c,RTL_RelatedOpportunity_3__r.Closed_Won_Date__c',
            Migrated_Field_1__c = '',
            Migrated_Field_2__c = 'RTL_RelatedOpportunity_4__r.Closed_Won_Emp__c,RTL_RelatedOpportunity_4__r.Closed_Won_Date__c,RTL_RelatedOpportunity_5__r.Closed_Won_Emp__c,RTL_RelatedOpportunity_5__r.Closed_Won_Date__c',
            ObjectName__c = 'CampaignMember',
            SQL1__c = 'Id,Customer__r.TMB_Customer_ID_PE__c,Oldest_Closed_Date_Opportunity__c,RTL_RelatedOpportunity_1__r.Closed_Won_Emp__c,RTL_RelatedOpportunity_1__r.Closed_Won_Date__c',
            SQL2__c = '',
            SQL3__c = '',
            Type__c = 'EXPORT_REPORT'
        ));

        migtLst.add(new Migration_Info__c(
            Name = 'Fulfillment_Upload',
            Email__c = '',
            IsActive__c = true,
            Migrated_Field__c = 'RTL_Fulfillment_Type__c,RTL_Description__c,RTL_Account_ID__c,RTL_Amount__c,RTL_Campaign__r.RTL_Campaign_Code_10_digits__c,RTL_Customer__r.TMB_Customer_ID_PE__c,RTL_Delivery_Date__c,RTL_Fulfillment_ID__c,RTL_Fulfillment_Status__c',
            Migrated_Field_1__c = 'RTL_Fulfillment_Type__c,RTL_Home_No__c,RTL_Mobile_No__c,RTL_Office_No__c,RTL_PCI_Card_NO__c',
            Migrated_Field_2__c = '',
            ObjectName__c = 'RTL_Fulfillment__c',
            SQL1__c = '',
            SQL2__c = '',
            SQL3__c = '',
            Type__c = 'UPLOAD_EMAIL'
        ));
        insert migtLst;
        List<User> retailUsers = RTL_TestUtility.createRetailTestUserOppt(true);
        User firstUser = retailUsers[0];//outbound channel

        Lead l = new Lead(Company = 'JohnMiller', LastName = 'Mike', Status = 'Open');
        l.RTL_Branch_Code_Rpt__c = '611';
        insert l;

        Campaign camp = new Campaign();
        camp.Name = 'Campaign_';
        camp.Segment__c = 'MB';
        camp.OwnerId  = UserInfo.getUserId();
        camp.RecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('Dummy_Campaign').getRecordTypeId();
        insert camp;
            
    
        List<CampaignMember> cmList = new List<CampaignMember>();
        CampaignMember cm1 = new CampaignMember();
        cm1.LeadId = l.id;
        cm1.CampaignId = camp.id;
        cm1.RTL_TMB_Campaign_Source__c = 'Web';     
        cm1.RTL_Product_Name__c = 'product';
        cm1.RTL_Lead_Group__c =  'group';
        cm1.RTL_OfferResult_Product_1__c = 'N/A';
        cmList.add(cm1);
            
        Contact con1 = RTL_TestUtility.createContacts(accList.get(0));
        con1.OwnerId = firstUser.id;
        insert con1;
    
        CampaignMember cm2 = new CampaignMember();
        cm2.ContactId = con1.id;
        cm2.CampaignId = camp.id;
        cm2.RTL_TMB_Campaign_Source__c = 'Web';     
        cm2.RTL_Product_Name__c = 'product';
        cm2.RTL_Lead_Group__c =  'group';
        cm2.RTL_OfferResult_Product_1__c = 'N/A';
        cmList.add(cm2);
    
        insert cmList;

        List<Opportunity> opptList = new List<Opportunity>();
        Id retailBancassuranceOpportunityRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Retail_Bancassurance').getRecordTypeId();
        for (Integer i = 0;i<10;i++) {
            Opportunity o = new Opportunity(Name='II-OPP-'+i,
                                StageName = 'Analysis',
                                CloseDate = Date.today(),
                                AccountId = accList.get(0).Id,
                                Description = 'desc'+i,
                                CA_Prep_Start_Date__c = Date.today(),
                                Approval_Process_Date__c = Date.today(),
                                Post_Approval_Date__c = Date.today(),
                                Complete_Date__c = Date.today(),
                                Expected_submit_date__c = Date.today(),
                                RecordTypeId=retailBancassuranceOpportunityRecordTypeId,
                                Created_Channel__c = 'Branch'
                            );
            opptList.add(o);
        }
        
        insert opptList;
        Test.startTest();
        // Schedule the test job, but after Test.stopTest, the purge hasn't started.
        String jobId = System.schedule('EmailErrorLogTest', RTL_TestUtility.CRON_EXP, new RTL_SchedulerEmailErrorLog());
        Test.stopTest();
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        // Verify the expressions are the same
        System.assertEquals(RTL_TestUtility.CRON_EXP, ct.CronExpression);
    }
    
    public static testMethod void batchEmailErrorLogTest(){
        //create retail online service log
       RTL_TestUtility.createOnlineServiceLog(100,true);  
        
        Test.startTest();
        
        // Call the batch class in order to check the batch result
        String query = 'select ID from RTL_Online_Service_Log__c where CreatedDate = TODAY LIMIT 10';
        RTL_BatchEmailErrorLog emailLog = new RTL_BatchEmailErrorLog(query);
        Id BatchProcessId = Database.ExecuteBatch(emailLog);
                
        Test.stopTest();
        
        
    }
}