force-app/main/default/objects/Account/fields/Branch_and_Zone__c.field-meta.xml
<CustomField>
    <fullName>Branch_and_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preferred Branch</label>
    <referenceTo>Branch_and_Zone__c</referenceTo>
    <relationshipLabel>Accounts (Branch and Zone)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch_and_Zone__c/Branch_and_Zone__c.object-meta.xml
<CustomObject>
    <label>Branch and Zone</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch and Zone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch_and_Zone__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Branch Code</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTL_product_master__c/RTL_product_master__c.object-meta.xml
<CustomObject>
    <description>To store list of products for Retail banking only.</description>
    <label>Retail Product Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Retail Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_product_master__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Show only products marked as Active in interested products &amp; opportunity .</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/RTL_Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{YY}{MM}{DD}-{000}</displayFormat>
        <label>Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Referral__c/fields/Before_Over_SLA__c.field-meta.xml
<CustomField>
    <fullName>Before_Over_SLA__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Before Over SLA</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_FirstName__c.field-meta.xml
<CustomField>
    <fullName>RTL_FirstName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Interested_Product__c.field-meta.xml
<CustomField>
    <fullName>RTL_Interested_Product__c</fullName>
    <label>Interested Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>RTL_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BA(Credit Life)</fullName>
            </value>
            <value>
                <fullName>BA (IL)</fullName>
            </value>
            <value>
                <fullName>BA (Unit Link)</fullName>
            </value>
            <value>
                <fullName>BA (Others)</fullName>
            </value>
            <value>
                <fullName>Business Click (Basic Plus)</fullName>
            </value>
            <value>
                <fullName>Business Click  (Basic Plus)</fullName>
            </value>
            <value>
                <fullName>Credit Card &amp; RDC</fullName>
            </value>
            <value>
                <fullName>EDC</fullName>
            </value>
            <value>
                <fullName>FX</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>LG</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>OD</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>Prompt Pay</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>TMB Business Touch</fullName>
            </value>
            <value>
                <fullName>TMB Business  Touch</fullName>
            </value>
            <value>
                <fullName>TMB QR</fullName>
            </value>
            <value>
                <fullName>TMB Payroll</fullName>
            </value>
            <value>
                <fullName>TMB SME One Bank (155)</fullName>
            </value>
            <value>
                <fullName>TMB SME One Bank  (155)</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเพื่อธุรกิจ - LG</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเพื่อธุรกิจ - Loan</fullName>
            </value>
            <value>
                <fullName>Refer From TBANK: สินเชื่อเพื่อธุรกิจ - Loan</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเพื่อธุรกิจ - OD</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเพื่อธุรกิจ - Supply Chain [ODB (Clean)]</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเพื่อธุรกิจ - Supply Chain [Factoring (Accepted Invoice)]</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเพื่อธุรกิจ - Supply Chain [Factoring (Confirmed Payment)]</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_LastName__c.field-meta.xml
<CustomField>
    <fullName>RTL_LastName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Mobile1__c.field-meta.xml
<CustomField>
    <fullName>RTL_Mobile1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mobile1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Preferred_Branch__c.field-meta.xml
<CustomField>
    <fullName>RTL_Preferred_Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>สาขาที่ไม่รับบริการคือ สาขา Flagship ได้แก่ ไอคอน สยาม (283) และ อาคารยูไนเต็ด เซ็นเตอร์ สีลม (252), ระบุ WAT เพื่อส่งให้ Investment Line, ระบุ DSA เพื่อส่งให้ Mortgage Sales</inlineHelpText>
    <label>Preferred Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Branch_and_Zone__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch_and_Zone__c</referenceTo>
    <relationshipLabel>Referral Layout</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Preferred_Staff__c.field-meta.xml
<CustomField>
    <fullName>RTL_Preferred_Staff__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Search by Name/Emp ID/Branch code</inlineHelpText>
    <label>Preferred Staff</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>RTL_Product_Group__c</fullName>
    <formula>RTL_Product_Name__r.Product_Group__c</formula>
    <label>Product Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>RTL_product_master__c.Product_Group__c</field>
            <operation>notEqual</operation>
            <value>Loan Retention</value>
        </filterItems>
        <filterItems>
            <field>RTL_product_master__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RTL_product_master__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Stage__c.field-meta.xml
<CustomField>
    <fullName>RTL_Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RTL_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In progress_Contacted</fullName>
                <label>Contacted &amp; In progress</label>
            </value>
            <value>
                <fullName>Closed (Interested)</fullName>
            </value>
            <value>
                <fullName>Closed (Not Interested)</fullName>
            </value>
            <value>
                <fullName>Closed (Unable to contact)</fullName>
            </value>
            <value>
                <fullName>Closed (Unqualified)</fullName>
            </value>
            <value>
                <fullName>Closed (Service Completed)</fullName>
            </value>
            <value>
                <fullName>Closed By AL System</fullName>
            </value>
            <value>
                <fullName>Invalid (Duplicate Opportunity)</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Closed (Transferred)</fullName>
            </value>
            <value>
                <fullName>Closed (Referral Ticket)</fullName>
            </value>
            <value>
                <fullName>Closed (Unqualified  Customer)</fullName>
                <isActive>false</isActive>
                <label>Closed (Unqualified  Customer)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Type__c.field-meta.xml
<CustomField>
    <fullName>RTL_Type__c</fullName>
    <label>Refer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sell (เพื่อนำเสนอขาย)</fullName>
            </value>
            <value>
                <fullName>Account Opening/Service (เพื่อเปิดบัญชี / สมัครบริการ)</fullName>
            </value>
            <value>
                <fullName>Collect Document</fullName>
            </value>
            <value>
                <fullName>Meeting at branch (สาขารอต้อนรับ)</fullName>
            </value>
            <value>
                <fullName>Meeting at branch &amp; Account Opening (สาขารอต้อนรับพร้อมให้บริการเปิดบัญชี)</fullName>
            </value>
            <value>
                <fullName>Introduction call (สาขาโทรสร้างความสัมพันธ์)</fullName>
            </value>
            <value>
                <fullName>เพื่อติดต่อกลับ</fullName>
            </value>
            <value>
                <fullName>To Product Team (เพื่อส่งให้ทีม Product)</fullName>
            </value>
            <value>
                <fullName>บริการให้คำปรึกษา (TMB BIZ ADVISORY)</fullName>
            </value>
            <value>
                <fullName>Service (เพื่อทำรายการ)</fullName>
            </value>
            <value>
                <fullName>For System Only</fullName>
            </value>
            <value>
                <fullName>DM Lead (โทรนัดหมายเพื่อการขาย)</fullName>
            </value>
            <value>
                <fullName>Drop Lead (โทรนัดหมายเพื่อการขาย)</fullName>
            </value>
            <value>
                <fullName>Service (เพื่อให้บริการ)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/overSLAReferralEmailNotifyBatchTest.cls
@isTest
public class overSLAReferralEmailNotifyBatchTest{
    static List<Branch_And_Zone__c> branchAndZoneList;
    static{
        TestUtils.createAppConfig();
        Id TMB_RC_PROFILE_ID = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id;
        system.debug(TMB_RC_PROFILE_ID);

        RTL_product_master__c prod = new RTL_product_master__c();
        prod.Name = 'CYC';
        prod.Active__c = true;
        insert prod;
        Branch_and_Zone__c branch = new Branch_and_Zone__c();
        branch.Branch_Code__c = '001';
        branch.IsActive__c = true;
        insert branch;

        // List<User> userlst = [SELECT Id, ManagerId, Email, RTL_Branch_Code__c FROM User LIMIT 2];
        // for(User u:userlst){
        //     u.RTL_Branch_Code__c = '001';           
        // }
        // Id prdId = [SELECT Id,Name FROM  RTL_product_master__c WHERE Name = 'CYC' LIMIT 1].Id;
        // Id branchId = [SELECT Id,Branch_Code__c  FROM  Branch_and_Zone__c WHERE Branch_Code__c = '001' LIMIT 1].Id;

        User ManagerUser = new User(FirstName='TestApproval',LastName='Manager', 
                                    UserName='Manager_TMBTestTMB@tmb.com',
                                    Email='tmbmanager@tmbbank.com', Alias='TmbMr',Segment__c ='MB',
                                    LocaleSidKey='en_US', LanguageLocaleKey='en_US', EmailEncodingKey='ISO-8859-1', 
                                    CommunityNickname='ManagerNickname',
                                    ProfileId = TMB_RC_PROFILE_ID, TimeZoneSidKey='America/New_York',isActive = true,
                                    Employee_ID__c ='MN001');
        insert ManagerUser;
        User PreferredStaff = new User(FirstName='TestApproval',LastName='PS', 
                                    UserName='RM_TMBTestTMB@tmb.com',
                                    Email='rmtmb@tmbbank.com', Alias='TmbRM',Segment__c ='MB',
                                    LocaleSidKey='en_US', LanguageLocaleKey='en_US', EmailEncodingKey='ISO-8859-1', 
                                    CommunityNickname='RMNickname',RTL_Branch_Code__c='001',
                                    ProfileId = TMB_RC_PROFILE_ID, TimeZoneSidKey='America/New_York',isActive = true,
                                    Employee_ID__c ='RM001',ManagerId = ManagerUser.id);
        insert PreferredStaff;

        System.runAs(PreferredStaff){
        String RecordTypeId = Schema.SObjectType.RTL_Referral__c.getRecordTypeInfosByName().get('Retail Cross Channel Referral').getRecordTypeId();
        RTL_Referral__c ref01 = new RTL_Referral__c();
        ref01.RecordTypeId = RecordTypeId;
        ref01.RTL_FirstName__c = 'Fname001';
        ref01.RTL_LastName__c = 'Lname001';
        ref01.RTL_Mobile1__c = '0951234560';
        ref01.RTL_Type__c = 'Sell (เพื่อนำเสนอขาย)';
        ref01.RTL_Preferred_Staff__c = PreferredStaff.Id;
        ref01.RTL_Product_Name__c = prod.Id;
        ref01.RTL_Stage__c = 'New';
        ref01.RTL_Preferred_Branch__c = branch.Id;
        insert ref01;
        ref01.Before_Over_SLA__c = Datetime.now();
        update ref01;
        RTL_Referral__c ref02 = new RTL_Referral__c();
        ref02.RecordTypeId = RecordTypeId;
        ref02.RTL_FirstName__c = 'Fname002';
        ref02.RTL_LastName__c = 'Lname002';
        ref02.RTL_Mobile1__c = '0951234560';
        ref02.RTL_Type__c = 'Sell (เพื่อนำเสนอขาย)';
        ref02.RTL_Product_Name__c = prod.Id;
        ref02.RTL_Stage__c = 'New';
        ref02.RTL_Preferred_Branch__c = branch.Id;
        insert ref02;
        ref02.Before_Over_SLA__c = Datetime.now();
        update ref02;
        RTL_Referral__c ref03 = new RTL_Referral__c();
        ref03.RecordTypeId = RecordTypeId;
        ref03.RTL_FirstName__c = 'Fname003';
        ref03.RTL_LastName__c = 'Lname003';
        ref03.RTL_Mobile1__c = '0951234560';
        ref03.RTL_Type__c = 'Sell (เพื่อนำเสนอขาย)';
        ref03.RTL_Preferred_Staff__c = PreferredStaff.Id;
        ref03.RTL_Product_Name__c = prod.Id;
        ref03.RTL_Stage__c = 'New';
        ref03.RTL_Preferred_Branch__c = branch.Id;
        insert ref03;
        ref03.Before_Over_SLA__c = Datetime.now();
        update ref03;
        }
        
    }

    @isTest
    public static void testFlow(){
        String q = 	' SELECT Id, OwnerId, CreatedBy.Email, Owner.Name, Owner.Email, RTL_Preferred_Staff__c, Name, RTL_Stage__c, RecordType.Name, RTL_Interested_Product__c, RTL_Account_Name__c, RTL_Account_Name__r.Name, RTL_Type__c, RTL_Product_Group__c, RTL_Product_Name__r.Name, RTL_Preferred_Staff__r.Manager_Email__c'
					+ ' FROM RTL_Referral__c '
					+ ' WHERE Before_Over_SLA__c = TODAY AND'
					+ ' (RecordType.Name = \'Refer to Retail\' OR RecordType.Name = \'Retail Cross Channel Referral\') AND'
					+ ' RTL_Stage__c = \'New\' ';
        Test.startTest();
        Database.executeBatch(new overSLAReferralEmailNotificationBatch(q));
        Test.stopTest();
    }

    @isTest
    public static void testScheduled(){
        Test.startTest();
        String jobId = System.schedule('test', '0 0 8 ? * MON,TUE,WED,THU,FRI *', new overSLAReferralEmailNotifyScheduled());
        Test.stopTest();
    }
}