force-app/main/default/objects/Account/fields/C_Home_phone_PE__c.field-meta.xml
<CustomField>
    <fullName>C_Home_phone_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Home phone.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Name_PE_Eng__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name_PE_Eng__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Customer Name EN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FATCA_Form_Completed__c.field-meta.xml
<CustomField>
    <fullName>FATCA_Form_Completed__c</fullName>
    <inlineHelpText>ให้ลูกค้ากรอกและลงนามแบบพอร์ม FATCA นำส่งผ่านระบบ FATCA Cleansing เพื่อนำส่ง บลจ. ทหารไทย</inlineHelpText>
    <label>FATCA Form Completed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mobile_Number_PE__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>Mobile or Office Phone Number must be entered</inlineHelpText>
    <label>Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/RTL_Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>RTL_Date_Of_Birth__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/RTL_Occupation_Details__c.field-meta.xml
<CustomField>
    <fullName>RTL_Occupation_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Occupation Details</label>
    <referenceTo>RTL_Occupation_Details__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/RTL_Wealth_RM__c.field-meta.xml
<CustomField>
    <fullName>RTL_Wealth_RM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CR Wealth RM Info , convert EMP/BR Code to Wealth RM</description>
    <label>Wealth RM/BM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TMB_Customer_ID_PE__c.field-meta.xml
<CustomField>
    <fullName>TMB_Customer_ID_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>TMB Customer ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Income_Expense__c/Income_Expense__c.object-meta.xml
<CustomObject>
    <label>Income - Expense</label>
    <nameField>
        <displayFormat>IE-{00000}</displayFormat>
        <label>Income - Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incomes - Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Income_Expense__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Incomes - Expenses</relationshipLabel>
    <relationshipName>Incomes_Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Income_Expense__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <label>Expense</label>
</RecordType>

force-app/main/default/objects/Income_Expense__c/recordTypes/Income.recordType-meta.xml
<RecordType>
    <fullName>Income</fullName>
    <active>true</active>
    <label>Income</label>
</RecordType>

force-app/main/default/objects/RTL_Occupation_Details__c/RTL_Occupation_Details__c.object-meta.xml
<CustomObject>
    <label>Occupation Details</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Occupation Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Occupation Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Occupation_Details__c/fields/RTL_Occupation_Desc__c.field-meta.xml
<CustomField>
    <fullName>RTL_Occupation_Desc__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Occupation Desc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EditCustomerControllerTest.cls
@istest
public class EditCustomerControllerTest {
	@istest
    static void test(){
        TestUtils.createAppConfig(); 
        
        Account acc = new Account();
        acc.Name = 'test';
        acc.Phone = '0999932211';
        acc.Mobile_Number_PE__c = '083234222';
        acc.RTL_Date_Of_Birth__c = Date.today();
        acc.RTL_Wealth_RM__c = UserInfo.getUserId();
        insert acc;
        
        List<String> fields = new List<String>{'Id'};
        EditCustomerController.getDescribeFieldResultAndValue(acc.Id, fields, new List<String>());
        
        EditCustomerController.verifyFieldSecurity('section', userinfo.getProfileId(), acc.Id);
        
        EditCustomerController.getInitialDataController(userinfo.getUserId(), acc.Id);
        
        Income_Expense__c ie = new Income_Expense__c();
        ie.Customer__c = acc.Id;
        ie.RecordTypeId = Schema.SObjectType.Income_Expense__c.getRecordTypeInfosByDeveloperName().get('Income').getRecordTypeId();
        insert ie;
        
 		Income_Expense__c ie2 = new Income_Expense__c();
        ie2.Customer__c = acc.Id;
        ie2.RecordTypeId = Schema.SObjectType.Income_Expense__c.getRecordTypeInfosByDeveloperName().get('Expense').getRecordTypeId();
        insert ie2;
        
        Income_Expense__c ie3 = new Income_Expense__c();
        ie3.Customer__c = acc.Id;
        ie3.RecordTypeId = Schema.SObjectType.Income_Expense__c.getRecordTypeInfosByDeveloperName().get('Expense').getRecordTypeId(); 
        
        EditCustomerController.getIncomeExpense(acc.Id);
        
        List<Income_Expense__c> incomeList = new List<Income_Expense__c>();
        incomeList.add(ie);
        List<Income_Expense__c> expenseList = new List<Income_Expense__c>();
        expenseList.add(ie);
        expenseList.add(ie3);
        
        EditCustomerController.submitEditAccount(acc, incomeList, expenseList);
    }

    @isTest
    static void testgetDataAfterRefresh(){
        TestUtils.createAppConfig(); 
        
        List<String> fields = new List<String>{ 'FATCA_Form_Completed__c', 'C_Home_phone_PE__c', 'Customer_Name_PE_Eng__c', 'RTL_Occupation_Details__r.RTL_Occupation_Desc__c', 'TMB_Customer_ID_PE__c', 'RecordTypeId'}; 
        List<String> fieldstranslate = new List<String>{};
       
        Account acc = new Account();
        acc.Name = 'test';
        acc.Phone = '0999932211';
        acc.Mobile_Number_PE__c = '083234222';
        acc.RTL_Date_Of_Birth__c = Date.today();
        acc.RTL_Wealth_RM__c = UserInfo.getUserId();
        insert acc;
        Test.startTest();
        Object returnValue = EditCustomerController.getDataAfterRefresh(acc.Id, fields, fieldstranslate);   
        Test.stopTest();
    }
}