force-app/main/default/objects/Account/fields/Core_Banking_Suggested_Segment__c.field-meta.xml
<CustomField>
    <fullName>Core_Banking_Suggested_Segment__c</fullName>
    <formula>IF(OR(ISBLANK(Segment_crm__c), ISNULL(Segment_crm__c), Segment_crm__c == &quot;0&quot;), 
&quot;&quot;, 
CASE(Segment_crm__c , 
&quot;1&quot; , &quot;MB&quot;, 
&quot;2&quot;, &quot;CB&quot;, 
&quot;3&quot;,&quot;BB&quot;, 
&quot;4&quot;,&quot;SE&quot;, 
&quot;5&quot;,&quot;Affluent&quot;, 
&quot;6&quot;,&quot;Middle Income&quot;, 
&quot;7&quot;,&quot;Mass&quot;, 
&quot;Others&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/First_Name_ENG_PE__c.field-meta.xml
<CustomField>
    <fullName>First_Name_ENG_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>First Name EN</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/First_name_PE__c.field-meta.xml
<CustomField>
    <fullName>First_name_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>First Name TH</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_name_PE__c.field-meta.xml
<CustomField>
    <fullName>Last_name_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Last Name TH</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Name_PE_Eng__c.field-meta.xml
<CustomField>
    <fullName>Last_Name_PE_Eng__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Last Name EN</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/All_Previous_Owner__c.field-meta.xml
<CustomField>
    <fullName>All_Previous_Owner__c</fullName>
    <description>This field for use to filter Case outbox. Store all previous owner.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>All Previous Owner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <formula>Account.TMB_Customer_ID_PE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID_Number__c</fullName>
    <formula>Account.ID_Number_PE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer ID Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>This field only for send to DWH</description>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Is_Edit_Branch_Queue__c.field-meta.xml
<CustomField>
    <fullName>Is_Edit_Branch_Queue__c</fullName>
    <formula>if(AND(Owner:Queue.DeveloperName &lt;&gt; &apos;&apos;, ISPICKVAL($User.RTL_Channel__c, &apos;Branch&apos;)) , 
if(AND(CONTAINS( Owner:Queue.DeveloperName , $User.RTL_Branch_Code__c ), NOT(ISBLANK( $User.RTL_Branch_Code__c ))), true, 
if( AND(LEN(All_Previous_Owner__c) &lt; 2, CreatedById = $User.Id, TEXT(Status) = &apos;New&apos; ), true, false) ), 
true )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Edit Branch Queue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/E_Client_Suitability__c/E_Client_Suitability__c.object-meta.xml
<CustomObject>
    <label>E-Client Suitability</label>
    <nameField>
        <displayFormat>CS-{YYMMDD}-{000}</displayFormat>
        <label>E-Client Suitability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>E-Client Suitability</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/E_Client_Suitability__c/fields/ECM_App_ID__c.field-meta.xml
<CustomField>
    <fullName>ECM_App_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ECM App ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/E_Client_Suitability__c/fields/ECM_Repository__c.field-meta.xml
<CustomField>
    <fullName>ECM_Repository__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ECM Repository</label>
    <referenceTo>ECM_Repository__c</referenceTo>
    <relationshipLabel>E-Client Suitability</relationshipLabel>
    <relationshipName>E_Client_Suitability_ECM_Repository</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ECM_Repository__c/ECM_Repository__c.object-meta.xml
<CustomObject>
    <label>ECM Repository</label>
    <nameField>
        <displayFormat>ECM Rep.{000}</displayFormat>
        <label>ECM Repository Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ECM Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ECM_Repository__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ECM Repositories</relationshipLabel>
    <relationshipName>ECM_Repositories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ECM_Repository__c/fields/Customer_Firstname__c.field-meta.xml
<CustomField>
    <fullName>Customer_Firstname__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Firstname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECM_Repository__c/fields/Customer_Firstname_EN__c.field-meta.xml
<CustomField>
    <fullName>Customer_Firstname_EN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Firstname EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECM_Repository__c/fields/Customer_Lastname__c.field-meta.xml
<CustomField>
    <fullName>Customer_Lastname__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Lastname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECM_Repository__c/fields/Customer_Lastname_EN__c.field-meta.xml
<CustomField>
    <fullName>Customer_Lastname_EN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Lastname EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECM_Repository__c/fields/E_Client_Suitability__c.field-meta.xml
<CustomField>
    <fullName>E_Client_Suitability__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup which e-client has this ecm record</description>
    <label>E-Client Suitability</label>
    <referenceTo>E_Client_Suitability__c</referenceTo>
    <relationshipLabel>ECM Repositories</relationshipLabel>
    <relationshipName>ECM_Eclient</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ECM_Repository__c/fields/ECM_App_ID__c.field-meta.xml
<CustomField>
    <fullName>ECM_App_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ECM App ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECM_Repository__c/fields/ECM_Uploaded_By__c.field-meta.xml
<CustomField>
    <fullName>ECM_Uploaded_By__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ECM Uploaded By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECM_Repository__c/fields/ECM_Uploaded_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>ECM_Uploaded_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ECM Uploaded Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ECM_Repository__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>File Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECM_Repository__c/fields/Is_ECM_Upload__c.field-meta.xml
<CustomField>
    <fullName>Is_ECM_Upload__c</fullName>
    <defaultValue>false</defaultValue>
    <description>check if ECM is upload or not</description>
    <label>Is ECM Upload</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ECM_Repository__c/fields/Object_ID__c.field-meta.xml
<CustomField>
    <fullName>Object_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Object ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECM_Repository__c/fields/Repository__c.field-meta.xml
<CustomField>
    <fullName>Repository__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Repository</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECM_Repository__c/fields/Uploaded_By__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Uploaded By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ECM_Uploaded_By</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/viewECMfileController.cls
public class viewECMfileController {
    public String ecmFile {get;set;}
    
    private String repId;
    private String objId;   
    public String obId {get;set;}
    public string contentType{get;set;}
    public Boolean typePDF{get;set;}
    public Boolean errorMessage{get;set;}
    public Boolean isAllowedEdit{get;set;}
    
    public static AppConfig__c appCon_Endpoint {
        get
        { 
            if( appCon_Endpoint == null)
            {
                appCon_Endpoint = AppConfig__c.getValues('ECM_Endpoint');
            }
            return appCon_Endpoint;
        } 
        set; 
    }

    public static App_Config__mdt appConMeta_Timeout { 
        get
        { 
            if( appConMeta_Timeout == null)
            {
                appConMeta_Timeout = [SELECT Id, Label, Value__c FROM App_Config__mdt WHERE Label = 'ECM_REQUEST_TIMEOUT']; 
            }
            return appConMeta_Timeout;
        } 
        set; 
    }

    public viewECMfileController()
    {
        obId = apexpages.currentpage().getparameters().get('obId');
        isAllowedEdit = true;
        typePDF = false;
    }

    public PageReference getStream()
    {
        try {
        ECM_Repository__c ecmRepo = [SELECT Customer_Firstname_EN__c, Customer_Firstname__c, Customer_Lastname_EN__c, Customer_Lastname__c,
                                    ECM_App_ID__c, ECM_Uploaded_By__c, ECM_Uploaded_Date_Time__c, E_Client_Suitability__c, File_Name__c,
                                    Is_ECM_Upload__c, Object_ID__c, Repository__c, Uploaded_By__c, Case__c,CreatedDate, Id ,CreatedById
                                    FROM ECM_Repository__c where Object_ID__c =: obId];
        //system.debug('obId zz '+obId);
        boolean allowedView = allowEdit(ecmRepo.Case__c,ecmRepo.CreatedById);
        if(!allowedView){
            ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.Case_Edit_NotAuthorizedMsg));
            isAllowedEdit = false;
        }
        else{
            isAllowedEdit = true;
            List<Case> caseMaster = [SELECT Id,CaseNumber,Customer_ID__c,AccountId,Customer_ID_Number__c, Customer_Name__c FROM Case where id =: ecmRepo.Case__c];
            List<Account> accList = [SELECT Id, First_Name_ENG_PE__c, Last_Name_PE_Eng__c, First_name_PE__c, Last_name_PE__c,Core_Banking_Suggested_Segment__c
                                    FROM Account where id =:caseMaster[0].AccountId];
            
            string caseNumber = caseMaster[0].CaseNumber;
            string appId = caseMaster[0].CaseNumber;
            String repositoryId = ecmRepo.Repository__c;
            String objectId = string.valueOf(ecmRepo.Object_ID__c);
            system.debug('repositoryId '+repositoryId);
            system.debug('objectId '+objectId);
            
            //
            UploadToECMController serviceECM = new UploadToECMController();
            UploadToECMController.viewECM res = serviceECM.viewInECM(repositoryId,objectId);

            if(res.succesView){
                onlineLog(caseNumber,appId,caseMaster,accList,res);
                ecmFile = res.ecmFile;
                contentType = res.contentType;
                system.debug('contentType11 '+contentType);
                if(contentType.contains('application')){
                    typePDF = true;
                }
            }
            else{
                onlineLog(caseNumber,appId,caseMaster,accList,res);
                system.debug('res.errorMessage '+res.errorMessage);
                ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR, res.errorMessage));
                errorMessage = true;
            }
        }
        } catch (Exception e) {
            errorMessage = true;
            ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
        
        return null;
    }

    private void onlineLog(String caseNumber,String appId,List<Case> caseMaster,List<Account> accList,UploadToECMController.viewECM res){
        boolean isSuccess = res.succesView;
        String customerName = caseNumber;
        String errorMessageRespone = res.errorMessage;
        String msLogId = appId;
        String userName = UserInfo.getFirstName() + ' ' + UserInfo.getLastName();
        String rmId = caseMaster[0].Customer_ID_Number__c;
        String serviceName = 'View Case Attachment ECM';
        string requestBody=res.requestToJSON;
        string responseBody=res.responseToJSON;
        Account acc=accList[0];
        DateTime startTime = res.startTime;
        DateTime endTime = res.endTime;
        String base64Data = res.base64Data;
        OnlineServiceLogUtils.saveToOnlineLog(isSuccess ,customerName, errorMessageRespone, msLogId , userName, rmId , serviceName ,requestBody ,responseBody , acc , startTime , endTime, base64Data );
    }

    private boolean allowEdit(Id caseId,Id ownerId){

        boolean isAllowedView = false;

        if(UserInfo.getUserId()==ownerId){
            isAllowedView = true;
        }
        else{
            UserRecordAccess uAccess = [SELECT RecordID, HasReadAccess, HasEditAccess FROM UserRecordAccess
                                            WHERE UserId = : UserInfo.getUserId()
                                                    AND RecordID = : caseId
                                                            //AND HasReadAccess = True
                                           ];
            Case casePermision = [SELECT Id, Is_Edit_Branch_Queue__c, CreatedById, LastModifiedById, Status, All_Previous_Owner__c FROM case WHERE ID = :caseId];

            if( uAccess.HasEditAccess == true && casePermision.Is_Edit_Branch_Queue__c == true) {
                isAllowedView = true;
            }
            else{
                isAllowedView = false;
                //ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR,  Label.Case_Edit_NotAuthorizedMsg ));
            }
        }
        return isAllowedView;
    }

}