force-app/main/default/objects/Account/fields/Customer_Name_PE_Eng__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name_PE_Eng__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Customer Name EN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/First_name_PE__c.field-meta.xml
<CustomField>
    <fullName>First_name_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>First Name TH</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Number_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Number_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>เลขที่เอกสารสำคัญของลูกค้า</inlineHelpText>
    <label>ID Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Type_PE__c</fullName>
    <description>Identification Type Ex. Citizen ID, BRN ID, Passport ID, Alien ID, Work permit</description>
    <inlineHelpText>ประเภทเอกสารสำคัญของลูกค้า</inlineHelpText>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Customer_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BRN ID</fullName>
            </value>
            <value>
                <fullName>Citizen ID</fullName>
            </value>
            <value>
                <fullName>Passport ID</fullName>
            </value>
            <value>
                <fullName>Work permit ID</fullName>
            </value>
            <value>
                <fullName>Alien ID</fullName>
            </value>
            <value>
                <fullName>Tax ID</fullName>
            </value>
            <value>
                <fullName>Other ID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Last_name_PE__c.field-meta.xml
<CustomField>
    <fullName>Last_name_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Last Name TH</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Service_class__c.field-meta.xml
<CustomField>
    <fullName>Service_class__c</fullName>
    <inlineHelpText>To identify the target customers</inlineHelpText>
    <label>Service Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Top 20 Group</fullName>
            </value>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Maintain</fullName>
            </value>
            <value>
                <fullName>Military&amp;PS / FI</fullName>
            </value>
            <value>
                <fullName>MNC &amp; JAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Visit_Class__c.field-meta.xml
<CustomField>
    <fullName>Visit_Class__c</fullName>
    <inlineHelpText>The recommended frequency of customer visits</inlineHelpText>
    <label>Visit Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly Visit</fullName>
            </value>
            <value>
                <fullName>Once per 2 Months</fullName>
            </value>
            <value>
                <fullName>Quarterly Visit</fullName>
            </value>
            <value>
                <fullName>Half-Yearly Visit</fullName>
            </value>
            <value>
                <fullName>Annually Visit</fullName>
            </value>
            <value>
                <fullName>When Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <label>Visit Plan / Report</label>
    <nameField>
        <displayFormat>Visit-{0000}</displayFormat>
        <label>Visit Report No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Plan / Reports</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report__c/fields/Categories__c.field-meta.xml
<CustomField>
    <fullName>Categories__c</fullName>
    <label>Categories</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre boarding</fullName>
            </value>
            <value>
                <fullName>On-boarding</fullName>
            </value>
            <value>
                <fullName>Post-boarding</fullName>
            </value>
            <value>
                <fullName>SE Default</fullName>
            </value>
            <value>
                <fullName>Initiatives</fullName>
            </value>
            <value>
                <fullName>Float Charge</fullName>
            </value>
            <value>
                <fullName>RPD Team Face To Face Visit</fullName>
            </value>
            <value>
                <fullName>RPD Team Telephone Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Customer_name__c.field-meta.xml
<CustomField>
    <fullName>Customer_name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>notEqual</operation>
            <value>Disqualified Prospect</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visit Plan / Reports</relationshipLabel>
    <relationshipName>Call_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Date_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Visit__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Visit Plan Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Main_purpose__c.field-meta.xml
<CustomField>
    <fullName>Main_purpose__c</fullName>
    <label>Main purpose</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Categories__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>First visit</fullName>
            </value>
            <value>
                <fullName>Find Oppty</fullName>
            </value>
            <value>
                <fullName>Product pitching / Present Product</fullName>
            </value>
            <value>
                <fullName>Follow up sales</fullName>
            </value>
            <value>
                <fullName>Submit proposal</fullName>
            </value>
            <value>
                <fullName>Sign Agreement</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>On-boarding new product</fullName>
            </value>
            <value>
                <fullName>Credit review</fullName>
            </value>
            <value>
                <fullName>Service review for credit product (Interview cust need)</fullName>
            </value>
            <value>
                <fullName>Service review for non-credit product (Interview cust need)</fullName>
            </value>
            <value>
                <fullName>Boost u% (Business Volume)</fullName>
            </value>
            <value>
                <fullName>Hand over (New RM)</fullName>
            </value>
            <value>
                <fullName>Debt collection</fullName>
            </value>
            <value>
                <fullName>Relationship</fullName>
            </value>
            <value>
                <fullName>Sell product</fullName>
            </value>
            <value>
                <fullName>Doc. Collection</fullName>
            </value>
            <value>
                <fullName>Control quality &amp; Follow up debt</fullName>
            </value>
            <value>
                <fullName>Make relationship</fullName>
            </value>
            <value>
                <fullName>Solve problem</fullName>
            </value>
            <value>
                <fullName>CB</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>BB.</fullName>
            </value>
            <value>
                <fullName>SE.</fullName>
            </value>
            <value>
                <fullName>แนะนำตัว / นัดหมายขอเข้าพบลูกค้า</fullName>
            </value>
            <value>
                <fullName>เข้าพบเพื่อสร้างความสัมพันธ์กับลูกค้า</fullName>
            </value>
            <value>
                <fullName>นำเสนอขายผลิตภัณฑ์และบริการ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Main_purpose__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Win Deal</fullName>
            </value>
            <value>
                <fullName>Lost Deal</fullName>
            </value>
            <value>
                <fullName>Win oppty</fullName>
            </value>
            <value>
                <fullName>Lost oppty</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Need follow up</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Not interested</fullName>
            </value>
            <value>
                <fullName>To follow up</fullName>
            </value>
            <value>
                <fullName>Very satisfied</fullName>
            </value>
            <value>
                <fullName>Satisfied</fullName>
            </value>
            <value>
                <fullName>Moderate</fullName>
            </value>
            <value>
                <fullName>Dissatisfied</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Accept &amp;Sign-off Agreement</fullName>
            </value>
            <value>
                <fullName>Customer Reject</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Customer Accept &amp; will Sign-off Agreement</fullName>
            </value>
            <value>
                <fullName>Float Charge_Not Receive Registration, Already had/Will sign-off Negative Pledge</fullName>
            </value>
            <value>
                <fullName>Float Charge_Stay with Customer, No Negative Pledge</fullName>
            </value>
            <value>
                <fullName>Float Chrage_Exit this Customer</fullName>
            </value>
            <value>
                <fullName>Cancelled this visit</fullName>
            </value>
            <value>
                <fullName>อยู่ระหว่างดำเนินการ</fullName>
            </value>
            <value>
                <fullName>สำเร็จ</fullName>
            </value>
            <value>
                <fullName>ไม่สำเร็จ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 - Open</fullName>
                <default>true</default>
                <label>1 - Open</label>
            </value>
            <value>
                <fullName>2 - Completed</fullName>
            </value>
            <value>
                <fullName>3 - Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>Target</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Target__c/fields/Monthly_Target_Date__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Target_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Yearly Target Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Target__c/fields/Monthly_Visit_Actual__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Visit_Actual__c</fullName>
    <label>Monthly Visit Actual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CallReportTriggerTest.cls
@IsTest
public class CallReportTriggerTest {
    public static String STR_POSITIVE = 'positive';
    public static String STR_NEGATIVE = 'negative';
    
    static{
        TestUtils.CreateProceBookAccess();
        TestUtils.createAppConfig();
        TestUtils.createStatusCode();        
        TestUtils.createIdType();
        TestUtils.createTriggerMsg();
        TestUtils.createObjUserPermission();
    }
    
    
    public static testmethod void RunPositiveTestReport(){
        System.debug(':::: RunPositiveTestReport Start ::::');
        //TestInit.createUser(false);
        //User u = TestInit.us;
        
           User newUser = new User(FirstName='callFirst', LastName='callLast', 
                                    UserName='callreportname@tmb.com', 
                                    Email='callreportname@tmbbank.com', Alias='visit',
                                    LocaleSidKey='en_US', LanguageLocaleKey='en_US', EmailEncodingKey='ISO-8859-1', 
                                    CommunityNickname='visittmb',
                                    ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id
                                   , TimeZoneSidKey='America/New_York',isActive = true,
                                    Employee_ID__c ='V0001',Zone__c=
                                  '1001',Segment__c ='AA',Zone_Code__c ='1001');
           
           insert newUser;
        System.runAs(newUser) {
            // Test for T03
            
            Account acct =  TestUtils.createAccounts(1,'callreport','Individual', false).get(0);
        acct.First_Name_PE__c ='Tinnakrit';
        acct.Customer_Name_PE_Eng__c = 'Tinnakrit';
        acct.Last_name_PE__c  ='Kidmai'; 
        acct.ID_Type_PE__c = 'Passport ID';
        acct.ID_Number_PE__c = '13255555';
        insert acct;
            List <Account> acctList = new List<Account>();
            acctList.add(acct);
            TestInit.createTarget(acctList);
            
            TEST.startTest();
            flowTest(STR_POSITIVE);
            DifferentOwnerTest(STR_POSITIVE);
            TEST.stopTest();
            
        }
        System.debug(':::: RunPositiveTestReport End ::::');
    }
    
      public static testmethod void Tier0(){
        TestInit.createAccount(1);
        TestInit.createTarget(TestInit.accountList.values());
        TEST.startTest();
        TargetActualTest(STR_POSITIVE,'Silver',' ');
        TEST.stopTest();
    }    
    
    public static testmethod void Tier1(){
        TestInit.createAccount(1);
        TestInit.createTarget(TestInit.accountList.values());
        TEST.startTest();
        TargetActualTest(STR_POSITIVE,'Gold','Tier 1');
        TEST.stopTest();
    }
    
    public static testmethod void Tier2(){
        TestInit.createAccount(1);
        TestInit.createTarget(TestInit.accountList.values());
        TEST.startTest();
        TargetActualTest(STR_POSITIVE,'Platinum','Tier 2');
        TEST.stopTest();
    }
    
    public static void Tier3(){
        TestInit.createAccount(1);
        TestInit.createTarget(TestInit.accountList.values());
        TEST.startTest();
        TargetActualTest(STR_POSITIVE,'Platinum','Tier 3');
        TEST.stopTest();
    }
    
    public static testmethod void Tier4(){
       TestInit.createAccount(1);
       TestInit.createTarget(TestInit.accountList.values());
        TEST.startTest();
        TargetActualTest(STR_POSITIVE,'Platinum','Tier 4');
        TEST.stopTest();
    }
    
        public static void flowTest(String testMode){
        TestInit.createReport(TestInit.accountList.values());
        List<Target__c> listTarget = [select OwnerId,Monthly_Visit_Actual__c,Zone__c 
                                      from Target__c 
                                      where Id IN :TestInit.targetList.keySet()];
        System.debug('listTarget : '+listTarget);
        //for(Target__c t : listTarget){
        //    System.assertEquals(0,t.Monthly_Visit_Actual__c);    
        //}
        
        Map<Id,Call_Report__c> mapReport = new Map<Id,Call_Report__c>();
        List<Call_Report__c> listForDML = new List<Call_Report__c>();
        Call_Report__c createReport = new Call_Report__c();
        for(Account a : TestInit.accountList.values() ){
             createReport = new Call_Report__c(OwnerId=UserInfo.getUserId(),
                                                             Customer_name__c = a.id,
                                                             Status__c = 'Open',
                                                             Date_of_Visit__c = Date.today(),
                                                            Categories__c  = 'Sell product',
                                                Main_purpose__c = 'Sell product'
                                                            );  
            listForDML.add(createReport);
        }
        
        insert listForDML;
        mapReport.putAll(listForDML);
        
        List<Call_Report__c> listReport = [select Id from Call_Report__c where Id IN :mapReport.keySet()];
        for( Call_Report__c report : listReport ){
            report.Status__c = 'Completed';
            report.Outcome__c = 'Win oppty';
        }
        update listReport;
        //for(Target__c t : listTarget){
         //   System.assertEquals(1,t.Monthly_Visit_Actual__c);    
        //}
    }
    
        public static void TargetActualTest(String testMode,String typeTarget,String VisitClass){
        
        Date currentDate = Date.today();
        Integer currentMonth = currentDate.month();
        Integer currentYear = currentDate.year();
        if(currentYear>2557) currentYear = currentDate.year() - 543;
        
        User u = [SELECT ID,Segment__c FROM User WHERE ID=:UserInfo.getUserId() LIMIT 1];
        List<RecordType> recordTypeId = [select Id from RecordType where name = 'Activities Target' limit 1];
        Id activitiesId = recordTypeId[0].Id;    
        
        Target__c TG = new Target__c(Monthly_Target_Date__c=currentDate,RecordTypeId =activitiesId,OwnerId =u.Id);

        for(Account a : TestInit.accountList.values() ){
             a.Service_class__c= typeTarget;
             a.Visit_Class__c= VisitClass;
             update a;
         }
        TestInit.createTarget(TestInit.accountList.values());
        TestInit.createReport(TestInit.accountList.values());    

            
        //List<Target__c> listTarget = [ select OwnerId,Monthly_Target_Date__c,Actual_Visit_Silver__c,Actual_Visit_Gold__c,Actual_Visit_Platinum__c from Target__c where OwnerId = : UserInfo.getUserId() and CALENDAR_MONTH(Monthly_Target_Date__c) = : currentMonth and CALENDAR_YEAR(Monthly_Target_Date__c) = : currentYear and RecordTypeId = : activitiesId];                    
        /*for(Target__c t : listTarget){
            if(typeTarget=='Silver'){
            System.assertEquals(1,t.Actual_Visit_Silver__c);  
            System.assertEquals(null,t.Actual_Visit_Gold__c);  
            System.assertEquals(null,t.Actual_Visit_Platinum__c);      
            }else if(typeTarget=='Gold'){
            System.assertEquals(1,t.Actual_Visit_Silver__c);  
            System.assertEquals(1,t.Actual_Visit_Gold__c);  
            System.assertEquals(null,t.Actual_Visit_Platinum__c);      
            }else if(typeTarget=='Platinum'){
            System.assertEquals(1,t.Actual_Visit_Silver__c);  
            System.assertEquals(1,t.Actual_Visit_Gold__c);  
            System.assertEquals(1,t.Actual_Visit_Platinum__c);      
            }
        }*/
            

    }
    
        public static void DifferentOwnerTest(String testMode){
         User AdminUser;
        for(Account a : TestInit.accountList.values() ){
             AdminUser = TestUtils.createUsers(1,'AccountOwner', 'Ownertest','OwnerIDtest@email.com', true).get(0);
             a.OwnerId = AdminUser.id;
             update a;
         }
        TestInit.createTarget(TestInit.accountList.values());
        TestInit.createReport(TestInit.accountList.values());    

            

    }
        
}