force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>ประเภทลูกค้าว่าเป็น  บุคคล หรือ บริษัท</description>
    <inlineHelpText>ประเภทลูกค้าว่าเป็น  บุคคล หรือ บริษัท</inlineHelpText>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
                <default>true</default>
                <label>Individual</label>
            </value>
            <value>
                <fullName>Juristic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Number_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Number_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>เลขที่เอกสารสำคัญของลูกค้า</inlineHelpText>
    <label>ID Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Type_PE__c</fullName>
    <description>Identification Type Ex. Citizen ID, BRN ID, Passport ID, Alien ID, Work permit</description>
    <inlineHelpText>ประเภทเอกสารสำคัญของลูกค้า</inlineHelpText>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Customer_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BRN ID</fullName>
            </value>
            <value>
                <fullName>Citizen ID</fullName>
            </value>
            <value>
                <fullName>Passport ID</fullName>
            </value>
            <value>
                <fullName>Work permit ID</fullName>
            </value>
            <value>
                <fullName>Alien ID</fullName>
            </value>
            <value>
                <fullName>Tax ID</fullName>
            </value>
            <value>
                <fullName>Other ID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TMB_Customer_ID_PE__c.field-meta.xml
<CustomField>
    <fullName>TMB_Customer_ID_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>TMB Customer ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/submitToEOnBoardingButtonController.cls
public with sharing class submitToEOnBoardingButtonController {

    public Id recID {get; set;}

    public String RecordtypeToUpdate = 'Non-credit Product2';

    public Boolean submitPass {
        get{
            submitPass = false;
            if(ThisOpty != null){
                System.debug('This Oppty : ' + ThisOpty);
                System.debug('This Account : ' + ThisAccount);

                // Boolean cond1 = ThisAccount.TMB_Customer_ID_PE__c == null;
                Boolean cond2 = ThisAccount.Customer_Type__c == 'Individual';
                Boolean cond3 = ThisAccount.ID_Type_PE__c == 'Citizen ID';
                Boolean cond4 = ThisAccount.ID_Number_PE__c != null;
                
                Boolean fag = (cond2 && cond3 && cond4);

                if(fag){
                    submitPass = true;
                }else{
                    ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.submit_f2f_errmsg));
                }
            }
            return submitPass;
        }

        set;
    }
    
    public Account ThisAccount {
        get{
            if(ThisAccount == null){
                if(ThisOpty != null){
                    ThisAccount = [SELECT Id, TMB_Customer_ID_PE__c, ID_Type_PE__c, ID_Number_PE__c, Customer_Type__c FROM Account WHERE Id = :ThisOpty.AccountId LIMIT 1];
                    System.debug('This Account :: ' + ThisAccount);
                }
            }
            return ThisAccount;
        }
        set;
    }

    public Opportunity ThisOpty {
        get{
            if(ThisOpty == null){
                try {
                    ThisOpty = [SELECT Id, RTL_TMB_Customer_ID_PE__c, AccountId, StageName, RecordtypeId, Host_System__c FROM Opportunity WHERE Id = :recID LIMIT 1];
                    System.debug('ThisOpty :: ' + ThisOpty);
                } catch (Exception e) {
                   System.debug(e.getMessage());
                   return null;
                }
            }
            return ThisOpty;
        }
        set;
    }

    public void ValidateEBoarding(){
        System.debug('Opportunity Id : ' + recID);
        System.debug(ThisOpty);

        if(submitPass){
            try {
                Id nonCrProd2 = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(RecordtypeToUpdate).getRecordTypeId();

                ThisOpty.StageName = 'Submitted to e-onBoarding';
                ThisOpty.RecordtypeId = nonCrProd2;
                ThisOpty.Host_System__c = 'F2F';

                update ThisOpty;
            } catch (Exception e) {
                System.debug(e.getMessage());
            }
        }
    }

    public Pagereference optyPage(){
        return new PageReference('/' + recID).setRedirect(true);
    }

    public submitToEOnBoardingButtonController(ApexPages.StandardController ctrl) {
        recID = ApexPages.currentPage().getParameters().get('Id');
    }
}