force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>ประเภทลูกค้าว่าเป็น  บุคคล หรือ บริษัท</description>
    <inlineHelpText>ประเภทลูกค้าว่าเป็น  บุคคล หรือ บริษัท</inlineHelpText>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
                <default>true</default>
                <label>Individual</label>
            </value>
            <value>
                <fullName>Juristic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Number_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Number_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>เลขที่เอกสารสำคัญของลูกค้า</inlineHelpText>
    <label>ID Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Type_PE__c</fullName>
    <description>Identification Type Ex. Citizen ID, BRN ID, Passport ID, Alien ID, Work permit</description>
    <inlineHelpText>ประเภทเอกสารสำคัญของลูกค้า</inlineHelpText>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Customer_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BRN ID</fullName>
            </value>
            <value>
                <fullName>Citizen ID</fullName>
            </value>
            <value>
                <fullName>Passport ID</fullName>
            </value>
            <value>
                <fullName>Work permit ID</fullName>
            </value>
            <value>
                <fullName>Alien ID</fullName>
            </value>
            <value>
                <fullName>Tax ID</fullName>
            </value>
            <value>
                <fullName>Other ID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Host_Product_Mapping__c/Host_Product_Mapping__c.object-meta.xml
<CustomObject>
    <description>Master table to map host products to SF product table</description>
    <label>Host Product Mapping</label>
    <nameField>
        <displayFormat>HP-{0000}</displayFormat>
        <label>Host Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Host Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Host_Product_Mapping__c/fields/Host_Name__c.field-meta.xml
<CustomField>
    <fullName>Host_Name__c</fullName>
    <inlineHelpText>ชื่อระบบขออนุมัติสินเชื่อ</inlineHelpText>
    <label>Host Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SLS</fullName>
            </value>
            <value>
                <fullName>EXCEL</fullName>
            </value>
            <value>
                <fullName>FSR</fullName>
                <isActive>false</isActive>
                <label>FSR</label>
            </value>
            <value>
                <fullName>TPT</fullName>
                <isActive>false</isActive>
                <label>TPT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Host_Product_Mapping__c/fields/Host_Prod_Name_Credit_Facility__c.field-meta.xml
<CustomField>
    <fullName>Host_Prod_Name_Credit_Facility__c</fullName>
    <inlineHelpText>ชื่อ Credit Facility (SLS)</inlineHelpText>
    <label>Host Prod Name/Credit Facility</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Program__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loan - Core WC</fullName>
            </value>
            <value>
                <fullName>Loan - Quick Loan 10%</fullName>
            </value>
            <value>
                <fullName>Loan - Quick Loan 15%</fullName>
            </value>
            <value>
                <fullName>Loan - Land</fullName>
            </value>
            <value>
                <fullName>Loan - Construction</fullName>
            </value>
            <value>
                <fullName>Loan - Machine</fullName>
            </value>
            <value>
                <fullName>OD</fullName>
            </value>
            <value>
                <fullName>L/G Utility</fullName>
            </value>
            <value>
                <fullName>L/G Lending Guarantee</fullName>
            </value>
            <value>
                <fullName>L/G Credit Purchasing Guarantee</fullName>
            </value>
            <value>
                <fullName>L/G Performance Guarantee</fullName>
            </value>
            <value>
                <fullName>L/G Advance Payment Guarantee</fullName>
            </value>
            <value>
                <fullName>L/G Retention Guarantee</fullName>
            </value>
            <value>
                <fullName>L/G Tax/Duty Guarantee</fullName>
            </value>
            <value>
                <fullName>L/G Tender Guarantee/Bid Bond</fullName>
            </value>
            <value>
                <fullName>L/G Other</fullName>
            </value>
            <value>
                <fullName>AVAL</fullName>
            </value>
            <value>
                <fullName>ACCEPTANCE</fullName>
            </value>
            <value>
                <fullName>F/X - FORWARD</fullName>
            </value>
            <value>
                <fullName>L/C Loan one time</fullName>
            </value>
            <value>
                <fullName>Fleet Card</fullName>
            </value>
            <value>
                <fullName>OBOD</fullName>
            </value>
            <value>
                <fullName>Excel Test</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL LOANS</fullName>
            </value>
            <value>
                <fullName>OD for Floating Charge</fullName>
            </value>
            <value>
                <fullName>Loan - General</fullName>
            </value>
            <value>
                <fullName>Loan - Special (GSB)</fullName>
            </value>
            <value>
                <fullName>Top-up for Refinance cost</fullName>
            </value>
            <value>
                <fullName>OD for Growth</fullName>
            </value>
            <value>
                <fullName>UNSECURED LOAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Host_Product_Mapping__c/fields/Host_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Host_Product_Group__c</fullName>
    <inlineHelpText>ชื่อ Product Group (SLS)</inlineHelpText>
    <label>Host Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Host_Name__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TMB SME SmartBiz</fullName>
            </value>
            <value>
                <fullName>F-Cash</fullName>
            </value>
            <value>
                <fullName>NEW IFC</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>Excel Test</fullName>
            </value>
            <value>
                <fullName>OD No Asset</fullName>
            </value>
            <value>
                <fullName>Quick Loan</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Non Product Program</fullName>
                <isActive>false</isActive>
                <label>Non Product Program</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Host_Product_Mapping__c/fields/Product_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Group_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Group ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Host_Product_Mapping__c/fields/Product_Program__c.field-meta.xml
<CustomField>
    <fullName>Product_Program__c</fullName>
    <inlineHelpText>ชื่อ Product Program (SLS)</inlineHelpText>
    <label>Host Product Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Host_Product_Group__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SmartBiz for Construction</fullName>
            </value>
            <value>
                <fullName>OD No Asset</fullName>
            </value>
            <value>
                <fullName>Retention Pre Approve</fullName>
            </value>
            <value>
                <fullName>Retention Non Pre Approve</fullName>
            </value>
            <value>
                <fullName>Quick Loan</fullName>
            </value>
            <value>
                <fullName>NEW IFC</fullName>
            </value>
            <value>
                <fullName>Excel Test</fullName>
            </value>
            <value>
                <fullName>TMB SME SmartBiz</fullName>
            </value>
            <value>
                <fullName>Top Up Bancassurance</fullName>
            </value>
            <value>
                <fullName>F-Cash</fullName>
            </value>
            <value>
                <fullName>ODB</fullName>
            </value>
            <value>
                <fullName>Factoring</fullName>
            </value>
            <value>
                <fullName>SmartBiz E-Commerce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Host_Product_Mapping__c/fields/Salesforce_Product__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>ชื่อ Product บนระบบ Salesforce</inlineHelpText>
    <label>Salesforce Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.FLAG_RTL_Product__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Host Product Mappings</relationshipLabel>
    <relationshipName>Host_Product_Mapping</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Status_Code__c/Status_Code__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Error,Warning message handler</description>
    <label>Status Code</label>
</CustomObject>

force-app/main/default/objects/Status_Code__c/fields/Status_Message__c.field-meta.xml
<CustomField>
    <fullName>Status_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SmartBDMPreviewQuickCAController.cls
public class SmartBDMPreviewQuickCAController {

    public class productItem {
        @AuraEnabled
        public string Index {
            get;
            set;
        }
        @AuraEnabled
        public string oppProdId {
            get;
            set;
        }
        @AuraEnabled
        public OpportunityLineItem oppProd {
            get;
            set;
        }
        @AuraEnabled
        public Host_Product_Mapping__c hostMapTemp {
            get;
            set;
        }
        @AuraEnabled
        public string amount {
            get;
            set;
        }
        @AuraEnabled
        public string productName {
            get;
            set;
        }
        public productItem(string i, string o, OpportunityLineItem ol, Host_Product_Mapping__c h, string a, string p) {
            Index = i;
            oppProdId = o;
            oppProd = ol;
            hostMapTemp = h;
            amount = a;
            productName = p;
        }
    }

    public class wrapProductList {
        @AuraEnabled
        public string programName {
            get;
            set;
        }
        @AuraEnabled
        public List < productItem > programList {
            get;
            set;
        }

    }

    public static Map < String, String > mapProductGroupID {
        get {
            if (mapProductGroupID != null) {
                return mapProductGroupID;
            } else {
                map < String, String > retDat = new map < String, String > ();
                for (Host_Product_Mapping__c hp: [SELECT Host_Product_Group__c, Product_Group_ID__c
                        FROM Host_Product_Mapping__c WHERE Active_Flag__c = true
                    ]) {
                    retDat.put(hp.Host_Product_Group__c, hp.Product_Group_ID__c);
                }
                return retDat;
            }
        }
        set;
    }

    @AuraEnabled
    public static List < wrapProductList > getProductionList(String opptyId) {
        List < productItem > listOpportunityProduct2 = new List < productItem > ();
        List < wrapProductList > listOfProgram = new List < wrapProductList > ();
        Integer indexList2 = 0;
        string productGroup;
        string productGroup2;
        string oldProductGroup;
        String host = Smart_BDM_Constant.HOST_SYSTEM;
        boolean isCanSelectProductGroup;

        isCanSelectProductGroup = true;
        //isHasProductGroup = true;
        oldProductGroup = '';
        //oldHost = '';

        Opportunity oppty = [SELECT Id, AccountId, Account.Name, Account.Customer_Type__c, Name, CAID__c, Host_Product_Group__c, Owner.Name, Owner.Employee_ID__c, Owner.Zone_Code__c, Owner.Region_Code__c
            FROM Opportunity Where Id =: opptyId
        ];

        if (oppty.Host_Product_Group__c != '' && oppty.Host_Product_Group__c != null) {
            productGroup = oppty.Host_Product_Group__c;
            isCanSelectProductGroup = false;
            oldProductGroup = oppty.Host_Product_Group__c;
        }
        if (productGroup2 != null && productGroup2 != '') {
            productGroup = productGroup2;
        }

        for (OpportunityLineItem ol: [SELECT Id, Name, Product2.Name, product2Id, Host_Product_Mapping__c, Host_Product_Mapping__r.Host_Name__c, Host_Product_Mapping__r.Host_Product_Group__c, Host_Product_Mapping__r.Product_Program__c, Host_Product_Mapping__r.Host_Prod_Name_Credit_Facility__c, Host_Product_Mapping__r.Salesforce_Product__c, Host_Product_Mapping__r.Salesforce_Product__r.Name, Quantity, UnitPrice, PricebookEntryId, opportunity.Host_Product_Group__c

                FROM OpportunityLineItem
                Where OpportunityId =: opptyId
            ]) {
            Host_Product_Mapping__c hp = new Host_Product_Mapping__c();
            if (ol.Host_Product_Mapping__c != null) {
                hp.Host_Name__c = ol.Host_Product_Mapping__r.Host_Name__c;
                hp.Host_Product_Group__c = ol.Host_Product_Mapping__r.Host_Product_Group__c;
                hp.Product_Program__c = ol.Host_Product_Mapping__r.Product_Program__c;
                hp.Host_Prod_Name_Credit_Facility__c = ol.Host_Product_Mapping__r.Host_Prod_Name_Credit_Facility__c;
                hp.salesforce_product__r = ol.Host_Product_Mapping__r.Salesforce_Product__r;
            } else {
                hp.Host_Name__c = host;
                hp.Host_Product_Group__c = productGroup;
            }

            string productNameTmp = (string.isNotBlank(ol.Host_Product_Mapping__r.Salesforce_Product__r.name)) ? ol.Host_Product_Mapping__r.Salesforce_Product__r.name : ol.product2.name;
            listOpportunityProduct2.add(new productItem(string.valueof(indexList2), string.valueof(ol.id), ol, hp, string.valueof(ol.unitprice), productNameTmp));
            indexList2++;
        }

        Map < String, List < productItem >> programMap = new Map < String, List < productItem >> ();

        for (productItem pd: listOpportunityProduct2) {
            //System.debug('name:'+pd.hostMapTemp.Product_Program__c);
            if (!programMap.containsKey(pd.hostMapTemp.Product_Program__c)) {
                programMap.put(pd.hostMapTemp.Product_Program__c, new List < productItem > ());
            }
            programMap.get(pd.hostMapTemp.Product_Program__c).add(pd);
        }

        for (String name: programMap.keySet()) {
            wrapProductList program = new wrapProductList();
            program.programName = name;
            program.programList = programMap.get(name);
            listOfProgram.add(program);
        }
        return listOfProgram;
    }

    @AuraEnabled
    public static Opportunity getOppty(String opptyId) {
        Opportunity oppty = [SELECT Id, AccountId, Account.Name, Account.Customer_Type__c, Account.ID_Type_PE__c, Account.ID_Number_PE__c, Name, CAID__c, Host_Product_Group__c, App_Ref_Number__c, Owner.Name, Owner.Employee_ID__c, Owner.Zone_Code__c, Owner.Region_Code__c, Product_Group_ID__c, Host_System__c, Expected_submit_date__c
        FROM Opportunity Where Id =: opptyId
        ];
        return oppty;
    }
    
    @AuraEnabled
    public static String getHost() {
        return Smart_BDM_Constant.HOST_SYSTEM;
    }

    @AuraEnabled
    public static void submitToHost(String opptyId) {
        string errMsg = '';
        try {
            Opportunity oppty = [SELECT Id, AccountId, Account.Name, Account.Customer_Type__c, Name, CAID__c, Host_Product_Group__c, App_Ref_Number__c, Owner.Name, Owner.Employee_ID__c, Owner.Zone_Code__c, Owner.Region_Code__c, Product_Group_ID__c, Host_System__c, Expected_submit_date__c
                FROM Opportunity Where Id =: opptyId
            ];

            System.debug('oppty:'+oppty);

            if (string.isNotBlank(oppty.Host_Product_Group__c) && string.isBlank(oppty.Product_Group_ID__c)) {
                oppty.Product_Group_ID__c = mapProductGroupID.get(oppty.Host_Product_Group__c);
            }

            if (oppty.Host_System__c == 'SLS') {
                              
                SLOSContext.SLOSRequest req = new SLOSContext.SLOSRequest(oppty, null);
                SLOSContext.SLOSRespond resp = SLOSServiceBroker.sendRequest(req);
                
                if (resp.Status == true) {
                    oppty.App_Ref_Number__c = resp.AppRefNo;

                    Id seCreditPproduct2RecordType = Schema.Sobjecttype.Opportunity.getRecordTypeInfosByName().get('SE Credit Product2').getRecordTypeId();
                    oppty.RecordTypeId = seCreditPproduct2RecordType;
                    oppty.StageName = 'Submit to Credit Process';
                    update oppty;
                } else {
                    errMsg = Status_code__c.getValues('8044').status_message__c + '' + resp.ErrorCode + '.Error: ' + resp.Message;
                    throw new AuraHandledException(errMsg);
                }

            } else if (oppty.Host_System__c.toLowerCase().contains('excel')) {
                oppty.RecordTypeId = Schema.Sobjecttype.Opportunity.getRecordTypeInfosByName().get('SE Credit Product2').getRecordTypeId();
                oppty.StageName = 'Submit to Credit Process';
                update oppty;
            }
        } catch (Exception e) {
            if (errMsg != '') {
                System.debug(errMsg);
                throw new AuraHandledException(errMsg);
            } else {
                System.debug(e.getMessage());
                throw new AuraHandledException(e.getMessage());
            }

        }
    }
    @AuraEnabled
    public static string getDeepLink(){
        return Smart_BDM_Constant.DEEP_LINK_TO_KONY_TELL_LANDING;
    }

}