force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>ประเภทลูกค้าว่าเป็น  บุคคล หรือ บริษัท</description>
    <inlineHelpText>ประเภทลูกค้าว่าเป็น  บุคคล หรือ บริษัท</inlineHelpText>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
                <default>true</default>
                <label>Individual</label>
            </value>
            <value>
                <fullName>Juristic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/First_Name_ENG_PE__c.field-meta.xml
<CustomField>
    <fullName>First_Name_ENG_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>First Name EN</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/First_name_PE__c.field-meta.xml
<CustomField>
    <fullName>First_name_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>First Name TH</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Number_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Number_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>เลขที่เอกสารสำคัญของลูกค้า</inlineHelpText>
    <label>ID Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Type_PE__c</fullName>
    <description>Identification Type Ex. Citizen ID, BRN ID, Passport ID, Alien ID, Work permit</description>
    <inlineHelpText>ประเภทเอกสารสำคัญของลูกค้า</inlineHelpText>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Customer_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BRN ID</fullName>
            </value>
            <value>
                <fullName>Citizen ID</fullName>
            </value>
            <value>
                <fullName>Passport ID</fullName>
            </value>
            <value>
                <fullName>Work permit ID</fullName>
            </value>
            <value>
                <fullName>Alien ID</fullName>
            </value>
            <value>
                <fullName>Tax ID</fullName>
            </value>
            <value>
                <fullName>Other ID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IsDisqualified__c.field-meta.xml
<CustomField>
    <fullName>IsDisqualified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsDisqualified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_name_PE__c.field-meta.xml
<CustomField>
    <fullName>Last_name_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Last Name TH</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Name_PE_Eng__c.field-meta.xml
<CustomField>
    <fullName>Last_Name_PE_Eng__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Last Name EN</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mobile_Number_PE__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>Mobile or Office Phone Number must be entered</inlineHelpText>
    <label>Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Remark__c.field-meta.xml
<CustomField>
    <fullName>Remark__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Remark</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/SLL_Group__c.object-meta.xml
<CustomObject>
    <label>SLL Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLL Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SLL_Group__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval - Active</fullName>
            </value>
            <value>
                <fullName>Approved - Active</fullName>
            </value>
            <value>
                <fullName>Rejected - Active</fullName>
            </value>
            <value>
                <fullName>Recalled - Active</fullName>
            </value>
            <value>
                <fullName>Pending Approval - Update</fullName>
            </value>
            <value>
                <fullName>Approved - Update</fullName>
            </value>
            <value>
                <fullName>Rejected - Update</fullName>
            </value>
            <value>
                <fullName>Recalled - Update</fullName>
            </value>
            <value>
                <fullName>Pending Approval - Inactive</fullName>
            </value>
            <value>
                <fullName>Approved - Inactive</fullName>
            </value>
            <value>
                <fullName>Rejected - Inactive</fullName>
            </value>
            <value>
                <fullName>Recalled - Inactive</fullName>
            </value>
            <value>
                <fullName>PAM Approver1 Approved - Active</fullName>
            </value>
            <value>
                <fullName>PAM Approver1 Approved - Update</fullName>
            </value>
            <value>
                <fullName>PAM Approver1 Approved - Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/PAM__c.field-meta.xml
<CustomField>
    <fullName>PAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PAM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>TMB RM Profile,TMB BDM Profile, TMB SE Zone Manager Profile</value>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>SLL_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/Primary_Customer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Existing_Customer, Prospect</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SLL Groups (Primary Customer)</relationshipLabel>
    <relationshipName>SLL_Groups1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/Remark__c.field-meta.xml
<CustomField>
    <fullName>Remark__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Remark</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SLL_Group_Member__c/SLL_Group_Member__c.object-meta.xml
<CustomObject>
    <label>SLL Group Member</label>
    <nameField>
        <displayFormat>SGM-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLL Group Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SLL_Group_Member__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SLL Group Members</relationshipLabel>
    <relationshipName>SLL_Group_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group_Member__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2001700001:เป็นผู้ที่เกี่ยวข้อง (ตามประกาศ Single Lending Limit)</fullName>
            </value>
            <value>
                <fullName>2001700003:มีบุคคลในครอบครัวเกี่ยวข้องอย่างมีนัยสำคัญ (นอกเหนือจากเกณฑ์ Single Lending Limit)</fullName>
            </value>
            <value>
                <fullName>2001700004:การจัดกลุ่มลูกหนี้อื่น ๆ</fullName>
            </value>
            <value>
                <fullName>2001700005:การจัดกลุ่มเพื่อติดตามความเสี่ยงภายใน</fullName>
            </value>
            <value>
                <fullName>2001700006:การจัดกลุ่มลูกหนี้ที่ส่งธนาคารกลางอื่น ๆ</fullName>
            </value>
            <value>
                <fullName>2001700002:มีการถือหุ้นหรือกรรมการไขว้กัน</fullName>
                <isActive>false</isActive>
                <label>2001700002:มีการถือหุ้นหรือกรรมการไขว้กัน</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SLL_Group_Member__c/fields/SLL_Group__c.field-meta.xml
<CustomField>
    <fullName>SLL_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLL Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SLL_Group__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SLL_Group__c</referenceTo>
    <relationshipLabel>SLL Group Members</relationshipLabel>
    <relationshipName>SLL_Group_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RequestToRemoveSLLGroupControllerTest.cls
@isTest
public class RequestToRemoveSLLGroupControllerTest {
    public static final Id PAM_TMB_RM_PROFILE = [SELECT Id FROM Profile WHERE Name = 'TMB RM Profile' LIMIT 1].Id;
    public static final String ERROR_EXISTCUSTOMER_LABEL = System.Label.SLLGroupMessage11;
    public static final String ERROR_NO_PAM_MANAGER_LABEL = System.Label.SLLGroupMessage3;
    public static final String ERROR_EXIST_PENDING_LABEL = System.Label.SLLGroupMessage14;
    public static final Id ExistingRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Existing Customer').getRecordTypeId();

    @TestSetup
    static void makeData(){
        TestUtils.createAppConfig();
        List<User> user = TestUtils.createUsers(4,'UserTest','Test00','Test@gmail.com',false);
        user[0].profileId = PAM_TMB_RM_PROFILE;
        user[3].profileId = PAM_TMB_RM_PROFILE;
        insert user;

        user[0].ManagerId = user[1].Id;
        user[1].ManagerId = user[2].Id;
        update user;

        Account customer = TestUtils.createAccounts(1,'CustomerTest','Individual',false).get(0);
        customer.RecordTypeId = ExistingRecordType;
        insert customer;
        Account customer2 = TestUtils.createAccounts(1,'CustomerTest','Individual',false).get(0);
        insert customer2;

        SLL_Group__c sllGroup = new SLL_Group__c();
        sllGroup.Name = 'SLLGROUP001';
        sllGroup.PAM__c = user[0].Id;
        sllGroup.Approval_Status__c	='Approved - Active';
        sllGroup.Is_Active__c = true;
        sllGroup.Remark__c = 'TestGroup';
        sllGroup.Primary_Customer__c = customer.Id;
        insert sllGroup;

        SLL_Group__c sllGroup2 = new SLL_Group__c();
        sllGroup2.Name = 'SLLGROUP002';
        sllGroup2.PAM__c =user[3].Id;
        sllGroup2.Approval_Status__c = 'Approved - Active';
        sllGroup2.Is_Active__c = true;
        sllGroup2.Remark__c = 'TestGroup2';
        sllGroup2.Primary_Customer__c = customer.Id;
        insert sllGroup2;

        SLL_Group__c sllGroup3 = new SLL_Group__c();
        sllGroup3.Name = 'SLLGROUP003';
        sllGroup3.Approval_Status__c = 'Approved - Active';
        sllGroup3.Is_Active__c = true;
        sllGroup3.Remark__c = 'TestGroup3';
        sllGroup3.Primary_Customer__c = customer.Id;
        insert sllGroup3;

        SLL_Group_Member__c sllGroupMember = new SLL_Group_Member__c();
        sllGroupMember.Customer_Name__c = customer.Id;
        sllGroupMember.SLL_Group__c = sllGroup.Id;
        sllGroupMember.Reason__c = '2001700001:เป็นผู้ที่เกี่ยวข้อง (ตามประกาศ Single Lending Limit)';
        insert sllGroupMember;

        SLL_Group_Member__c sllGroupMember2 = new SLL_Group_Member__c();
        sllGroupMember2.Customer_Name__c = customer.Id;
        sllGroupMember2.SLL_Group__c = sllGroup2.Id;
        sllGroupMember2.Reason__c = '2001700001:เป็นผู้ที่เกี่ยวข้อง (ตามประกาศ Single Lending Limit)';
        insert sllGroupMember2;
        
        SLL_Group_Member__c sllGroupMember3 = new SLL_Group_Member__c();
        sllGroupMember3.Customer_Name__c = customer.Id;
        sllGroupMember3.SLL_Group__c = sllGroup3.Id;
        sllGroupMember3.Reason__c = '2001700001:เป็นผู้ที่เกี่ยวข้อง (ตามประกาศ Single Lending Limit)';
        insert sllGroupMember3;
    }
    @isTest
    public static void TestGetGroupRecord(){
        RequestToRemoveSLLGroupController.wrapGroupMember case_success = new RequestToRemoveSLLGroupController.wrapGroupMember();
        RequestToRemoveSLLGroupController.wrapGroupMember case_fail_no_manager = new RequestToRemoveSLLGroupController.wrapGroupMember();
        RequestToRemoveSLLGroupController.wrapGroupMember case_fail_no_pam = new RequestToRemoveSLLGroupController.wrapGroupMember();

        List<SLL_Group_Member__c> sllGroupMember = [SELECT Id,SLL_Group__c,SLL_Group__r.PAM__c FROM SLL_Group_Member__c WHERE SLL_Group__r.PAM__c != null LIMIT 2];
        
        case_success = RequestToRemoveSLLGroupController.getGroupMemRec(sllGroupMember[0].Id);//Sucess
        System.assertEquals(case_success.errMsg, null);

        case_fail_no_manager = RequestToRemoveSLLGroupController.getGroupMemRec(sllGroupMember[1].Id);//Failed NO manager
        System.assertEquals(case_fail_no_manager.errMsg, ERROR_NO_PAM_MANAGER_LABEL);

        SLL_Group_Member__c sllGroupMember2 = [SELECT Id,SLL_Group__c,SLL_Group__r.PAM__c FROM SLL_Group_Member__c WHERE SLL_Group__r.PAM__c = null LIMIT 1];
        case_fail_no_pam = RequestToRemoveSLLGroupController.getGroupMemRec(sllGroupMember2.Id);//Fail No PAM
        System.assertEquals(case_fail_no_pam.errMsg, 'This Group Member don\'t have PAM');
    }
    @isTest
    public static void TestcreateRecordGroupHistory(){
        String reason = '2001700001:เป็นผู้ที่เกี่ยวข้อง (ตามประกาศ Single Lending Limit)';

        SLL_Group_Member__c sllGroupMember = [SELECT Id,SLL_Group__c,SLL_Group__r.PAM__c,SLL_Group__r.PAM__r.ManagerId,Customer_Name__c FROM SLL_Group_Member__c WHERE SLL_Group__r.PAM__c != null AND SLL_Group__r.PAM__r.profileId =: PAM_TMB_RM_PROFILE LIMIT 1];
        Id approver1 = sllGroupMember.SLL_Group__r.PAM__r.ManagerId;
        // Id approver2 = sllGroupMember.SLL_Group__r.PAM__r.Manager.ManagerId;
        
        try {
            RequestToRemoveSLLGroupController.createRecord(sllGroupMember.Id,sllGroupMember.SLL_Group__c,sllGroupMember.Customer_Name__c,reason,null);
        } catch (Exception e) {
            System.debug(e.getMessage());
            System.assertEquals(e.getMessage(), 'Script-thrown exception');
        }

        String Status_success = RequestToRemoveSLLGroupController.createRecord(sllGroupMember.Id,sllGroupMember.SLL_Group__c,sllGroupMember.Customer_Name__c,reason,approver1);//Success
        System.assertEquals(Status_success, 'SUCCESS');

        String Status_Fail_Dup = RequestToRemoveSLLGroupController.createRecord(sllGroupMember.Id,sllGroupMember.SLL_Group__c,sllGroupMember.Customer_Name__c,reason,approver1);//Create Duplicate Record
        System.assertEquals(Status_Fail_Dup, ERROR_EXIST_PENDING_LABEL);

        Account Acct = new Account(); 
        Acct.Name = 'Test Account Test';
        Acct.Phone ='050111222';
        Acct.Mobile_Number_PE__c  = '0801112233';
        Acct.ID_Type_PE__c  = 'Citizen ID';
        Acct.ID_Number_PE__c  = '1510100181965';
        
        Acct.Customer_Type__c = 'Individual';
        Acct.First_name_PE__c = 'TestMock3';
        Acct.First_Name_ENG_PE__c = 'TestMock3';
        Acct.Last_name_PE__c = 'TestMock';
        Acct.Last_Name_PE_Eng__c  = 'TestMock';
        Acct.Rating = 'Hot';
        Acct.IsDisqualified__c = false;
        String Status_Fail_No_Group = RequestToRemoveSLLGroupController.createRecord(sllGroupMember.Id,sllGroupMember.SLL_Group__c,Acct.Id,reason,approver1);//No Group Member
        System.assertEquals(Status_Fail_No_Group, 'No customer in this Group Member to remove.');

    }
}