force-app/main/default/objects/Account/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Group Profile data</description>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mobile_Number_PE__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>Mobile or Office Phone Number must be entered</inlineHelpText>
    <label>Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/AcctPlanActionPlan__c/AcctPlanActionPlan__c.object-meta.xml
<CustomObject>
    <label>Account Plan Action Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Plan Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan Action Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanActionPlan__c/fields/AcctPlanWalletByDomain__c.field-meta.xml
<CustomField>
    <fullName>AcctPlanWalletByDomain__c</fullName>
    <label>AccountPlanWalletByDomain</label>
    <referenceTo>AcctPlanWalletByDomain__c</referenceTo>
    <relationshipLabel>Account Plan Action Plan</relationshipLabel>
    <relationshipName>Account_Plan_Action_Plan</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctPlanActionPlan__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <description>Objective</description>
    <inlineHelpText>Objective</inlineHelpText>
    <label>Objective</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Maintain</fullName>
            </value>
            <value>
                <fullName>Increase Utilization</fullName>
            </value>
            <value>
                <fullName>Cross sell New to products</fullName>
            </value>
            <value>
                <fullName>Acquire New customers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctPlanActionPlan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Objective__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pre Board</fullName>
            </value>
            <value>
                <fullName>On Board</fullName>
            </value>
            <value>
                <fullName>Post Board</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctPlanActionPlan__c/fields/WinningPropostion__c.field-meta.xml
<CustomField>
    <fullName>WinningPropostion__c</fullName>
    <description>Winning Proposition</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Winning Proposition</inlineHelpText>
    <label>WinningPropostion</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctPlanActivity__c/AcctPlanActivity__c.object-meta.xml
<CustomObject>
    <label>Account Plan Activity</label>
    <nameField>
        <displayFormat>Act-{000000}</displayFormat>
        <label>Account Plan Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Activity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanActivity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plan Activity</relationshipLabel>
    <relationshipName>Account_Plan_Activity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctPlanActivity__c/fields/AccountPlanActionPlanID__c.field-meta.xml
<CustomField>
    <fullName>AccountPlanActionPlanID__c</fullName>
    <label>AccountPlanActionPlan</label>
    <referenceTo>AcctPlanActionPlan__c</referenceTo>
    <relationshipLabel>Account Plan Activity</relationshipLabel>
    <relationshipName>Account_Plan_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctPlanActivity__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <description>Group</description>
    <inlineHelpText>Group</inlineHelpText>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Group 1 Relationship</fullName>
            </value>
            <value>
                <fullName>Group 2 Information update to customer</fullName>
            </value>
            <value>
                <fullName>Group 3 Collect information</fullName>
            </value>
            <value>
                <fullName>Group 4 Credit Preparation</fullName>
            </value>
            <value>
                <fullName>Group 5 Pitching Doc preparation and presentation</fullName>
            </value>
            <value>
                <fullName>Group 6 System design</fullName>
            </value>
            <value>
                <fullName>Group 7 Others</fullName>
            </value>
            <value>
                <fullName>Group 3 First transaction handholding</fullName>
            </value>
            <value>
                <fullName>Group 3 Solve customers problem</fullName>
            </value>
            <value>
                <fullName>Group 4 Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctPlanActivity__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <label>Objective</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Maintain</fullName>
            </value>
            <value>
                <fullName>Increase Utilization</fullName>
            </value>
            <value>
                <fullName>Cross sell New to products</fullName>
            </value>
            <value>
                <fullName>Acquire New customers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctPlanActivity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Objective__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pre Board</fullName>
            </value>
            <value>
                <fullName>On Board</fullName>
            </value>
            <value>
                <fullName>Post Board</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctPlanCompanyProfile__c/AcctPlanCompanyProfile__c.object-meta.xml
<CustomObject>
    <description>Account Plan Company Profile</description>
    <label>Account Plan Company Profile</label>
    <nameField>
        <displayFormat>Com-{0000000}</displayFormat>
        <label>AcctPlanCompanyProfile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Company Profile</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanCompanyProfile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Account</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>notEqual</operation>
            <value>Disqualified Prospect</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plan Company Profile</relationshipLabel>
    <relationshipName>Account_Plan_Company_Profile</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctPlanCompanyProfile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Account plan status of company</description>
    <inlineHelpText>Status of the Account Plan (e.g. Open, Waitng for Approval, Approved, etc.)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Edited</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctPlanStakeholder__c/AcctPlanStakeholder__c.object-meta.xml
<CustomObject>
    <label>Account Plan Stakeholder</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Account Plan Stakeholder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Stakeholder</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanStakeholder__c/fields/AcctPlanActivity__c.field-meta.xml
<CustomField>
    <fullName>AcctPlanActivity__c</fullName>
    <label>AcctPlanActivity</label>
    <referenceTo>AcctPlanActivity__c</referenceTo>
    <relationshipLabel>Account Plan Stakeholder</relationshipLabel>
    <relationshipName>Account_Plan_Stakeholder</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctPlanWallet__c/AcctPlanWallet__c.object-meta.xml
<CustomObject>
    <label>Account Plan Wallet</label>
    <nameField>
        <displayFormat>Wallet-{000000}</displayFormat>
        <label>Account Plan Wallet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Wallet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanWallet__c/fields/AcctPlanCompanyProfile__c.field-meta.xml
<CustomField>
    <fullName>AcctPlanCompanyProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Plan Company Profile of Wallet</description>
    <label>Account Plan Company Profile</label>
    <referenceTo>AcctPlanCompanyProfile__c</referenceTo>
    <relationshipLabel>Account Plan Wallet</relationshipLabel>
    <relationshipName>Account_Plan_Wallet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctPlanWalletByDomain__c/AcctPlanWalletByDomain__c.object-meta.xml
<CustomObject>
    <label>Account Plan Wallet By Domain</label>
    <nameField>
        <displayFormat>WD-{000000}</displayFormat>
        <label>Account Plan Wallet By Domain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Wallet By Domain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanWalletByDomain__c/fields/AcctPlanWallet__c.field-meta.xml
<CustomField>
    <fullName>AcctPlanWallet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan Wallet</label>
    <referenceTo>AcctPlanWallet__c</referenceTo>
    <relationshipLabel>Account Plan Wallet By Domain</relationshipLabel>
    <relationshipName>Account_Plan_Wallet_By_Domain</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctPlanWalletByDomain__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Priority</description>
    <inlineHelpText>Priority</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctPlanWalletByDomain__c/fields/SubDomain__c.field-meta.xml
<CustomField>
    <fullName>SubDomain__c</fullName>
    <description>Sub Domain</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Sub Domain</inlineHelpText>
    <label>SubDomain</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctPlanWalletByDomain__c/fields/TypeOfNI__c.field-meta.xml
<CustomField>
    <fullName>TypeOfNI__c</fullName>
    <description>Type of NI</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Type of NI</inlineHelpText>
    <label>TypeOfNI</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctPlanWalletByDomain__c/fields/WalletDomain__c.field-meta.xml
<CustomField>
    <fullName>WalletDomain__c</fullName>
    <description>Domain</description>
    <inlineHelpText>Domain</inlineHelpText>
    <label>WalletDomain</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Position</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EdittableStakeHolderModelTest.cls
@IsTest
public class EdittableStakeHolderModelTest{
    static{
        TestUtils.createAppConfig();
        TestUtils.createStatusCode();        
        TestUtils.createIdType();
        TestUtils.createTriggerMsg();
        TestUtils.createObjUserPermission();
    } 
       public static testmethod void EdittableStakeHolder(){
              //Create Account
        Account  testAccount1 = new Account();
        testAccount1.Name='Test AccountPlan Step5' ;
        testAccount1.Phone ='050111222';
        testAccount1.Mobile_Number_PE__c  = '0801112233';   
        insert testAccount1;
        
        //Create Contact
        Contact cont1 = new Contact();
        cont1.FirstName='AccountPlan';
        cont1.LastName='Step5';
        cont1.Position__c = 'Manager';
        cont1.Accountid= testAccount1.id;
        insert cont1;
        
        //Create Account Plan
        AcctPlanCompanyProfile__c Company1 = new AcctPlanCompanyProfile__c();
        Company1.Account__c=testAccount1.id;
        //Company1.Name='AccountPlan Step5';
        insert Company1;
        
        AcctPlanWallet__c Wallet1 = new AcctPlanWallet__c();
        Wallet1.AcctPlanCompanyProfile__c = Company1.id;
        insert Wallet1;
        
        AcctPlanWalletByDomain__c WalletDomain1 = new AcctPlanWalletByDomain__c();
        WalletDomain1.AcctPlanWallet__c = Wallet1.id;
        WalletDomain1.WalletDomain__c = 1;
        WalletDomain1.Priority__c ='High';
        WalletDomain1.SubDomain__c ='Liquidity Management';
        WalletDomain1.TypeOfNI__c = 'NIIC';
        insert WalletDomain1;
        
        
        AcctPlanActionPlan__c acctplan1 = new AcctPlanActionPlan__c();
        acctplan1.AcctPlanWalletByDomain__c = WalletDomain1.id;
        acctplan1.Objective__c = 'Acquire New customers';
        acctplan1.Status__c = 'Post Board';
        acctplan1.WinningPropostion__c = 'Test Class';
        insert acctplan1;   
        
        AcctPlanActivity__c activity1 = new AcctPlanActivity__c();
        activity1.AccountPlanActionPlanID__c = acctplan1.id;
        activity1.Account__c= testAccount1.id;
        activity1.Objective__c = 'Acquire New customers';
        activity1.Status__c = 'Post Board';
        activity1.Group__c = 'Group 1 Relationship';
        activity1.Activities__c = 'Work on negative relationship';
        activity1.Date__c = System.Today();
        activity1.CustomerCounterparties__c = cont1.id;
        insert activity1;
        
        Id select1user = [select id from user limit 1].Id;
        /*AcctPlanStakeholder__c stake1 = new AcctPlanStakeholder__c(AcctPlanActivity__c=activity1.id, User__c=select1user); 
        insert Stake1; */
        
        PageReference pageRef1 = Page.EdittableStakeHolder;
        pageRef1.getParameters().put('ActivityId', String.valueOf(activity1.id));
        Test.setCurrentPage(pageRef1);
        
        AcctPlanStakeholder__c  act = new AcctPlanStakeholder__c (AcctPlanActivity__c=activity1.id);
        ApexPages.StandardController sc1 = new ApexPages.StandardController(act);
        EdittableStakeHolderModel ActCntrl1= new EdittableStakeHolderModel(sc1);
        //Boolean isSelect = ActCntrl1.isSelected;
        ActCntrl1.initChildRecord();
        List<AcctPlanStakeholder__c> act1 = ActCntrl1.getChildren();
        for(AcctPlanStakeholder__c act11: act1 ){
        act11.user__c=select1user;
        }
        ActCntrl1.dosave();
        }
}