force-app/main/default/objects/Account/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Group Profile data</description>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Plan_Company_Top_5__c/Account_Plan_Company_Top_5__c.object-meta.xml
<CustomObject>
    <label>Account Plan Company Top 5</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Plan Company Top 5 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan Company Top 5s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Plan_Fiscal_Year__c/Account_Plan_Fiscal_Year__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Account Plan Fiscal Year</label>
</CustomObject>

force-app/main/default/objects/AcctPlan_Questionnaire_Template__c/AcctPlan_Questionnaire_Template__c.object-meta.xml
<CustomObject>
    <label>AcctPlan Questionnaire Template</label>
    <nameField>
        <displayFormat>QT-{000000}</displayFormat>
        <label>AcctPlan Questionnaire Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctPlan Questionnaire Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanCompanyPort__c/AcctPlanCompanyPort__c.object-meta.xml
<CustomObject>
    <label>Account Plan Company Port</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>AcctPlanCompanyPort Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Company Ports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanCompanyPort__c/fields/AcctPlanGroupPort__c.field-meta.xml
<CustomField>
    <fullName>AcctPlanGroupPort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AcctPlanGroupPort</label>
    <referenceTo>AcctPlanGroupPort__c</referenceTo>
    <relationshipName>AcctPlanCompanyPorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctPlanCompanyProfile__c/AcctPlanCompanyProfile__c.object-meta.xml
<CustomObject>
    <description>Account Plan Company Profile</description>
    <label>Account Plan Company Profile</label>
    <nameField>
        <displayFormat>Com-{0000000}</displayFormat>
        <label>AcctPlanCompanyProfile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Company Profile</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanCompanyProfile__c/fields/AcctPlanGroup__c.field-meta.xml
<CustomField>
    <fullName>AcctPlanGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Plan Group</description>
    <label>Account Plan Group</label>
    <referenceTo>AcctPlanGroupProfile__c</referenceTo>
    <relationshipLabel>Account Plan Company Profile</relationshipLabel>
    <relationshipName>Account_Plan_Company_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctPlanContribution__c/AcctPlanContribution__c.object-meta.xml
<CustomObject>
    <description>Account Plan Contribution</description>
    <label>Account Plan Contribution</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>AcctPlanContribution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan Contribution</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanExistingLongTermLoan__c/AcctPlanExistingLongTermLoan__c.object-meta.xml
<CustomObject>
    <label>Account Plan Existing Long Term Loan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Plan Existing Long Term Loan Nam</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan Existing Long Term Loan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanExistingLongTermLoan__c/fields/AcctPlanWallet__c.field-meta.xml
<CustomField>
    <fullName>AcctPlanWallet__c</fullName>
    <label>Account Plan Wallet</label>
    <referenceTo>AcctPlanWallet__c</referenceTo>
    <relationshipLabel>Account Plan Existing Long Term Loan</relationshipLabel>
    <relationshipName>Account_Plan_Existing_Long_Term_Loan</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctPlanGroupPort__c/AcctPlanGroupPort__c.object-meta.xml
<CustomObject>
    <label>Account Plan Group Port</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>AcctPlanGroupPort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AcctPlanGroupPorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanGroupPort__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipName>AcctPlanGroupPorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctPlanGroupProfile__c/AcctPlanGroupProfile__c.object-meta.xml
<CustomObject>
    <description>Account Plan Group Profile</description>
    <label>Account Plan Group Profile</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>AcctPlan Group Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan Group Profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanGroupProfile__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Group Master data</description>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Account Plan Group Profile</relationshipLabel>
    <relationshipName>AcctPlanGroup</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctPlanPortfolio__c/AcctPlanPortfolio__c.object-meta.xml
<CustomObject>
    <label>Account Plan Portfolio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>AcctPlanPortfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio Management</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanProdStrategy__c/AcctPlanProdStrategy__c.object-meta.xml
<CustomObject>
    <label>Account Plan Product Strategy</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Plan Product Strategy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan Product Strategy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanProdStrategy__c/fields/AcctPlanWallet__c.field-meta.xml
<CustomField>
    <fullName>AcctPlanWallet__c</fullName>
    <label>Account Plan Wallet</label>
    <referenceTo>AcctPlanWallet__c</referenceTo>
    <relationshipLabel>Account Plan Product Strategy</relationshipLabel>
    <relationshipName>Account_Plan_Product_Strategy</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctPlanQuestionnaire__c/AcctPlanQuestionnaire__c.object-meta.xml
<CustomObject>
    <label>Account Plan Questionnaire</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Account Plan Questionnaire Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Questionnaire</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanQuestionnaire__c/fields/AcctPlanWallet__c.field-meta.xml
<CustomField>
    <fullName>AcctPlanWallet__c</fullName>
    <label>Account Plan Wallet</label>
    <referenceTo>AcctPlanWallet__c</referenceTo>
    <relationshipLabel>Account Plan Questionnaire</relationshipLabel>
    <relationshipName>Account_Plan_Questionnaire</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctPlanStandardFee__c/AcctPlanStandardFee__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า Standard Fee step 3 Domain I</description>
    <label>Account Plan Standard Fee</label>
</CustomObject>

force-app/main/default/objects/AcctPlanSupplierOrBuyer__c/AcctPlanSupplierOrBuyer__c.object-meta.xml
<CustomObject>
    <label>Account Plan Supplier Or Buyer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>AcctPlanSupplierOrBuyer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan Supplier Or Buyer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanWallet__c/AcctPlanWallet__c.object-meta.xml
<CustomObject>
    <label>Account Plan Wallet</label>
    <nameField>
        <displayFormat>Wallet-{000000}</displayFormat>
        <label>Account Plan Wallet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Wallet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanWallet__c/fields/AcctPlanCompanyProfile__c.field-meta.xml
<CustomField>
    <fullName>AcctPlanCompanyProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Plan Company Profile of Wallet</description>
    <label>Account Plan Company Profile</label>
    <referenceTo>AcctPlanCompanyProfile__c</referenceTo>
    <relationshipLabel>Account Plan Wallet</relationshipLabel>
    <relationshipName>Account_Plan_Wallet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctPlanWalletCreditFacility__c/AcctPlanWalletCreditFacility__c.object-meta.xml
<CustomObject>
    <label>Account Plan Wallet Credit Facility</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Plan Wallet Credit Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan Wallet Credit Facility</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanWalletCreditFacility__c/fields/AcctPlanWallet__c.field-meta.xml
<CustomField>
    <fullName>AcctPlanWallet__c</fullName>
    <label>Account Plan Wallet</label>
    <referenceTo>AcctPlanWallet__c</referenceTo>
    <relationshipLabel>Account Plan Wallet Credit Facility</relationshipLabel>
    <relationshipName>Account_Plan_Wallet_Credit_Facility</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <description>Group master data</description>
    <label>Group Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>Target</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Target__c/fields/group__c.field-meta.xml
<CustomField>
    <fullName>group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sale volume</fullName>
            </value>
            <value>
                <fullName>Utilization</fullName>
            </value>
            <value>
                <fullName>NI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountPlanUtilitiesTest.cls
@isTest
global class AccountPlanUtilitiesTest {
    static{
        TestUtils.createAppConfig();
        TestUtils.createStatusCode(); 
        TestUtils.createDisqualifiedReason(); 
        TestUtils.CreateAddress();
        AccountPlanTestUtilities.getAcctPlanMode();
        AccountPlanWalletTestUtilities.createStandardFee();
        AccountPlanWalletTestUtilities.createBanks();
        AccountPlanWalletTestUtilities.createCurrencies();
         List<sObject> ls = 
            Test.loadData(AcctPlan_Questionnaire_Template__c.sObjectType /*API Name*/, 'AcctPlanQuestionnaireTemplate' /*Static Resource Name*/);
   
         }
    
    static testmethod void AccountPlanUtilitiesTest(){
      
         User SalesOwner = AccountPlanTestUtilities.createUsers(1, 'RM', 'PortfolioMngTest', 'portfoliomng@tmbbank.com', AccountPlanTestUtilities.TMB_RM_PROFILE_ID,false, true).get(0);
        
          List<Account> AccountList = AccountPlanTestUtilities.createAccounts(5, 'InitiateTest', 'Individual', SalesOwner.id, true, true);
        Group__c mastergroup = AccountPlanTestUtilities.createGroupMaster(1,'Initiatetest', false, true).get(0);
        for(account acct  : AccountList){
            acct.Group__c =mastergroup.id;
        }
        update AccountList;
        AccountPlanTestUtilities.createAccounts(1, 'InitiateNonGroupTest', 'Individual', SalesOwner.id, true, true);
        List<Target__c> TaragetList = AccountPlanTestUtilities.createTargetNI(5,  SalesOwner.id, true);
       
       List<Account> acctForCompanyProfile = new List<Account>();
        acctForCompanyProfile.add(AccountList.get(0));
        system.runAs(SalesOwner){
        List<AcctPlanCompanyProfile__c> comprofileList = AccountPlanTestUtilities.createCompanyProfileByAccount(acctForCompanyProfile, true);
         AcctPlanCompanyProfile__c comprofile = comprofileList.get(0);
             List<group__c> mgroupList = new List <group__c>();
        mgroupList.add(mastergroup);
            AcctPlanGroupProfile__c groupprofile = AccountPlanTestUtilities.createGroupProfilebyGroup(mgroupList,true).get(0);
         comprofile.AcctPlanGroup__c = groupprofile.id;
         update comprofile;
        AcctPlanPortfolio__c portfolio = AccountPlanTestUtilities.createAccountPlanPortfolio(SalesOwner.id, '2014', 10000000, true);
        AcctPlanWallet__c AcctPlanwallet = AccountPlanWalletTestUtilities.createAccountPlanWallet(comprofile.id, true);
        List<AcctPlanContribution__c> contributionlist = AccountPlanTestUtilities.createRenevueContribution(3,null, comprofile.id);
        
        AccountPlanWalletTestUtilities.createWalletCurrency(AcctPlanwallet.id);
        AccountPlanWalletTestUtilities.createQuestionnaireTemplate();
        AccountPlanWalletTestUtilities.createWalletDomainITables(AcctPlanwallet.id);
            AcctPlanPortfolio__c newPort =AccountPlanUtilities.portfolio;
            List <AcctPlanQuestionnaire__c > QuestionnaireList =AccountPlanUtilities.QuestionnaireList;
            List<Account> newAcctList =AccountPlanUtilities.AccountList;
            List<AcctPlanCompanyProfile__c> comlist =AccountPlanUtilities.companyProfileList;
            List <AcctPlanGroupProfile__c>  groupProfileList = AccountPlanUtilities.groupProfileList;
            List <AcctPlanProdStrategy__c>  AcctPlanProdStrategyList = AccountPlanUtilities.AcctPlanProdStrategyList;
            String GroupProfileID = AccountPlanUtilities.GroupProfileID;
            String  CompanyProfileID = AccountPlanUtilities.CompanyProfileID;
            Boolean isSystemAdmin = AccountPlanUtilities.isSystemAdmin;
            boolean ISHASPERMISSION = AccountPlanUtilities.ISHASPERMISSION;
            boolean IsAccountTeamReadWrite = AccountPlanUtilities.IsAccountTeamReadWrite;
            AccountPlanUtilities.QueryPortfolioByID(portfolio.id);
            AccountPlanUtilities.QueryGroupProfileByID(mastergroup.id);
            AccountPlanUtilities.QueryCompanyProfileByID(comprofile.id);
            AccountPlanUtilities.QueryCompanyProfileByGroupID(mastergroup.id);
            AccountPlanUtilities.QueryAccountByOwnerID(SalesOwner.id);
            //new query
            AccountPlanUtilities.QueryAccountByOwnerIDLimit(SalesOwner.id);
            AccountPlanUtilities.QueryAccountByAcctID(AccountList.get(0).id);
            AccountPlanUtilities.QueryAccountByGroupID(mastergroup.id);
            //new query
            AccountPlanUtilities.QueryAccountByGroupIDLimit(mastergroup.id);
            AccountPlanUtilities.QueryTargetNI12monthsbyOwnerID(SalesOwner.id);
            AccountPlanUtilities.QueryTargetNIbyOwnerIDandYear(SalesOwner.id,2015);
            AccountPlanUtilities.QueryContributionByGroupProfileID(groupprofile.id);
            AccountPlanUtilities.QueryProductStrategyByCompanyProfileID(comprofile.id);
            AccountPlanUtilities.QueryProductStrategyByGroupProfileID(groupprofile.id);
            AccountPlanUtilities.QueryAcctPlanCompanyProfileByID(comprofile.id);
            //new query
            AccountPlanUtilities.QueryAcctPlanCompanyProfileByIDLimit(comprofile.id);
            AccountPlanUtilities.QueryQuestionnaireByWalletID(AcctPlanwallet.id);
            AccountPlanUtilities.QueryAccountByCompanyProfile(comprofile.id);
            AccountPlanUtilities.QueryCompanyPortbyPortID(portfolio.id);
            //new query
            AccountPlanUtilities.QueryCompanyPortbyPortIDLimit(portfolio.id);
            AccountPlanUtilities.QueryCompanyPortbyPortIDFlag(portfolio.id);
            AccountPlanUtilities.QueryCompanyPortbyPortIDTarget(portfolio.id);
            AccountPlanUtilities.QueryCompanyPortbyPortIDGroup(portfolio.id);
            
            List<Account_Plan_Fiscal_Year__c> getFiscalYear = AccountPlanTestUtilities.getFiscalYear;
            List<AcctPlanGroupPort__c> createGroupPortbyGroupMaster = AccountPlanTestUtilities.createGroupPortbyGroupMaster(mgroupList,portfolio,true);
            List<AcctPlanCompanyPort__c> createCompanyPortByAccount = AccountPlanTestUtilities.createCompanyPortByAccount(AccountList,portfolio,true);
            List<AcctPlanSupplierOrBuyer__c> CreateSupplierOrBuyer = AccountPlanTestUtilities.CreateSupplierOrBuyer(3,comprofile.id);
            List<Account_Plan_Company_Top_5__c> CreateTop5 = AccountPlanTestUtilities.CreateTop5(3,comprofile.id);
            
            }
        
        
        
     
        
    
    }
    
    static testmethod void AccountPlanWalletUtilitiesTest(){
      
         User SalesOwner = AccountPlanTestUtilities.createUsers(1, 'RM', 'PortfolioMngTest', 'portfoliomng@tmbbank.com', AccountPlanTestUtilities.TMB_RM_PROFILE_ID,false, true).get(0);
        
          List<Account> AccountList = AccountPlanTestUtilities.createAccounts(5, 'InitiateTest', 'Individual', SalesOwner.id, true, true);
        Group__c mastergroup = AccountPlanTestUtilities.createGroupMaster(1,'Initiatetest', false, true).get(0);
        for(account acct  : AccountList){
            acct.Group__c =mastergroup.id;
        }
        update AccountList;
        AccountPlanTestUtilities.createAccounts(1, 'InitiateNonGroupTest', 'Individual', SalesOwner.id, true, true);
        List<Target__c> TaragetList = AccountPlanTestUtilities.createTargetNI(5,  SalesOwner.id, true);
       
       List<Account> acctForCompanyProfile = new List<Account>();
        acctForCompanyProfile.add(AccountList.get(0));
        system.runAs(SalesOwner){
        List<AcctPlanCompanyProfile__c> comprofileList = AccountPlanTestUtilities.createCompanyProfileByAccount(acctForCompanyProfile, true);
         AcctPlanCompanyProfile__c comprofile = comprofileList.get(0);
             List<group__c> mgroupList = new List <group__c>();
        mgroupList.add(mastergroup);
            AcctPlanGroupProfile__c groupprofile = AccountPlanTestUtilities.createGroupProfilebyGroup(mgroupList,true).get(0);
         comprofile.AcctPlanGroup__c = groupprofile.id;
         update comprofile;
        AcctPlanPortfolio__c portfolio = AccountPlanTestUtilities.createAccountPlanPortfolio(SalesOwner.id, '2014', 10000000, true);
        AcctPlanWallet__c AcctPlanwallet = AccountPlanWalletTestUtilities.createAccountPlanWallet(comprofile.id, true);
        List<AcctPlanContribution__c> contributionlist = AccountPlanTestUtilities.createRenevueContribution(3,null, comprofile.id);
        
        AccountPlanWalletTestUtilities.createWalletCurrency(AcctPlanwallet.id);
        AccountPlanWalletTestUtilities.createQuestionnaireTemplate();
        AccountPlanWalletTestUtilities.createWalletDomainITables(AcctPlanwallet.id);
            
             List<AcctPlanWalletCreditFacility__c> creditlist = AccountPlanWalletTestUtilities.CreateCreditFacility(AcctPlanwallet.id);
        List<AcctPlanExistingLongTermLoan__c> longtermlist = AccountPlanWalletTestUtilities.CreateLongTermLoan(AcctPlanwallet.id);    
       
        AcctPlanPortfolio__c newPort =AccountPlanUtilities.portfolio;
        List<AcctPlanWallet__c> walletList = AccountPlanWalletUtilities.walletList;
        List<AcctPlan_Questionnaire_Template__c> questionTemplate1= AccountPlanWalletUtilities.questionTemplate;
        List<AcctPlan_Questionnaire_Template__c> questionTemplate2 =AccountPlanWalletUtilities.queryQuestionnaireTemplate('Domain I');
         List<AcctPlanStandardFee__c> stfList = AccountPlanWalletTestUtilities.stdFeeList;
         AccountPlanWalletTestUtilities.createQuestionniare(AcctPlanwallet.id);
            
            
            
            }
        
        
        
     
        
    
    }
    
    
}