force-app/main/default/objects/Account/fields/ID_Number_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Number_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>เลขที่เอกสารสำคัญของลูกค้า</inlineHelpText>
    <label>ID Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Type_PE__c</fullName>
    <description>Identification Type Ex. Citizen ID, BRN ID, Passport ID, Alien ID, Work permit</description>
    <inlineHelpText>ประเภทเอกสารสำคัญของลูกค้า</inlineHelpText>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Customer_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BRN ID</fullName>
            </value>
            <value>
                <fullName>Citizen ID</fullName>
            </value>
            <value>
                <fullName>Passport ID</fullName>
            </value>
            <value>
                <fullName>Work permit ID</fullName>
            </value>
            <value>
                <fullName>Alien ID</fullName>
            </value>
            <value>
                <fullName>Tax ID</fullName>
            </value>
            <value>
                <fullName>Other ID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Using for RMC allows to create opportunity on other&apos;s existing customer.</description>
    <label>Create Opportunity Privilege</label>
</CustomObject>

force-app/main/default/objects/Case/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Appraisal_Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>กระบี่</fullName>
            </value>
            <value>
                <fullName>กรุงเทพมหานคร</fullName>
            </value>
            <value>
                <fullName>กาญจนบุรี</fullName>
            </value>
            <value>
                <fullName>กาฬสินธุ์</fullName>
            </value>
            <value>
                <fullName>กำแพงเพชร</fullName>
            </value>
            <value>
                <fullName>ขอนแก่น</fullName>
            </value>
            <value>
                <fullName>จันทบุรี</fullName>
            </value>
            <value>
                <fullName>ฉะเชิงเทรา</fullName>
            </value>
            <value>
                <fullName>ชลบุรี</fullName>
            </value>
            <value>
                <fullName>ชัยนาท</fullName>
            </value>
            <value>
                <fullName>ชัยภูมิ</fullName>
            </value>
            <value>
                <fullName>ชุมพร</fullName>
            </value>
            <value>
                <fullName>ตรัง</fullName>
            </value>
            <value>
                <fullName>ตราด</fullName>
            </value>
            <value>
                <fullName>ตาก</fullName>
            </value>
            <value>
                <fullName>นครนายก</fullName>
            </value>
            <value>
                <fullName>นครปฐม</fullName>
            </value>
            <value>
                <fullName>นครพนม</fullName>
            </value>
            <value>
                <fullName>นครราชสีมา</fullName>
            </value>
            <value>
                <fullName>นครศรีธรรมราช</fullName>
            </value>
            <value>
                <fullName>นครสวรรค์</fullName>
            </value>
            <value>
                <fullName>นนทบุรี</fullName>
            </value>
            <value>
                <fullName>นราธิวาส</fullName>
            </value>
            <value>
                <fullName>น่าน</fullName>
            </value>
            <value>
                <fullName>บึงกาฬ</fullName>
            </value>
            <value>
                <fullName>บุรีรัมย์</fullName>
            </value>
            <value>
                <fullName>ปทุมธานี</fullName>
            </value>
            <value>
                <fullName>ประจวบคีรีขันธ์</fullName>
            </value>
            <value>
                <fullName>ปราจีนบุรี</fullName>
            </value>
            <value>
                <fullName>ปัตตานี</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/C_AddressLine4_PE__c.field-meta.xml
<CustomField>
    <fullName>C_AddressLine4_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sub District</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/C_AddressLine5_PE__c.field-meta.xml
<CustomField>
    <fullName>C_AddressLine5_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>District</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/C_Country_PE__c.field-meta.xml
<CustomField>
    <fullName>C_Country_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Country</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/C_Province_PE__c.field-meta.xml
<CustomField>
    <fullName>C_Province_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Province</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/C_Zipcode_PE__c.field-meta.xml
<CustomField>
    <fullName>C_Zipcode_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zipcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>สามารถพิมพ์วันที่ที่ต้องการในช่องได้</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_Number_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Number_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>ID Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_Type_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Type_PE__c</fullName>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alien ID</fullName>
            </value>
            <value>
                <fullName>BRN ID</fullName>
            </value>
            <value>
                <fullName>Citizen ID</fullName>
            </value>
            <value>
                <fullName>Passport ID</fullName>
            </value>
            <value>
                <fullName>Work Permit ID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>CR Migrate Contact WBG : use this field for migrate contact from dwh Rcordtype Core Back only.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Province__c/Province__c.object-meta.xml
<CustomObject>
    <label>Province</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Province Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provinces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Province__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Contact_Address__c/RTL_Contact_Address__c.object-meta.xml
<CustomObject>
    <label>Contact Address</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contact Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Contact_Address__c/fields/RTL_District__c.field-meta.xml
<CustomField>
    <fullName>RTL_District__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>District</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Contact_Address__c/fields/RTL_Province__c.field-meta.xml
<CustomField>
    <fullName>RTL_Province__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Province</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Contact_Address__c/fields/RTL_Sub_District__c.field-meta.xml
<CustomField>
    <fullName>RTL_Sub_District__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sub District</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Contact_Address__c/fields/RTL_Zipcode__c.field-meta.xml
<CustomField>
    <fullName>RTL_Zipcode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zipcode</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status_Code__c/Status_Code__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Error,Warning message handler</description>
    <label>Status Code</label>
</CustomObject>

force-app/main/default/objects/Status_Code__c/fields/Status_Message__c.field-meta.xml
<CustomField>
    <fullName>Status_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sub_District__c/Sub_District__c.object-meta.xml
<CustomObject>
    <label>Sub District</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sub District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_District__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Sub Discticts</relationshipLabel>
    <relationshipName>Sub_Discticts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sub_District__c/fields/Location_code__c.field-meta.xml
<CustomField>
    <fullName>Location_code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sub_District__c/fields/Zip_code__c.field-meta.xml
<CustomField>
    <fullName>Zip_code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactExtensionV3.cls
public with sharing class ContactExtensionV3 implements Database.AllowsCallouts{
    //**********************************************************//
    // Modify log
    //**********************************************************//
    // Change No. : CH01
    // Change By : Uttaporn L.
    // Change Date : 2015.06.22
    // Change Detail : Edit When select Sub-District to --None-- Return Error
    // Case No. : 00002582
    //**********************************************************//   
    public Contact contact;
    
    public string accid {get;set;}
    public static final String DML_EXCEPTION_CODE = '1000';
    public static final String CALLOUT_EXCEPTION_CODE = '1002';
    public static final String QUERY_EXCEPTION_CODE = '1001'; 
    public boolean isCalloutAllow {get;set;}
    public boolean isCreateSuccess {get;set;}
    public boolean isIDValid {get;set;}
    public boolean IsCountryAsTH {get;set;}
    public boolean IsOtherCountry {get;set;}
    public String selected {get;set;}
    public Integer ContactMobileNoTemp {get;set;}
    public Province__C province;
    public District__c district;
    public Sub_District__c subdis;
    public Map<id, List<SelectOption>> provinceMap {get;set;}
    public static Map<String,id> districtMap {get;set;}
    public Map<String,id> subdisMap {get;set;}
    public Map<id,string> postcodes {get;set;}
    public String selectedProvince {get;set;}
    public String selectedDistrict {get;set;}
    public String selectedSubDistrict {get;set;}
    public String selectedPostcode {get;set;}
    public List<Province__c> ProvinceList{get;set;}
    public List<District__c> DistrictList{get;set;}
    public List<Sub_District__c> subdisList {get;set;}
    public Set<String> postcodeSet {get;set;}
    public List<SelectOption> ProvinceOptionList {get;set;}
    public List<SelectOption> DistrictOptionList {get;set;}
    public List<SelectOption> SubDistrictOptionList {get;set;}
    public List<SelectOption> PostcodeOptionList {get;set;}
    public string selectedCountry {get;set;}
    public Map<String,String> CountryMap {get;set;}
    public  List<SelectOption> CountriesOptionList {get;set;}
    public  List<Country__c> CountriesList {get;set;}
    //--- Modifed at 9 Feb 2022 CR AL Re-org Long Term --
    Map<String, Map<String, Map<String, String>>> mapAddress = new Map<String, Map<String, Map<String, String>>>();
  
    //constructor
    public ContactExtensionV3(ApexPages.StandardController controller) {
        ProvinceList = new List<Province__c>();
        DistrictList = new List<District__C>();
        subdisList = new List<Sub_District__c>();
        provinceMap = new Map<id, List<SelectOption>>();
        districtMap = new Map<String,id>();
        subdisMap = new Map<String,id>();
        postcodes = new Map<id,string>();
        postcodeSet = new Set<String>();            
        ProvinceOptionList = new List<SelectOption>();
        ProvinceOptionList.add(new SelectOption('','--None--'));
        //--- Modifed at 9 Feb 2022 CR AL Re-org Long Term --
        //ProvinceList = new List<Province__c>( [SELECT Id,Name,Code__c FROM Province__C WHERE id != null ORDER BY Name]);
        
        for(AggregateResult ca : [SELECT RTL_Province__c FROM RTL_Contact_Address__c WHERE IsActive__c = true GROUP BY RTL_Province__c])
        {
            String province = (ca.get('RTL_Province__c') == null || ca.get('RTL_Province__c') == '') ? '' : (String) ca.get('RTL_Province__c');
            ProvinceOptionList.add(new SelectOption(province,province));
        }
        System.debug('ProvinceOptionList:'+ProvinceOptionList.size());
        
        ProvinceOptionList.sort();

        //ProvinceOptionList.sort();
        // for(Province__C pro : ProvinceList){
        //     ProvinceOptionList.add(new SelectOption(pro.id,pro.Name));
        // }

        DistrictOptionList = new List<SelectOption>();
        SubDistrictOptionList = new List<SelectOption>();
        PostcodeOptionList = new List<SelectOption>();
        contact = (Contact)controller.getRecord();      
        
         if(ApexPages.currentPage().getParameters().containsKey('accid'))
        {
            contact.Account__c = ApexPages.currentPage().getParameters().get('accid');
        }
        
        CountryMap = new Map<String,String>();
        CountriesOptionList = new List<SelectOption>();
        DistrictOptionList.add(new SelectOption('','--None--'));
        SubDistrictOptionList.add(new SelectOption('','--None--'));
        PostcodeOptionList.add(new SelectOption('','--None--'));            
        CountriesList = new List<Country__c>( [SELECT ID,Name,Code__c FROM Country__c WHERE Name != '' AND Code__c != null ORDER BY Name]);
        for(Country__c coun : CountriesList){
            CountriesOptionList.add(new SelectOption(coun.Name,coun.Name));
            CountryMap.put(coun.Code__c, coun.Name);
        }
        contact.C_Country_PE__c = 'Thailand';
        selectedCountry = 'Thailand';
        IsCountryAsTH =true;
    }
    
    public PageReference save(){ 
        if(contact.ID_Type_PE__c!=null&&contact.ID_Number_PE__c==null){         
           ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR, Status_Code__c.GetValues('3004').Status_Message__c));
           return null;
        }
        if(contact.FirstName==null||contact.FirstName==''){
            ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR, Status_Code__c.GetValues('3009').Status_Message__c));
            return null;
        }
        
       /* if(!isIDValid&&contact.ID_Type_PE__c=='Citizen ID'){
            ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR, Status_Code__c.GetValues('3001').Status_Message__c));
            return null;
        }*/
        
        contact.LastName = contact.Last_Name__c!=null?contact.Last_Name__c:null;
        contact.AccountId = contact.Account__c!=null?contact.Account__c:null;

        try{
            
            insert contact;
            
            PageReference ContactPage;
            ContactPage = new ApexPages.StandardController(contact).view();
            ContactPage.setRedirect(true);          
            return ContactPage; 
            
        }catch(DMLException e){
            if(contact.Date_of_Birth__c !=null){
                if(contact.Date_of_Birth__c > System.today()){
                 ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR,Status_Code__c.GetValues('3019').Status_Message__c) );
            }
            }else{
                System.debug('DMLException msg : '+e.getMessage());
                //ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR, Status_Code__c.GetValues('1000').Status_Message__c));
            }
            return null;
        }

        return null;
    }
    
        public PageReference saveSF1(){ 
            isCreateSuccess=true;
        if(contact.ID_Type_PE__c!=null&&contact.ID_Number_PE__c==null){         
            isCreateSuccess=false;
           ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR, Status_Code__c.GetValues('3004').Status_Message__c));
           return null;
        }
        if(contact.FirstName==null||contact.FirstName==''){
            isCreateSuccess=false;
            ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR, Status_Code__c.GetValues('3009').Status_Message__c));
            return null;
        }
        
       /* if(!isIDValid&&contact.ID_Type_PE__c=='Citizen ID'){
            isCreateSuccess=false;
            ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR, Status_Code__c.GetValues('3001').Status_Message__c));
            return null;
        }*/
        
        contact.LastName = contact.Last_Name__c!=null?contact.Last_Name__c:null;
        contact.AccountId = contact.Account__c!=null?contact.Account__c:null;

        try{
            
            insert contact;
            
        }catch(DMLException e){
            if(contact.Date_of_Birth__c !=null){
                if(contact.Date_of_Birth__c > System.today()){
                 isCreateSuccess=false;   
                 ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR,Status_Code__c.GetValues('3019').Status_Message__c) );
            }
            }else{
                isCreateSuccess=false;
                System.debug('DMLException msg : '+e.getMessage());
                //ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR, Status_Code__c.GetValues('1000').Status_Message__c));
            }
            return null;
        }

        return null;
    }
    
    
    private String provinceholder;
    
      public PageReference viewContact(){
        PageReference ContactPage;
        ContactPage = new ApexPages.StandardController(contact).view();
        ContactPage.setRedirect(true);          
        return ContactPage; 
    }
    
        
        public void Provinceselected(){
            boolean provincechange =false;
             selectedSubDistrict =null;
        //--- Modifed at 9 Feb 2022 CR AL Re-org Long Term --
        SubDistrictOptionList = new List<SelectOption>();
        subDistrictOptionList.add(new SelectOption('','--None--'));
        selectedPostcode = null;
        //contact.Province_Temp__c = null;   Comment cleansing remove this fields Attasit 22/08/2016
          //--- Modifed at 9 Feb 2022 CR AL Re-org Long Term --
        PostcodeOptionList =  new List<SelectOption>();
        PostcodeOptionList.add(new SelectOption('','--None--')); 

            if(provinceholder ==null){
                provinceholder = selectedProvince;
            }else{
                if(selectedProvince !=null && selectedprovince !='' && provinceholder != selectedProvince){
                    provincechange = true;
                }
            }
          
            if((selectedProvince !=null && selectedProvince != '' && selectedProvince !='null')||provincechange){
            //--- Modifed at 9 Feb 2022 CR AL Re-org Long Term --
              DistrictOptionList = new List<SelectOption>();
                //contact.C_Province_PE__c = [SELECT ID,NAME FROM Province__C WHERE ID =:selectedProvince LIMIT 1].Name;
                contact.C_Province_PE__c  = selectedProvince;
            
         
            //DistrictList = new List<District__c>([SELECT ID,Name,Code__c FROM District__c WHERE Province__c =:selectedProvince ORDER BY Name]);

             DistrictOptionList.add(new SelectOption('','--None--'));
            //    for(District__C dis : DistrictList){
            //       DistrictOptionList.add(new SelectOption(dis.id,dis.Name)); 
            //         }
            for(AggregateResult ca : [SELECT RTL_District__c FROM RTL_Contact_Address__c WHERE RTL_Province__c =: selectedProvince AND IsActive__c = true GROUP BY RTL_District__c])
            {
                String district = (ca.get('RTL_District__c') == null || ca.get('RTL_District__c') == '') ? '' : (String) ca.get('RTL_District__c');
                DistrictOptionList.add(new SelectOption(district,district)); 
            }
           
            DistrictOptionList.sort();
            provinceholder = selectedprovince;
      }else{
        selectedDistrict = null;
        selectedSubDistrict = null;
        selectedpostcode = null;
        DistrictOptionList = new List<SelectOption>();
        contact.C_AddressLine5_PE__c =null;
        contact.C_AddressLine4_PE__c =null;  
        contact.C_Zipcode_PE__c = null;  
        postcodeSet = new Set<String>(); 
        SubDistrictOptionList = new List<SelectOption>();
         PostcodeOptionList = new List<SelectOption>();
      }  
           
      
    }
    
    public void DistrictSelected(){
       
         if(selectedDistrict !=null && selectedDistrict != '' && selectedDistrict !='null' ){
            SubDistrictOptionList = new List<SelectOption>();
                PostcodeOptionList = new List<SelectOption>();
            PostcodeOptionList.add(new SelectOption('','--None--'));
                selectedSubDistrict = null;
            postcodeSet = new Set<String>();
            //contact.C_AddressLine5_PE__c = [SELECT ID,NAME FROM District__c WHERE ID =:selectedDistrict LIMIT 1].Name;
            //--- Modifed at 9 Feb 2022 CR AL Re-org Long Term --
            contact.C_AddressLine5_PE__c = selectedDistrict;
            // subdisList = new List<Sub_District__c>([SELECT ID,Name,Code__c,Zip_code__c,Location_Code__c FROM Sub_District__c WHERE District__c =:selectedDistrict ORDER BY Name]);
            subDistrictOptionList.add(new SelectOption('','--None--'));
            // for(Sub_District__c subdis : subdisList){
            //   SubDistrictOptionList.add(new SelectOption(subdis.id,subdis.Name));
            //   postcodeSet.add(subdis.Zip_code__c);
            // }  
            for(RTL_Contact_Address__c ca : [SELECT Id, Name, RTL_Province__c, RTL_District__c, RTL_Sub_District__c, RTL_Zipcode__c, IsActive__c FROM RTL_Contact_Address__c WHERE RTL_District__c =: selectedDistrict AND IsActive__c = TRUE])
            {
                SubDistrictOptionList.add(new SelectOption(ca.RTL_Sub_District__c,ca.RTL_Sub_District__c)); 
            }
            SubDistrictOptionList.sort();
        }else{
            selectedSubDistrict = null;
            selectedSubDistrict = null;
            selectedPostcode = null;
            contact.C_AddressLine5_PE__c = null;
            contact.C_AddressLine4_PE__c =null;  
            contact.C_Zipcode_PE__c = null;  
            SubDistrictOptionList = new List<SelectOption>();
            PostcodeOptionList = new List<SelectOption>();
            postcodeSet = new Set<String>(); 
        
        }
    }
    
     public void SubDistrictSelected(){
        
        if(selectedSubDistrict !=null && selectedSubDistrict != '' && selectedSubDistrict !='null' ){
    //--- Modifed at 9 Feb 2022 CR AL Re-org Long Term --
            //Sub_District__c sub = [SELECT ID,Name,Zip_code__c FROM Sub_District__c WHERE ID=: selectedSubDistrict LIMIT 1];
            // contact.C_AddressLine4_PE__c = sub.Name;
            // contact.C_Zipcode_PE__c = sub.Zip_code__c;
            contact.C_AddressLine4_PE__c = selectedSubDistrict;

            
            selectedpostcode =null;
            PostcodeOptionList = new List<SelectOption>();
                PostcodeOptionList.add(new SelectOption('','--None--'));
            // for(String Postcode : postcodeSet){
                    
            // PostcodeOptionList.add(new SelectOption(Postcode,Postcode)); 
            //         System.debug(Postcode);
            // }
            for(RTL_Contact_Address__c ca : [SELECT Id,Name,RTL_Province__c,RTL_District__c,RTL_Sub_District__c,RTL_Zipcode__c,IsActive__c FROM RTL_Contact_Address__c WHERE RTL_Sub_District__c =: selectedSubDistrict AND IsActive__c = true])
            {
                PostcodeOptionList.add(new SelectOption(ca.RTL_Zipcode__c,ca.RTL_Zipcode__c));
                contact.C_Zipcode_PE__c = ca.RTL_Zipcode__c;
            }
        }else{
           PostcodeOptionList = new List<SelectOption>();
           selectedpostcode =null;
            
             contact.C_Zipcode_PE__c = null;
        }
    }
   
        public static Integer calculateAge(Date birthDate){
        Integer Age;

        Date day = Date.today();
        
        if(day >= birthDate)
        {
          Age =   day.year() - birthDate.year();
        }
        else{
            Age =   day.year() - (birthDate.year() - 1);
        }  
        return Age;
    }
    
    
    public void CheckCountry(){
        System.debug(selectedCountry);
         contact.C_Country_PE__c = selectedCountry;
        if(selectedCountry =='Thailand'){
            IsCountryAsTH =true;
            IsOtherCountry = false;
        }else{
            IsCountryAsTH =false;
            IsOtherCountry = true;
            
        }        
    }
    
    public Pagereference customCancel(){
        PageReference viewPage;
        if (contact.Account__c != null) {
            Account accountObj = [select id,name from Account where id=:contact.Account__c limit 1];
            viewPage = new ApexPages.StandardController(accountObj).view();   
            
        }
        viewPage.setRedirect(true);
        return viewPage; 
    }

    public Id getRecordType (){
        List<Schema.RecordTypeInfo> infos = Schema.SObjectType.Contact.RecordTypeInfos;
        Id defaultRecordTypeId;

        //check each one
        for (Schema.RecordTypeInfo info : infos) {
            if (info.DefaultRecordTypeMapping) {
                defaultRecordTypeId = info.RecordTypeId;
            }
        }

        //here is the default Opportunity RecordType Id for the current user
        return defaultRecordTypeId;
    }
}