force-app/main/default/objects/Account/fields/ID_Number_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Number_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>เลขที่เอกสารสำคัญของลูกค้า</inlineHelpText>
    <label>ID Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Type_PE__c</fullName>
    <description>Identification Type Ex. Citizen ID, BRN ID, Passport ID, Alien ID, Work permit</description>
    <inlineHelpText>ประเภทเอกสารสำคัญของลูกค้า</inlineHelpText>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Customer_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BRN ID</fullName>
            </value>
            <value>
                <fullName>Citizen ID</fullName>
            </value>
            <value>
                <fullName>Passport ID</fullName>
            </value>
            <value>
                <fullName>Work permit ID</fullName>
            </value>
            <value>
                <fullName>Alien ID</fullName>
            </value>
            <value>
                <fullName>Tax ID</fullName>
            </value>
            <value>
                <fullName>Other ID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/C_AddressLine4_PE__c.field-meta.xml
<CustomField>
    <fullName>C_AddressLine4_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sub District</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/C_AddressLine5_PE__c.field-meta.xml
<CustomField>
    <fullName>C_AddressLine5_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>District</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/C_Country_PE__c.field-meta.xml
<CustomField>
    <fullName>C_Country_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Country</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/C_Province_PE__c.field-meta.xml
<CustomField>
    <fullName>C_Province_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Province</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>สามารถพิมพ์วันที่ที่ต้องการในช่องได้</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Decision_Map__c.field-meta.xml
<CustomField>
    <fullName>Decision_Map__c</fullName>
    <label>Decision Map 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Gate Keeper</fullName>
            </value>
            <value>
                <fullName>Influencer</fullName>
            </value>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>User and Decision maker</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_Number_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Number_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>ID Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_Type_PE__c.field-meta.xml
<CustomField>
    <fullName>ID_Type_PE__c</fullName>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alien ID</fullName>
            </value>
            <value>
                <fullName>BRN ID</fullName>
            </value>
            <value>
                <fullName>Citizen ID</fullName>
            </value>
            <value>
                <fullName>Passport ID</fullName>
            </value>
            <value>
                <fullName>Work Permit ID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Position</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Product_Decision__c.field-meta.xml
<CustomField>
    <fullName>Product_Decision__c</fullName>
    <label>Product Decision 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>All Products</fullName>
            </value>
            <value>
                <fullName>Deposit and Investment</fullName>
            </value>
            <value>
                <fullName>Digital Channel</fullName>
            </value>
            <value>
                <fullName>Domestic Transactional Banking</fullName>
            </value>
            <value>
                <fullName>Fleet card</fullName>
            </value>
            <value>
                <fullName>Hedging : Derivative</fullName>
            </value>
            <value>
                <fullName>Hedging : FX</fullName>
            </value>
            <value>
                <fullName>International Transactional Banking : Export</fullName>
            </value>
            <value>
                <fullName>International Transactional Banking : Import</fullName>
            </value>
            <value>
                <fullName>L/G</fullName>
            </value>
            <value>
                <fullName>Limit setup</fullName>
            </value>
            <value>
                <fullName>Long Term Funding</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>PN</fullName>
            </value>
            <value>
                <fullName>Short Term Funding</fullName>
            </value>
            <value>
                <fullName>Supply chain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Value_Style__c.field-meta.xml
<CustomField>
    <fullName>Value_Style__c</fullName>
    <label>Value Style</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Benefit Awareness</fullName>
            </value>
            <value>
                <fullName>Risk Awareness</fullName>
            </value>
            <value>
                <fullName>Relationship Awareness</fullName>
            </value>
            <value>
                <fullName>Principle Awarness</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Salesforce.recordType-meta.xml
<RecordType>
    <fullName>Salesforce</fullName>
    <active>true</active>
    <label>Salesforce</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status_Code__c/Status_Code__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Error,Warning message handler</description>
    <label>Status Code</label>
</CustomObject>

force-app/main/default/objects/Status_Code__c/fields/Status_Message__c.field-meta.xml
<CustomField>
    <fullName>Status_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sub_District__c/Sub_District__c.object-meta.xml
<CustomObject>
    <label>Sub District</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sub District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_District__c/fields/Zip_code__c.field-meta.xml
<CustomField>
    <fullName>Zip_code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactUpdateExtensionV3Test.cls
@isTest
global class ContactUpdateExtensionV3Test {
	static testmethod void UpdateContact(){
        TestUtils.createIdType();
        TestUtils.createAppConfig();        
        TestUtils.createStatusCode();
        TestUtils.createDisqualifiedReason();
        TestUtils.createDateOfBirth();
         Map<String,ID> addressmap = TestUtils.CreateAddress();
        
    	Account acct = TestUtils.createAccounts(1,'CreateContact','Individual', true).get(0);
        Contact cont = TestUtils.createContacts(1, acct.id, true).get(0);
        cont.RecordTypeId = [SELECT Name,id,SobjectType 
                             FROM RecordType 
                             WHERE Name=:'Salesforce' AND SobjectType='Contact' LIMIT 1].get(0).id;
        cont.C_Country_PE__c = 'Thailand';
        cont.C_Province_PE__c = addressmap.get('Province');
        cont.C_AddressLine5_PE__c = addressmap.get('District');
        cont.C_AddressLine4_PE__c =  addressmap.get('Sub District');
        update cont;
  Country__C Thailand = new Country__c ();
        
        thailand.Name = 'Thailand';
        thailand.Code__c ='66';
        insert thailand;
        ApexPages.StandardController sc = new ApexPages.StandardController(cont);
        ContactUpdateExtensionV3 ConEX = new ContactUpdateExtensionV3(sc);
         conEx.Provinceselected();
        conEx.DistrictSelected();
        ConEx.SubDistrictSelected();
                ConEx.selectedProvince = addressmap.get('Province');
        
        ConEx.selectedDistrict = addressmap.get('District');
        
        ConEx.selectedSubDistrict =  addressmap.get('Sub District');
      	
       
       	conEx.isIDValid = true;
        conEx.Provinceselected();
        conEx.DistrictSelected();
        Sub_District__c subdistrict = new Sub_District__c();
        subdistrict.Name = 'ห้วยขวาง';
        subdistrict.Zip_code__c ='10230';
        
        insert subdistrict;
         ConEx.selectedSubDistrict = subdistrict.id;
        ConEx.SubDistrictSelected();
        ConEx.CheckCountry();
        ConEx.contact.C_Country_PE__c='EN';
        conEx.CheckCountry();
        conEx.contact.C_Country_PE__c='Thailand';
        ContactUpdateExtensionV3.calculateAge(Date.newInstance(1980, 2, 17));
        conEx.IsCountryAsTH = true;
        ConEX.save(); 
        ConEx.saveSF1();
        
        cont.ID_Type_PE__c = 'Alien ID';
      	 ConEX.save(); 
        ConEx.saveSF1();
        cont.FirstName ='Tinnakrit';
       	ConEX.save(); 
        ConEx.saveSF1();
        cont.ID_Type_PE__c = 'Citizen ID';
        cont.ID_Number_PE__c = '15101';
       	ConEX.save(); 
        ConEx.saveSF1();
        cont.Date_of_Birth__c = System.today();
        cont.LastName = 'Kidmai';
        cont.Last_Name__c = 'Kidmai';
		ConEX.save();  
        ConEx.saveSF1();      
        ConEx.viewContact();
    }
    
    //Fixed[2018-03]: BAU_6785 (INC0046474) - CRM-Unable to complete survey & Convert leads        
    static testmethod void UpdateContactByNotAdmin(){
    
        User newUser = new User(FirstName='ctFirst', LastName='ctLast', 
                                    UserName='ctname@tmb.com', 
                                    Email='ctname@tmbbank.com', Alias='ct',
                                    LocaleSidKey='en_US', LanguageLocaleKey='en_US', EmailEncodingKey='ISO-8859-1', 
                                    CommunityNickname='cttmb',
                                    ProfileId = [SELECT Id FROM Profile WHERE Name = 'TMB BDM Profile' LIMIT 1].Id
                                    ,TimeZoneSidKey='America/New_York',isActive = true,
                                    Employee_ID__c ='C0001',Zone__c=
                                    '1001',Segment__c ='AA',Zone_Code__c ='1001');           
        insert newUser;
        System.runAs(newUser) {
        	insert new PermissionSetAssignment(PermissionSetId=TestUtils.SetupPermissionSet().Id,AssigneeId=newUser.Id);
        }
        System.runAs(newUser) {
            TestUtils.createIdType();
            TestUtils.createAppConfig();
                
            //Status_Code__c error9001 = new Status_Code__c();
            //error9001.isError__c = true;
            //error9001.Name = '9001';
            //error9001.Status_Message__c = 'Retail contact can’t be edited.';
            //insert error9001;
                
            TestUtils.createStatusCode();
            TestUtils.createDisqualifiedReason();
            TestUtils.createDateOfBirth();
            Map<String,ID> addressmap = TestUtils.CreateAddress();
            
            Account acct = TestUtils.createAccounts(1,'CreateContact_Aa','Individual', true).get(0);
                
            Contact newContact = new Contact(
                AccountId = acct.Id,
                Salutation = 'Mr.',
                LastName = 'contact_Aa',
                Date_of_Birth__c = Date.today(),
                Position__c = 'position1',
                Value_Style__c = 'Risk Awareness',
                Decision_Map__c = 'User',
                Product_Decision__c = '',
                Description__c = 'contact description',
                OwnerId  = newUser.Id);     
            insert newContact;
            
            Contact cont = newContact; //TestUtils.createContacts(1, acct.id, true).get(0);
            cont.RecordTypeId = [SELECT Name,id,SobjectType 
                                 FROM RecordType 
                                 WHERE Name=:'Retail Contact' AND SobjectType='Contact' LIMIT 1].get(0).id;
            cont.C_Country_PE__c = 'Thailand';
            cont.C_Province_PE__c = addressmap.get('Province');
            cont.C_AddressLine5_PE__c = addressmap.get('District');
            cont.C_AddressLine4_PE__c =  addressmap.get('Sub District');
            update cont;
            Country__C Thailand = new Country__c ();        
            thailand.Name = 'Thailand';
            thailand.Code__c ='66';
            insert thailand;
            ApexPages.StandardController sc = new ApexPages.StandardController(cont);
            ContactUpdateExtensionV3 ConEX = new ContactUpdateExtensionV3(sc);
             conEx.Provinceselected();
            conEx.DistrictSelected();
            ConEx.SubDistrictSelected();
            ConEx.selectedProvince = addressmap.get('Province');
            ConEx.selectedDistrict = addressmap.get('District');        
            ConEx.selectedSubDistrict =  addressmap.get('Sub District');
            conEx.isIDValid = true;
            conEx.Provinceselected();
            conEx.DistrictSelected();
                
            Sub_District__c subdistrict = new Sub_District__c();
            subdistrict.Name = 'ห้วยขวาง';
            subdistrict.Zip_code__c ='10230';        
            insert subdistrict;
                
            ConEx.selectedSubDistrict = subdistrict.id;
            ConEx.SubDistrictSelected();
            ConEx.CheckCountry();
            ConEx.contact.C_Country_PE__c='EN';
            conEx.CheckCountry();
            conEx.contact.C_Country_PE__c='Thailand';
            ContactUpdateExtensionV3.calculateAge(Date.newInstance(1980, 2, 17));
            conEx.IsCountryAsTH = true;
            ConEX.save();                           
        }    
    }

}