force-app/main/default/objects/Account/fields/Mobile_Number_PE__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>Mobile or Office Phone Number must be entered</inlineHelpText>
    <label>Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/RTL_Wealth_RM__c.field-meta.xml
<CustomField>
    <fullName>RTL_Wealth_RM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CR Wealth RM Info , convert EMP/BR Code to Wealth RM</description>
    <label>Wealth RM/BM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TMB_Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>TMB_Employee_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Referral Staff ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Security_Matrix__c/Data_Security_Matrix__c.object-meta.xml
<CustomObject>
    <description>Table to maintain data partition security matrix for each profile</description>
    <label>Data Security Matrix</label>
    <nameField>
        <displayFormat>SEC-{0000}</displayFormat>
        <label>Data Security Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Security Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Security_Matrix__c/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <label>Access Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Authorize Only</fullName>
            </value>
            <value>
                <fullName>No Access</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Security_Matrix__c/fields/Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Profile_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Profile Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Security_Matrix__c/fields/Section_Name__c.field-meta.xml
<CustomField>
    <fullName>Section_Name__c</fullName>
    <label>Section Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ComCust:Account Information</fullName>
            </value>
            <value>
                <fullName>ComCust:Address Information</fullName>
            </value>
            <value>
                <fullName>ComCust:Campaign Lead History</fullName>
            </value>
            <value>
                <fullName>ComCust:Collateral</fullName>
            </value>
            <value>
                <fullName>ComCust:Contact Information</fullName>
            </value>
            <value>
                <fullName>ComCust:Contacts</fullName>
            </value>
            <value>
                <fullName>ComCust:Executive Summary/Account Plan</fullName>
            </value>
            <value>
                <fullName>ComCust:Other Information</fullName>
            </value>
            <value>
                <fullName>ComCust:Performance</fullName>
            </value>
            <value>
                <fullName>ComCust:Pipeline</fullName>
            </value>
            <value>
                <fullName>ComCust:Product On Hand</fullName>
            </value>
            <value>
                <fullName>ComCust:Product On Hand (Partition)</fullName>
            </value>
            <value>
                <fullName>ComCust:Risk Information</fullName>
            </value>
            <value>
                <fullName>ComCust:Wallet</fullName>
            </value>
            <value>
                <fullName>ComPros:Customer Information</fullName>
            </value>
            <value>
                <fullName>ComPros:Customer Source</fullName>
            </value>
            <value>
                <fullName>ComPros:Detail Information</fullName>
            </value>
            <value>
                <fullName>ComPros:General Information</fullName>
            </value>
            <value>
                <fullName>ComPros:Product Interest</fullName>
            </value>
            <value>
                <fullName>ComPros:Re-assignment Customer</fullName>
            </value>
            <value>
                <fullName>RtlCust:Address Information</fullName>
            </value>
            <value>
                <fullName>RtlCust:Alternative Contact Information</fullName>
            </value>
            <value>
                <fullName>RtlCust:Campaign History</fullName>
            </value>
            <value>
                <fullName>RtlCust:Contact Number and Email Address</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Demographic (High)</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Demographic (Low)</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Demographic (Medium)</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Insight - Personalized Information</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Product Holding (High)</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Product Holding (Low)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/editCustomerForCCOutboundCSVCtlTest.cls
@isTest
public with sharing class editCustomerForCCOutboundCSVCtlTest {

    @TestSetup
    static void settingAppConfig(){
        AppConfig__c appConfig1 = new AppConfig__c(Name='runtrigger', Value__c='false');
        insert appConfig1;
        
        AppConfig__c appConfig2 = new AppConfig__c(Name='runCustomerNoteTrigger', Value__c='false');
        insert appConfig2;

        AppConfig__c appConfig3 = new AppConfig__c(Name='DefaultOwner', Value__c='00000');
        insert appConfig3;

        AppConfig__c appConfig4 = new AppConfig__c(Name='FilterRetailSegment', Value__c='5|6|7|8|9');
        insert appConfig4;

        Data_Security_Matrix__c dsm = new Data_Security_Matrix__c();
        dsm.Section_Name__c = 'RtlCust:Contact Number and Email Address';
        dsm.Profile_Name__c = 'System Administrator';
        dsm.Access_Type__c = 'All';
        insert dsm;
    }

    @isTest
    static void getDescribeFieldResultAndValue() {
        List<User> testUser = TestUtils.createUsers(1, 'myTest', 'User1', 'testUser1@example.com', true);
        Account acct = new Account();
        acct.Name = 'TEST ACCOUNT';
        acct.Mobile_Number_PE__c = '0123456789';
        acct.RTL_Wealth_RM__c = testUser[0].Id;
        insert acct;

        List<String> fields = new List<String>{'Id', 'Name'};
        List<String> fields_translate = new List<String>();
        Test.startTest();
            Object returnObj = editCustomerForCCOutboundCSVController.getDescribeFieldResultAndValue(acct.Id, fields, fields_translate);
        Test.stopTest();
    }

    @isTest
    static void testGetInitialData() {
        List<User> testUser = TestUtils.createUsers(1, 'myTest', 'User1', 'testUser1@example.com', true);
        Account acct = new Account();
        acct.Name = 'TEST ACCOUNT';
        acct.Mobile_Number_PE__c = '0123456789';
        acct.RTL_Wealth_RM__c = testUser[0].Id;
        insert acct;
        Test.startTest();
            System.runAs(testUser[0]) {
                System.debug(testUser[0]);

                Object returnObj = editCustomerForCCOutboundCSVController.getInitialData(acct.Id);
                Map<String, Object> returnAccObj = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(returnObj));

                Map<String, Object> returnAccountId = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(returnAccObj.get('account')));
                
                System.assertEquals(acct.Id, returnAccountId.get('Id'));

                try {
                    Object falsereturnObj = editCustomerForCCOutboundCSVController.getInitialData(null);
                } catch (Exception e) {
                    
                }
            }
        Test.stopTest();
    }

    @isTest
    static void testUpdateAccountData() {
        List<User> testUser = TestUtils.createUsers(1, 'myTest', 'User1', 'testUser1@example.com', true);
        Account acct = new Account();
        acct.Name = 'TEST ACCOUNT';
        acct.Mobile_Number_PE__c = '0123456789';
        acct.RTL_Wealth_RM__c = testUser[0].Id;
        acct.TMB_Employee_ID__c = testUser[0].Employee_ID__c;
        insert acct;

        Account acctToUpdate = [SELECT Id, Mobile_Number_PE__c FROM Account WHERE Id =:acct.Id];
        acctToUpdate.Mobile_Number_PE__c = '0000000000';
        
        Test.startTest();
            System.runAs(testUser[0]) {
                Map<String, Object> returnResult = editCustomerForCCOutboundCSVController.updateAccountData(acctToUpdate);
                System.assertEquals(true, returnResult.get('success'));

                try {
                    Map<String, Object> failResult = editCustomerForCCOutboundCSVController.updateAccountData(null);
                } catch (Exception e) {
                    
                }
            }
        Test.stopTest();
    }
}