force-app/main/default/objects/Account/fields/Mobile_Number_PE__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>Mobile or Office Phone Number must be entered</inlineHelpText>
    <label>Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/RTL_Wealth_RM__c.field-meta.xml
<CustomField>
    <fullName>RTL_Wealth_RM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CR Wealth RM Info , convert EMP/BR Code to Wealth RM</description>
    <label>Wealth RM/BM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RM_Cockpit_My_Customer_CreateTaskTest.cls
@isTest
public class RM_Cockpit_My_Customer_CreateTaskTest {

    @TestSetup
    static void makeData(){
        AppConfig__c aConfig1 = new AppConfig__c(Name='runtrigger', Value__c='false');
        insert aConfig1;

        AppConfig__c aConfig2 = new AppConfig__c(Name='runCustomerNoteTrigger', Value__c = 'false');
        insert aConfig2;
    }

    @isTest
    static void testCreateTaskHelper() {
       
        List<String> acctIdList = new List<String>();
        
        List<Account> acctList = new List<Account>();

        List<User> Wealth_RMC = TestUtils.createUsers(1 ,'mvp2TestUser', 'user', 'mvp2_tus@example.com', true);
        
        Account acct = new Account();
        acct.Name = 'TEST ACCOUNT';
        acct.Mobile_Number_PE__c = '0812345678';
        acct.RTL_Wealth_RM__c = Wealth_RMC[0].id;
        acctList.add(acct);
        
        insert acctList;
        acctIdList.add(acct.Id);

        Test.startTest();
            RM_Cockpit_My_Customer_CreateTask.createTaskHelper(acctIdList);
        
            Integer checkSOQL = [SELECT COUNT() FROM Task WHERE WhatId IN :acctIdList];
        
            System.assertEquals(acctIdList.size(), checkSOQL);
        Test.stopTest();
    }
}