force-app/main/default/objects/Account/fields/Mobile_Number_PE__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number_PE__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>Mobile or Office Phone Number must be entered</inlineHelpText>
    <label>Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Using for RMC allows to create opportunity on other&apos;s existing customer.</description>
    <label>Create Opportunity Privilege</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsTBankData__c.field-meta.xml
<CustomField>
    <fullName>IsTBankData__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TBank</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsVerified__c.field-meta.xml
<CustomField>
    <fullName>IsVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CommercialVerifyButtonControllerTest.cls
@isTest
public with sharing class CommercialVerifyButtonControllerTest {
    private static string MockData() {
        AppConfig__c appconfigObj1 = new AppConfig__c(Name = 'runtrigger',Value__c = 'true');
        insert appconfigObj1;
        
        Account a = new Account();
        a.mobile_number_pe__c = '1111111';
        a.name = 'name';
        insert a;
                
        Contact con = new Contact();
        con.FirstName = 'firstname';
        con.LastName = 'lastname';
        con.Phone = '095-959-9561';
        con.Email = 'test@test.co.th';
        con.IsVerified__c = true;
        con.IsTBankData__c = true;
        con.Account__c = a.id;
        con.AccountId = a.id;
        insert con;
        
        return con.Id;
    }
    
    @isTest
    public static void Test_CommercialVerifyButtonController() {
        CommercialVerifyButtonController c = new CommercialVerifyButtonController();
    }
    
	@isTest
    public static void Test_getContactDetail() {
		string conId = MockData();
        Contact con = CommercialVerifyButtonController.getContactDetail(conId);
    }
    
    @isTest
    public static void Test_UpdateContact() {
        string conId = MockData();
        CommercialVerifyButtonController.UpdateContact(conId, true);
    }
}