force-app/main/default/objects/Account/fields/Murex_Counter_Label__c.field-meta.xml
<CustomField>
    <fullName>Murex_Counter_Label__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Counter Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/E_Client_Suitability__c/E_Client_Suitability__c.object-meta.xml
<CustomObject>
    <label>E-Client Suitability</label>
    <nameField>
        <displayFormat>CS-{YYMMDD}-{000}</displayFormat>
        <label>E-Client Suitability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>E-Client Suitability</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/E_Client_Suitability__c/fields/CS_Customer_Survey_A__c.field-meta.xml
<CustomField>
    <fullName>CS_Customer_Survey_A__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CS Customer Survey A</label>
    <referenceTo>Survey_Sheet__c</referenceTo>
    <relationshipLabel>E-Client Suitability</relationshipLabel>
    <relationshipName>E_Client_Suitability</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/E_Client_Suitability__c/fields/CS_Customer_Survey_B__c.field-meta.xml
<CustomField>
    <fullName>CS_Customer_Survey_B__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CS Customer Survey B</label>
    <referenceTo>Survey_Sheet__c</referenceTo>
    <relationshipLabel>E-Client Suitability (CS Customer Survey B)</relationshipLabel>
    <relationshipName>E_Client_Suitability1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/E_Client_Suitability__c/fields/CS_RM__c.field-meta.xml
<CustomField>
    <fullName>CS_RM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>E_Client_Suitability2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/E_Client_Suitability__c/fields/Murex_Counter_Label__c.field-meta.xml
<CustomField>
    <fullName>Murex_Counter_Label__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Counter Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Manager__c/Survey_Manager__c.object-meta.xml
<CustomObject>
    <description>Survey Master for each survey form</description>
    <label>Survey Manager</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Manager</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Sheet__c/Survey_Sheet__c.object-meta.xml
<CustomObject>
    <label>Survey Sheet</label>
    <nameField>
        <displayFormat>SS-{0000}</displayFormat>
        <label>Survey Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Sheet</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CSEClientSharingTest.cls
@isTest
private class CSEClientSharingTest {
	
	@testSetup static void setup() {
		// Implement test code
		AppConfig__c mc =new AppConfig__c(Name = 'runtrigger', Value__c = 'false');
        insert mc;

        User u = CSTestUtils.createUsers(1, 'UserTestqqq' ,'Userqqq' , 'test22@email.com' , false).get(0);
        u.IsActive = true;
        insert u;

		Account acc = CSTestUtils.createAccounts(1,false).get(0);
		acc.Murex_Counter_Label__c = 'eclient';
		insert acc;

		List<Survey_Manager__c> smList = CSTestUtils.createSurveyManager(2);
		Survey_Sheet__c formA = CSTestUtils.insertSurveySheet(smList[0], acc.Id,u.Id,'FormA');
		Survey_Sheet__c formB = CSTestUtils.insertSurveySheet(smList[1],acc.Id,u.Id,'FormB');

		List<E_Client_Suitability__c> esList = CSTestUtils.createEclient(1,acc.Id,u.Id,formA,formB);
	}
	
	@isTest static void manualShareRead() {
		// Implement test code
		List<E_Client_Suitability__c> ecs = [SELECT Id, OwnerId, Name, CS_Customer_Survey_A__c, CS_Customer_Survey_B__c, CS_RM__c FROM E_Client_Suitability__c Limit 1];
		List<Id> ecIdList = new List<Id>();
		for(E_Client_Suitability__c ec : ecs)
		{
			ecIdList.add(ec.Id);
		}
		CSEClientSharing.manualShareRead(ecIdList, ecs[0].CS_RM__c);
	}

	@isTest static void deleteSharingEclient() {
		// Implement test code
		List<E_Client_Suitability__c> ecs = [SELECT Id, OwnerId, Name, CS_Customer_Survey_A__c, CS_Customer_Survey_B__c, CS_RM__c FROM E_Client_Suitability__c Limit 1];
		List<Id> ecIdList = new List<Id>();
		for(E_Client_Suitability__c ec : ecs)
		{
			ecIdList.add(ec.Id);
		}
		CSEClientSharing.deleteSharingEclient(ecIdList);
	}

	
}