force-app/main/default/objects/Account/fields/Murex_Counter_Label__c.field-meta.xml
<CustomField>
    <fullName>Murex_Counter_Label__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Counter Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/E_Client_Suitability__c/E_Client_Suitability__c.object-meta.xml
<CustomObject>
    <label>E-Client Suitability</label>
    <nameField>
        <displayFormat>CS-{YYMMDD}-{000}</displayFormat>
        <label>E-Client Suitability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>E-Client Suitability</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/E_Client_Suitability__c/fields/Murex_Counter_Label__c.field-meta.xml
<CustomField>
    <fullName>Murex_Counter_Label__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Counter Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/Survey_Answer__c.object-meta.xml
<CustomObject>
    <label>Survey Answer</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Survey Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Answer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Answer__c/fields/Survey_Choice__c.field-meta.xml
<CustomField>
    <fullName>Survey_Choice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Choice</label>
    <referenceTo>Survey_Choice__c</referenceTo>
    <relationshipName>Customer_Survey_Answer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Question</label>
    <referenceTo>Survey_Question__c</referenceTo>
    <relationshipName>Customer_Survey_Answer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Survey_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Survey_Sheet__c</fullName>
    <label>Survey Sheet</label>
    <referenceTo>Survey_Sheet__c</referenceTo>
    <relationshipLabel>Survey Answer</relationshipLabel>
    <relationshipName>Survey_Answer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Choice__c/Survey_Choice__c.object-meta.xml
<CustomObject>
    <label>Survey Choice</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Survey Choice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Choice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Choice__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Question</label>
    <referenceTo>Survey_Question__c</referenceTo>
    <relationshipLabel>Survey Choice</relationshipLabel>
    <relationshipName>Survey_Choice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Manager__c/Survey_Manager__c.object-meta.xml
<CustomObject>
    <description>Survey Master for each survey form</description>
    <label>Survey Manager</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Manager</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Manager__c/fields/Survey_Version__c.field-meta.xml
<CustomField>
    <fullName>Survey_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Version</label>
    <referenceTo>Survey_Version__c</referenceTo>
    <relationshipLabel>Survey Manager</relationshipLabel>
    <relationshipName>FX_Survey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/Survey_Question__c.object-meta.xml
<CustomObject>
    <label>Survey Question</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Question</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question__c/fields/Survey_Version__c.field-meta.xml
<CustomField>
    <fullName>Survey_Version__c</fullName>
    <label>Survey Version</label>
    <referenceTo>Survey_Version__c</referenceTo>
    <relationshipLabel>Survey Question</relationshipLabel>
    <relationshipName>Survey_Question</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Sheet__c/Survey_Sheet__c.object-meta.xml
<CustomObject>
    <label>Survey Sheet</label>
    <nameField>
        <displayFormat>SS-{0000}</displayFormat>
        <label>Survey Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Sheet</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Sheet__c/fields/Survey_Version__c.field-meta.xml
<CustomField>
    <fullName>Survey_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Version</label>
    <referenceTo>Survey_Version__c</referenceTo>
    <relationshipName>Customer_Survey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Version__c/Survey_Version__c.object-meta.xml
<CustomObject>
    <label>Survey Version</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Survey Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Version</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Version__c/fields/Survey_Manager__c.field-meta.xml
<CustomField>
    <fullName>Survey_Manager__c</fullName>
    <label>Survey Manager</label>
    <referenceTo>Survey_Manager__c</referenceTo>
    <relationshipLabel>Survey Version</relationshipLabel>
    <relationshipName>Survey_Version</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CSReleatedSurveyQuestionListCtrlTest.cls
@isTest
private class CSReleatedSurveyQuestionListCtrlTest {
	
	
	@testSetup static void setup() {
		// Implement test code
	    AppConfig__c mc =new AppConfig__c(Name = 'runtrigger', Value__c = 'false');
        insert mc;

        User u = CSTestUtils.createUsers(1, 'UserTestqqq' ,'Userqqq' , 'test22@email.com' , false).get(0);
        u.IsActive = true;
        insert u;

		Account acc = CSTestUtils.createAccounts(1,false).get(0);
		acc.Murex_Counter_Label__c = 'eclient';
		insert acc;

		List<Survey_Manager__c> smList = CSTestUtils.createSurveyManager(2);
		Survey_Version__c sv1 = CSTestUtils.createSurveyVersion(1,smList[0]);
		Survey_Version__c sv2 = CSTestUtils.createSurveyVersion(2,smList[1]);

		Survey_Sheet__c formA = CSTestUtils.insertSurveySheet(smList[0], acc.Id,u.Id,'FormA');
		Survey_Sheet__c formB = CSTestUtils.insertSurveySheet(smList[1],acc.Id,u.Id,'FormB');

		Survey_Question__c Q1 = CSTestUtils.createSurveyQuestion(sv1.Id);
		Survey_Question__c subQ1 = CSTestUtils.createSurveySubQuestion(sv1.Id,Q1);
		Survey_Choice__c subChoiceA =  CSTestUtils.createSurveyChoiceSub(subQ1);
		Survey_Choice__c choiceQ1 = CSTestUtils.createSurveyChoice(Q1);
		Survey_Answer__c saQ1 = CSTestUtils.createSurveyAnswer(Q1,choiceQ1,formA);

		List<E_Client_Suitability__c> esList = CSTestUtils.createEclient(1,acc.Id,u.Id,formA,formB);
	}

		@isTest static void getQuestionList() {
		// Implement test code
		List<Survey_Question__c> sq = [SELECT Id FROM Survey_Question__c Limit 1];
		CSReleatedSurveyQuestionListController.getQuestionList(sq[0].Id);
	}
	
}