force-app/main/default/objects/Account/fields/Owner_Assignment_Rule__c.field-meta.xml
<CustomField>
    <fullName>Owner_Assignment_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner Assignment Rule</label>
    <referenceTo>Owner_Assignment_Rule__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Owner_Assignment_Rule__c/Owner_Assignment_Rule__c.object-meta.xml
<CustomObject>
    <label>Owner Assignment Rule</label>
    <nameField>
        <displayFormat>OWNER-ASSGMNT-RULE-{0000}</displayFormat>
        <label>Owner Assignment Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Owner Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Owner_Assignment_Rule__c/fields/Criteria_Field_Value_1__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Field_Value_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value of criteria such as if Entry Criteria is &quot;Core_Banking_Suggested_Segment__c&quot;, the input value must be &quot;SE&quot;, &quot;BB&quot;, &quot;CB&quot; or &quot;MB&quot;.</inlineHelpText>
    <label>Criteria Field Value 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Owner_Assignment_Rule__c/fields/Criteria_Field_Value_2__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Field_Value_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value of criteria such as if Entry Criteria is &quot;Core_Banking_Suggested_Segment__c&quot;, the input value must be &quot;SE&quot;, &quot;BB&quot;, &quot;CB&quot; or &quot;MB&quot;.</inlineHelpText>
    <label>Criteria Field Value 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Owner_Assignment_Rule__c/fields/Criteria_Field_Value_3__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Field_Value_3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Criteria Field Value 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Owner_Assignment_Rule__c/fields/Criteria_Field_Value_4__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Field_Value_4__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Criteria Field Value 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Owner_Assignment_Rule__c/fields/Criteria_Field_Value_5__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Field_Value_5__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Criteria Field Value 5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Owner_Assignment_Rule__c/fields/Entry_Criteria_Field_1__c.field-meta.xml
<CustomField>
    <fullName>Entry_Criteria_Field_1__c</fullName>
    <inlineHelpText>Field to be use as rule entry criteria such as Core_Banking_Suggested_Segment__c or Province_Primary_PE__c.</inlineHelpText>
    <label>Entry Criteria Field 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core_Banking_Suggested_Segment__c</fullName>
            </value>
            <value>
                <fullName>Province_Primary_PE__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Owner_Assignment_Rule__c/fields/Entry_Criteria_Field_2__c.field-meta.xml
<CustomField>
    <fullName>Entry_Criteria_Field_2__c</fullName>
    <inlineHelpText>Field to be use as rule entry criteria such as Core_Banking_Suggested_Segment__c or Province_Primary_PE__c.</inlineHelpText>
    <label>Entry Criteria Field 2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core_Banking_Suggested_Segment__c</fullName>
            </value>
            <value>
                <fullName>Province_Primary_PE__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Owner_Assignment_Rule__c/fields/Entry_Criteria_Field_3__c.field-meta.xml
<CustomField>
    <fullName>Entry_Criteria_Field_3__c</fullName>
    <label>Entry Criteria Field 3</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core_Banking_Suggested_Segment__c</fullName>
            </value>
            <value>
                <fullName>Province_Primary_PE__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Owner_Assignment_Rule__c/fields/Entry_Criteria_Field_4__c.field-meta.xml
<CustomField>
    <fullName>Entry_Criteria_Field_4__c</fullName>
    <label>Entry Criteria Field 4</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core_Banking_Suggested_Segment__c</fullName>
            </value>
            <value>
                <fullName>Province_Primary_PE__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Owner_Assignment_Rule__c/fields/Entry_Criteria_Field_5__c.field-meta.xml
<CustomField>
    <fullName>Entry_Criteria_Field_5__c</fullName>
    <label>Entry Criteria Field 5</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core_Banking_Suggested_Segment__c</fullName>
            </value>
            <value>
                <fullName>Province_Primary_PE__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountOwnerAssignmentBatchUtil.cls
public class AccountOwnerAssignmentBatchUtil {

    public static Boolean checkCriteria(Account acct, Owner_Assignment_Rule__c rule){
        Boolean result = false;

        Boolean cond1 = !RTL_Utility.isNotNull(rule.Entry_Criteria_Field_1__c);
        Boolean cond2 = !RTL_Utility.isNotNull(rule.Entry_Criteria_Field_2__c);
        Boolean cond3 = !RTL_Utility.isNotNull(rule.Entry_Criteria_Field_3__c);
        Boolean cond4 = !RTL_Utility.isNotNull(rule.Entry_Criteria_Field_4__c);
        Boolean cond5 = !RTL_Utility.isNotNull(rule.Entry_Criteria_Field_5__c);

        cond1 = checkCondition(rule.Entry_Criteria_Field_1__c, acct, rule.Criteria_Field_Value_1__c);
        // System.debug('cond1 : ' + cond1);
        cond2 = checkCondition(rule.Entry_Criteria_Field_2__c, acct, rule.Criteria_Field_Value_2__c);
        // System.debug('cond2 : ' + cond2);
        cond3 = checkCondition(rule.Entry_Criteria_Field_3__c, acct, rule.Criteria_Field_Value_3__c);
        // System.debug('cond3 : ' + cond3);
        cond4 = checkCondition(rule.Entry_Criteria_Field_4__c, acct, rule.Criteria_Field_Value_4__c);
        // System.debug('cond4 : ' + cond4);
        cond5 = checkCondition(rule.Entry_Criteria_Field_5__c, acct, rule.Criteria_Field_Value_5__c);
        // System.debug('cond5 : ' + cond5);

        if(cond1 && cond2 && cond3 && cond4 && cond5){
            result = true;           
        }

        return result;
    }

    private static Boolean checkCondition(String cond, SObject data, String condValue){
        if(cond == null || cond == ''){
            return true;
        }
        
        // System.debug(cond);
        // System.debug(data.get(cond));
        // System.debug(condValue);
        
        if(String.valueOf(data.get(cond)) == condValue){
        	return true;    
        }
        return false;
    }
}