force-app/main/default/objects/Account/fields/Remark__c.field-meta.xml
<CustomField>
    <fullName>Remark__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Remark</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segment_crm__c.field-meta.xml
<CustomField>
    <fullName>Segment_crm__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Segment_crm</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/Product_Volume_Information__c.object-meta.xml
<CustomObject>
    <label>Product Volume Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Volume Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Volume Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Volume_Information__c/fields/Account_Status_Desc__c.field-meta.xml
<CustomField>
    <fullName>Account_Status_Desc__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Status Desc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Account_Suffix_Ref__c.field-meta.xml
<CustomField>
    <fullName>Account_Suffix_Ref__c</fullName>
    <description>เลขที่บัญชี+Suffix+ACCOUNT REF</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Account/Suffix/Ref</label>
    <length>33</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Average_Balance_BE__c.field-meta.xml
<CustomField>
    <fullName>Average_Balance_BE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Average Balance (BE)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Average_Balance_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Average_Balance_Deposit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Average Balance (Deposit)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Average_Balance_Loan__c.field-meta.xml
<CustomField>
    <fullName>Average_Balance_Loan__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Average Balance (Loan)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Business_Readiness_Level_BRL__c.field-meta.xml
<CustomField>
    <fullName>Business_Readiness_Level_BRL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Readiness Level (BRL)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Current_4G__c.field-meta.xml
<CustomField>
    <fullName>Current_4G__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Current 4G</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Volume Informations</relationshipLabel>
    <relationshipName>Product_Volume_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Ending_Balance_BE__c.field-meta.xml
<CustomField>
    <fullName>Ending_Balance_BE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Ending Balance (BE)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Ending_Balance_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Ending_Balance_Deposit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Ending Balance (Deposit)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Ending_Balance_Loan__c.field-meta.xml
<CustomField>
    <fullName>Ending_Balance_Loan__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Ending Balance (Loan)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Gross_Rate__c.field-meta.xml
<CustomField>
    <fullName>Gross_Rate__c</fullName>
    <label>Gross Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Liability_O_S__c.field-meta.xml
<CustomField>
    <fullName>Liability_O_S__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Liability O/S</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Limit_Loan__c.field-meta.xml
<CustomField>
    <fullName>Limit_Loan__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Limit (Loan)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>Loan_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Loan Status</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Volume Informations</relationshipLabel>
    <relationshipName>Product_Volume_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/RPN_Type__c.field-meta.xml
<CustomField>
    <fullName>RPN_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RPN Type</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/TMB_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>TMB_Account_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TMB Account ID</label>
    <length>14</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/TMB_Ref__c.field-meta.xml
<CustomField>
    <fullName>TMB_Ref__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TMB Ref</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Volume_Information__c/fields/TMB_Suffix__c.field-meta.xml
<CustomField>
    <fullName>TMB_Suffix__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TMB Suffix</label>
    <length>14</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductVolumeInformationTriggerHandTest.cls
@isTest
global class ProductVolumeInformationTriggerHandTest {
    static{
        TestUtils.createAppConfig();
        
        
        AppConfig__c Aconfig = new AppConfig__c();
        Aconfig.Name = 'runtrigger';
        Aconfig.Value__c = 'true';        
        insert Aconfig;
    }

    @IsTest
    static void testCreateProdVol(){
        List<Account> existingAccts = TestUtils.createAccounts(1, 'nametestforecast', 'Existing Customer', false);

        existingAccts.get(0).RecordTypeId = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Existing Customer').getRecordTypeId();
        existingAccts.get(0).Segment_crm__c = '1';
        
        insert existingAccts;

        List<Product2> prdlst = new List<Product2>();
        Product2 prd = new Product2();
        prd.Name = 'LT Loan';
        prd.isActive = true;
        prd.FLAG_RTL_Product__c = false;
        prd.Financial_Product_Code__c = 'CAH1';
        prd.Financial_Product_Domain__c = 'Credit';
        prd.Financial_Product_Group_Name__c = 'LT Loan';
        prd.Financial_Product_Group__c = 'Loan';
        prd.Financial_Product_ID__c = '110101';
        prd.Forecast_NIIc_NIId_Flag__c = true;
        prd.Remark__c = 'LT loan';
        prd.Sub_Remark__c = 'non-Trade';
        prdlst.add(prd);
        insert prdlst;

        Product_Volume_Information__c prdVol = new Product_Volume_Information__c();
        prdVol.Account_Status_Desc__c = 'Account_Status_Desc__c';
        prdVol.Account_Suffix_Ref__c = '001aLT-G1-Acc1';
        prdVol.As_of_Date__c = Date.today().addMonths(-1);
        prdVol.Average_Balance_BE__c = 0;
        prdVol.Average_Balance_Deposit__c = 0;
        prdVol.Average_Balance_Loan__c = 1000000;
        prdVol.Business_Readiness_Level_BRL__c = 'High';
        prdVol.Current_4G__c = '01.Guard';
        prdVol.Customer__c = existingAccts.get(0).Id;
        prdVol.Ending_Balance_BE__c = 0;
        prdVol.Ending_Balance_Deposit__c = 0;
        prdVol.Ending_Balance_Loan__c = 1000000;
        prdVol.Gross_Rate__c = 0;
        prdVol.Interest_Revenue__c = 0;
        prdVol.Issue_Date__c = Date.today().addDays(-2);
        prdVol.Liability_O_S__c = 0;
        prdVol.Limit_Loan__c = 1000000;
        prdVol.Loan_Status__c = 'PL';
        prdVol.Maturity_Date__c = Date.today().addYears(1);
        prdVol.Origination_Date__c = Date.today().addDays(-2);
        prdVol.Product_Code__c = 'CAH1';
        prdVol.Product_Group__c = 'Loan';
        prdVol.Product_ID__c = '78998';
        prdVol.Product_Type__c = 'LT Loan';
        prdVol.Product__c = prdlst.get(0).Id;
        prdVol.RPN_Type__c = '';
        prdVol.SABS_Type__c = 'BU';
        prdVol.TMB_Account_ID__c = '001';
        prdVol.TMB_Ref__c = 'a';
        prdVol.TMB_Suffix__c = 'LT-G1-Acc1';
        prdVol.Unused_Balance__c  = 0;

        Test.startTest();
        insert prdVol;
        Test.stopTest();
    }
}