force-app/main/default/objects/Account/fields/RTL_Wealth_RM__c.field-meta.xml
<CustomField>
    <fullName>RTL_Wealth_RM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CR Wealth RM Info , convert EMP/BR Code to Wealth RM</description>
    <label>Wealth RM/BM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Retail_Customer.recordType-meta.xml
<RecordType>
    <fullName>Retail_Customer</fullName>
    <active>true</active>
    <description>For Retail Customer Accounts</description>
    <label>Retail Customer</label>
</RecordType>

force-app/main/default/objects/Data_Security_Matrix__c/Data_Security_Matrix__c.object-meta.xml
<CustomObject>
    <description>Table to maintain data partition security matrix for each profile</description>
    <label>Data Security Matrix</label>
    <nameField>
        <displayFormat>SEC-{0000}</displayFormat>
        <label>Data Security Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Security Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Security_Matrix__c/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <label>Access Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Authorize Only</fullName>
            </value>
            <value>
                <fullName>No Access</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Security_Matrix__c/fields/Data_Matrix_Key__c.field-meta.xml
<CustomField>
    <fullName>Data_Matrix_Key__c</fullName>
    <description>Profile_Name__c+Section_Name__c</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Data Matrix Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Data_Security_Matrix__c/fields/Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Profile_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Profile Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Security_Matrix__c/fields/Section_Name__c.field-meta.xml
<CustomField>
    <fullName>Section_Name__c</fullName>
    <label>Section Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ComCust:Account Information</fullName>
            </value>
            <value>
                <fullName>ComCust:Address Information</fullName>
            </value>
            <value>
                <fullName>ComCust:Campaign Lead History</fullName>
            </value>
            <value>
                <fullName>ComCust:Collateral</fullName>
            </value>
            <value>
                <fullName>ComCust:Contact Information</fullName>
            </value>
            <value>
                <fullName>ComCust:Contacts</fullName>
            </value>
            <value>
                <fullName>ComCust:Executive Summary/Account Plan</fullName>
            </value>
            <value>
                <fullName>ComCust:Other Information</fullName>
            </value>
            <value>
                <fullName>ComCust:Performance</fullName>
            </value>
            <value>
                <fullName>ComCust:Pipeline</fullName>
            </value>
            <value>
                <fullName>ComCust:Product On Hand</fullName>
            </value>
            <value>
                <fullName>ComCust:Product On Hand (Partition)</fullName>
            </value>
            <value>
                <fullName>ComCust:Risk Information</fullName>
            </value>
            <value>
                <fullName>ComCust:Wallet</fullName>
            </value>
            <value>
                <fullName>ComPros:Customer Information</fullName>
            </value>
            <value>
                <fullName>ComPros:Customer Source</fullName>
            </value>
            <value>
                <fullName>ComPros:Detail Information</fullName>
            </value>
            <value>
                <fullName>ComPros:General Information</fullName>
            </value>
            <value>
                <fullName>ComPros:Product Interest</fullName>
            </value>
            <value>
                <fullName>ComPros:Re-assignment Customer</fullName>
            </value>
            <value>
                <fullName>RtlCust:Address Information</fullName>
            </value>
            <value>
                <fullName>RtlCust:Alternative Contact Information</fullName>
            </value>
            <value>
                <fullName>RtlCust:Campaign History</fullName>
            </value>
            <value>
                <fullName>RtlCust:Contact Number and Email Address</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Demographic (High)</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Demographic (Low)</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Demographic (Medium)</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Insight - Personalized Information</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Product Holding (High)</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Product Holding (Low)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PowerBiListComponentExtension_Test.cls
@isTest
private class PowerBiListComponentExtension_Test {
    public static String testWealthUser = 'wealth@test-tmbbank.com';
    public static String testNonWealthUser = 'non-wealth@test-tmbbank.com';
    @testSetup static void setup() {
        TestUtils.createAppConfig();
        List<Account> accList = RTL_TestUtility.createAccounts(1,true);
        //create test user
        User adminUser = [SELECT Id FROM User WHERE Id =: UserInfo.getUserId()];
        System.runAs(adminUser){
            //Create User Wealth Management Test
            Profile wealthManagementRMCockpit = [SELECT Id FROM Profile WHERE Name ='TMB Retail Wealth Management RM Cockpit'];
            UserRole userRoleWM_SS_2_6 = [SELECT Id FROM UserRole WHERE DeveloperName = 'WM_SS_2_6'];
            User testUser = new User(
                FirstName = 'wealth test',
                LastName = 'wealth test',
                UserName=PowerBiListComponentExtension_Test.testWealthUser,
                Email=PowerBiListComponentExtension_Test.testWealthUser, 
                Alias='w-testus',
                LocaleSidKey='en_US', 
                LanguageLocaleKey='en_US', 
                EmailEncodingKey='ISO-8859-1',
                ProfileId = wealthManagementRMCockpit.Id,
                UserRoleId = userRoleWM_SS_2_6.Id,
                TimeZoneSidKey='America/New_York',
                isActive = true,
                Employee_ID__c ='MM01t'
            );
            insert testUser;
        }
        System.runAs(adminUser){
            //setup data security matrix
            Data_Security_Matrix__c testSecurityMatrix = new Data_Security_Matrix__c(
                Access_Type__c = 'Authorize Only',
                Data_Matrix_Key__c = 'TMB Retail Wealth Management RM CockpitRtlCust:Customer Product Holding (High)',
                Profile_Name__c = 'TMB Retail Wealth Management RM Cockpit',
                Section_Name__c = 'RtlCust:Customer Product Holding (High)'
            );
            insert testSecurityMatrix;
        }
        System.runAs(adminUser){
            //Create User Non-Wealth Management Test
            Profile retailChannelSales = [SELECT Id FROM Profile WHERE Name ='TMB Retail Channel Sales'];
            UserRole userRoleBR_Sales_Zone_1870 = [SELECT Id FROM UserRole WHERE DeveloperName = 'BR_Sales_Zone_1870'];
            User testUser = new User(
                FirstName = 'non-wealth test',
                LastName = 'non-wealth test',
                UserName=PowerBiListComponentExtension_Test.testNonWealthUser,
                Email=PowerBiListComponentExtension_Test.testNonWealthUser, 
                Alias='mw-test',
                LocaleSidKey='en_US', 
                LanguageLocaleKey='en_US', 
                EmailEncodingKey='ISO-8859-1',
                ProfileId = retailChannelSales.Id,
                UserRoleId = userRoleBR_Sales_Zone_1870.Id,
                TimeZoneSidKey='America/New_York',
                isActive = true,
                Employee_ID__c ='non-w01t'
            );
            insert testUser;
        }
    }

    @isTest static void Test_WealthUser_PowerBiListComponentExtension() {
        User testUser = [SELECT Id FROM User WHERE UserName=:PowerBiListComponentExtension_Test.testWealthUser];
        Account acc = [SELECT Id,RTL_Wealth_RM__c,RTL_Wealth_RM__r.UserName,RecordType.DeveloperName FROM Account LIMIT 1];
        acc.RTL_Wealth_RM__c = testUser.Id;
        acc.OwnerId = testUser.Id;
        update acc;
        system.assertEquals('Retail_Customer',acc.RecordType.DeveloperName,'Account should be retail customer');
        Test.startTest();
        System.runAs(testUser){
            Account acObj = [SELECT Id FROM Account LIMIT 1];
            ApexPages.StandardController sc1 = new ApexPages.StandardController(acObj);
            PageReference powerbiListPage = Page.PowerBiListComponent;
            powerbiListPage.getparameters().put('id',acObj.id);
            Test.setCurrentPage(powerbiListPage);
            PowerBiListComponentExtension biExten = New PowerBiListComponentExtension(sc1);
            system.assertEquals(true,biExten.IsAccess,'User should have access');
        }
        Test.stopTest();
    }

    @isTest static void Test_Non_WealthUser_PowerBiListComponentExtension() {
        User testUser = [SELECT Id FROM User WHERE UserName=:PowerBiListComponentExtension_Test.testNonWealthUser];
        Account acc = [SELECT Id,RTL_Wealth_RM__c,RTL_Wealth_RM__r.UserName,RecordType.DeveloperName FROM Account LIMIT 1];
        acc.RTL_Wealth_RM__c = testUser.Id;
        acc.OwnerId = testUser.Id;
        update acc;
        Test.startTest();
        System.runAs(testUser){
            Account acObj = [SELECT Id FROM Account LIMIT 1];
            ApexPages.StandardController sc1 = new ApexPages.StandardController(acObj);
            PageReference powerbiListPage = Page.PowerBiListComponent;
            powerbiListPage.getparameters().put('id',acObj.id);
            Test.setCurrentPage(powerbiListPage);
            PowerBiListComponentExtension biExten = New PowerBiListComponentExtension(sc1);
            system.assertEquals(false,biExten.IsAccess,'User should have not access');
        }
        Test.stopTest();
    }
}