force-app/main/default/objects/Account/fields/RTL_Wealth_RM__c.field-meta.xml
<CustomField>
    <fullName>RTL_Wealth_RM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CR Wealth RM Info , convert EMP/BR Code to Wealth RM</description>
    <label>Wealth RM/BM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TMB_Customer_ID_PE__c.field-meta.xml
<CustomField>
    <fullName>TMB_Customer_ID_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>TMB Customer ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Advisory_Planning__c/Advisory_Planning__c.object-meta.xml
<CustomObject>
    <label>Advisory Planning</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Advisory Planning ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advisory Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Advisory_Planning__c/fields/Advisory_Planning_Name__c.field-meta.xml
<CustomField>
    <fullName>Advisory_Planning_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Advisory Planning Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Advisory_Planning__c/fields/Baseline_Advisory_Planning_Date__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Advisory_Planning_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Baseline Advisory Planning Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Advisory_Planning__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advisory Plannings</relationshipLabel>
    <relationshipName>Advisory_Plannings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advisory_Planning__c/fields/Is_Sync_Product_Holding__c.field-meta.xml
<CustomField>
    <fullName>Is_Sync_Product_Holding__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To indicate that this advisory planning already be sync to get the current product holding.</description>
    <label>IsSyncProductHolding</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Advisory_Planning__c/fields/Target_Advisory_Planning_Date__c.field-meta.xml
<CustomField>
    <fullName>Target_Advisory_Planning_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Target Advisory Planning Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Advisory_Planning_Item__c/Advisory_Planning_Item__c.object-meta.xml
<CustomObject>
    <description>Advisory Planning Item Informatiton.</description>
    <label>Advisory Planning Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Advisory Planning Item No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advisory Planning Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advisory_Planning_Item__c/fields/Advisory_Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Advisory_Item_Type__c</fullName>
    <description>The advisory planning item type, using to identify which tab that the item is belonged to.</description>
    <label>Advisory Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Risk</fullName>
            </value>
            <value>
                <fullName>Expense &amp; Liquidity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advisory_Planning_Item__c/fields/Advisory_Planning__c.field-meta.xml
<CustomField>
    <fullName>Advisory_Planning__c</fullName>
    <description>The advisory planning master.</description>
    <label>Advisory Planning</label>
    <referenceTo>Advisory_Planning__c</referenceTo>
    <relationshipLabel>Advisory Planning Items</relationshipLabel>
    <relationshipName>Advisory_Planning_and_RTL_Product_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advisory_Planning_Item__c/fields/Baseline_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Allocation__c</fullName>
    <description>The baseline allocation percentage based on each advisory item type.</description>
    <label>Baseline Allocation (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Advisory_Planning_Item__c/fields/Baseline_Amount__c.field-meta.xml
<CustomField>
    <fullName>Baseline_Amount__c</fullName>
    <description>The baseline amount or the outstanding amount for each product item.</description>
    <label>Baseline Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Advisory_Planning_Item__c/fields/Is_Product_Holding__c.field-meta.xml
<CustomField>
    <fullName>Is_Product_Holding__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To indicate that planning item is from the product holding or not.</description>
    <label>IsProductHolding</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Advisory_Planning_Item__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>The product family information for each item.</description>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INVESTMENT</fullName>
            </value>
            <value>
                <fullName>DEPOSIT</fullName>
            </value>
            <value>
                <fullName>BOND</fullName>
            </value>
            <value>
                <fullName>BANCASSURANCE</fullName>
            </value>
            <value>
                <fullName>AUTO LOAN</fullName>
            </value>
            <value>
                <fullName>LOAN</fullName>
            </value>
            <value>
                <fullName>PERSONAL LOAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advisory_Planning_Item__c/fields/Product_Holding_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Holding_Code__c</fullName>
    <description>The product holding code  from current holding product.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Advisory_Planning_Item__c/fields/Product_Master__c.field-meta.xml
<CustomField>
    <fullName>Product_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The reference product master information (if any).</description>
    <label>Product Master</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Advisory Planning Items</relationshipLabel>
    <relationshipName>Advisory_Planning_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advisory_Planning_Item__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>The name of advisory product.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Name</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Advisory_Planning_Item__c/fields/Product_Sub_Group_Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Group_Asset_Class__c</fullName>
    <description>The values from field Sub Family and Asset Class of that product.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Sub Group - Asset Class</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Advisory_Planning_Item__c/fields/RMC_1Year_Return__c.field-meta.xml
<CustomField>
    <fullName>RMC_1Year_Return__c</fullName>
    <description>The 1 year return of the investment product.</description>
    <formula>IF(ISNULL(Product_Master__r.RMC_1Year_Return__c), 0, Product_Master__r.RMC_1Year_Return__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>1 Year Return (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Advisory_Planning_Item__c/fields/Target_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Target_Allocation__c</fullName>
    <description>The target allocation percentage based on each advisory item type.</description>
    <label>Target Allocation (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Advisory_Planning_Item__c/fields/Target_Amount__c.field-meta.xml
<CustomField>
    <fullName>Target_Amount__c</fullName>
    <description>The target amount or the outstanding amount for each product item.</description>
    <label>Target Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMC_AppConfig__c/RMC_AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The configurable setting for RM - Cockpits Module.</description>
    <label>RM Cockpits - AppConfig</label>
</CustomObject>

force-app/main/default/objects/RMC_AppConfig__c/fields/RMC_Latest_Update_of_MF_Return__c.field-meta.xml
<CustomField>
    <fullName>RMC_Latest_Update_of_MF_Return__c</fullName>
    <description>The latest updated date of MF return rate</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Latest Update of MF Return</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AdvisoryPlanningEditAllocServices_Test.cls
@isTest
public without sharing class AdvisoryPlanningEditAllocServices_Test {

    @testSetup 
    static void setup() {
        TestUtils.createAppConfig();

        List<AppConfig__c> mc = new List<AppConfig__c> ();
        mc.Add(new AppConfig__c(Name = 'runtrigger', Value__c = 'false'));
        insert mc;

        RMC_AppConfig__c appConfig = new RMC_AppConfig__c();
        appConfig.RMC_Latest_Update_of_MF_Return__c = DateTime.now();
        insert appConfig;

        List<Account> acct = TestUtils.createAccounts(1, 'Fname', 'Individual', false);
        acct[0].TMB_Customer_ID_PE__c = '001100000000000000000000000500';
        acct[0].RTL_Wealth_RM__c = UserInfo.getUserId();
        insert acct;

        Advisory_Planning__c planning = new Advisory_Planning__c(
            Advisory_Planning_Name__c = 'test planning',
            Baseline_Advisory_Planning_Date__c = Date.today(),
            Is_Sync_Product_Holding__c = true,
            Target_Advisory_Planning_Date__c = Date.today().addDays(30),
            Customer__c = acct[0].Id
        );
        insert  planning;

        List<Product2> productList = new List<Product2>();
        Product2 prod1 = new Product2(
            Name = 'Test Product 1',
            Product_Domain__c = '1. Transactional Banking',
            RTL_Product_Name_ENG__c = 'Test Product EN 1',
            RTL_Product_Name_TH__c = 'Test Product TH 1',
            Sub_Family__c = 'Non',
            IsActive = true,
            Family = 'INVESTMENT',
            ProductCode = 'JBPLTF1',
            RMC_1Year_Return__c = 12.021,
            RMC_Latest_Update_of_MF_Return__c = DateTime.now(),
            RTL_Asset_Class__c = 'FF'
        );
        productList.add(prod1);

        Product2 prod2 = new Product2(
            Name = 'Test Product 2',
            RTL_Product_Name_ENG__c = 'Test Product EN 2',
            RTL_Product_Name_TH__c = 'Test Product TH 2',
            Sub_Family__c = 'Non',
            Product_Domain__c = '1. Transactional Banking',
            IsActive = true,
            Family = 'INVESTMENT',
            ProductCode = 'JBPLTF2',
            RTL_Asset_Class__c = 'FF',
            RMC_1Year_Return__c = 12.021,
            RMC_Latest_Update_of_MF_Return__c = DateTime.now()
        );
        productList.add(prod2);

        insert productList;

        List<Advisory_Planning_Item__c> itemList  =  new List<Advisory_Planning_Item__c>();

        Product2 eachProduct = productList.get(0);
        Advisory_Planning_Item__c eachPlanningItem = new Advisory_Planning_Item__c(
            Name = 'Test',
            Advisory_Planning__c = planning.Id,
            Advisory_Item_Type__c = 'Return',
            Is_Product_Holding__c = false,
            Product_Group__c      = 'INVESTMENT',
            Baseline_Amount__c    = 5000,
            Baseline_Allocation__c    = 1,
            Target_Amount__c    = 100000,
            Target_Allocation__c    = 1,
            Product_Master__c = eachProduct.Id ,
            Product_Name__c = eachProduct.RTL_Product_Name_ENG__c,
            Product_Holding_Code__c = eachProduct.ProductCode,
            Product_Sub_Group_Asset_Class__c =  eachProduct.Sub_Family__c
        );
        itemList.add(eachPlanningItem);

        Advisory_Planning_Item__c eachBond = new Advisory_Planning_Item__c(
            Name = 'Test Bond',
            Advisory_Planning__c = planning.Id,
            Advisory_Item_Type__c = 'Return',
            Is_Product_Holding__c = false,
            Product_Group__c      = 'Bond',
            Baseline_Amount__c    = 5000,
            Baseline_Allocation__c    = 1,
            Target_Amount__c    = 100000,
            Target_Allocation__c    = 1,
            Product_Master__c = null ,
            Product_Name__c =  'test bond',
            Product_Holding_Code__c = 'test bond code',
            Product_Sub_Group_Asset_Class__c =  'Debenture'
        );
        itemList.add(eachBond);
        insert itemList;
    }

    @isTest
    private static void Test_getProductInformation_Keyword1() {
        Product2 eachProduct = [SELECT Id FROM Product2 LIMIT 1];

        Test.startTest();
            List<String> existingProduuctIdSet  = new List<String>();
            existingProduuctIdSet.add(eachProduct.Id);

            List<String> productFamilySet = new List<String>();
            productFamilySet.add('INVESTMENT');

            AdvisoryPlanningEditAllocationServices.ProductSearchCriteria criteria = new AdvisoryPlanningEditAllocationServices.ProductSearchCriteria();
            criteria.productFamily = productFamilySet;
            criteria.keyword1 = 'Product TH';
            criteria.keyword2 = 'Product EN';
            criteria.keyword3 = 'Non';
            criteria.existingProduuctIdSet = existingProduuctIdSet;
            criteria.maxReturnRow = 50;
            AdvisoryPlanningEditAllocationServices.getProductInformation(criteria);
        Test.stopTest();

    }

    @isTest
    private static void Test_getProductInformation_Keyword2() {
        Product2 eachProduct = [SELECT Id FROM Product2 LIMIT 1];

        Test.startTest();
            List<String> existingProduuctIdSet  = new List<String>();
            existingProduuctIdSet.add(eachProduct.Id);

            List<String> productFamilySet = new List<String>();
            productFamilySet.add('INVESTMENT');

            AdvisoryPlanningEditAllocationServices.ProductSearchCriteria criteria = new AdvisoryPlanningEditAllocationServices.ProductSearchCriteria();
            criteria.productFamily = productFamilySet;
            criteria.keyword1 = 'Product EN';
            criteria.keyword2 = 'Product TH';
            criteria.keyword3 = 'Non';
            criteria.existingProduuctIdSet = existingProduuctIdSet;
            criteria.maxReturnRow = 50;
            AdvisoryPlanningEditAllocationServices.getProductInformation(criteria);
        Test.stopTest();

    }

    @isTest
    private static void Test_getProductInformation_Keyword3() {
        Product2 eachProduct = [SELECT Id FROM Product2 LIMIT 1];

        Test.startTest();
            List<String> existingProduuctIdSet  = new List<String>();
            existingProduuctIdSet.add(eachProduct.Id);

            List<String> productFamilySet = new List<String>();
            productFamilySet.add('INVESTMENT');

            AdvisoryPlanningEditAllocationServices.ProductSearchCriteria criteria = new AdvisoryPlanningEditAllocationServices.ProductSearchCriteria();
            criteria.productFamily = productFamilySet;
            criteria.keyword1 = 'Product EN';
            criteria.keyword2 = 'Non';
            criteria.keyword3 = 'Product TH';
            criteria.existingProduuctIdSet = existingProduuctIdSet;
            criteria.maxReturnRow = 50;
            AdvisoryPlanningEditAllocationServices.getProductInformation(criteria);
        Test.stopTest();

    }


    @isTest
    private static void Test_saveAdvisoryPlanningItem_Blank() {
        Test.startTest();
            List<Advisory_Planning_Item__c> itemList  =  new List<Advisory_Planning_Item__c>();
            AdvisoryPlanningEditAllocationServices.saveAdvisoryPlanningItem(null, itemList, null);
        Test.stopTest();

    }

    @isTest
    private static void Test_saveAdvisoryPlanningItem() {
        Advisory_Planning__c planning = [SELECT Id FROM Advisory_Planning__c LIMIT 1];
        Product2 eachProduct = [SELECT Id,RTL_Product_Name_ENG__c,ProductCode, Sub_Family__c FROM Product2 LIMIT 1];
        List<Advisory_Planning_Item__c> existingItemList =  [SELECT Id,Advisory_Item_Type__c,Product_Group__c,Target_Allocation__c,Target_Amount__c,Baseline_Allocation__c,Advisory_Planning__c
                                                             FROM Advisory_Planning_Item__c];
        Advisory_Planning_Item__c existingItem = existingItemList.get(0);
        existingItem.Target_Amount__c = 2000000;

        Test.startTest();
            List<Advisory_Planning_Item__c> itemList  =  new List<Advisory_Planning_Item__c>();

            Advisory_Planning_Item__c eachPlanningItem = new Advisory_Planning_Item__c(
                Name = 'Test',
                Advisory_Planning__c = planning.Id,
                Advisory_Item_Type__c = 'Return',
                Is_Product_Holding__c = false,
                Product_Group__c      = 'INVESTMENT',
                Baseline_Amount__c    = 5000,
                Baseline_Allocation__c    = 1,
                Target_Amount__c    = 100000,
                Target_Allocation__c    = 1,
                Product_Master__c = eachProduct.Id ,
                Product_Name__c = eachProduct.RTL_Product_Name_ENG__c,
                Product_Holding_Code__c = eachProduct.ProductCode,
                Product_Sub_Group_Asset_Class__c =  eachProduct.Sub_Family__c
            );
            itemList.add(eachPlanningItem);

            Advisory_Planning_Item__c eachBond = new Advisory_Planning_Item__c(
                Name = 'Test Bond',
                Advisory_Planning__c = planning.Id,
                Advisory_Item_Type__c = 'Return',
                Is_Product_Holding__c = false,
                Product_Group__c      = 'Bond',
                Baseline_Amount__c    = 5000,
                Baseline_Allocation__c    = 1,
                Target_Amount__c    = 100000,
                Target_Allocation__c    = 1,
                Product_Master__c = null ,
                Product_Name__c =  'test bond',
                Product_Holding_Code__c = 'test bond code',
                Product_Sub_Group_Asset_Class__c =  'Debenture'
            );
            itemList.add(eachBond);
            itemList.add(existingItem);
            itemList.add(existingItemList.get(1));

            AdvisoryPlanningEditAllocationServices.saveAdvisoryPlanningItem(planning.Id, itemList, null);
        Test.stopTest();

    }

    @isTest
    private static void Test_saveAdvisoryPlanningItemWithDelete() {
        Advisory_Planning__c planning = [SELECT Id FROM Advisory_Planning__c LIMIT 1];
        Product2 eachProduct = [SELECT Id,RTL_Product_Name_ENG__c,ProductCode, Sub_Family__c FROM Product2 LIMIT 1];
        List<Advisory_Planning_Item__c> existingItemList =  [SELECT Id FROM Advisory_Planning_Item__c LIMIT 1];
        List<String> toDeleteList = new List<String>();
        toDeleteList.add(existingItemList[0].Id);

        Test.startTest();
            List<Advisory_Planning_Item__c> itemList  =  new List<Advisory_Planning_Item__c>();

            Advisory_Planning_Item__c eachPlanningItem = new Advisory_Planning_Item__c(
                Name = 'Test',
                Advisory_Planning__c = planning.Id,
                Advisory_Item_Type__c = 'Return',
                Is_Product_Holding__c = false,
                Product_Group__c      = 'INVESTMENT',
                Baseline_Amount__c    = 5000,
                Baseline_Allocation__c    = 1,
                Target_Amount__c    = 100000,
                Target_Allocation__c    = 1,
                Product_Master__c = eachProduct.Id ,
                Product_Name__c = eachProduct.RTL_Product_Name_ENG__c,
                Product_Holding_Code__c = eachProduct.ProductCode,
                Product_Sub_Group_Asset_Class__c =  eachProduct.Sub_Family__c
            );
            itemList.add(eachPlanningItem);

            Advisory_Planning_Item__c eachBond = new Advisory_Planning_Item__c(
                Name = 'Test Bond',
                Advisory_Planning__c = planning.Id,
                Advisory_Item_Type__c = 'Return',
                Is_Product_Holding__c = false,
                Product_Group__c      = 'Bond',
                Baseline_Amount__c    = 5000,
                Baseline_Allocation__c    = 1,
                Target_Amount__c    = 100000,
                Target_Allocation__c    = 1,
                Product_Master__c = null ,
                Product_Name__c =  'test bond',
                Product_Holding_Code__c = 'test bond code',
                Product_Sub_Group_Asset_Class__c =  'Debenture'
            );
            itemList.add(eachBond);

            AdvisoryPlanningEditAllocationServices.saveAdvisoryPlanningItem(planning.Id, itemList, toDeleteList);
        Test.stopTest();

    }
}