force-app/main/default/objects/Account/fields/RTL_Wealth_RM__c.field-meta.xml
<CustomField>
    <fullName>RTL_Wealth_RM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CR Wealth RM Info , convert EMP/BR Code to Wealth RM</description>
    <label>Wealth RM/BM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Other_Bank__c/Other_Bank__c.object-meta.xml
<CustomObject>
    <label>Other Bank</label>
    <nameField>
        <displayFormat>OB-{000000}</displayFormat>
        <label>Other Bank Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Bank</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Other_Bank__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Other Banks</relationshipLabel>
    <relationshipName>Other_Banks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OtherBankTriggerTest.cls
@isTest
public class OtherBankTriggerTest {
	@istest
    static void test(){
         TestUtils.createAppConfig();
         Account acct = TestUtils.createAccounts(1,'acc','acc', true).get(0);
        acct.RTL_Wealth_RM__c = userinfo.getUserId();
        update acct;
        
        Other_Bank__c ob = new Other_Bank__c();
        ob.Customer__c = acct.Id;
        ob.Amount__c = 200;
        
        insert ob;
        
         TestInit.createUser(true);
         User u = TestInit.us;
         System.runAs(u) {
             try{
        		delete ob;
             }catch(Exception e){
                 
             }
         }
    }
}