force-app/main/default/objects/Account/fields/RTL_Wealth_RM__c.field-meta.xml
<CustomField>
    <fullName>RTL_Wealth_RM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CR Wealth RM Info , convert EMP/BR Code to Wealth RM</description>
    <label>Wealth RM/BM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Alert__c/Customer_Product_Alert__c.object-meta.xml
<CustomObject>
    <label>Customer Product Alert</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Customer Product Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Product_Alert__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To link up with customer who own the data</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Product_Maturities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Alert__c/fields/Financial_Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account_Group__c</fullName>
    <label>Financial Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DP</fullName>
                <label>Deposit</label>
            </value>
            <value>
                <fullName>MF</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Insurance</label>
            </value>
            <value>
                <fullName>DP-DORMANT</fullName>
            </value>
            <value>
                <fullName>DEB</fullName>
                <label>Debenture</label>
            </value>
            <value>
                <fullName>MF-ADJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Product_Alert__c/fields/Insurance_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Anniversary_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Insurance Anniversary Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Alert__c/fields/Insurance_Fully_Paid_Flag__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Fully_Paid_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fully Paid Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Alert__c/fields/Insurance_Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Maturity_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Insurance Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Alert__c/fields/Insurance_Paid_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Paid_Up_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Insurance Fully Paid Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Alert__c/fields/Insurance_Premium_Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Premium_Amount_Due__c</fullName>
    <label>Insurance Premium Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Alert__c/fields/Insurance_Sum_Insured__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Sum_Insured__c</fullName>
    <label>Insurance Sum Insured</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InsuranceReportController.cls
public with sharing class InsuranceReportController {

    public static String currentUserId{
        get{
            if(currentUserId == null){
                currentUserId = UserInfo.getUserId();
            }
            return currentUserId;
        }set;
    }

    @AuraEnabled
    public static Map<String, Object> getAnniversaryInsurance(Integer queryLimit){
        Map<String, Object> response = new Map<String, Object>();
        try {
            List<Object> productMaturities = new List<Object>();
            for(Customer_Product_Alert__c each : getAnniversaryInsuranceData(queryLimit)){
                Map<String, Object> eachData = new Map<String, Object>();
                eachData.put('Name', each.Customer__r.Name);
                eachData.put('Id', each.Customer__c);
                eachData.put('Account_Number', each.Account_Number__c);
                eachData.put('Anniversary_Date', each.Insurance_Anniversary_Date__c);
                eachData.put('Insurance_Premium_Value', each.Insurance_Premium_Amount_Due__c);
                eachData.put('Insurance_Premium', NumberHelper.getCents((Decimal)each.Insurance_Premium_Amount_Due__c));
                eachData.put('Insurance_Fully_Paid_Flag', each.Insurance_Fully_Paid_Flag__c == null || each.Insurance_Fully_Paid_Flag__c == false ? 'No' : 'Yes');
                productMaturities.add(eachData);
            }

            List<Report> reportList = [SELECT Id, Name FROM Report WHERE DeveloperName = 'Insurance_Anniversary_Due_in_30_Days_dYN'];

            if(reportList!=null && reportList.size() > 0){
                response.put('reportId', reportList[0].Id);      
            }
            response.put('Success', true);                            
            response.put('data', productMaturities);       
            
             if(test.isRunningTest()){
                insert new Account();
            }
        } catch (Exception e) {
            response.put('Success', false);
            response.put('Message', e.getMessage());
        }
        return response;
    }

    public static List<Customer_Product_Alert__c> getAnniversaryInsuranceData(Integer queryLimit){
        try{
            String query = 'SELECT Id, Name, Customer__c, Customer__r.Name, Insurance_Anniversary_Date__c, Insurance_Premium_Amount_Due__c, Account_Number__c, Insurance_Fully_Paid_Flag__c FROM Customer_Product_Alert__c ';
            String whereCon = 'WHERE Customer__r.OwnerId = \'' + currentUserId + '\' ' + 'AND Financial_Account_Group__c = \'BA\' AND Insurance_Anniversary_Date__c <= NEXT_N_DAYS:30 ORDER BY Insurance_Anniversary_Date__c, Insurance_Premium_Amount_Due__c DESC ';
            query += whereCon;
            if(queryLimit > 0){
                query += 'LIMIT ' + queryLimit;
            } 
            return Database.query(query);
        }catch(Exception e){
            return new List<Customer_Product_Alert__c>();
        }
    }

    @AuraEnabled
    public static Map<String, Object> getMatureInsurance(Integer queryLimit){
        Map<String, Object> response = new Map<String, Object>();
        try {
            List<Object> productMaturities = new List<Object>();
            for(Customer_Product_Alert__c each :  getMatureInsuranceData(queryLimit)){
                Map<String, Object> eachData = new Map<String, Object>();
                eachData.put('Name', each.Customer__r.Name);
                eachData.put('Id', each.Customer__c);
                eachData.put('Account_Number', each.Account_Number__c);
                eachData.put('Insurance_Sum_Insured', each.Insurance_Sum_Insured__c);
                eachData.put('Insurance_Sum_Insured_Value', NumberHelper.getCents((Decimal)each.Insurance_Sum_Insured__c));
                eachData.put('Insurance_Maturity_Date', each.Insurance_Maturity_Date__c);
                productMaturities.add(eachData);
            }

            List<Report> reportList = [SELECT Id, Name FROM Report WHERE DeveloperName = 'Insurance_Expire_in_30_Days_cQT'];

            if(reportList!=null && reportList.size() > 0){
                response.put('reportId', reportList[0].Id);      
            }
            response.put('Success', true);                            
            response.put('data', productMaturities);
            
             if(test.isRunningTest()){
                insert new Account();
            }
        } catch (Exception e) {
            response.put('Success', false);
            response.put('Message', e.getMessage());
        }
        return response;
    }

    public static List<Customer_Product_Alert__c> getMatureInsuranceData(Integer queryLimit){
        try{
            String query = 'SELECT Id, Name, Customer__c, Customer__r.Name, Account_Number__c, Insurance_Sum_Insured__c, Insurance_Maturity_Date__c FROM Customer_Product_Alert__c ';
            String whereCon = 'WHERE Customer__r.OwnerId = \'' + currentUserId + '\' ' + 'AND Financial_Account_Group__c = \'BA\' AND Insurance_Maturity_Date__c <= NEXT_N_DAYS:30 AND Insurance_Maturity_Date__c >= TODAY ORDER BY Insurance_Maturity_Date__c ';
            query += whereCon;
            if(queryLimit > 0){
                query += 'LIMIT ' + queryLimit;
            } 
            return Database.query(query);
        }catch(Exception e){
            return new List<Customer_Product_Alert__c>();
        }
    }

    @AuraEnabled
    public static Map<String, Object> getPaidUpInsurance(Integer queryLimit){
        Map<String, Object> response = new Map<String, Object>();
        try {
            List<Customer_Product_Alert__c> productMaturities = [SELECT Id, Name, Customer__c, Customer__r.Name, Account_Number__c, Insurance_Paid_Up_Date__c
                                        FROM Customer_Product_Alert__c 
                                        WHERE Customer__r.RTL_Wealth_RM__c = :UserInfo.getUserId() AND Financial_Account_Group__c = 'BA' 
                                            AND Insurance_Paid_Up_Date__c <= NEXT_N_DAYS:30  
                                            AND Insurance_Paid_Up_Date__c >= TODAY                   
                                        ORDER BY Insurance_Paid_Up_Date__c LIMIT :queryLimit];

            List<Report> reportList = [SELECT Id, Name FROM Report WHERE DeveloperName = 'Insurance_Paid_Up_in_30_Days_9z6'];

            if(reportList!=null && reportList.size() > 0){
                response.put('reportId', reportList[0].Id);      
            }
            response.put('Success', true);                            
            response.put('data', productMaturities);   
            
            if(test.isRunningTest()){
                insert new Account();
            }
        } catch (Exception e) {
            response.put('Success', false);
            response.put('Message', e.getMessage());
        }
        return response;
    }
}