force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>CB</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>RMC-Sales</fullName>
            </value>
            <value>
                <fullName>RMC-Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Forecast_Income__c/Deal_Forecast_Income__c.object-meta.xml
<CustomObject>
    <label>Deal Forecast Income</label>
    <nameField>
        <displayFormat>Deal Forecast-{000000}</displayFormat>
        <label>Deal Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Forecast Incomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Forecast_Income__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Forecast Incomes</relationshipLabel>
    <relationshipName>Deal_Forecast_Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Forecast_Income__c/fields/Main_Deal_forecast__c.field-meta.xml
<CustomField>
    <fullName>Main_Deal_forecast__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Deal forecast</label>
    <referenceTo>Deal_Forecast_Income__c</referenceTo>
    <relationshipLabel>Deal Forecast Incomes</relationshipLabel>
    <relationshipName>Deal_Forecast_Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Forecast_Income__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Forecast Incomes</relationshipLabel>
    <relationshipName>Deal_Forecast_Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Forecast_Income__c/fields/Opportunity_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Opportunity Product Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Forecast_Income__c/fields/OpportunityLineItem_Limit_Volume__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem_Limit_Volume__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This Year Expected Revenue</description>
    <label>Limit / Volume</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Forecast_Income__c/fields/Probability__c.field-meta.xml
<CustomField>
    <fullName>Probability__c</fullName>
    <description>Probability from opportunity product</description>
    <label>Probability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Forecast_Income__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Deal Forecast Incomes</relationshipLabel>
    <relationshipName>Deal_Forecast_Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Forecast_Income__c/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Volume/Drawdown Amount</description>
    <label>Volume / Drawdown</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Forecast_Income__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>Year of forecast</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_Forecast_Input__c/Monthly_Forecast_Input__c.object-meta.xml
<CustomObject>
    <label>Monthly Forecast Input</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Monthly Forecast Input Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Forecast Inputs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Forecast_Input__c/fields/Account_Suffix_Ref__c.field-meta.xml
<CustomField>
    <fullName>Account_Suffix_Ref__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Account/Suffix/Ref</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_Forecast_Input__c/fields/adjustMonthYear__c.field-meta.xml
<CustomField>
    <fullName>adjustMonthYear__c</fullName>
    <description>Use for back end process</description>
    <encryptionScheme>None</encryptionScheme>
    <label>adjustMonthYear</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monthly_Forecast_Input__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Monthly Forecast Inputs</relationshipLabel>
    <relationshipName>Monthly_Forecast_Inputs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Monthly_Forecast_Input__c/fields/Deal_Forecast_Income__c.field-meta.xml
<CustomField>
    <fullName>Deal_Forecast_Income__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Forecast Income</label>
    <referenceTo>Deal_Forecast_Income__c</referenceTo>
    <relationshipLabel>Monthly Forecast Inputs</relationshipLabel>
    <relationshipName>Monthly_Forecast_Inputs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Forecast_Input__c/fields/Ending_Balance__c.field-meta.xml
<CustomField>
    <fullName>Ending_Balance__c</fullName>
    <label>Ending Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Monthly_Forecast_Input__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Month</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_Forecast_Input__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Monthly Forecast Inputs</relationshipLabel>
    <relationshipName>Monthly_Forecast_Inputs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Forecast_Input__c/fields/OpportunityLineItem_Id__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Opportunity Product Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_Forecast_Input__c/fields/Probability__c.field-meta.xml
<CustomField>
    <fullName>Probability__c</fullName>
    <formula>Text(Deal_Forecast_Income__r.Probability__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Probability</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_Forecast_Input__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Monthly Forecast Inputs</relationshipLabel>
    <relationshipName>Monthly_Forecast_Inputs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Forecast_Input__c/fields/YearMonthAcctSuffRef__c.field-meta.xml
<CustomField>
    <fullName>YearMonthAcctSuffRef__c</fullName>
    <description>Use for backend process</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>YearMonthAcctSuffRef</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DealForecastTriggerHandlerTest.cls
@isTest
public class DealForecastTriggerHandlerTest {
    public static testmethod void teatInsertTrigger() {
        Test.startTest();
        DealForecastTriggerHandler dfth = new DealForecastTriggerHandler();
        testutils.createAppConfig();
        Id pricebookId = Test.getStandardPricebookId();
        Campaign camp = new Campaign();
            camp.Name = 'Campaign_1';
            camp.Segment__c = 'SE';
            camp.OwnerId  = userinfo.getUserId();
        	insert camp;
        list<account> listacc = testutils.createAccounts(1,'f','Individual',true);
        list<opportunity> listopp = testutils.createOpportunity(2,listacc.get(0).id,true);
        	listopp.get(0).campaignid = camp.id;
        	listopp.get(1).campaignid = camp.id;
        	update listopp;
        list<product2> listpro = testutils.createProduct(1,true);
        list<pricebookentry> listpricebook = testutils.createPricebookEntry(1,pricebookId,listpro,true);
        list<OpportunityLineItem> listoppline = testutils.createOpportunityProduct(1,listopp.get(0).id,listpricebook,true);
        
        Deal_Forecast_Income__c deal1 = new Deal_Forecast_Income__c();
        deal1.Customer__c = listacc.get(0).Id;
        deal1.Opportunity__c = listopp.get(0).Id;
        deal1.Opportunity_Product_Id__c = listoppline.get(0).Id;
        deal1.Product__c = listpro.get(0).Id;
        deal1.OpportunityLineItem_Limit_Volume__c = 1000000;
        deal1.Probability__c = 'Low';
        deal1.Volume__c = 1000000;
        insert deal1;
        
        list<Deal_Forecast_Income__c> listnewDeal = [select id,Customer__c,Volume__c,Opportunity__c,Opportunity_Product_Id__c,Product__c
                                                		from Deal_Forecast_Income__c where id =: deal1.id];

        DealForecastTriggerHandler.generateForecastInput(listnewDeal);
            
        Test.stopTest();
    }
    public static testmethod void teatUpdateTrigger() {
        Test.startTest();
        DealForecastTriggerHandler dfth = new DealForecastTriggerHandler();
        testutils.createAppConfig();
        Id pricebookId = Test.getStandardPricebookId();
        Campaign camp = new Campaign();
            camp.Name = 'Campaign_1';
            camp.Segment__c = 'SE';
            camp.OwnerId  = userinfo.getUserId();
        	insert camp;
        list<account> listacc = testutils.createAccounts(1,'f','Individual',true);
        list<opportunity> listopp = testutils.createOpportunity(2,listacc.get(0).id,true);
        	listopp.get(0).campaignid = camp.id;
        	listopp.get(1).campaignid = camp.id;
        	update listopp;
        list<product2> listpro = testutils.createProduct(1,true);
        list<pricebookentry> listpricebook = testutils.createPricebookEntry(1,pricebookId,listpro,true);
        list<OpportunityLineItem> listoppline = testutils.createOpportunityProduct(1,listopp.get(0).id,listpricebook,true);
        
        Deal_Forecast_Income__c deal1 = new Deal_Forecast_Income__c();
        deal1.Customer__c = listacc.get(0).Id;
        deal1.Opportunity__c = listopp.get(0).Id;
        deal1.Opportunity_Product_Id__c = listoppline.get(0).Id;
        deal1.Product__c = listpro.get(0).Id;
        deal1.OpportunityLineItem_Limit_Volume__c = 1000000;
        deal1.Probability__c = 'Low';
        deal1.Volume__c = 1000000;
        insert deal1;
        
        Id RTNewDeal = Schema.Sobjecttype.Monthly_Forecast_Input__c.getRecordTypeInfosByName().get('New Deal').getRecordTypeId();
        Monthly_Forecast_Input__c forecastInput = new Monthly_Forecast_Input__c();
        forecastInput.Deal_Forecast_Income__c = deal1.id;
        forecastInput.RecordTypeId = RTNewDeal;
        forecastInput.Ending_Balance__c = 1000000;
        forecastInput.Customer__c = listacc.get(0).Id;
        forecastInput.Opportunity__c = listopp.get(0).Id;
        forecastInput.OpportunityLineItem_Id__c = listoppline.get(0).Id;
        forecastInput.Product__c = listpro.get(0).Id;
        forecastInput.adjustMonthYear__c = Date.Today();
        forecastInput.Year__c = String.valueOf(Date.Today().Year());
        forecastInput.Month__c = Date.Today().Month() < 10 ? '0' + String.valueOf(Date.Today().Month()) : String.valueOf(Date.Today().Month());
        
        forecastInput.Account_Suffix_Ref__c = forecastInput.OpportunityLineItem_Id__c; 
        forecastInput.YearMonthAcctSuffRef__c = forecastInput.Year__c + forecastInput.Month__c + deal1.Id + forecastInput.OpportunityLineItem_Id__c;
        insert forecastInput;
        
        map<Id, Deal_Forecast_Income__c> listnewDeal = new map<Id, Deal_Forecast_Income__c>([select id,Opportunity_Product_Id__c,Probability__c,OpportunityLineItem_Limit_Volume__c,Volume__c 
                                                		from Deal_Forecast_Income__c where id =: deal1.id]);
        
        map<Id, Deal_Forecast_Income__c> listnewDeal2 = listnewDeal;
        listnewDeal.get(deal1.id).OpportunityLineItem_Limit_Volume__c = 2000000;
        listnewDeal.get(deal1.id).Probability__c = 'Medium';
        listnewDeal.get(deal1.id).Volume__c = 2000000;
        update listnewDeal.values();
        
        map<Id, Deal_Forecast_Income__c> listnewDeal3 = new map<Id, Deal_Forecast_Income__c>([select id,Opportunity_Product_Id__c,Probability__c,OpportunityLineItem_Limit_Volume__c,Volume__c 
                                                		from Deal_Forecast_Income__c where id =: deal1.id]);
        
        
        DealForecastTriggerHandler.updateOpportunitylineitem(listnewDeal2, listnewDeal3);
        DealForecastTriggerHandler.updateForecastInput(listnewDeal3);
            
        Test.stopTest();
    }
    public static testmethod void teatDeleteTrigger() {
        Test.startTest();
        DealForecastTriggerHandler dfth = new DealForecastTriggerHandler();
        testutils.createAppConfig();
        Id pricebookId = Test.getStandardPricebookId();
        Campaign camp = new Campaign();
            camp.Name = 'Campaign_1';
            camp.Segment__c = 'SE';
            camp.OwnerId  = userinfo.getUserId();
        	insert camp;
        list<account> listacc = testutils.createAccounts(1,'f','Individual',true);
        list<opportunity> listopp = testutils.createOpportunity(2,listacc.get(0).id,true);
        	listopp.get(0).campaignid = camp.id;
        	listopp.get(1).campaignid = camp.id;
        	update listopp;
        list<product2> listpro = testutils.createProduct(1,true);
        list<pricebookentry> listpricebook = testutils.createPricebookEntry(1,pricebookId,listpro,true);
        list<OpportunityLineItem> listoppline = testutils.createOpportunityProduct(1,listopp.get(0).id,listpricebook,true);
        
        Deal_Forecast_Income__c deal1 = new Deal_Forecast_Income__c();
        deal1.Customer__c = listacc.get(0).Id;
        deal1.Opportunity__c = listopp.get(0).Id;
        deal1.Opportunity_Product_Id__c = listoppline.get(0).Id;
        deal1.Product__c = listpro.get(0).Id;
        deal1.OpportunityLineItem_Limit_Volume__c = 1000000;
        deal1.Probability__c = 'Low';
        insert deal1;
        
        map<Id, Deal_Forecast_Income__c> listnewDeal = new map<Id, Deal_Forecast_Income__c>([select id,Opportunity_Product_Id__c,Probability__c,OpportunityLineItem_Limit_Volume__c,Main_Deal_forecast__c 
                                                		from Deal_Forecast_Income__c where id =: deal1.id]);
        Deal_Forecast_Income__c subdeal1 = new Deal_Forecast_Income__c();
        subdeal1.Customer__c = listacc.get(0).Id;
        subdeal1.Opportunity__c = listopp.get(0).Id;
        subdeal1.Opportunity_Product_Id__c = listoppline.get(0).Id;
        subdeal1.Product__c = listpro.get(0).Id;
        subdeal1.Main_Deal_forecast__c = deal1.id;
        insert subdeal1;
        
        Id RTNewDeal = Schema.Sobjecttype.Monthly_Forecast_Input__c.getRecordTypeInfosByName().get('New Deal').getRecordTypeId();
        Monthly_Forecast_Input__c forecastInput = new Monthly_Forecast_Input__c();
        forecastInput.Deal_Forecast_Income__c = deal1.id;
        forecastInput.RecordTypeId = RTNewDeal;
        forecastInput.Customer__c = listacc.get(0).Id;
        forecastInput.Opportunity__c = listopp.get(0).Id;
        forecastInput.OpportunityLineItem_Id__c = listoppline.get(0).Id;
        forecastInput.Product__c = listpro.get(0).Id;
        forecastInput.adjustMonthYear__c = Date.Today();
        forecastInput.Year__c = String.valueOf(Date.Today().Year());
        forecastInput.Month__c = Date.Today().Month() < 10 ? '0' + String.valueOf(Date.Today().Month()) : String.valueOf(Date.Today().Month());
        
        forecastInput.Account_Suffix_Ref__c = forecastInput.OpportunityLineItem_Id__c; 
        forecastInput.YearMonthAcctSuffRef__c = forecastInput.Year__c + forecastInput.Month__c + deal1.Id + forecastInput.OpportunityLineItem_Id__c;
        insert forecastInput;
        
        DealForecastTriggerHandler.syncOpportunitylineitem(listnewDeal);
        DealForecastTriggerHandler.deleteSubDealForecast(listnewDeal);
        DealForecastTriggerHandler.deleteForecastInput(listnewDeal);
        Test.stopTest();
    }
}