force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>CB</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>RMC-Sales</fullName>
            </value>
            <value>
                <fullName>RMC-Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Dummy_Campaign.recordType-meta.xml
<RecordType>
    <fullName>Dummy_Campaign</fullName>
    <active>true</active>
    <label>Dummy Campaign</label>
</RecordType>

force-app/main/default/objects/CampaignMember/fields/RTL_Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>RTL_Contact_Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Re-attempt</fullName>
            </value>
            <value>
                <fullName>Not Contact</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Memo__c.field-meta.xml
<CustomField>
    <fullName>RTL_Memo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Memo</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_OfferResult_Product_1__c.field-meta.xml
<CustomField>
    <fullName>RTL_OfferResult_Product_1__c</fullName>
    <label>Offer Result for Product-1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RTL_OfferResultPRD</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Product_Group_1__c.field-meta.xml
<CustomField>
    <fullName>RTL_Product_Group_1__c</fullName>
    <label>Product Group 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BANCASSURANCE</fullName>
                <label>Bancassurance</label>
            </value>
            <value>
                <fullName>CREDIT CARD &amp; RDC</fullName>
                <label>Credit Card &amp; RDC</label>
            </value>
            <value>
                <fullName>DEPOSIT</fullName>
                <label>Deposit</label>
            </value>
            <value>
                <fullName>INVESTMENT</fullName>
                <label>Investment</label>
            </value>
            <value>
                <fullName>LOAN</fullName>
                <label>Loan</label>
            </value>
            <value>
                <fullName>OTHERS</fullName>
                <label>Others</label>
            </value>
            <value>
                <fullName>AUTO LOAN</fullName>
                <label>Auto Loan</label>
            </value>
            <value>
                <fullName>LOAN RETENTION</fullName>
                <isActive>false</isActive>
                <label>LOAN RETENTION</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Reason_1__c.field-meta.xml
<CustomField>
    <fullName>RTL_Reason_1__c</fullName>
    <label>Reason of Not Interested-1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RTL_Product_Group_1__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>RTL_Reason_NotInterested</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_RelatedOpportunity_1__c.field-meta.xml
<CustomField>
    <fullName>RTL_RelatedOpportunity_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related to Opportunity-1</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_TMB_Campaign_Source__c.field-meta.xml
<CustomField>
    <fullName>RTL_TMB_Campaign_Source__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TMB Campaign Source</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RTL_Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>RTL_Contact_Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Re-attempt</fullName>
            </value>
            <value>
                <fullName>Not Contact</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Campaign_Running_No__c/RTL_Campaign_Running_No__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Campaign Running No.</label>
</CustomObject>

force-app/main/default/objects/RTL_Campaign_Running_No__c/fields/DateValue__c.field-meta.xml
<CustomField>
    <fullName>DateValue__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DateValue</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Campaign_Running_No__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Day</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Campaign_Running_No__c/fields/Running_No__c.field-meta.xml
<CustomField>
    <fullName>Running_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Running No</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Campaign_Running_No__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Year</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_CampaignMember_Running_No__c/RTL_CampaignMember_Running_No__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RTL_CampaignMember_Running_No</label>
</CustomObject>

force-app/main/default/objects/RTL_CampaignMember_Running_No__c/fields/Running_No__c.field-meta.xml
<CustomField>
    <fullName>Running_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Running No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Interested_products_c__c/RTL_Interested_products_c__c.object-meta.xml
<CustomObject>
    <description>To store interested product details for a lead.</description>
    <label>Interested Products</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Interested Products Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interested Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Interested_products_c__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Interested Products</relationshipLabel>
    <relationshipName>Interested_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/RTL_OfferResultPRD.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>Interested</fullName>
    </customValue>
    <customValue>
        <fullName>Not Interested</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Referred</fullName>
    </customValue>
    <description>List of Offer result for Campaign Product on Retail Campaign</description>
    <masterLabel>Campaign Product Offer Result</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RTL_CampaignMemberExtensionTest.cls
@isTest
public with sharing class RTL_CampaignMemberExtensionTest {
    static {
        TestUtils.createAppConfig();

        //Add for Test Campaignmember to CXM
        List<AppConfig__c> apps = new  List<AppConfig__c>();
        AppConfig__c Aconfig = new AppConfig__c();
        Aconfig.Name = 'CXM_SERVICE_CONNECTOR';
        Aconfig.Value__c = 'true';        
        apps.add(Aconfig);
        insert apps;
        TestUtils.prepareIntegrationMapping();
        TestUtils.prepareEIMmaps();
    }  
    
    public static testMethod void positive() {     
        //TestUtils.createForCXMToSales();
        Id recordTypeId  = [select Id from RecordType where SobjectType = 'Campaign' and DeveloperName=: 'Dummy_Campaign' and IsActive=true ].Id;

        RTL_Campaign_Running_No__c rn = new RTL_Campaign_Running_No__c( 
            Name ='Local Exclusive Campaign Running No.' , 
            DateValue__c='170717',
            Day__c='17',
            Month__c='07',
            Year__c='17',
            Running_No__c = '01' );
        insert rn;
        
        RTL_CampaignMember_Running_No__c cmrn = new RTL_CampaignMember_Running_No__c(
            Name = 'Campaign Member Running No',
            Running_No__c = '000000'
        );
        
        insert cmrn;
        
        List<Lead> leads = new List<Lead>();
        
        List<User> retailUsers = RTL_TestUtility.createRetailTestUserOppt(true);
        User firstUser = retailUsers[0];//outbound channel
        
        List<Account> accList = RTL_TestUtility.createAccounts(1,true);
        List<Opportunity> oppList = new List<Opportunity>();
        
        User retailUser = RTL_TestUtility.createRetailTestUser(true);
        System.runAs(retailUser) {
            RTL_TestUtility.createRetailMasterProducts(true);
        	leads = RTL_TestUtility.createLeads(2,true);
        	RTL_TestUtility.createInterestedProducts(leads, true);
            
            RTL_Interested_products_c__c nonPrimaryProduct = [select Is_Primary__c from RTL_Interested_products_c__c where Lead__c = :leads.get(0).Id and Is_Primary__c = false];
            nonPrimaryProduct.Is_Primary__c = true;
            //check result: the update should be failed because no more than one primary interested product is allowed
            boolean errMsgMatch = false;
            try {
                update nonPrimaryProduct;
            } catch (Exception ex) {
                
            }   
        }
        System.runAs(firstUser) {
            insert new PermissionSetAssignment(PermissionSetId=TestUtils.SetupPermissionSet().Id,AssigneeId=firstUser.Id);
        }
        System.runAs(firstUser) {
            oppList = RTL_TestUtility.createOpportunity(accList,true);
        }
        
        
        Campaign camp = new Campaign();
        camp.Name = 'Campaign_';
        camp.Segment__c = 'MB';
        camp.OwnerId  = UserInfo.getUserId();
        camp.RecordTypeId = Recordtypeid;
        insert camp;
        
        CampaignMember cm1 = new CampaignMember();
        cm1.LeadId = leads.get(0).id;
        cm1.CampaignId = camp.id;
        cm1.RTL_TMB_Campaign_Source__c = 'web';     
        cm1.RTL_Contact_Status__c = 'Contact';
        cm1.RTL_Product_Group_1__c = 'Bancassurance';
        cm1.RTL_OfferResult_Product_1__c = 'Interested';
        //cm1.RTL_RelatedOpportunity_1__c = oppList.get(0).Id;
        insert cm1;
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(cm1);
        RTL_CampaignMemberExtension camPage = new RTL_CampaignMemberExtension(sc);       
        for( Integer i = 1 ; i <= 1 ; i++ ){
            camPage.createOppList.add( new RTL_CampaignMemberExtension.CampaignProductInterestedWrapper(i++,
                                                                            'RTL_Product_Group_'+i+'__c',
                                                                            'RTL_Sub_Group_'+i+'__c',
                                                                            'RTL_Campaign_Product_'+i+'__c',
                                                                            'RTL_Campaign_Product_'+i+'__r.Name',
                                                                            oppList.get(0),
                                                                            true,
                                                                            true,
                                                                            'RTL_Campaign_Product_'+i+'__r.Name'                            
                                                                           )  );
        }
        camPage.createInterestedProduct(leads.get(0));
        camPage.updateCampaignMember();
        camPage.getOpportunityList();
        //camPage.queryFulfillment('1','1');
        camPage.getNID('123');
        
        camPage.apexSave();
        camPage.redirectAfterSave();
        camPage.apexCreateOpportunity();

        cm1.RTL_RelatedOpportunity_1__c = null;
        update cm1;
        camPage.nextPageCreateOpportunity();
        camPage.getCampaignProductInterested();
        
        cm1.RTL_OfferResult_Product_1__c = 'Not Interested';
        // cm1.RTL_Reason_1__c = 'Others';
        cm1.RTL_Contact_Status__c = 'New';
        cm1.RTL_Memo__c = 'test only';
        update cm1;
        camPage.apexSave();
        camPage.redirectAfterSave();
                
        
        camPage.backPageEditCampaignMember();
        camPage.nextPageViewOpportunity();
        camPage.defaultContactStatus();
        camPage.editCampaignMemberButton();
        camPage.closeWithSalesApp();
        camPage.canceltoview();
        camPage.getCampaignProduct();
        
        camPage.isCampaignActive = true;
        camPage.editCampaignMemberButton();
        

        Test.stopTest();  
    }          
}