force-app/main/default/objects/Account/fields/TMB_Customer_ID_PE__c.field-meta.xml
<CustomField>
    <fullName>TMB_Customer_ID_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>TMB Customer ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Product_Alert__c/Customer_Product_Alert__c.object-meta.xml
<CustomObject>
    <label>Customer Product Alert</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Customer Product Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Product_Alert__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Deposit/MF Balance</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Alert__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To link up with customer who own the data</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Product_Maturities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Alert__c/fields/Dormant_Date__c.field-meta.xml
<CustomField>
    <fullName>Dormant_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Near Dormant Account Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Alert__c/fields/Financial_Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account_Group__c</fullName>
    <label>Financial Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DP</fullName>
                <label>Deposit</label>
            </value>
            <value>
                <fullName>MF</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Insurance</label>
            </value>
            <value>
                <fullName>DP-DORMANT</fullName>
            </value>
            <value>
                <fullName>DEB</fullName>
                <label>Debenture</label>
            </value>
            <value>
                <fullName>MF-ADJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DormantAccountController.cls
public with sharing class DormantAccountController {

    public static String currentUserId{
        get{
            if(currentUserId == null){
                currentUserId = UserInfo.getUserId();
            }
            return currentUserId;
        }set;
    }

    @AuraEnabled
    public static Map<String, Object> getDormantAccount(Integer queryLimit){
        Map<String, Object> response = new Map<String, Object>();
        try {
            List<Object> dataList = new List<Object>();
            for(Customer_Product_Alert__c each : getDormantAccountData(queryLimit)){
                Map<String, Object> eachData = new Map<String, Object>();
                eachData.put('Name', each.Customer__r.Name);
                eachData.put('Id', each.Customer__c);
                eachData.put('Account_Number', each.Account_Number__c);
                eachData.put('Dormant_Date', each.Dormant_Date__c);
                eachData.put('Amount', NumberHelper.getCents(each.Amount__c));
                eachData.put('Amount_Value', each.Amount__c);
                dataList.add(eachData);
            }

            List<Report> reportList = [SELECT Id, Name FROM Report WHERE DeveloperName = 'Dormant_Account_Ifp'];

            if(reportList!=null && reportList.size() > 0){
                response.put('reportId', reportList[0].Id);      
            }
            response.put('Success', true);                            
            response.put('data', dataList);
            
            if(test.isRunningTest()){
                insert new Account();
            }
        } catch (Exception e) {
            response.put('Success', false);
            response.put('Message', e.getMessage());
        }
        return response;
    }

    public static List<Customer_Product_Alert__c> getDormantAccountData(Integer queryLimit){
        try{
            String query = 'SELECT Id, Customer__c, Customer__r.Name, Dormant_Date__c, Account_Number__c, Customer__r.TMB_Customer_ID_PE__c, Amount__c FROM Customer_Product_Alert__c ';
            String whereCon = 'WHERE customer__r.OwnerId = \'' + currentUserId + '\' ' + ' AND Financial_Account_Group__c = \'DP-DORMANT\' AND Dormant_Date__c <= NEXT_N_DAYS:30 ORDER BY Dormant_Date__c, Amount__c DESC ';
            query += whereCon;
            if(queryLimit > 0){
                query += 'LIMIT ' + queryLimit;
            } 
            return Database.query(query);
        }catch(Exception e){
            return new List<Customer_Product_Alert__c>();
        }
    }
}