force-app/main/default/objects/Account/fields/TMB_Customer_ID_PE__c.field-meta.xml
<CustomField>
    <fullName>TMB_Customer_ID_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>TMB Customer ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Main_Bank_Info__c/Customer_Main_Bank_Info__c.object-meta.xml
<CustomObject>
    <label>Customer Main Bank Info</label>
    <nameField>
        <displayFormat>MB-{000000}</displayFormat>
        <label>Customer Main Bank Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Main Bank Infos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Main_Bank_Info__c/fields/Calculation_Date__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>As of Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Main_Bank_Info__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Main Bank Infos</relationshipLabel>
    <relationshipName>Customer_Main_Bank_Infos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Data_Security_Matrix__c/Data_Security_Matrix__c.object-meta.xml
<CustomObject>
    <description>Table to maintain data partition security matrix for each profile</description>
    <label>Data Security Matrix</label>
    <nameField>
        <displayFormat>SEC-{0000}</displayFormat>
        <label>Data Security Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Security Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Security_Matrix__c/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <label>Access Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Authorize Only</fullName>
            </value>
            <value>
                <fullName>No Access</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Security_Matrix__c/fields/Data_Matrix_Key__c.field-meta.xml
<CustomField>
    <fullName>Data_Matrix_Key__c</fullName>
    <description>Profile_Name__c+Section_Name__c</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Data Matrix Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Data_Security_Matrix__c/fields/Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Profile_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Profile Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Security_Matrix__c/fields/Section_Name__c.field-meta.xml
<CustomField>
    <fullName>Section_Name__c</fullName>
    <label>Section Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ComCust:Account Information</fullName>
            </value>
            <value>
                <fullName>ComCust:Address Information</fullName>
            </value>
            <value>
                <fullName>ComCust:Campaign Lead History</fullName>
            </value>
            <value>
                <fullName>ComCust:Collateral</fullName>
            </value>
            <value>
                <fullName>ComCust:Contact Information</fullName>
            </value>
            <value>
                <fullName>ComCust:Contacts</fullName>
            </value>
            <value>
                <fullName>ComCust:Executive Summary/Account Plan</fullName>
            </value>
            <value>
                <fullName>ComCust:Other Information</fullName>
            </value>
            <value>
                <fullName>ComCust:Performance</fullName>
            </value>
            <value>
                <fullName>ComCust:Pipeline</fullName>
            </value>
            <value>
                <fullName>ComCust:Product On Hand</fullName>
            </value>
            <value>
                <fullName>ComCust:Product On Hand (Partition)</fullName>
            </value>
            <value>
                <fullName>ComCust:Risk Information</fullName>
            </value>
            <value>
                <fullName>ComCust:Wallet</fullName>
            </value>
            <value>
                <fullName>ComPros:Customer Information</fullName>
            </value>
            <value>
                <fullName>ComPros:Customer Source</fullName>
            </value>
            <value>
                <fullName>ComPros:Detail Information</fullName>
            </value>
            <value>
                <fullName>ComPros:General Information</fullName>
            </value>
            <value>
                <fullName>ComPros:Product Interest</fullName>
            </value>
            <value>
                <fullName>ComPros:Re-assignment Customer</fullName>
            </value>
            <value>
                <fullName>RtlCust:Address Information</fullName>
            </value>
            <value>
                <fullName>RtlCust:Alternative Contact Information</fullName>
            </value>
            <value>
                <fullName>RtlCust:Campaign History</fullName>
            </value>
            <value>
                <fullName>RtlCust:Contact Number and Email Address</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Demographic (High)</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Demographic (Low)</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Demographic (Medium)</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Insight - Personalized Information</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Product Holding (High)</fullName>
            </value>
            <value>
                <fullName>RtlCust:Customer Product Holding (Low)</fullName>
            </value>
            <value>
                <fullName>RtlCust:MI Benefits</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MainBankHistoryTableComponentTest.cls
@isTest
public class MainBankHistoryTableComponentTest {

    public static final Id RM_Cockpit_PROFILE_ID = [SELECT Id FROM Profile WHERE Name = 'TMB Retail Wealth Management RM Cockpit' LIMIT 1].Id;

	@testSetup
    static void testSetup() {
        
    	list<Data_Security_Matrix__c> dsm = new  list<Data_Security_Matrix__c>();
        Data_Security_Matrix__c ds1 = new Data_Security_Matrix__c();
		ds1.Access_Type__c ='All';
        ds1.Profile_Name__c ='System Administrator';
        ds1.Data_Matrix_Key__c ='TMB CM Product Manager ProfileCommCust:Customer Product Holding (Low)';
        ds1.Section_Name__c  ='RtlCust:MI Benefits';
        dsm.add(ds1);
        insert dsm;
        TestUtils.createAppConfig();
        Account acct = TestUtils.createAccounts(1,'TESTACCOUNT','Individual', true).get(0);
        
        List<Customer_Main_Bank_Info__c> mainBankInfoList = new List<Customer_Main_Bank_Info__c>();
        mainBankInfoList.add(new Customer_Main_Bank_Info__c(Calculation_Date__c = System.today() - 30,Customer__c = acct.Id));
        mainBankInfoList.add(new Customer_Main_Bank_Info__c(Calculation_Date__c = System.today() - 60,Customer__c = acct.Id));
        insert mainBankInfoList;
    }
    
    @isTest
    static void testGetMainBankHistoryList() {
        User adminUser = [SELECT Id,Name , Profile.Name FROM User WHERE IsActive = true AND ProfileId =: TestUtils.SYSADMIN_PROFILE_ID LIMIT 1];
        Account acct = [select Id , TMB_Customer_ID_PE__c from Account LIMIT 1];
        acct.TMB_Customer_ID_PE__c ='00000000';
        update acct;
        Test.startTest();
        System.runAs(adminUser) {
            List<Customer_Main_Bank_Info__c> mainBankList = MainBankHistoryTableComponent.getMainBankHistoryList(acct.Id);
            System.assertEquals(mainBankList.size(), 2);
        }
        Test.stopTest();
    }
    
    @isTest
    static void testGetMainBankLabels() {
        Map<String,String> fieldNameLabelMap = MainBankHistoryTableComponent.getMainBankLabels();
        System.assert(fieldNameLabelMap.size() > 0, 'Map of field name and label is returned');
    }
    
    @isTest
    static void testGetLabels() {
        String fieldNameLabelMap = MainBankHistoryTableComponent.getMainbankLabel();
    }
}