force-app/main/default/objects/RTL_NBO_History__c/RTL_NBO_History__c.object-meta.xml
<CustomObject>
    <label>NBO</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NBOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_NBO_History__c/fields/RTL_Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>RTL_Campaign_Code__c</fullName>
    <description>Campaign Code this NBO is linked to</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Campaign Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History__c/fields/RTL_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_Campaign_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NBO Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History__c/fields/RTL_Channel__c.field-meta.xml
<CustomField>
    <fullName>RTL_Channel__c</fullName>
    <description>Channel which this NBO is offerred e.g. Branch Email SMS DM EDM MIB Outbound Inbound Others</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Assigned Channel</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History__c/fields/RTL_Contact_Date__c.field-meta.xml
<CustomField>
    <fullName>RTL_Contact_Date__c</fullName>
    <description>Date customer was contacted for this NBO</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History__c/fields/RTL_Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer that this NBO is offerred to</description>
    <label>Customer Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Retail Customer, Retail Prospect</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>NBO_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History__c/fields/RTL_NBO_Group__c.field-meta.xml
<CustomField>
    <fullName>RTL_NBO_Group__c</fullName>
    <description>Grouping for this NBO</description>
    <encryptionScheme>None</encryptionScheme>
    <label>NBO Group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History__c/fields/RTL_NBO_ID__c.field-meta.xml
<CustomField>
    <fullName>RTL_NBO_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID of this NBO from MIS</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>NBO ID</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTL_NBO_History__c/fields/RTL_NBO_Product_Latest_Modified_Date__c.field-meta.xml
<CustomField>
    <fullName>RTL_NBO_Product_Latest_Modified_Date__c</fullName>
    <description>Latest modified date for any NBO product(s) linked to this NBO for purging purposes</description>
    <encryptionScheme>None</encryptionScheme>
    <label>NBO Product Latest Modified Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History__c/fields/RTL_NBO_SubGroup__c.field-meta.xml
<CustomField>
    <fullName>RTL_NBO_SubGroup__c</fullName>
    <description>Subgroup of this NBO</description>
    <encryptionScheme>None</encryptionScheme>
    <label>NBO SubGroup</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History__c/fields/RTL_Smart_Info__c.field-meta.xml
<CustomField>
    <fullName>RTL_Smart_Info__c</fullName>
    <description>Smart Info Link that comes from MIS</description>
    <encryptionScheme>None</encryptionScheme>
    <label>NBO Detail Info</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History__c/fields/RTL_Status__c.field-meta.xml
<CustomField>
    <fullName>RTL_Status__c</fullName>
    <description>0. all product has no status --&gt; Contact Center
1. No product --&gt; Invalid
2. All Accepted --&gt; Accepted All
3. All Rejected --&gt; Rejected All
4. All New --&gt; New
5. All Pending --&gt; Pending
6. All Invalid --&gt; Invalid
7. Some Accepted --&gt; Accepted Some
8. Some Rejected, no Accepted --&gt; Rejected Some
9. Some Pending, no Accepted/Rejected --&gt; Pending
10. Some New, no Accepted/Rejected/Pending --&gt; New
11. Other scenarios --&gt; New</description>
    <formula>IF(
AND(NOT(ISBLANK(RTL_Result_Business__c)), RTL_Number_of_No_Status_NBO__c =  RTL_Number_of_Products__c ),
$Label.RTL_NBO_Status_ContactCenter
,
IF(RTL_Number_of_Products__c == 0,  $Label.RTL_NBO_Status_Invalid , 
IF(RTL_Number_of_Products__c ==  RTL_Number_of_Accepted_NBO__c,  $Label.RTL_NBO_Status_Accepted_All , 
IF(RTL_Number_of_Products__c ==  RTL_Number_of_Rejected_NBO__c, $Label.RTL_NBO_Status_Rejected_All, 
IF(RTL_Number_of_Products__c ==  RTL_Number_of_New_NBO__c, $Label.RTL_NBO_Status_New, 
IF(RTL_Number_of_Products__c ==  RTL_Number_of_Pending_NBO__c, $Label.RTL_NBO_Status_Pending, 
IF(RTL_Number_of_Products__c ==  RTL_Number_of_Invalid_NBO__c , $Label.RTL_NBO_Status_Invalid, 
IF(and(RTL_Number_of_Accepted_NBO__c &gt; 0, RTL_Number_of_Invalid_NBO__c == 0), $Label.RTL_NBO_Status_Accepted_Some,
IF(RTL_Number_of_Accepted_NBO__c &gt; 0, $Label.RTL_NBO_Status_Accepted_All,
IF(and(RTL_Number_of_Rejected_NBO__c &gt; 0, RTL_Number_of_Invalid_NBO__c == 0), $Label.RTL_NBO_Status_Rejected_Some,
IF(RTL_Number_of_Rejected_NBO__c &gt; 0, $Label.RTL_NBO_Status_Rejected_All,  
IF(RTL_Number_of_Pending_NBO__c &gt; 0, $Label.RTL_NBO_Status_Pending,
IF(RTL_Number_of_New_NBO__c &gt; 0 , $Label.RTL_NBO_Status_New, $Label.RTL_NBO_Status_New) ) ) ) ) ) ) ) ) ) ) ) )</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History__c/fields/RTL_TMB_Customer_ID_PE__c.field-meta.xml
<CustomField>
    <fullName>RTL_TMB_Customer_ID_PE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TMB Customer ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History__c/fields/RTL_Valid_From__c.field-meta.xml
<CustomField>
    <fullName>RTL_Valid_From__c</fullName>
    <description>Date this NBO is valid from</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History__c/fields/RTL_Valid_To__c.field-meta.xml
<CustomField>
    <fullName>RTL_Valid_To__c</fullName>
    <description>Date this NBO is valid to</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History_Product__c/RTL_NBO_History_Product__c.object-meta.xml
<CustomObject>
    <label>NBO Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>NBO Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NBO Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_NBO_History_Product__c/fields/RTL_NBO_ID__c.field-meta.xml
<CustomField>
    <fullName>RTL_NBO_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>NBO External ID</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History_Product__c/fields/RTL_NBO_Product_External_ID__c.field-meta.xml
<CustomField>
    <fullName>RTL_NBO_Product_External_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>NBO Product External ID</label>
    <length>31</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTL_NBO_History_Product__c/fields/RTL_Offering_Channel__c.field-meta.xml
<CustomField>
    <fullName>RTL_Offering_Channel__c</fullName>
    <label>Offering Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Contact Center</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_NBO_History_Product__c/fields/RTL_Product__c.field-meta.xml
<CustomField>
    <fullName>RTL_Product__c</fullName>
    <description>Display Product Name, or Product Subgroup, or Product Group</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Product</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History_Product__c/fields/RTL_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>RTL_Product_Group__c</fullName>
    <description>Product Group of this NBO product to be send via Mulesoft</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History_Product__c/fields/RTL_Product_Smart_Info__c.field-meta.xml
<CustomField>
    <fullName>RTL_Product_Smart_Info__c</fullName>
    <description>Smart Info Link for this NBO Product</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Smart Info</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History_Product__c/fields/RTL_Product_SubGroup__c.field-meta.xml
<CustomField>
    <fullName>RTL_Product_SubGroup__c</fullName>
    <description>Product Subgroup of this NBO Product to be sent by Mulesoft</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Product SubGroup</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History_Product__c/fields/RTL_Related_NBO__c.field-meta.xml
<CustomField>
    <fullName>RTL_Related_NBO__c</fullName>
    <description>NBO that this NBO Product is related to</description>
    <label>Related NBO</label>
    <referenceTo>RTL_NBO_History__c</referenceTo>
    <relationshipName>NBO_History_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History_Product__c/fields/RTL_Status__c.field-meta.xml
<CustomField>
    <fullName>RTL_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_NBO_History_Product__c/fields/RTL_User_Branch__c.field-meta.xml
<CustomField>
    <fullName>RTL_User_Branch__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Branch</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History_Product__c/fields/RTL_User_Region__c.field-meta.xml
<CustomField>
    <fullName>RTL_User_Region__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_NBO_History_Product__c/fields/RTL_User_Zone__c.field-meta.xml
<CustomField>
    <fullName>RTL_User_Zone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zone</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RTL_NBOService.cls
public with sharing class RTL_NBOService {
    public class NBO {
        public String SoapStatus;
        public String SoapMessage;
        public Map<NBOHistory, List<NBOHistoryProduct>> nboMap;
    }
    public class NBOHistory {
        //public String RTL_NBO_Name;//Name (keyword, can't use Name as variable) 
        public String RTL_Campaign_Name;//Campaign Name   
        public String RTL_Campaign_Code;//Campaign Code
        public Date RTL_Contact_Date;//Contact Date
        public String RTL_Customer_Name;//Customer Name (SFDC ID)
        public String RTL_NBO_Group;//NBO Group
        public String RTL_NBO_ID;//NBO ID
        public String RTL_NBO_SubGroup;//NBO SubGroup
        public String RTL_Smart_Info;//Smart Info
        public String RTL_Status;//Status
        public String RTL_TMB_Customer_ID_PE;//TMB Customer ID
        public Date RTL_Valid_From;//Valid From
        public Date RTL_Valid_To;//Valid To
        public String RTL_Channel;//Assigned Channel
    }

    public class NBOHistoryProduct {
        public String RTL_NBO_ID;//NBO ID
        public String RTL_Product;//Product
        public String RTL_Product_Group;//Product Group
        public String RTL_Product_SubGroup;//Product SubGroup
        public String RTL_Product_Smart_Info;//Smart Info
        public String RTL_User_Branch;//Branch
        public String RTL_User_Region;//Region
        public String RTL_User_Zone;//Zone
        public String RTL_NBO_Product_External_ID;    
    }

    public static RTL_NBO_History__c newNBO(Id acctId, NBOHistory nbo) {
        RTL_NBO_History__c nboHistory = new RTL_NBO_History__c();
        nboHistory.RTL_NBO_ID__c = nbo.RTL_NBO_ID;
        nboHistory.RTL_Campaign_Name__c = nbo.RTL_Campaign_Name;
        nboHistory.RTL_Campaign_Code__c = nbo.RTL_Campaign_Code;
        nboHistory.RTL_Customer_Name__c = acctId;
        nboHistory.RTL_NBO_Group__c = nbo.RTL_NBO_Group;
        nboHistory.RTL_NBO_SubGroup__c = nbo.RTL_NBO_SubGroup;
        nboHistory.RTL_Valid_From__c = nbo.RTL_Valid_From;
        nboHistory.RTL_Valid_To__c = nbo.RTL_Valid_To;
        nboHistory.RTL_Smart_Info__c = nbo.RTL_Smart_Info;
        nboHistory.RTL_Contact_Date__c = nbo.RTL_Contact_Date;
        nboHistory.RTL_Channel__c = nbo.RTL_Channel;   
        nboHistory.RTL_NBO_Product_Latest_Modified_Date__c = DateTime.now();  
        nboHistory.RTL_TMB_Customer_ID_PE__c = nbo.RTL_TMB_Customer_ID_PE;
        return nboHistory;
    }   
    
    public static RTL_NBO_History_Product__c newNBOProduct(NBOHistoryProduct nboProduct, User user) {
        RTL_NBO_History_Product__c nboHistoryProduct = new RTL_NBO_History_Product__c();
        nboHistoryProduct.RTL_NBO_ID__c = nboProduct.RTL_NBO_ID;
        nboHistoryProduct.RTL_Product__c = nboProduct.RTL_Product;
        nboHistoryProduct.RTL_Product_Group__c = nboProduct.RTL_Product_Group;
        nboHistoryProduct.RTL_Product_SubGroup__c = nboProduct.RTL_Product_SubGroup;
        nboHistoryProduct.RTL_Product_Smart_Info__c = nboProduct.RTL_Product_Smart_Info;
        //nboHistoryProduct.RTL_User_Branch__c = user.RTL_Branch_Code__c;//leave it as blank until the NBO product is offered
        //nboHistoryProduct.RTL_User_Region__c = user.Region_Code__c;//leave it as blank until the NBO product is offered
        //nboHistoryProduct.RTL_User_Zone__c = user.Zone_Code__c;//leave it as blank until the NBO product is offered
        //nboHistoryProduct.RTL_Offering_Channel__c = 'Branch';//leave it as blank until the NBO product is offered
        nboHistoryProduct.RTL_Status__c = 'New';
        nboHistoryProduct.RTL_NBO_Product_External_ID__c = nboProduct.RTL_NBO_Product_External_ID;
        return nboHistoryProduct;//map the parent id later
    }     
    
    /**
    * @param acctId - Account Id specific to the NBO
    * @param user - User who press the 
    * @param nboMap - map of NBO and product
    */
    public static String validateNBO (Id acctId, User user, Map<NBOHistory, List<NBOHistoryProduct>> nboMap) {
        List<RTL_NBO_History__c> newNBOListToReturn = new List<RTL_NBO_History__c>(); 
        String insertionErrMsg = '';
        String errMsg = null;  
        
        //Get the list of inbound external NBO ID first
        Set<String> nboExtIdList = new Set<String>();
        for (NBOHistory nbo : nboMap.keySet()){
            nboExtIdList.add(nbo.RTL_NBO_ID);
        }
        
        //Store the list of existing NBO history filtering by inbound external NBO ID
        Map<String, RTL_NBO_History__c> nboHistoryList = new Map<String, RTL_NBO_History__c>();
        for(RTL_NBO_History__c nboHistory : [Select RTL_NBO_ID__c from RTL_NBO_History__c where RTL_NBO_ID__c in : nboExtIdList and RTL_Customer_Name__c = :acctId]) {
            nboHistoryList.put(nboHistory.RTL_NBO_ID__c, nboHistory);
        }      

        List<RTL_NBO_History__c> nboHistoryListToInsert = new List<RTL_NBO_History__c>();
        List<RTL_NBO_History_Product__c> nboHistoryProductListToInsertFinal = new List<RTL_NBO_History_Product__c>();
        List<NBOHistoryProduct> nboHisProductList = null;
        List<RTL_NBO_History_Product__c> nboHistoryProductList = null;
        Map<String, List<RTL_NBO_History_Product__c>> nboHistoryProductMapToInsert = new Map<String, List<RTL_NBO_History_Product__c>>();//key is NBO external ID
        for (NBOHistory nbo : nboMap.keySet()){
            if (nboHistoryList.get(nbo.RTL_NBO_ID) == null) {//nbo is not exist for this customer
                nboHistoryListToInsert.add(newNBO(acctId, nbo));
                nboHisProductList = nboMap.get(nbo);
                nboHistoryProductList = new List<RTL_NBO_History_Product__c>();
                for (NBOHistoryProduct nboProduct: nboHisProductList) {                 
                    nboHistoryProductList.add(newNBOProduct(nboProduct, user));
                }
                nboHistoryProductMapToInsert.put(nbo.RTL_NBO_ID, nboHistoryProductList);
            }
        }
        
        String nboId = null;
        List<RTL_NBO_History__c> nboInsertedList = new List<RTL_NBO_History__c>();
        if(nboHistoryListToInsert.size() > 0){
            Integer nboCounter = 0;
            // Insert new NBO History
            Database.SaveResult[] lsr = Database.insert(nboHistoryListToInsert, false);
            // Iterate through each returned result
            for (Database.SaveResult sr : lsr) {
                if (sr.isSuccess()) {
                    // Operation was successful, so get the ID of the record that was processed
                    System.debug('Successfully inserted NBO History with ID: ' + sr.getId());
                    nboInsertedList.add(nboHistoryListToInsert[nboCounter]);
                }
                else {
                    // Operation failed, so get all errors                
                    for(Database.Error err : sr.getErrors()) {
                        if (nboHistoryListToInsert[nboCounter].RTL_NBO_ID__c == null) nboId = 'Unknown';
                        else nboId = nboHistoryListToInsert[nboCounter].RTL_NBO_ID__c;
                        errMsg = System.Label.RTL_NBO + ' - ID=' + nboId + ' - ' + System.Label.RTL_NBO_Insertion_ERR001 + ' ' + System.Label.RTL_NBO_Insertion_ERR000 + ': ' + err.getMessage();
                        System.debug(logginglevel.ERROR, errMsg);
                        insertionErrMsg += errMsg + '<br/>';
                    }
                }
                nboCounter++;
            }             
        }
        
        //map NBO history SFDC ID to each NBO History Product, then insert
        for (RTL_NBO_History__c nboHistoryWithId: nboInsertedList) {
            List<RTL_NBO_History_Product__c> nboHistoryProdList = nboHistoryProductMapToInsert.get(nboHistoryWithId.RTL_NBO_ID__c);
            if (nboHistoryProdList != null) {//invalid NBO History doesn't have NBO History Product
                for (RTL_NBO_History_Product__c nboHistoryProd: nboHistoryProdList) {
                    nboHistoryProd.RTL_Related_NBO__c = nboHistoryWithId.Id;//map to parent NBO History Id
                    nboHistoryProductListToInsertFinal.add(nboHistoryProd);
                }
            }
        }
        
        String nboProductId = null;
        if(nboHistoryProductListToInsertFinal.size() > 0){
            Integer nboProductCounter = 0;          
            // Insert new NBO History
            Database.SaveResult[] lsr = Database.insert(nboHistoryProductListToInsertFinal, false);
            // Iterate through each returned result
            for (Database.SaveResult sr : lsr) {
                if (sr.isSuccess()) {
                    // Operation was successful, so get the ID of the record that was processed
                    System.debug('Successfully inserted NBO History Product with ID: ' + sr.getId());
                }
                else {
                    // Operation failed, so get all errors                
                    for(Database.Error err : sr.getErrors()) {
                        if (nboHistoryProductListToInsertFinal[nboProductCounter].RTL_NBO_Product_External_ID__c == null) nboProductId = 'Unknown';
                        else nboProductId = nboHistoryProductListToInsertFinal[nboProductCounter].RTL_NBO_Product_External_ID__c;                       
                        errMsg = System.Label.RTL_NBO_Product + ' - ID=' + nboProductId + ' - ' + System.Label.RTL_NBO_Insertion_ERR002 + ' ' + System.Label.RTL_NBO_Insertion_ERR000 + ': ' + err.getMessage();
                        System.debug(logginglevel.ERROR, errMsg);
                        insertionErrMsg += errMsg + '<br/>';                        
                    }
                }
                nboProductCounter++;
            }             
        }
                                            
        return insertionErrMsg;
    }     
}