force-app/main/default/objects/SLL_Group__c/SLL_Group__c.object-meta.xml
<CustomObject>
    <label>SLL Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLL Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SLL_Group__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SLL_Groups2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/Approver2__c.field-meta.xml
<CustomField>
    <fullName>Approver2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SLL_Groups3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/PAM__c.field-meta.xml
<CustomField>
    <fullName>PAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PAM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>TMB RM Profile,TMB BDM Profile, TMB SE Zone Manager Profile</value>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>SLL_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SLL_Groups6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group_Approval_History__c/SLL_Group_Approval_History__c.object-meta.xml
<CustomObject>
    <label>SLL Group Approval History</label>
    <nameField>
        <displayFormat>SG-Req-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLL Group Approval Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SLL_Group_Approval_History__c/fields/Approval_Status_Pending__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status_Pending__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Approver1 Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SLL_Group_Approval_History__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SLL_Group_Approval_Histories1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group_Approval_History__c/fields/Approver2__c.field-meta.xml
<CustomField>
    <fullName>Approver2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SLL_Group_Approval_Histories2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group_Approval_History__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SLL Group Approval Histories</relationshipLabel>
    <relationshipName>SLL_Group_Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group_Approval_History__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2001700001:เป็นผู้ที่เกี่ยวข้อง (ตามประกาศ Single Lending Limit)</fullName>
            </value>
            <value>
                <fullName>2001700002:มีการถือหุ้นหรือกรรมการไขว้กัน</fullName>
            </value>
            <value>
                <fullName>2001700003:มีบุคคลในครอบครัวเกี่ยวข้องอย่างมีนัยสำคัญ (นอกเหนือจากเกณฑ์ Single Lending Limit)</fullName>
            </value>
            <value>
                <fullName>2001700004:การจัดกลุ่มลูกหนี้อื่น ๆ</fullName>
            </value>
            <value>
                <fullName>2001700005:การจัดกลุ่มเพื่อติดตามความเสี่ยงภายใน</fullName>
            </value>
            <value>
                <fullName>2001700006:การจัดกลุ่มลูกหนี้ที่ส่งธนาคารกลางอื่น ๆ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SLL_Group_Approval_History__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SLL_Group_Approval_History__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request to add</fullName>
            </value>
            <value>
                <fullName>Request to remove</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SLL_Group_Approval_History__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SLL_Group_Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group_Approval_History__c/fields/SLL_Group_Member__c.field-meta.xml
<CustomField>
    <fullName>SLL_Group_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLL Group Member</label>
    <referenceTo>SLL_Group_Member__c</referenceTo>
    <relationshipLabel>SLL Group Approval Histories</relationshipLabel>
    <relationshipName>SLL_Group_Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group_Approval_History__c/fields/SLL_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>SLL_Group_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLL Group Name</label>
    <referenceTo>SLL_Group__c</referenceTo>
    <relationshipLabel>SLL Group Approval Histories</relationshipLabel>
    <relationshipName>SLL_Group_Approval_Histories1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group_Member__c/SLL_Group_Member__c.object-meta.xml
<CustomObject>
    <label>SLL Group Member</label>
    <nameField>
        <displayFormat>SGM-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLL Group Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SLL_Group_Member__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SLL Group Members</relationshipLabel>
    <relationshipName>SLL_Group_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group_Member__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2001700001:เป็นผู้ที่เกี่ยวข้อง (ตามประกาศ Single Lending Limit)</fullName>
            </value>
            <value>
                <fullName>2001700003:มีบุคคลในครอบครัวเกี่ยวข้องอย่างมีนัยสำคัญ (นอกเหนือจากเกณฑ์ Single Lending Limit)</fullName>
            </value>
            <value>
                <fullName>2001700004:การจัดกลุ่มลูกหนี้อื่น ๆ</fullName>
            </value>
            <value>
                <fullName>2001700005:การจัดกลุ่มเพื่อติดตามความเสี่ยงภายใน</fullName>
            </value>
            <value>
                <fullName>2001700006:การจัดกลุ่มลูกหนี้ที่ส่งธนาคารกลางอื่น ๆ</fullName>
            </value>
            <value>
                <fullName>2001700002:มีการถือหุ้นหรือกรรมการไขว้กัน</fullName>
                <isActive>false</isActive>
                <label>2001700002:มีการถือหุ้นหรือกรรมการไขว้กัน</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SLL_Group_Member__c/fields/SLL_Group__c.field-meta.xml
<CustomField>
    <fullName>SLL_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLL Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SLL_Group__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SLL_Group__c</referenceTo>
    <relationshipLabel>SLL Group Members</relationshipLabel>
    <relationshipName>SLL_Group_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RequestToAddSLLGroupController.cls
public class RequestToAddSLLGroupController {
    private static final String REQUEST_TO_ADD = 'Request to add';
    private static final String ERROR_PROCESSINSTANCE_LABEL = System.Label.RequestChangeOwnerMessage2;
    private static final String ERROR_EXISTCUSTOMER_LABEL = System.Label.SLLGroupMessage11;
    private static final String ERROR_NO_PAM_MANAGER_LABEL = System.Label.SLLGroupMessage3;
    private static final String ERROR_EXIST_PENDING_LABEL = System.Label.SLLGroupMessage14;
   
    public class wrapApprover{
        @AuraEnabled
        public User approver1 {get;set;}
        // @AuraEnabled
        // public User approver2 {get;set;}
        @AuraEnabled
        public String errMsg {get;set;}
    }
        
    @AuraEnabled
    public static Account getAccRec(String recordId) {
        Account acc = [SELECT id,name FROM Account WHERE id =: recordId LIMIT 1];
        return acc;
    }

    @AuraEnabled        
    public static List<String> getPickListValues() {
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = SLL_Group_Approval_History__c.Reason__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }     
        return pickListValuesList;
    }
        
    @AuraEnabled
    public static SLL_Group__c getGroupPAM(String GroupId) {
        SLL_Group__c sll = [SELECT Id, Name, Pam__c, Pam__r.Name, Is_Active__c FROM SLL_Group__c WHERE id =: GroupId LIMIT 1];
        return sll;
    }
        
    @AuraEnabled
    public static wrapApprover getPAMapprover(String userId) {
        User user = [SELECT id, ProfileId, Profile.Name, ManagerId, Manager.Name, Manager.ProfileId, Manager.Profile.Name, Manager.ManagerId FROM User WHERE id =: userId LIMIT 1];

        System.debug('Manager Profile : ' + user.Manager.Profile.Name);

        wrapApprover approverlst = new wrapApprover();
        if(user.ManagerId != null && user.Manager.ManagerId != null){
            User Approver1 = [SELECT IsActive,FirstName,LastName,id,ProfileId,Profile.Name, ManagerId, Manager.Name FROM User WHERE id =: user.ManagerId LIMIT 1];
            // User Approver2 = [SELECT IsActive,FirstName,LastName,id,ProfileId,Profile.Name, ManagerId, Manager.Name FROM User WHERE id =: user.Manager.ManagerId LIMIT 1];
            approverlst.approver1 = Approver1;
            // approverlst.approver2 = Approver2;
        }else{
                approverlst.errMsg = ERROR_NO_PAM_MANAGER_LABEL;
        }
        return approverlst;
    }

    @AuraEnabled
    public static String createRecord(String GroupId,String CustomerId, String Reason, String Approver1 ) {
    // public static String createRecord(String GroupId,String CustomerId, String Reason, String Approver1, String Approver2 ) {
        String status;

        List<ProcessInstanceWorkitem>  checkWorkItem = [SELECT Id, ProcessInstance.TargetObjectId FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId =: GroupId];

        if(checkWorkItem.size() == 0){
            List<SLL_Group_Member__c> groupMember = [SELECT id FROM SLL_Group_Member__c WHERE Customer_Name__c =: CustomerId AND SLL_Group__c =: GroupId];

            if(groupMember.size() == 0){
                List<SLL_Group_Approval_History__c> SLLHistory = [SELECT id, Request_Type__c, Approval_Status_Pending__c FROM SLL_Group_Approval_History__c WHERE Customer__c =: CustomerId AND SLL_Group_Name__c =: GroupId AND Approval_Status_Pending__c = 'Pending' AND Request_Type__c =: REQUEST_TO_ADD];

                if(SLLHistory.size() == 0){
                    SLL_Group_Approval_History__c rec = new SLL_Group_Approval_History__c();

                    Id currentuserId = Userinfo.getUserId();
                    datetime curDateTime = datetime.now();
                    String RequestType = REQUEST_TO_ADD;

                    rec.Customer__c = CustomerId;
                    rec.SLL_Group_Name__c = GroupId;
                    rec.Requester__c = currentuserId;
                    rec.Request_Date__c = curDateTime;
                    rec.Request_Type__c = RequestType;
                    rec.Reason__C = Reason;
                    rec.Approver1__c = Approver1;
                    // rec.Approver2__c = Approver2;
                    rec.Approval_Status_Pending__c = 'Pending';

                    Savepoint sp = Database.setSavepoint();
                    try{
                        insert rec;

                        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                        req.setObjectId(rec.Id);
                        Approval.ProcessResult result = Approval.process(req);
                        System.debug('Insert Record : ' + rec);
                        System.debug('Approval result : ' + result);
                        status = 'SUCCESS';
                    }catch (Exception e){
                        Database.rollback(sp);
                        System.debug('Exception caught');
                        System.debug(e.getMessage());
                        throw new AuraHandledException(e.getMessage());
                    }
                }else{
                    status = ERROR_EXIST_PENDING_LABEL;
                    System.debug(status);
                }
            }else{
                status = ERROR_EXISTCUSTOMER_LABEL;
                System.debug(status);
            }
        }else{
            status = ERROR_PROCESSINSTANCE_LABEL;
            System.debug(status);
        }
        return status;
    }
}