force-app/main/default/objects/SLL_Group__c/SLL_Group__c.object-meta.xml
<CustomObject>
    <label>SLL Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLL Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SLL_Group__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval - Active</fullName>
            </value>
            <value>
                <fullName>Approved - Active</fullName>
            </value>
            <value>
                <fullName>Rejected - Active</fullName>
            </value>
            <value>
                <fullName>Recalled - Active</fullName>
            </value>
            <value>
                <fullName>Pending Approval - Update</fullName>
            </value>
            <value>
                <fullName>Approved - Update</fullName>
            </value>
            <value>
                <fullName>Rejected - Update</fullName>
            </value>
            <value>
                <fullName>Recalled - Update</fullName>
            </value>
            <value>
                <fullName>Pending Approval - Inactive</fullName>
            </value>
            <value>
                <fullName>Approved - Inactive</fullName>
            </value>
            <value>
                <fullName>Rejected - Inactive</fullName>
            </value>
            <value>
                <fullName>Recalled - Inactive</fullName>
            </value>
            <value>
                <fullName>PAM Approver1 Approved - Active</fullName>
            </value>
            <value>
                <fullName>PAM Approver1 Approved - Update</fullName>
            </value>
            <value>
                <fullName>PAM Approver1 Approved - Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SLL_Groups2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/Approver2__c.field-meta.xml
<CustomField>
    <fullName>Approver2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SLL_Groups3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/PAM__c.field-meta.xml
<CustomField>
    <fullName>PAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PAM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>TMB RM Profile,TMB BDM Profile, TMB SE Zone Manager Profile</value>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>SLL_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/PAM_To_Be__c.field-meta.xml
<CustomField>
    <fullName>PAM_To_Be__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To Be PAM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SLL_Groups1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/Primary_Customer__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Existing_Customer, Prospect</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SLL Groups (Primary Customer)</relationshipLabel>
    <relationshipName>SLL_Groups1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/Primary_Customer_To_Be__c.field-meta.xml
<CustomField>
    <fullName>Primary_Customer_To_Be__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To Be Primary Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SLL Groups (Primary Customer To Be)</relationshipLabel>
    <relationshipName>SLL_Groups2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/Remark__c.field-meta.xml
<CustomField>
    <fullName>Remark__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Remark</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/Remark_To_Be__c.field-meta.xml
<CustomField>
    <fullName>Remark_To_Be__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>To Be Remark</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SLL_Groups6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/fields/SLL_Group_Name_To_Be__c.field-meta.xml
<CustomField>
    <fullName>SLL_Group_Name_To_Be__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>To Be SLL Group Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SLL_Group__c/recordTypes/Available.recordType-meta.xml
<RecordType>
    <fullName>Available</fullName>
    <active>true</active>
    <label>Available</label>
</RecordType>

force-app/main/default/objects/SLL_Group__c/recordTypes/Draft.recordType-meta.xml
<RecordType>
    <fullName>Draft</fullName>
    <active>true</active>
    <label>Draft</label>
</RecordType>

force-app/main/default/objects/SLL_Group_Approval_History__c/SLL_Group_Approval_History__c.object-meta.xml
<CustomObject>
    <label>SLL Group Approval History</label>
    <nameField>
        <displayFormat>SG-Req-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLL Group Approval Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SLL_Group_Approval_History__c/fields/Approval_Status_Pending__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status_Pending__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Approver1 Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SLL_Group_Approval_History__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SLL_Group_Approval_Histories1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group_Approval_History__c/fields/Approver2__c.field-meta.xml
<CustomField>
    <fullName>Approver2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SLL_Group_Approval_Histories2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group_Approval_History__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SLL_Group_Approval_History__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SLL_Group_Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLL_Group_Approval_History__c/fields/SLL_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>SLL_Group_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLL Group Name</label>
    <referenceTo>SLL_Group__c</referenceTo>
    <relationshipLabel>SLL Group Approval Histories</relationshipLabel>
    <relationshipName>SLL_Group_Approval_Histories1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EditSLLGroupController.cls
public class EditSLLGroupController{
    
    @AuraEnabled
    public static String editSllG(String recordId, String selectedName, String selectedPrimCus, String selectedPAMId, String selectedRemark) {
        
        //get id requester
        Id userId = Userinfo.getUserId();
        // SELECT Record Type Name กับ isActive ของ record ที่ต้องการแก้ไข
        SLL_Group__c recGroup = [SELECT Id, RecordType.Name, Is_Active__c, Approver1__c  FROM SLL_Group__c WHERE id =: recordId limit 1];
        // SLL_Group__c recGroup = [SELECT Id, RecordType.Name, Is_Active__c, Approver1__c, Approver2__c  FROM SLL_Group__c WHERE id =: recordId limit 1];
        // SELECT Manager คนที่ 1 และ Manager คนที่ 2  ของ PAM
        User PAM = [SELECT id, Name, ManagerId, Manager.IsActive FROM User WHERE id =: selectedPAMId limit 1];
        // User PAM = [SELECT id, Name, ManagerId, Manager.IsActive, Manager.ManagerId, Manager.Manager.IsActive FROM User WHERE id =: selectedPAMId limit 1];
    
        Boolean acApprover1 = PAM.Manager.IsActive;
        // Boolean acApprover2 = PAM.Manager.Manager.IsActive;
        String nameApprover1 = PAM.ManagerId;
        // String nameApprover2 = PAM.Manager.ManagerId;
        datetime myDate = datetime.now();
        String msg = null;

        List<SLL_Group_Approval_History__c> groupAppHistLst = new List<SLL_Group_Approval_History__c>();

        //Check Approver1 & Approver2 Active(true) หรือเปล่า
        if(acApprover1) {
        // if(acApprover1 && acApprover2) {
            msg = 'active';

            recGroup.Id = recordId;
            //filter RecordType กับ IsActive
            if (recGroup.RecordType.Name == 'Available' && recGroup.Is_Active__c == true) {
                recGroup.SLL_Group_Name_To_Be__c = selectedName;
                recGroup.Primary_Customer_To_Be__c = selectedPrimCus;
                recGroup.PAM_To_Be__c = selectedPAMId;
                recGroup.Remark_To_Be__c = selectedRemark;
                recGroup.Approval_Status__c = 'Pending Approval - Update';
                recGroup.Requester__c = userId;
                recGroup.Request_Date__c = myDate;
            } else if (recGroup.RecordType.Name == 'Draft' && recGroup.Is_Active__c == false) {
                //SELECT Approval Status Pending ที่ต้องการแก้ไขของ SLL Group Approval History 
                groupAppHistLst = [SELECT Id, Approval_Status_Pending__c FROM SLL_Group_Approval_History__c WHERE SLL_Group_Name__c =: recordId];
                //loop แก้ไข Approval Status Pending = 'Pending' loop แล้วเก็บไว้ใน groupAppHistLst
                for(SLL_Group_Approval_History__c groupHistory : groupAppHistLst) {
                    groupHistory.Approval_Status_Pending__c = 'Pending';
                }
                recGroup.Name = selectedName;
                recGroup.Primary_Customer__c = selectedPrimCus;
                recGroup.PAM__c = selectedPAMId;
                recGroup.Remark__c = selectedRemark;
                recGroup.Approval_Status__c = 'Pending Approval - Active';
                recGroup.Requester__c = userId;
                recGroup.Request_Date__c = myDate;
                recGroup.Approver1__c = nameApprover1;
                // recGroup.Approver2__c = nameApprover2;
            }
            //Save point ตามชื่อ Save Database ก่อนที่จะทำการ update Database
            Savepoint sp = Database.setSavepoint();

            try{
                update recGroup;
                System.debug(recGroup);
                if(groupAppHistLst.size() > 0) update groupAppHistLst;
                
                Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                req.setObjectId(recGroup.Id);
                // req.setComments('Get user Id Submitter.');
                req.setSubmitterId(Userinfo.getUserId());
                //คำสั่ง Approval process ให้เริ่มทำงาน
                Approval.ProcessResult result = Approval.process(req);
                System.debug('Approval result : ' + result);

            } catch (Exception e) {
                //ให้กลับไปยังจุดที่ Save Database ไว้ก่อนที่จะ update Database เพราะ error
                Database.rollback(sp);
                System.debug('Exception caught');
                System.debug(e.getMessage());
                throw new AuraHandledException(e.getMessage());
            }
        } else {
            msg = 'inactive';
        }
       return msg;
    } 
}