force-app/main/default/objects/RTL_HHM_RLID__c/RTL_HHM_RLID__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Related List ID for custom button</description>
    <label>Household Member Related List ID</label>
</CustomObject>

force-app/main/default/objects/RTL_HHM_RLID__c/fields/RTL_RLID__c.field-meta.xml
<CustomField>
    <fullName>RTL_RLID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Related List ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Household__c/RTL_Household__c.object-meta.xml
<CustomObject>
    <label>Household</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/RTL_Household_History_and_Approval__c.object-meta.xml
<CustomObject>
    <label>Household History and Approval</label>
    <nameField>
        <displayFormat>HH-{00000000}</displayFormat>
        <label>Household History and Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Household History and Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Household__c.field-meta.xml
<CustomField>
    <fullName>RTL_Household__c</fullName>
    <description>Household which this History record belongs to</description>
    <label>Household</label>
    <referenceTo>RTL_Household__c</referenceTo>
    <relationshipLabel>Household History and Approvals</relationshipLabel>
    <relationshipName>Household_History_and_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTL_Household_History_and_Approval__c/fields/RTL_Household_Member__c.field-meta.xml
<CustomField>
    <fullName>RTL_Household_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Household member which this change is related to</description>
    <label>Household Member</label>
    <referenceTo>RTL_Household_Member__c</referenceTo>
    <relationshipLabel>Household History and Approvals</relationshipLabel>
    <relationshipName>Household_History_and_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Household_Member__c/RTL_Household_Member__c.object-meta.xml
<CustomObject>
    <label>Household Membership</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Household Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Household_Member__c/fields/RTL_Household__c.field-meta.xml
<CustomField>
    <fullName>RTL_Household__c</fullName>
    <description>Household that this member record belongs to</description>
    <label>Household</label>
    <referenceTo>RTL_Household__c</referenceTo>
    <relationshipName>Household_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RTL_HouseholdRelatedListProxyCtrlTest.cls
@isTest
public class RTL_HouseholdRelatedListProxyCtrlTest {
	static User rmUser;
    static User rmManager;
    static List<Account> acctList;
    static RTL_Household_Member__c member;
    static List<RTL_Household__c> householdList;
    static List<RTL_Household_History_And_Approval__c> historyList;
   
    static{
        
        TestUtils.createAppConfig();
        rmUser = RTL_TestUtility.createRetailTestUserWithBranch(true);
        rmManager = RTL_TestUtility.createRetailTestUser(true);
        acctList = RTL_TestUtility.createAccounts(2,true);
        householdList = RTL_TestUtility2.createHouseholdwithPrimaryMember(1,true,rmUser,acctList[0]);
        
        rmUser.ManagerId = rmManager.id;
        update rmUser;   
        
        RTL_HHM_RLID__c hhmrlid = new RTL_HHM_RLID__c(Name='ID',RTL_RLID__c='id');
        insert hhmrlid;
    }
	testmethod static void testCreateHouseholdMember(){
        Test.startTest();
        	RTL_HouseholdHistoryTriggerHandler.historyTrigger = false;
			Test.setCurrentPage(Page.RTL_HouseHold_Detail);
        	ApexPages.currentPage().getParameters().put('acctId',acctList[0].id);
        	member = new RTL_Household_Member__c();
        	ApexPages.StandardController std = new ApexPages.StandardController(member);
        	RTL_HouseholdRelatedListProxyCtrl ext = new RTL_HouseholdRelatedListProxyCtrl(std);
        	ext.redirectPage();
		Test.stopTest();  
    }
}