force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Problem_Type__c.field-meta.xml
<CustomField>
    <fullName>Problem_Type__c</fullName>
    <label>Problem Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Failure - ไม่ได้รับบริการในสิ่งที่ลูกค้าต้องการ</fullName>
            </value>
            <value>
                <fullName>Delay - ได้รับบริการ แต่ช้า</fullName>
            </value>
            <value>
                <fullName>Quality/Suitability - ได้รับบริการ แต่ลูกค้าขอให้ตรวจสอบ</fullName>
            </value>
            <value>
                <fullName>Quality/Suitability - ได้รับบริการ แต่ลูกค้าไม่พอใจ</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PostChannel2Queue__mdt/PostChannel2Queue__mdt.object-meta.xml
<CustomObject>
    <label>Post Channel to Queue</label>
    <pluralLabel>Post Channel to Queue</pluralLabel>
</CustomObject>

force-app/main/default/objects/PostChannel2Queue__mdt/fields/Social_ID__c.field-meta.xml
<CustomField>
    <fullName>Social_ID__c</fullName>
    <label>Social ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostChannel2Queue__mdt/fields/Topic_Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Topic_Profile_Name__c</fullName>
    <label>Topic Profile Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostChannel2Queue__mdt/fields/Warroom_Channel__c.field-meta.xml
<CustomField>
    <fullName>Warroom_Channel__c</fullName>
    <label>Warroom Channel</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Skill_Master__c/Skill_Master__c.object-meta.xml
<CustomObject>
    <label>Skill Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Skill Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skill Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill_Master__c/fields/Assign_to_Queue__c.field-meta.xml
<CustomField>
    <fullName>Assign_to_Queue__c</fullName>
    <description>Assign to Queue</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Assign to Queue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Problem_Type__c.field-meta.xml
<CustomField>
    <fullName>Problem_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Problem Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Segment</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Service_Level1__c.field-meta.xml
<CustomField>
    <fullName>Service_Level1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Level1</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Service_Level2__c.field-meta.xml
<CustomField>
    <fullName>Service_Level2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Level2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Service_Level3__c.field-meta.xml
<CustomField>
    <fullName>Service_Level3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Level3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Social_Network__c.field-meta.xml
<CustomField>
    <fullName>Social_Network__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Social Network</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Topic</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Topic_Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Topic_Profile_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Topic Profile Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/fields/Validate_Code__c.field-meta.xml
<CustomField>
    <fullName>Validate_Code__c</fullName>
    <description>This field for define code to validate in case validation rule</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This field for define service code to use in validation rule, report, back end integration.</inlineHelpText>
    <label>Service Type Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/Social_Post__c.object-meta.xml
<CustomObject>
    <label>Warroom Social Post</label>
    <nameField>
        <displayFormat>SP-{yyyy}{mm}-{00000}</displayFormat>
        <label>Social Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warroom Social Posts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Post__c/fields/Comment_No__c.field-meta.xml
<CustomField>
    <fullName>Comment_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comment No.</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Conversation_Id_List__c.field-meta.xml
<CustomField>
    <fullName>Conversation_Id_List__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Conversation Id List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/External_Link__c.field-meta.xml
<CustomField>
    <fullName>External_Link__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>External Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Internal_Link__c.field-meta.xml
<CustomField>
    <fullName>Internal_Link__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Internal Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_Author_Type__c.field-meta.xml
<CustomField>
    <fullName>Post_Author_Type__c</fullName>
    <label>Post Author Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_Body__c.field-meta.xml
<CustomField>
    <fullName>Post_Body__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Post Body</label>
    <length>3200</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Post_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Post Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_ID__c.field-meta.xml
<CustomField>
    <fullName>Post_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Post ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_Identity_ID__c.field-meta.xml
<CustomField>
    <fullName>Post_Identity_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Post Identity ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_Title__c.field-meta.xml
<CustomField>
    <fullName>Post_Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Post Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Post_Type__c.field-meta.xml
<CustomField>
    <fullName>Post_Type__c</fullName>
    <label>Post Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>post</fullName>
            </value>
            <value>
                <fullName>comment</fullName>
            </value>
            <value>
                <fullName>Tweet</fullName>
            </value>
            <value>
                <fullName>Inbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Sentiment__c.field-meta.xml
<CustomField>
    <fullName>Sentiment__c</fullName>
    <label>Sentiment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>positive</fullName>
            </value>
            <value>
                <fullName>neutral</fullName>
            </value>
            <value>
                <fullName>negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Social_Post_Author__c.field-meta.xml
<CustomField>
    <fullName>Social_Post_Author__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Social Post Author</label>
    <referenceTo>Social_Post_Author__c</referenceTo>
    <relationshipName>Custom_Social_Posts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Source_Channel__c.field-meta.xml
<CustomField>
    <fullName>Source_Channel__c</fullName>
    <label>Source Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Facebook Inbox</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>LINE</fullName>
            </value>
            <value>
                <fullName>LINE Account Connect</fullName>
            </value>
            <value>
                <fullName>Pantip</fullName>
            </value>
            <value>
                <fullName>Pantip Inbox</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>Twitter Inbox</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Google Business Review</fullName>
            </value>
            <value>
                <fullName>Google Business QA</fullName>
            </value>
            <value>
                <fullName>Warroom Connect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Subject_ID__c.field-meta.xml
<CustomField>
    <fullName>Subject_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Subject ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Subject_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Subject Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Thread_ID__c.field-meta.xml
<CustomField>
    <fullName>Thread_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Thread ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post__c/fields/Topic_Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Topic_Profile_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Topic Profile Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post_Author__c/Social_Post_Author__c.object-meta.xml
<CustomObject>
    <label>Social Post Author</label>
    <nameField>
        <displayFormat>SA-{YYYY}{MM}{0000}</displayFormat>
        <label>Social Post Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Post Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Post_Author__c/fields/Post_Author_ID__c.field-meta.xml
<CustomField>
    <fullName>Post_Author_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Post Author ID</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Social_Post_Author__c/fields/Post_Author_Name__c.field-meta.xml
<CustomField>
    <fullName>Post_Author_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Social Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Post_Author__c/fields/Post_Author_Social_ID__c.field-meta.xml
<CustomField>
    <fullName>Post_Author_Social_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Post Author Social ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/acceptPostControllerTest.cls
@istest
public with sharing class acceptPostControllerTest {
    
    //public static final Id System_Administrator = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id;
    @TestSetup
    static void makeData(){
        Id System_Administrator = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id;
 
        System.runAs(new User(Id=UserInfo.getUserId()))
		{
            List<Group> g = [SELECT Id FROM Group WHERE DeveloperName = 'test_queue' AND Type = 'Queue' LIMIT 1];
            if (g.isEmpty()) {
                Group q = new Group(Name = 'Post - TTB Advisory', DeveloperName = 'test_queue', type = 'Queue');
                insert q;
                g.add(q);
        	}
        QueueSobject supportObj = new QueueSobject(QueueId = g.get(0).Id, SobjectType = 'Social_Post__c');
        insert supportObj;
        Skill_Master__c skillMaster = new Skill_Master__c();
        skillMaster.Topic__c='สอบถามเรื่องทั่วไปและข้อเสนอแนะ';
        skillMaster.Source__c='Social Media - TTB Advisory';
        skillMaster.Segment__c='RBG';
        skillMaster.Assign_to_Queue__c='Post - TTB Advisory';
        skillMaster.Service_Level1__c='Inquiry';
        skillMaster.Service_Level2__c='Contact Center';
        skillMaster.Service_Level3__c='';
        skillMaster.Problem_Type__c='';
        skillMaster.Social_Network__c='Facebook';
        skillMaster.Topic_Profile_Name__c ='ttb advisory';
        skillMaster.Validate_Code__c ='X0027';
        insert skillMaster;   
        }
        
        //create User
        User newUser1 = new User(
            FirstName = 'FName1',
            LastName = 'LName1',
            UserName = 'test1@tmb.com',
            Email = 'test1@tmbbank.com',
            Alias = 'Testtmb',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            CommunityNickname = 'TMBTesttmb1',
            ProfileId = System_Administrator,
            TimeZoneSidKey = 'America/New_York',
            isActive = true,
            Employee_ID__c = 'MM012'
        );
        insert newUser1;
        
        User newUser2 = new User(
            FirstName = 'FName2',
            LastName = 'LName2',
            UserName = 'test2@tmb.com',
            Email = 'test2@tmbbank.com',
            Alias = 'Testtmb',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            CommunityNickname = 'TMBTesttmb2',
            ProfileId = System_Administrator,
            TimeZoneSidKey = 'America/New_York',
            isActive = true,
            Employee_ID__c = 'MM013'
        );
        insert newUser2;

        System.runAs(newUser2) {
            AppConfig__c runtrigger = new AppConfig__c();
            runtrigger.Name = 'runtrigger';
            runtrigger.Value__c = 'false';
            insert runtrigger;
            AppConfig__c ac = new AppConfig__c(Name = 'encrypt_CardKey', Value__c = 'TMBCRM76380f&uexjslmdka(-yjr9UAT');
            insert ac;
        }

        //create Social_Post__c
        System.runAs(new User(Id=UserInfo.getUserId()))
		{
            Group queue = [SELECT Id FROM Group WHERE Name = 'Post - TTB Advisory' and Type = 'queue' LIMIT 1];
            GroupMember g1 = new GroupMember(GroupId = queue.Id, UserOrGroupId = newUser1.Id);
            insert g1;
            GroupMember g2 = new GroupMember(GroupId = queue.Id, UserOrGroupId = newUser2.Id);
            insert g2;
        }
        
        
        Social_Post_Author__c socialPostAuthor = new Social_Post_Author__c();
        socialPostAuthor.Post_Author_ID__c = '12345679';
        socialPostAuthor.Post_Author_Social_ID__c = '65432109876543xx';
        socialPostAuthor.Post_Author_Name__c = 'abcdef';
        insert socialPostAuthor;
        
        List<PostChannel2Queue__mdt> postChannel2QueueList = [select id, Topic_Profile_Name__c, Warroom_Channel__c, Social_ID__c from PostChannel2Queue__mdt  where Topic_Profile_Name__c = 'ttb advisory'];
        String subjectName = postChannel2QueueList[0].Warroom_Channel__c;

        Social_Post__c socialPost2 = new Social_Post__c();
        socialPost2.Source_Channel__c='Facebook';
        socialPost2.Post_Author_Type__c='Customer';
        socialPost2.Conversation_Id_List__c='[\"3050282502\", \"3050283061\", \"3050283101\"]';
        socialPost2.External_Link__c='https://www.facebook.com/542164707373338';
        socialPost2.Internal_Link__c='https://warroom.wisesight.com/thread/47525025/3050283061';
        socialPost2.Post_ID__c='3050282zzz';
        socialPost2.Post_Title__c='';
        socialPost2.Post_Body__c='สวัสดีตอนยามเย็น ttb advisory (Page)';
        socialPost2.Post_Type__c='Post';
        socialPost2.Post_Date__c=Datetime.now();
        socialPost2.Post_Identity_ID__c='4450005976268xx_5421647073733zz';
        socialPost2.Sentiment__c='positive';
        socialPost2.Comment_No__c='1.00000';
        socialPost2.Subject_ID__c='118xx';
        socialPost2.Subject_Name__c=subjectName;
        socialPost2.Thread_ID__c='47525026';
        socialPost2.Post_Tags__c='[\"Chatbot\", \"Success\"]';
        socialPost2.Thread_Identity_ID__c='503815916439094_2233297906824zzz';
        socialPost2.Thread_Type__c='Facebook';
        socialPost2.Social_Post_Author__c=socialPostAuthor.id;

        insert socialPost2;

    }

    @IsTest
    static void acceptPostTest() {
        /*
        Id sp = [SELECT id FROM Social_Post__c WHERE Thread_Type__c = 'Facebook' LIMIT 1].Id;
        User newUser1 = [SELECT Id FROM User WHERE Firstname = 'FName1' LIMIT 1];
        User newUser2 = [SELECT Id FROM User WHERE Firstname = 'FName2' LIMIT 1];
        Group queue = [SELECT Id FROM Group WHERE Name = 'Post - TTB Advisory' and Type = 'queue' LIMIT 1];

        GroupMember g1 = new GroupMember(GroupId = queue.Id, UserOrGroupId = newUser1.Id);
        insert g1;
        GroupMember g2 = new GroupMember(GroupId = queue.Id, UserOrGroupId = newUser2.Id);
        insert g2;
*/
        // Id queueowner = [SELECT id FROM Social_Post__c WHERE Name = 'Test queue' LIMIT 1].Id;
        
        // test transfer to queue
        Group queue = [SELECT Id FROM Group WHERE Name = 'Post - TTB Advisory' and Type = 'queue' LIMIT 1];
        Id queueowner = queue.Id;
        User newUser1 = [select id from User where FirstName = 'FName1'];
        User newUser2 = [SELECT Id FROM User WHERE Firstname = 'FName2' LIMIT 1];
        Social_Post__c sp = [select Id from Social_Post__c where Post_ID__c='3050282zzz'];
       	// test transfer to queue
        System.runAs(newUser1) {
            try {
                Social_Post__c s = [select Id from Social_Post__c where Post_ID__c='3050282zzz'];
                s.OwnerId = newUser1.Id;
                update s;
                acceptPostButtonController.acceptPost(s.Id, newUser1.Id);
            } catch (Exception e) {
                System.assertEquals('You are already owner.', e.getMessage());
            }
        }

        System.runAs(newUser2) {
            try {
                acceptPostButtonController.acceptPost(sp.Id, newUser2.Id);
            } catch (Exception e) {
                System.assertEquals('You don\'t have authorization to accept case.', e.getMessage());
            }
        }
    }
}