force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDPA_Activity_Log__c/PDPA_Activity_Log__c.object-meta.xml
<CustomObject>
    <label>PDPA Activity Log</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000}</displayFormat>
        <label>PDPA Activity Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PDPA Activity Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PurgePDPAActivityLogBatchScheduler.cls
global class PurgePDPAActivityLogBatchScheduler implements Schedulable {

    private static Integer purge_backDate {
        get { 
            if( purge_backDate == null) {   
                AppConfig__c appConfig = AppConfig__c.getValues('PDPA_Activity_Log_Purge_Days');
                if(appConfig == null) {
                    purge_backDate = 365;
                } else {
                    purge_backDate = Integer.valueOf(appConfig.Value__c);
                }
            }
            return purge_backDate;
        } 
        set; 
    } 
    
    global void execute(SchedulableContext sc) {
        Date backDate = System.Today().addDays(-purge_backDate);
        String q = 'SELECT Id FROM PDPA_Activity_Log__c WHERE CreatedDate <=: BACKDATE';

		database.executebatch(new PurgePDPAActivityLogBatch(q, backDate), 2000);
    }
}