force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Online_Service_Log__c/RTL_Online_Service_Log__c.object-meta.xml
<CustomObject>
    <description>This object capture error log from Retail online services</description>
    <label>Online Service Log</label>
    <nameField>
        <displayFormat>Log No{0000000}</displayFormat>
        <label>Online Service Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Service Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Online_Service_Log__c/fields/RTL_Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_Customer_Name__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Reference Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/RTL_Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{YY}{MM}{DD}-{000}</displayFormat>
        <label>Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Referral__c/fields/Assigned_Pool__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Pool__c</fullName>
    <label>Assigned Pool</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRANCH</fullName>
            </value>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
            <value>
                <fullName>RMC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/Call_Me_Now_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Call_Me_Now_Datetime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Call Me Now Datetime</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/Call_Me_Now_Interested_Product__c.field-meta.xml
<CustomField>
    <fullName>Call_Me_Now_Interested_Product__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Call Me Now Interested Product</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/Call_Me_Now_URL__c.field-meta.xml
<CustomField>
    <fullName>Call_Me_Now_URL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Call Me Now URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/FNA_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>FNA_Product_Name__c</fullName>
    <description>For keep FNA product name (Interested product)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>FNA Product Name</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Call_Me_Now_Request__c.field-meta.xml
<CustomField>
    <fullName>RTL_Call_Me_Now_Request__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Call Me Now Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Call_Me_Now_Request_Count__c.field-meta.xml
<CustomField>
    <fullName>RTL_Call_Me_Now_Request_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Call Me Now Request Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Call_Me_Now_Response__c.field-meta.xml
<CustomField>
    <fullName>RTL_Call_Me_Now_Response__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Call Me Now Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Call_Me_Now_Status__c.field-meta.xml
<CustomField>
    <fullName>RTL_Call_Me_Now_Status__c</fullName>
    <description>list of value : success , fail</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Call Me Now Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Campaign__c.field-meta.xml
<CustomField>
    <fullName>RTL_Campaign__c</fullName>
    <description>used with integration to Telephony</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Campaign</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Campaign_Reference__c.field-meta.xml
<CustomField>
    <fullName>RTL_Campaign_Reference__c</fullName>
    <description>used in web to referral</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Campaign Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Channel_Segment__c.field-meta.xml
<CustomField>
    <fullName>RTL_Channel_Segment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Referred by Channel/Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_FirstName__c.field-meta.xml
<CustomField>
    <fullName>RTL_FirstName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_From_Call_Me_Now__c.field-meta.xml
<CustomField>
    <fullName>RTL_From_Call_Me_Now__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CR Call Me Now to check if trigger is called from call me now service</description>
    <label>From Call Me Now</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Interested_Product__c.field-meta.xml
<CustomField>
    <fullName>RTL_Interested_Product__c</fullName>
    <label>Interested Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>RTL_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BA(Credit Life)</fullName>
            </value>
            <value>
                <fullName>BA (IL)</fullName>
            </value>
            <value>
                <fullName>BA (Unit Link)</fullName>
            </value>
            <value>
                <fullName>BA (Others)</fullName>
            </value>
            <value>
                <fullName>Business Click (Basic Plus)</fullName>
            </value>
            <value>
                <fullName>Business Click  (Basic Plus)</fullName>
            </value>
            <value>
                <fullName>Credit Card &amp; RDC</fullName>
            </value>
            <value>
                <fullName>EDC</fullName>
            </value>
            <value>
                <fullName>FX</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>LG</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>OD</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>Prompt Pay</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>TMB Business Touch</fullName>
            </value>
            <value>
                <fullName>TMB Business  Touch</fullName>
            </value>
            <value>
                <fullName>TMB QR</fullName>
            </value>
            <value>
                <fullName>TMB Payroll</fullName>
            </value>
            <value>
                <fullName>TMB SME One Bank (155)</fullName>
            </value>
            <value>
                <fullName>TMB SME One Bank  (155)</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเพื่อธุรกิจ - LG</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเพื่อธุรกิจ - Loan</fullName>
            </value>
            <value>
                <fullName>Refer From TBANK: สินเชื่อเพื่อธุรกิจ - Loan</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเพื่อธุรกิจ - OD</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเพื่อธุรกิจ - Supply Chain [ODB (Clean)]</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเพื่อธุรกิจ - Supply Chain [Factoring (Accepted Invoice)]</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเพื่อธุรกิจ - Supply Chain [Factoring (Confirmed Payment)]</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_LastName__c.field-meta.xml
<CustomField>
    <fullName>RTL_LastName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Mobile1__c.field-meta.xml
<CustomField>
    <fullName>RTL_Mobile1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mobile1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Product_Name_Str__c.field-meta.xml
<CustomField>
    <fullName>RTL_Product_Name_Str__c</fullName>
    <formula>RTL_Product_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name Str</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_RecordType_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_RecordType_Name__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RecordType Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Remark_from_Online_Loan__c.field-meta.xml
<CustomField>
    <fullName>RTL_Remark_from_Online_Loan__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Remark from Online Loan</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Sub_Product__c.field-meta.xml
<CustomField>
    <fullName>RTL_Sub_Product__c</fullName>
    <label>Sub Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>สินเชื่อเงินกู้เบิกเกินบัญชีทั่วไป</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเงินกู้เบิกเกินบัญชี พร้อมเพิ่ม</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเงินกู้เพื่อก่อสร้างสถานประกอบการ</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเงินกู้เพื่อซื้อสถานประกอบการ</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเงินกู้เพื่อซื้ออาคารพาณิชย์ หรือ โฮมออฟฟิศ</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเงินกู้เพื่อซื้อเครื่องจักร</fullName>
            </value>
            <value>
                <fullName>สินเชื่อเงินกู้แบบไม่มีหลักประกัน</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/web_business01__c.field-meta.xml
<CustomField>
    <fullName>web_business01__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>business1</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/web_business02__c.field-meta.xml
<CustomField>
    <fullName>web_business02__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>business2</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/web_business03__c.field-meta.xml
<CustomField>
    <fullName>web_business03__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>business3</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/web_business04__c.field-meta.xml
<CustomField>
    <fullName>web_business04__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>business4</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/web_business05__c.field-meta.xml
<CustomField>
    <fullName>web_business05__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>business5</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/web_business06__c.field-meta.xml
<CustomField>
    <fullName>web_business06__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>business6</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/web_business07__c.field-meta.xml
<CustomField>
    <fullName>web_business07__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>business7</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/web_business08__c.field-meta.xml
<CustomField>
    <fullName>web_business08__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>business8</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/web_business09__c.field-meta.xml
<CustomField>
    <fullName>web_business09__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>business9</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/web_business10__c.field-meta.xml
<CustomField>
    <fullName>web_business10__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>business10</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/avayaCallListReferralBatch.cls
global class avayaCallListReferralBatch implements Database.Batchable<sObject>,Database.AllowsCallouts,Database.Stateful{
    String query;

    private List<RTL_Referral__c> updateReferralList;
    private Set<Id> queryReferralIdset;
    private Map<String, RTL_Online_Service_Log__c> mapWebUnioslog;
    private Map<String, OnlineServiceLog> mapWebUnioslogDetail;
    private BusinessHours bh;

    private static User currentUser {
        get{
            if(currentUser == null){
                currentUser = [SELECT Id, Name, Employee_ID__c FROM User WHERE Id = :System.UserInfo.getUserId()];
            }
            return currentUser;
        }
        set;
    }

    private static Map<String, NamedCredential> mapNamedCredentiallURL {
        get{
            if(mapNamedCredentiallURL == null){
                mapNamedCredentiallURL = new Map<String, NamedCredential>();
                for(NamedCredential namedCre : [SELECT DeveloperName, Endpoint FROM NamedCredential WHERE DeveloperName LIKE 'WsCallMeNow%']){
                    mapNamedCredentiallURL.put(namedCre.DeveloperName, namedCre);
                }
            }
            System.debug('mapNamedCredentiallURL : ' + mapNamedCredentiallURL);
            return mapNamedCredentiallURL;
        }
        set;
    }

    public avayaCallListReferralBatch(Set<Id> referralIdSet) {
        mapWebUnioslog = new Map<String, RTL_Online_Service_Log__c>();
        mapWebUnioslogDetail = new Map<String, OnlineServiceLog>();
        updateReferralList = new List<RTL_Referral__c>();

        bh = [SELECT Id FROM BusinessHours WHERE Name = 'Call Me Now'];

        queryReferralIdset = referralIdSet;

        query = 'SELECT Id, Name, RTL_FirstName__c, Assigned_Pool__c, RTL_LastName__c, RTL_RecordType_Name__c, RTL_Product_Name_Str__c, FNA_Product_Name__c, RTL_Interested_Product__c, RTL_Sub_Product__c, RTL_Mobile1__c, RTL_Channel_Segment__c, RTL_Campaign__c, RTL_Call_Me_Now_Request_Count__c, web_business01__c, web_business02__c, web_business03__c, web_business04__c, web_business05__c, web_business06__c, web_business07__c, web_business08__c, web_business09__c, web_business10__c, RTL_Remark_from_Online_Loan__c, RTL_Campaign_Reference__c FROM RTL_Referral__c WHERE Id IN :queryReferralIdset';
    }

    public avayaCallListReferralBatch(String queryStr, Set<Id> referralIdSet) {
        mapWebUnioslog = new Map<String, RTL_Online_Service_Log__c>();
        mapWebUnioslogDetail = new Map<String, OnlineServiceLog>();
        updateReferralList = new List<RTL_Referral__c>();

        bh = [SELECT Id FROM BusinessHours WHERE Name = 'Call Me Now'];

        query = queryStr;
        queryReferralIdset = referralIdSet;
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        Datetime dateTimeNow = Datetime.now();
        
        for(sObject obj : scope){
            RTL_Referral__c referral = (RTL_Referral__c)obj;
            
            // if(!BusinessHours.isWithin(bh.Id, dateTimeNow) && referral.RTL_RecordType_Name__c != 'Refer from Digital Channel'){
            //     referral.RTL_Call_Me_Now_Status__c = 'fail';
            //     referral.RTL_From_Call_Me_Now__c = true;
            // }else{
                avayaCallistDTO callMeNowObj = new avayaCallistDTO();

                DateTime now = System.now();
                String rtlDateTime = '';
                String strDateTime = '';
                String interestedProduct = '';
                String referralRecordTypeName = referral.RTL_RecordType_Name__c;

                //CR Refer from branch to any channel
                if (referralRecordtypeName == 'Retail Cross Channel Referral') {
                    interestedProduct = referral.RTL_Product_Name_Str__c;
                }else if(referralRecordtypeName == 'Refer from Digital Channel'){
                    interestedProduct = referral.FNA_Product_Name__c;
                    if(referral.Assigned_Pool__c == 'OUTBOUND'){
                        rtlDateTime = checkBusinessHour('Retail Outbound', Datetime.now());
                    }else{
                        rtlDateTime = checkBusinessHour('Call Me Now', Datetime.now());
                    }
                }else{
                    interestedProduct = referral.RTL_Interested_Product__c;
                }
               
                if(rtlDateTime != '' && rtlDateTime != null){
                    strDateTime = rtlDateTime;
                }else if (referralRecordTypeName == 'Retail Cross Channel Referral') {
                    strDateTime = RTL_ReferralAssignUtility.getNextnBSDate().addHours(7).formatGMT('dd/MM/yyyy HH:mm:ss');
                }else if(referral.RTL_Campaign_Reference__c == 'Call Me Now'){
                    strDateTime = System.now().addHours(7).formatGMT('dd/MM/yyyy HH:mm:ss');
                }else{
                    strDateTime = '';
                }
                
                AppConfig__c lightCF = AppConfig__c.getValues('URL_Lightning');
                String sfdcBaseLightningURL = lightCF == null ? 'https://tmbbank--uat.lightning.force.com' : lightCF.Value__c;

                callMeNowObj.request.setRequestId(referral.Id);
                callMeNowObj.request.setFirstName(referral.RTL_FirstName__c == null || referral.RTL_FirstName__c == '' ? '-' : referral.RTL_FirstName__c);
                callMeNowObj.request.setLastName(referral.RTL_LastName__c);
                callMeNowObj.request.setProductName(interestedProduct);
                callMeNowObj.request.setSub_ProductName(referral.RTL_Sub_Product__c);
                callMeNowObj.request.setMobile(referral.RTL_Mobile1__c);
                callMeNowObj.request.setCampaign(referral.RTL_Campaign__c);
                callMeNowObj.request.setDial_time(strDateTime);//'dd/MM/yyyy HH:mm:ss';
                callMeNowObj.request.setChannel_name(referral.RTL_Channel_Segment__c);
                callMeNowObj.request.setSf_id(referral.Id);
                
                callMeNowObj.request.setBusiness1(referral.web_business01__c);
                callMeNowObj.request.setBusiness2(referral.web_business02__c);
                callMeNowObj.request.setBusiness3(referral.web_business03__c);
                callMeNowObj.request.setBusiness4(referral.web_business04__c);
                callMeNowObj.request.setBusiness5(referral.web_business05__c);
                callMeNowObj.request.setBusiness6(referral.web_business06__c);
                callMeNowObj.request.setBusiness7(referral.web_business07__c);
                callMeNowObj.request.setBusiness8(referral.web_business08__c);
                callMeNowObj.request.setBusiness9(referral.web_business09__c);
                callMeNowObj.request.setBusiness10(referral.web_business10__c);
        
                callMeNowObj.request.setRemark(referral.RTL_Remark_from_Online_Loan__c);
                callMeNowObj.request.setURL(sfdcBaseLightningURL + '/lightning/r/RTL_Referral__c/' + referral.Id + '/view');

                System.debug(callMeNowObj.generateJSONContent());

                OnlineServiceLog oslogDetail = CallMeNowService.addToAvayaCallist(callMeNowObj, 'Avaya');

                System.debug(oslogDetail);
                
                referral.Call_Me_Now_Interested_Product__c = callMeNowObj.request.getTruncateProductName();
                referral.Call_Me_Now_Datetime__c = callMeNowObj.request.getDial_time();
                referral.Call_Me_Now_URL__c = callMeNowObj.request.getTruncateURL();

                referral.RTL_Call_Me_Now_Request__c = callMeNowObj.generateJSONContent();
                referral.RTL_Call_Me_Now_Response__c = callMeNowObj.response.rawResponse;
                referral.RTL_From_Call_Me_Now__c = true;
                referral.RTL_Call_Me_Now_Status__c = 'success';
                
                if(!oslogDetail.isSuccess){
                    referral.RTL_Call_Me_Now_Status__c = 'fail';

                    System.debug('Call Me Now Retry Count -->' + referral.RTL_Call_Me_Now_Request_Count__c);

                    referral.RTL_Call_Me_Now_Request_Count__c = referral.RTL_Call_Me_Now_Request_Count__c == null ? 0 : referral.RTL_Call_Me_Now_Request_Count__c;
                    referral.RTL_Call_Me_Now_Request_Count__c += 1;

                    if(referral.RTL_Call_Me_Now_Request_Count__c >= 3){
                        referral.RTL_Call_Me_Now_Status__c = 'fail';
                    }
                }

                RTL_Online_Service_Log__c oslog = new RTL_Online_Service_Log__c();
                oslog.RTL_Customer_Name__c = referral.Id;
                oslog.RTL_Name_of_User__c = currentUser.Name;
                oslog.RTL_RM_ID__c = currentUser.Employee_ID__c;
                
                if (mapNamedCredentiallURL.get('WsCallMeNow_Avaya') != null) {
                    oslog.RTL_Service_Name__c = mapNamedCredentiallURL.get('WsCallMeNow_Avaya').Endpoint;
                }
                oslog.RTL_Is_Success__c = oslogDetail.isSuccess;
                oslog.RTL_Start_DateTime__c = oslogDetail.startTime;
                oslog.RTL_End_DateTime__c = oslogDetail.endTime;
                
                if(oslogDetail.isSuccess){
                    osLog.Remark__c = oslogDetail.errorMesssage;
                }else{
                    oslog.RTL_Error_Message__c = oslogDetail.errorMesssage;
                }

                String key = referral.Id + '_' + referral.RTL_Call_Me_Now_Request_Count__c;

                mapWebUnioslog.put(key, oslog);
                mapWebUnioslogDetail.put(key, oslogDetail);
            // }

            updateReferralList.add(referral);
        }
    }

    global void finish(Database.BatchableContext BC) {
        System.debug(':::: avayaCallListReferralBatch finish ::::');

        if(mapWebUnioslog.size() > 0){
            RTL_CampaignUtil.insertOnlineServiceLogMultiWithAttach(mapWebUnioslog, mapWebUnioslogDetail);
        }

        System.debug('updateReferralList : ' + updateReferralList);
        if(updateReferralList.size() > 0){
            update updateReferralList;
        }
    }

    private static String checkBusinessHour (String businessName, Datetime targetTime){
        BusinessHours bh = [SELECT Id FROM BusinessHours WHERE name =: businessName];
        String nextStart = BusinessHours.nextStartDate(bh.id, targetTime).addHours(7).formatGMT('dd/MM/yyyy HH:mm:ss');
        return nextStart;
    }
}