force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Skill_Master__c/Skill_Master__c.object-meta.xml
<CustomObject>
    <label>Skill Master</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Skill Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skill Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Post__c/Social_Post__c.object-meta.xml
<CustomObject>
    <label>Warroom Social Post</label>
    <nameField>
        <displayFormat>SP-{yyyy}{mm}-{00000}</displayFormat>
        <label>Social Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warroom Social Posts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Post__c/fields/Social_Post_Author__c.field-meta.xml
<CustomField>
    <fullName>Social_Post_Author__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Social Post Author</label>
    <referenceTo>Social_Post_Author__c</referenceTo>
    <relationshipName>Custom_Social_Posts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Social_Post_Author__c/Social_Post_Author__c.object-meta.xml
<CustomObject>
    <label>Social Post Author</label>
    <nameField>
        <displayFormat>SA-{YYYY}{MM}{0000}</displayFormat>
        <label>Social Post Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Post Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SocialPostMainComponentControllerTest.cls
@isTest
public with sharing class SocialPostMainComponentControllerTest {
    @isTest
    static void SocialPostMainComponentControllerTestSuccess() {
        Test.startTest();
        AppConfig__c runtrigger = new AppConfig__c();
        runtrigger.Name = 'runtrigger';
        runtrigger.Value__c = 'false';
        
        Group testGroup = new Group(Name='Post - TTB Advisory', Type='Queue');
		insert testGroup;
        System.runAs(new User(Id=UserInfo.getUserId()))
		{
            QueuesObject testQueue = new QueueSObject(QueueID = testGroup.id, SObjectType = 'Social_Post__c');
            insert testQueue;
		}

        insert runtrigger;

        Skill_Master__c skillMaster = SocialPostTriggerHandler_Test.createSkillMaster();
        insert skillMaster;

        Social_Post_Author__c socialPostAuthor = SocialPostTriggerHandler_Test.createSocialPostAuthor();
        upsert socialPostAuthor;

        Social_Post__c socialPost = SocialPostTriggerHandler_Test.createSocialPost(socialPostAuthor.id);
        insert socialPost;
        try {
            SocialPostMainComponentController.getAccountList(socialPost.Id);
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
        try {
            SocialPostMainComponentController.getPostInfo(socialPost.Id);
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
        try {
            SocialPostMainComponentController.getThreadIdentity(socialPost.Id);
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
        Test.stopTest();
    }
}