force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/RTL_Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{YY}{MM}{DD}-{000}</displayFormat>
        <label>Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Campaign__c.field-meta.xml
<CustomField>
    <fullName>RTL_Campaign__c</fullName>
    <description>used with integration to Telephony</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Campaign</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Preferred_Branch__c.field-meta.xml
<CustomField>
    <fullName>RTL_Preferred_Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>สาขาที่ไม่รับบริการคือ สาขา Flagship ได้แก่ ไอคอน สยาม (283) และ อาคารยูไนเต็ด เซ็นเตอร์ สีลม (252), ระบุ WAT เพื่อส่งให้ Investment Line, ระบุ DSA เพื่อส่งให้ Mortgage Sales</inlineHelpText>
    <label>Preferred Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Branch_and_Zone__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch_and_Zone__c</referenceTo>
    <relationshipLabel>Referral Layout</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Referral_Assignment__c.field-meta.xml
<CustomField>
    <fullName>RTL_Referral_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral Assignment</label>
    <referenceTo>RTL_Referral_Assignment__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Referral__c/fields/RTL_Send_To_Call_Me_Now_Flag__c.field-meta.xml
<CustomField>
    <fullName>RTL_Send_To_Call_Me_Now_Flag__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Send to Call Me Now Flag</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/RTL_Referral_Assignment__c.object-meta.xml
<CustomObject>
    <label>Referral Assignment</label>
    <nameField>
        <displayFormat>RTLRA-{000000}</displayFormat>
        <label>Referral Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Assignment</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Assigned_Queue_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_Assigned_Queue_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>2.1 Assigned Queue Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>RTL_Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>1.1 Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Referral_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Assigned_User_field__c.field-meta.xml
<CustomField>
    <fullName>RTL_Assigned_User_field__c</fullName>
    <label>1.2 Assigned User field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RTL_RM_Owner_Id__c</fullName>
            </value>
            <value>
                <fullName>RTL_Wealth_RM_Id__c</fullName>
            </value>
            <value>
                <fullName>RTL_Referred_By_ID__c</fullName>
            </value>
            <value>
                <fullName>RTL_Preferred_Staff__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Branch_and_Zone_Queue_User_field__c.field-meta.xml
<CustomField>
    <fullName>RTL_Branch_and_Zone_Queue_User_field__c</fullName>
    <label>2.2 Branch and Zone Queue/User field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BB_Queue_Name__c</fullName>
            </value>
            <value>
                <fullName>SE_Queue_Name__c</fullName>
            </value>
            <value>
                <fullName>Branch_Queue_Name__c</fullName>
            </value>
            <value>
                <fullName>RMC_User__c</fullName>
            </value>
            <value>
                <fullName>RTL_Wealth_RM_User__c</fullName>
            </value>
            <value>
                <fullName>RTL_Branch_Manager_User__c</fullName>
            </value>
            <value>
                <fullName>AL_Queue_Name__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Campaign__c.field-meta.xml
<CustomField>
    <fullName>RTL_Campaign__c</fullName>
    <description>used in call me now to keep queue name of call center</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Campaign</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Default_Branch_Zone_Queue_User_field__c.field-meta.xml
<CustomField>
    <fullName>RTL_Default_Branch_Zone_Queue_User_field__c</fullName>
    <description>CR to default to queue or user on branch and zone field (preferred branch on referral)</description>
    <label>3.4 Default Branch/Zone Queue/User field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BB_Queue_Name__c</fullName>
            </value>
            <value>
                <fullName>SE_Queue_Name__c</fullName>
            </value>
            <value>
                <fullName>Branch_Queue_Name__c</fullName>
            </value>
            <value>
                <fullName>RMC_User__c</fullName>
            </value>
            <value>
                <fullName>RTL_Wealth_RM_User__c</fullName>
            </value>
            <value>
                <fullName>RTL_Branch_Manager_User__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Default_For_BM__c.field-meta.xml
<CustomField>
    <fullName>RTL_Default_For_BM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>3.3 Default Branch Queue of BM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Default_Queue_Name__c.field-meta.xml
<CustomField>
    <fullName>RTL_Default_Queue_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>3.1 Default Queue Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Default_User__c.field-meta.xml
<CustomField>
    <fullName>RTL_Default_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>3.2 Default User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Referral_Assignment1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Integration_Flag__c.field-meta.xml
<CustomField>
    <fullName>RTL_Integration_Flag__c</fullName>
    <label>Integration Flag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cisco</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Referral_Field_Criteria_1__c.field-meta.xml
<CustomField>
    <fullName>RTL_Referral_Field_Criteria_1__c</fullName>
    <label>Referral Field Criteria 1</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RTL_Preferred_Branch__c</fullName>
            </value>
            <value>
                <fullName>RTL_Is_BM__c</fullName>
            </value>
            <value>
                <fullName>RTL_Wealth_RM__c</fullName>
            </value>
            <value>
                <fullName>RTL_Account_Name__c</fullName>
            </value>
            <value>
                <fullName>RTL_Owner_Segment__c</fullName>
            </value>
            <value>
                <fullName>RTL_Owner_Zone__c</fullName>
            </value>
            <value>
                <fullName>RTL_Preferred_Branch_Name__c</fullName>
            </value>
            <value>
                <fullName>RTL_Segment__c</fullName>
            </value>
            <value>
                <fullName>RTL_Privilege__c</fullName>
            </value>
            <value>
                <fullName>RTL_Sales_Amount_Per_Year__c</fullName>
            </value>
            <value>
                <fullName>RTL_Interested_Product__c</fullName>
            </value>
            <value>
                <fullName>RTL_Product_Name_txt__c</fullName>
            </value>
            <value>
                <fullName>RTL_EMP_BR_Code__c</fullName>
            </value>
            <value>
                <fullName>RTL_RM_Owner__c</fullName>
            </value>
            <value>
                <fullName>RTL_Owner_Role__c</fullName>
            </value>
            <value>
                <fullName>RTL_Type__c</fullName>
            </value>
            <value>
                <fullName>RTL_Phone1__c</fullName>
            </value>
            <value>
                <fullName>RTL_Channel_Segment__c</fullName>
            </value>
            <value>
                <fullName>RTL_Campaign_Reference__c</fullName>
            </value>
            <value>
                <fullName>RTL_Preferred_Branch_Type__c</fullName>
            </value>
            <value>
                <fullName>RTL_Product_Group__c</fullName>
            </value>
            <value>
                <fullName>Is_Flagship__c</fullName>
            </value>
            <value>
                <fullName>RTL_Product_Name__c</fullName>
            </value>
            <value>
                <fullName>RTL_Refer_Branch_Name__c</fullName>
            </value>
            <value>
                <fullName>RTL_Product_Sub_Group__c</fullName>
            </value>
            <value>
                <fullName>RTL_Product_Name_Str__c</fullName>
            </value>
            <value>
                <fullName>Assigned_Pool__c</fullName>
            </value>
            <value>
                <fullName>FNA_Have_Loan_Product__c</fullName>
            </value>
            <value>
                <fullName>RTL_Purpose__c</fullName>
            </value>
            <value>
                <fullName>RTL_Customer_Segment__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Referral_Assignment__c/fields/RTL_Referral_Type__c.field-meta.xml
<CustomField>
    <fullName>RTL_Referral_Type__c</fullName>
    <label>Referral Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refer_to_Retail</fullName>
            </value>
            <value>
                <fullName>Retail_Cross_Channel_Referral</fullName>
            </value>
            <value>
                <fullName>Refer_to_Commercial</fullName>
            </value>
            <value>
                <fullName>Refer_within_Commercial</fullName>
            </value>
            <value>
                <fullName>Retail_Order_Transaction</fullName>
            </value>
            <value>
                <fullName>Refer_from_Digital_Channel</fullName>
            </value>
            <value>
                <fullName>Refer to Commercial</fullName>
                <isActive>false</isActive>
                <label>Refer to Commercial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTL_Referral_Default_Assignment__mdt/RTL_Referral_Default_Assignment__mdt.object-meta.xml
<CustomObject>
    <label>Referral Default Assignment</label>
    <pluralLabel>Referral Default Assignments</pluralLabel>
</CustomObject>

force-app/main/default/objects/RTL_Referral_Default_Assignment__mdt/fields/Referral_record_type__c.field-meta.xml
<CustomField>
    <fullName>Referral_record_type__c</fullName>
    <label>Referral record type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refer_to_Retail</fullName>
            </value>
            <value>
                <fullName>Retail_Cross_Channel_Referral</fullName>
            </value>
            <value>
                <fullName>Refer_to_Commercial</fullName>
            </value>
            <value>
                <fullName>Refer_Within_Commercial</fullName>
            </value>
            <value>
                <fullName>Retail_Order_Transaction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RTL_ReferralAssignment.cls
public class RTL_ReferralAssignment {
    private static String KEY_ISNULL = AppConfig__c.getValues('RTL_Referral_Assignment_ISNULL').Value__c;
    private static String KEY_NOT_NULL = AppConfig__c.getValues('RTL_Referral_Assignment_NOTNULL').Value__c;
    private static List<Group> queueList = [ select Id,Name,DeveloperName from Group where Type = 'Queue' ];
    private static Map<Id,Branch_and_Zone__c> branchAndZoneList = new Map<Id,Branch_and_Zone__c>();
    Map<String,RTL_Referral_Default_Assignment__mdt> mapDefaultAssignmentList = new Map<String,RTL_Referral_Default_Assignment__mdt>();
    private static Map<Id,User> mapUserInActiveList = new Map<Id,User>();
    
    public RTL_ReferralAssignment(List<RTL_Referral__c> newList){
        System.debug('Start RTL_ReferralAssignment');
        List<String> branchAndZone = new List<String>();
        List<Id> recordtypeIdList = new List<Id>();
        List<String> assignUserIdList = new List<String>();
        List<String> recordtypeDevNameList = new List<String>();
        Map<String,RecordType> mapRecordTypeByDevName = new Map<String,RecordType>();        
        Map<Id,Id> mapRTLAssignmentByRecordTypeId = new Map<Id,Id>();
        Map<Id,RTL_Referral_Assignment__c> mapRTLAssignment = new Map<Id,RTL_Referral_Assignment__c>();

        // loop for get condition
        for( RTL_Referral__c each : newList ){
            // get record type
            if( each.RecordTypeId != null ){
                recordtypeIdList.add(each.RecordTypeId);
            }
            if( each.RTL_Preferred_Branch__c != null ){
                branchAndZone.add(each.RTL_Preferred_Branch__c);
            }
        }
        
        // create map branch and zone
        for( Branch_and_Zone__c each : RTL_ReferralAssignUtility.getBranchAndZone(branchAndZone) ){
            branchAndZoneList.put(each.Id,each);
        }

        // get record type developer name
        for( RecordType each : getRTLRecordType(recordtypeIdList).Values() ){
            recordtypeDevNameList.add(each.DeveloperName);
            System.debug('each.DeveloperName : '+each.DeveloperName);
            mapRecordTypeByDevName.put(each.DeveloperName,each);
        }

        // create map Condition RTL Assignment
        for( RTL_Referral_Assignment__c each : getConditionRTLAssignment(recordtypeDevNameList) ){
            Id recordTypeId = mapRecordTypeByDevName.get(each.RTL_Referral_Type__c).Id;
            mapRTLAssignmentByRecordTypeId.put(each.Id,recordTypeId );   
            mapRTLAssignment.put(each.Id,each);
            
            if( RTL_Utility.isNotNull(each.RTL_Assigned_User__c) ){
                assignUserIdList.add( each.RTL_Assigned_User__c );    
            }
            if( RTL_Utility.isNotNull(each.RTL_Default_User__c) ){
                assignUserIdList.add( each.RTL_Default_User__c );                 
            }
            for( RTL_Referral__c rfr : newList ){
                try{
                    if( RTL_Utility.isNotNull(each.RTL_Assigned_User_field__c) ){
                        assignUserIdList.add( String.valueOf(rfr.get(each.RTL_Assigned_User_field__c)) );    
                    }
                    if( RTL_Utility.isNotNull(each.RTL_Branch_and_Zone_Queue_User_field__c) ){
                        if( branchAndZoneList.containsKey( rfr.RTL_Preferred_Branch__c ) ){      
                            assignUserIdList.add( String.valueOf(branchAndZoneList.get( rfr.RTL_Preferred_Branch__c ).get(each.RTL_Branch_and_Zone_Queue_User_field__c)) );   
                            //assignUserIdList.add( String.valueOf(rfr.get(each.RTL_Branch_and_Zone_Queue_User_field__c)) );   
                        } 
                    }                    
                }catch( Exception e ){
                    System.debug('error : '+e.getMessage()+' '+e.getLineNumber()+' '+e.getStackTraceString());
                }  
            }     
        }

        // fiter record
        System.debug('mapRTLAssignmentByRecordTypeId : '+mapRTLAssignmentByRecordTypeId);
        if( mapRTLAssignmentByRecordTypeId.size() > 0 ){            
            mapUserInActiveList = RTL_ReferralAssignUtility.getUserList(assignUserIdList);
            //assign userInActive to RTL_ReferralAssignUtility
            RTL_ReferralAssignUtility.setUserInActiveList(mapUserInActiveList);
            for( User u : mapUserInActiveList.values() ){
                branchAndZone.add( u.RTL_Branch_Code__c );
            }
            
            //create map meta default Assignment
            for( RTL_Referral_Default_Assignment__mdt each : RTL_ReferralAssignUtility.getMetaDefaultAssignment() ){
                mapDefaultAssignmentList.put(each.Referral_record_type__c,each);
            }
            //assign defaultAssignmentList to RTL_ReferralAssignUtility
            RTL_ReferralAssignUtility.setDefaultAssignmentList(mapDefaultAssignmentList);
            
            // create map branch and zone
            for( Branch_and_Zone__c each : RTL_ReferralAssignUtility.getBranchAndZone(branchAndZone) ){
                branchAndZoneList.put(each.Id,each);
            }
            //assigh branchAndZoneList to RTL_ReferralAssignUtility
            RTL_ReferralAssignUtility.setBranchAndZoneList(branchAndZoneList);
            System.debug('newList12 : '+newList);
            for( RTL_Referral__c each : newList ){          

                for( RTL_Referral_Assignment__c eachCond : mapRTLAssignment.values() ){
                    System.debug('eachCond1 : '+eachCond);
                    if( each.RecordTypeId == mapRTLAssignmentByRecordTypeId.get(eachCond.Id) ){
                        System.debug('eachCond : '+eachCond);
                        // if is true Assgin Owner
                        if( checkCriteria(each, eachCond) ){
                            try{
                                System.debug('cond can assign : '+eachCond.Name);                                
                                each.OwnerId = RTL_ReferralAssignUtility.assignOwner(each,eachCond);
                                
                                //CR Call Me Now
    
                                //Capture assignment rule which referral is assigned
                                each.RTL_Referral_Assignment__c = eachCond.Id;
                                //If need to send this referral to Telephony
                                // ปกติตรงนี้เปิด
                                if(eachCond.RTL_Integration_Flag__c == 'Cisco' || eachCond.RTL_Integration_Flag__c == 'Avaya' ){
                                    //stamp integration flag,campaign from referral assignment to referral
                                    each.RTL_Send_To_Call_Me_Now_Flag__c = eachCond.RTL_Integration_Flag__c;
                                    each.RTL_Campaign__c = eachCond.RTL_Campaign__c;
                                    
                                }


                                // meta default assignment
                                if( each.OwnerId == null || mapUserInActiveList.containsKey(each.OwnerId) ){
                                    System.debug('assign default');
									each.OwnerId = RTL_ReferralAssignUtility.assignDefault( each,eachCond );
                                    System.debug(' : '+each.OwnerId);
                                }
                                
                                break;
                            }catch( Exception e ){
                                System.debug('error : '+e.getMessage());
                                each.addError('error default assign : '+e.getMessage() );                                
                            }                        
                        }   
                    }
                }
            }
        }
        
    }
    
    /*public Id assignOwner( RTL_Referral__c data,RTL_Referral_Assignment__c cond ){
        String tempOwner = null;
        // 1.1
        if( isNotNull(cond.RTL_Assigned_User__c) ){        	
            tempOwner = cond.RTL_Assigned_User__c;
            if( !mapUserInActiveList.containsKey(tempOwner) ){
                 return tempOwner;
            }          
        }
        
        // 1.2
        if( isNotNull(cond.RTL_Assigned_User_field__c) ){
            tempOwner = String.ValueOf(data.get(cond.RTL_Assigned_User_field__c));
            if( !mapUserInActiveList.containsKey(tempOwner) && tempOwner != null ){
                return tempOwner; 
            }
        }
        
        // 2.1
        if( isNotNull(cond.RTL_Assigned_Queue_Name__c) ){
            for( Group q : queueList ){
                if( q.DeveloperName == cond.RTL_Assigned_Queue_Name__c ){
                    return q.Id;    
                }
            }        	
        }
        
        // 2.2
        if( isNotNull(cond.RTL_Branch_and_Zone_Queue_User_field__c) ){
            if( branchAndZoneList.containsKey( data.RTL_Preferred_Branch__c ) ){
                tempOwner = String.ValueOf(branchAndZoneList.get( data.RTL_Preferred_Branch__c ).get( cond.RTL_Branch_and_Zone_Queue_User_field__c ));
                if(tempOwner != null){
                    for( Group q : queueList ){
                    	if( q.DeveloperName == tempOwner ){
                        	return q.Id;    
                    	}    
                	}
                    if( !mapUserInActiveList.containsKey( tempOwner ) ){
                        return tempOwner;  
                    }
                	
                }
                              
            }                      	
        }
        
        // 3.1
        if( isNotNull(cond.RTL_Default_Queue_Name__c) ){
            for( Group q : queueList ){
                if( q.DeveloperName == cond.RTL_Default_Queue_Name__c ){
                    return q.Id;    
                }
            }
        }
        
        // 3.2
        if( isNotNull(cond.RTL_Default_User__c) ){
            tempOwner = cond.RTL_Default_User__c;
            if( !mapUserInActiveList.containsKey( tempOwner ) ){
                return tempOwner;    
            }
        }
        System.debug('Map User Inactive '+mapUserInActiveList);
        // 3.3
        if( cond.RTL_Default_For_BM__c && mapUserInActiveList.containsKey(tempOwner) && tempOwner != null ){
            System.debug('detect inactive');
            return assignForBM( tempOwner, cond );    
        }

        //3.4  -- CR RQ-014 to be able to default to queue/user from referral preferred branch
        if( isNotNull(cond.RTL_Default_Branch_Zone_Queue_User_field__c) ){
            if( branchAndZoneList.containsKey( data.RTL_Preferred_Branch__c ) ){
                tempOwner = String.ValueOf(branchAndZoneList.get( data.RTL_Preferred_Branch__c ).get( cond.RTL_Default_Branch_Zone_Queue_User_field__c ));
                if(tempOwner != null){
                    for( Group q : queueList ){
                        if( q.DeveloperName == tempOwner ){
                            return q.Id;    
                        }    
                    }
                    if( !mapUserInActiveList.containsKey( tempOwner ) ){
                        return tempOwner;  
                    }
                    
                }
                              
            }                       
        }
        return null;
    }*/
    
    public Boolean checkCriteria(RTL_Referral__c data,RTL_Referral_Assignment__c cond){
        Boolean criteriaPass = false;
		Boolean criteriaNotNull = false;
        if( RTL_Utility.isNotNull(cond.RTL_Referral_Field_Criteria_1__c) 
           || RTL_Utility.isNotNull(cond.RTL_Referral_Field_Criteria_2__c) 
           || RTL_Utility.isNotNull(cond.RTL_Referral_Field_Criteria_3__c) 
           || RTL_Utility.isNotNull(cond.RTL_Referral_Field_Criteria_4__c) 
           || RTL_Utility.isNotNull(cond.RTL_Referral_Field_Criteria_5__c) ){
               criteriaNotNull = true;
           }
        
        if( criteriaNotNull && 
           checkCondition(cond.RTL_Referral_Field_Criteria_1__c,
                           data,
                           cond.RTL_Referral_Field_Value_1__c) 
           && checkCondition(cond.RTL_Referral_Field_Criteria_2__c,
                           data,
                           cond.RTL_Referral_Field_Value_2__c) 
          && checkCondition(cond.RTL_Referral_Field_Criteria_3__c,
                           data,
                           cond.RTL_Referral_Field_Value_3__c)
          && checkCondition(cond.RTL_Referral_Field_Criteria_4__c,
                           data,
                           cond.RTL_Referral_Field_Value_4__c)
          && checkCondition(cond.RTL_Referral_Field_Criteria_5__c,
                           data,
                           cond.RTL_Referral_Field_Value_5__c)){
        	criteriaPass = true;	       
        }
        System.debug('criteriaNotNull : '+criteriaNotNull);        
        System.debug('criteriaPass : '+criteriaPass);
       return criteriaPass;
    }
    
    public Boolean checkCondition(String cond,SObject data,String condValue){
        if( cond == null || cond == '' ){
            return true;
        }
        System.debug(data.get(cond)+'=='+condValue);
        if( condValue == KEY_NOT_NULL ){
            if( String.valueOf(data.get(cond)) != '' && String.valueOf(data.get(cond)) != null ){
                return true;    
            }    
        }
        if( condValue == KEY_ISNULL ){
            condValue = null;
        }        
        if( String.valueOf(data.get(cond)) != condValue ){
        	return false;    
        }
        return true;
    }
    
    public List<RTL_Referral_Assignment__c> getConditionRTLAssignment(List<String> recordtypeDevNameList){
        return (List<RTL_Referral_Assignment__c>)queryConditionRTLAssignment(recordtypeDevNameList);
    }
    
    public List<SObject> queryConditionRTLAssignment(List<String> recordtypeDevNameList){
        try{            
            String objectName = 'RTL_Referral_Assignment__c';
            String strQuery = 'select ';
            strQuery += RTL_Utility.queryAllField(objectName);
            
            strQuery = strQuery.substring(0,strQuery.length()-1);
            String strWhere = ' where RTL_Active_Flag__c = true and RTL_Reassign_Flag__c = false and RTL_Referral_Type__c IN :recordtypeDevNameList order by RTL_Referral_Type__c,RTL_Priority__c asc ';
            strQuery += ' from '+objectName;
            System.debug('strWhere : '+strWhere);
            strQuery += strWhere;
            System.debug('strQuery : '+strQuery);
            return Database.query(strQuery);
            
        }catch(QueryException e){
          	return new List<SObject>();  
        }
    }

    public Map<Id,RecordType> getRTLRecordType(List<Id> recordtypeIdList){
        return new Map<Id,RecordType>([ select Id,DeveloperName 
                from RecordType 
                where Id IN :recordtypeIdList  ]);
    }

}