force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>CB</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>RMC-Sales</fullName>
            </value>
            <value>
                <fullName>RMC-Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Dummy_Campaign.recordType-meta.xml
<RecordType>
    <fullName>Dummy_Campaign</fullName>
    <active>true</active>
    <label>Dummy Campaign</label>
</RecordType>

force-app/main/default/objects/CampaignMember/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_AL_response__c.field-meta.xml
<CustomField>
    <fullName>RTL_AL_response__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Yes / No</description>
    <label>Hot Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_AL_Response_Flage__c.field-meta.xml
<CustomField>
    <fullName>RTL_AL_Response_Flage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AL Response Flage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Is_Interface_Success__c.field-meta.xml
<CustomField>
    <fullName>RTL_Is_Interface_Success__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Interface Success</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Is_Send_To_HPAP__c.field-meta.xml
<CustomField>
    <fullName>RTL_Is_Send_To_HPAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Send to HPAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Marketing_Code__c.field-meta.xml
<CustomField>
    <fullName>RTL_Marketing_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Marketing Code</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Web_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>RTL_Web_Unique_ID__c</fullName>
    <description>Web Unique ID sent from web/ATM</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Web Unique ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RTL_AL_WsCampaignMemberInfoTest.cls
@isTest
public with sharing class RTL_AL_WsCampaignMemberInfoTest {
    public RTL_AL_WsCampaignMemberInfoTest() {

    }

    private static String encryptKey {
        get {
            return 'c3018e70d8b7df129e502b2e12b8e4069e5c4cbae48ed9041a1454f069233265';
            // (String)SCSMessageAPIUtil.getEncryptKey(SCSMessageAPIUtil.fetchUserSessionId(), SCSMessageAPIUtil.INTEGRATE_SYSTEM.ONEAPP);
        }
    }

    @TestSetup
    static void makeData() {
        TestUtils.createAppConfig();
        AppConfig__c appConfig = AppConfig__c.getValues('runtrigger');
        appConfig.Value__c = 'true';
        update appConfig;
        
        Id recordTypeId  = [select Id from RecordType where SobjectType = 'Campaign' and DeveloperName=: 'Dummy_Campaign' and IsActive=true ].Id;
        Campaign camp = new Campaign();
        camp.Name = 'Campaign_';
        camp.Segment__c = 'MB';
        camp.OwnerId  = UserInfo.getUserId();
        camp.RecordTypeId = Recordtypeid;
        insert camp;

        Campaign camp1 = new Campaign();
        camp1.Name = 'Campaign_1';
        camp1.Segment__c = 'MB';
        camp1.OwnerId  = UserInfo.getUserId();
        camp1.RecordTypeId = Recordtypeid;
        insert camp1;

        Lead l = new Lead(Company = 'JohnMiller', LastName = 'Mike', Status = 'Open');
        l.RTL_Branch_Code_Rpt__c = '611';
        insert l;
        Lead l1 = new Lead(Company = 'JohnMiller', LastName = 'Mike', Status = 'Open');
        l.RTL_Branch_Code_Rpt__c = '611';
        insert l1;

        Campaignmember cm = new Campaignmember();
        cm.RTL_Marketing_Code__c = 'DOUTBOUND1HN00001023';
        cm.RTL_AL_response__c = true;
        cm.Customer__c = null;
        cm.RTL_AL_Response_Flage__c = true;
        cm.RTL_Is_Send_To_HPAP__c = true;
        cm.RTL_Is_Interface_Success__c = true;
        cm.CampaignId = camp.Id;
        cm.LeadId = l.Id;
        insert cm;

        Campaignmember cm1 = new Campaignmember();
        cm1.RTL_Web_Unique_ID__c = 'DOUTBOUND1HN00001023';
        cm1.RTL_AL_response__c = true;
        cm1.Customer__c = null;
        cm1.RTL_AL_Response_Flage__c = true;
        cm1.RTL_Is_Send_To_HPAP__c = true;
        cm1.RTL_Is_Interface_Success__c = true;
        cm1.CampaignId = camp1.Id;
        cm1.LeadId = l1.Id;
        insert cm1;
    }

    @IsTest
    static void testGetCarInfoByMarketingCode(){
        Test.startTest();
        User sfextapi = [SELECT Id FROM user WHERE name = 'sfextapi'];
        System.runAs(sfextapi){
            RTL_AL_WsCampaignMemberInfo webserviceClass = new RTL_AL_WsCampaignMemberInfo();
            System.debug(encryptKey);
            RestRequest request = new RestRequest();
            request.resourcePath = '0';
            request.requestUri = URL.getSalesforceBaseUrl().toExternalForm() + '/data/V1.0/CampaignMember/getInfoByMarketingCode/*';
            request.httpMethod = 'POST';
            request.requestBody = Blob.valueOf(String.valueOf(SCSMessageAPIUtil.encryptMessageWithKey(JSON.serialize(
                new Map<String, Object>{
                    'marketingCode' => 'DOUTBOUND1HN00001023'
                    
                    }
                
            ), encryptKey)));
            RestContext.request = request;
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseCallMeNow(200, encryptKey));
            RTL_AL_WebserviceAbstract.SCSReqRes responseEncrypt = RTL_AL_WsCampaignMemberInfo.getCarInfo();
        }
        Test.stopTest();
    }
    @IsTest
    static void testGetCarInfoByWebUniqueId(){
        Test.startTest();
        User sfextapi = [SELECT Id FROM user WHERE name = 'sfextapi'];
        System.runAs(sfextapi){
            RTL_AL_WsCampaignMemberInfo webserviceClass = new RTL_AL_WsCampaignMemberInfo();
            System.debug(encryptKey);
            RestRequest request = new RestRequest();
            request.resourcePath = '0';
            request.requestUri = URL.getSalesforceBaseUrl().toExternalForm() + '/data/V1.0/CampaignMember/getInfoByMarketingCode/*';
            request.httpMethod = 'POST';
            request.requestBody = Blob.valueOf(String.valueOf(SCSMessageAPIUtil.encryptMessageWithKey(JSON.serialize(
                new Map<String, Object>{
                    'webUniqueId' => 'DOUTBOUND1HN00001023'
                    
                    }
                
            ), encryptKey)));
            RestContext.request = request;
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseCallMeNow(200, encryptKey));
            RTL_AL_WebserviceAbstract.SCSReqRes responseEncrypt = RTL_AL_WsCampaignMemberInfo.getCarInfo();
        }
        Test.stopTest();
    }

    @IsTest
    static void testGetCarInfoByException(){
        Test.startTest();
        User sfextapi = [SELECT Id FROM user WHERE name = 'sfextapi'];
        System.runAs(sfextapi){
            RTL_AL_WsCampaignMemberInfo webserviceClass = new RTL_AL_WsCampaignMemberInfo();
            System.debug(encryptKey);
            RestRequest request = new RestRequest();
            request.resourcePath = '0';
            request.requestUri = URL.getSalesforceBaseUrl().toExternalForm() + '/data/V1.0/CampaignMember/getInfoByMarketingCode/*';
            request.httpMethod = 'POST';
            request.requestBody = Blob.valueOf(String.valueOf(SCSMessageAPIUtil.encryptMessageWithKey(JSON.serialize(
                new Map<String, Object>{
                    'webUniqueId' => 'DOUTBOUND1HN00001024'
                    
                    }
                
            ), encryptKey)));
            RestContext.request = request;
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseCallMeNow(200, encryptKey));
            RTL_AL_WebserviceAbstract.SCSReqRes responseEncrypt = RTL_AL_WsCampaignMemberInfo.getCarInfo();
        }
        Test.stopTest();
    }
}