force-app/main/default/objects/AppConfig__c/AppConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ค่า configuration  use in apex trigger and apex controller</description>
    <label>AppConfig</label>
</CustomObject>

force-app/main/default/objects/AppConfig__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>ค่า  config</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>ค่า  config</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <label>Visit Plan / Report</label>
    <nameField>
        <displayFormat>Visit-{0000}</displayFormat>
        <label>Visit Report No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Plan / Reports</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report__c/fields/Categories__c.field-meta.xml
<CustomField>
    <fullName>Categories__c</fullName>
    <label>Categories</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre boarding</fullName>
            </value>
            <value>
                <fullName>On-boarding</fullName>
            </value>
            <value>
                <fullName>Post-boarding</fullName>
            </value>
            <value>
                <fullName>SE Default</fullName>
            </value>
            <value>
                <fullName>Initiatives</fullName>
            </value>
            <value>
                <fullName>Float Charge</fullName>
            </value>
            <value>
                <fullName>RPD Team Face To Face Visit</fullName>
            </value>
            <value>
                <fullName>RPD Team Telephone Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Customer_name__c.field-meta.xml
<CustomField>
    <fullName>Customer_name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>notEqual</operation>
            <value>Disqualified Prospect</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visit Plan / Reports</relationshipLabel>
    <relationshipName>Call_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Date_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Visit__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Visit Plan Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Main_purpose__c.field-meta.xml
<CustomField>
    <fullName>Main_purpose__c</fullName>
    <label>Main purpose</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Categories__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>First visit</fullName>
            </value>
            <value>
                <fullName>Find Oppty</fullName>
            </value>
            <value>
                <fullName>Product pitching / Present Product</fullName>
            </value>
            <value>
                <fullName>Follow up sales</fullName>
            </value>
            <value>
                <fullName>Submit proposal</fullName>
            </value>
            <value>
                <fullName>Sign Agreement</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>On-boarding new product</fullName>
            </value>
            <value>
                <fullName>Credit review</fullName>
            </value>
            <value>
                <fullName>Service review for credit product (Interview cust need)</fullName>
            </value>
            <value>
                <fullName>Service review for non-credit product (Interview cust need)</fullName>
            </value>
            <value>
                <fullName>Boost u% (Business Volume)</fullName>
            </value>
            <value>
                <fullName>Hand over (New RM)</fullName>
            </value>
            <value>
                <fullName>Debt collection</fullName>
            </value>
            <value>
                <fullName>Relationship</fullName>
            </value>
            <value>
                <fullName>Sell product</fullName>
            </value>
            <value>
                <fullName>Doc. Collection</fullName>
            </value>
            <value>
                <fullName>Control quality &amp; Follow up debt</fullName>
            </value>
            <value>
                <fullName>Make relationship</fullName>
            </value>
            <value>
                <fullName>Solve problem</fullName>
            </value>
            <value>
                <fullName>CB</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>BB.</fullName>
            </value>
            <value>
                <fullName>SE.</fullName>
            </value>
            <value>
                <fullName>แนะนำตัว / นัดหมายขอเข้าพบลูกค้า</fullName>
            </value>
            <value>
                <fullName>เข้าพบเพื่อสร้างความสัมพันธ์กับลูกค้า</fullName>
            </value>
            <value>
                <fullName>นำเสนอขายผลิตภัณฑ์และบริการ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Sub_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sub_Purpose__c</fullName>
    <label>Sub Purpose</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Main_purpose__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Annual Review</fullName>
            </value>
            <value>
                <fullName>QRS</fullName>
            </value>
            <value>
                <fullName>EWS</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Executive lunch / dinner</fullName>
            </value>
            <value>
                <fullName>Senior visit</fullName>
            </value>
            <value>
                <fullName>Event by TMB</fullName>
            </value>
            <value>
                <fullName>Event by Customer</fullName>
            </value>
            <value>
                <fullName>EWS Customer</fullName>
            </value>
            <value>
                <fullName>DPD Customer</fullName>
            </value>
            <value>
                <fullName>NPL Customer</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Others (ให้ระบุ)</fullName>
            </value>
            <value>
                <fullName>Cash_X-Sell Payment &amp; CollectionTxn</fullName>
            </value>
            <value>
                <fullName>Cash_One Bank &amp; Chq. Solution</fullName>
            </value>
            <value>
                <fullName>Cash_Acquire New for Domestic txn</fullName>
            </value>
            <value>
                <fullName>Cash_Fleet Card</fullName>
            </value>
            <value>
                <fullName>Cash_Payroll Cash Card</fullName>
            </value>
            <value>
                <fullName>Loan_Working Capital Boost Utz.</fullName>
            </value>
            <value>
                <fullName>Loan_Setup New Limit , 8 Key Industries</fullName>
            </value>
            <value>
                <fullName>CreditFee_LG Campaign , Valued Group</fullName>
            </value>
            <value>
                <fullName>CreditFee_LG Campaign , Welcome Group</fullName>
            </value>
            <value>
                <fullName>CreditFee_SetupNewLTLoan, ProjectFinance</fullName>
            </value>
            <value>
                <fullName>CreditFee_SetupNewLimit, 3FocusIndustry</fullName>
            </value>
            <value>
                <fullName>TF&amp;FX_Increase TF Limit</fullName>
            </value>
            <value>
                <fullName>TF&amp;FX_Realign TOD to TF Limits</fullName>
            </value>
            <value>
                <fullName>TF&amp;FX_OTT Campaign</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Status_Code__c/Status_Code__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Error,Warning message handler</description>
    <label>Status Code</label>
</CustomObject>

force-app/main/default/objects/Status_Code__c/fields/Events__c.field-meta.xml
<CustomField>
    <fullName>Events__c</fullName>
    <description>Events trigger for this message.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Events</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status_Code__c/fields/Status_Message__c.field-meta.xml
<CustomField>
    <fullName>Status_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VisitCheckInCheckOutTest.cls
@isTest
public class VisitCheckInCheckOutTest {
    
    static account acct;
    
    static testmethod void visitcheckinout()
    {
        test.startTest();
        insert new AppConfig__c(name = 'runtrigger', value__c = 'TRUE');
        insert new Status_Code__c(name = '7011', Status_Message__c = 'sm', Events__c = 'ev');
        
        TestUtils.createAppConfigRetailtoComm();
        
        acct = testutils.createAccounts(1, 'fname', 'Individual', true).get(0);
            acct.ownerid = userinfo.getUserId();
            update acct;

        call_report__c cr = new call_report__c(Customer_name__c = acct.id,Date_of_Visit__c = date.today(),Categories__c = 'Pre boarding',Main_purpose__c = 'First visit',Sub_Purpose__c = 'Credit');
            cr.RecordTypeId = [select id from recordtype where name ='Visit Plan / Report'].get(0).id;
            insert cr;
        call_report__c cr2 = new call_report__c(Customer_name__c = acct.id,Date_of_Visit__c = date.today(),Categories__c = 'Pre boarding',Main_purpose__c = 'First visit',Sub_Purpose__c = 'Credit');
            cr.RecordTypeId = [select id from recordtype where name ='Visit Plan / Report'].get(0).id;
            insert cr2;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(cr);
        PageReference checkinoutpage = Page.VisitGetGeoLocation;
        checkinoutpage.getParameters().put('id',cr.id);
        checkinoutpage.getParameters().put('typeVisit','in');
        checkinoutpage.getParameters().put('lat','10');
        checkinoutpage.getParameters().put('lon','10');
        Test.setCurrentPage(checkinoutpage);
        VisitCheckInCheckOut vc = new VisitCheckInCheckOut(sc);
        pagereference pr1 = vc.RedirectCheckInOut();
        pagereference pr2 = vc.BackPage();
        vc.CheckIn();
        vc.CheckIn();
        vc.CheckOut();
        vc.CheckOut();
        
        ApexPages.StandardController sc2 = new ApexPages.StandardController(cr2);
        PageReference checkinoutpage2 = Page.VisitGetGeoLocation;
        checkinoutpage2.getParameters().put('id',cr2.id);
        checkinoutpage2.getParameters().put('typeVisit','out');
        checkinoutpage2.getParameters().put('lat','');
        checkinoutpage2.getParameters().put('lon','');
        Test.setCurrentPage(checkinoutpage2);
        VisitCheckInCheckOut vc2 = new VisitCheckInCheckOut(sc2);
        pr1 = vc2.RedirectCheckInOut();
        pr2 = vc2.BackPage();
        vc2.CheckOut();
        
        test.stopTest();
    }
    
}