force-app/main/default/objects/Social_Post_Negative__c/Social_Post_Negative__c.object-meta.xml
<CustomObject>
    <label>Social Post Negative</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Social Post Negative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Post Negatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Post_Negative__c/fields/Posted_Date__c.field-meta.xml
<CustomField>
    <fullName>Posted_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Posted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ClearSocialNegativeScheduler.cls
global without sharing class ClearSocialNegativeScheduler implements Schedulable {
    

    global void execute(SchedulableContext ctx) {
        ClearSocialNegative();
    }

    private void ClearSocialNegative() {
        List<Social_Post_Negative__c> socialPostNegativeListForDelete = [SELECT id, Posted_Date__c FROM Social_Post_Negative__c where Posted_Date__c < LAST_N_DAYS:30];
        System.debug('Deleted records [' + socialPostNegativeListForDelete + ']');
        
        delete socialPostNegativeListForDelete;
    }
}