force-app/main/default/objects/CampaignMember/fields/RTL_Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>RTL_Contact_Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Re-attempt</fullName>
            </value>
            <value>
                <fullName>Not Contact</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_isBatchUpdateCampaignMember__c.field-meta.xml
<CustomField>
    <fullName>RTL_isBatchUpdateCampaignMember__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag for allow update campaign member when campaign expired.</description>
    <label>isBatchUpdateCampaignMember</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Offer_Result__c.field-meta.xml
<CustomField>
    <fullName>RTL_Offer_Result__c</fullName>
    <formula>IF (TEXT(RTL_Contact_Status__c) = &apos;New&apos;, 
$Label.RTL_Campaign_Member_Filter_Offer_Pending, 
  IF( OR( TEXT(RTL_Contact_Status__c) = &apos;Unused&apos;, 
          TEXT(RTL_Contact_Status__c) = &apos;Close&apos;,
          RTL_Count_Offer_Product__c  = 0),
    &apos;N/A&apos;,
    IF( RTL_Count_Interest__c+RTL_Count_Not_Interest__c+RTL_Count_NA__c+RTL_Count_Referred__c &lt; RTL_Count_Offer_Product__c ,
        $Label.RTL_Campaign_Member_Filter_Offer_Pending ,
             IF( RTL_Count_Interest__c&gt;0 ,
             $Label.RTL_Campaign_Member_Filter_Offer_Interest,
             IF( RTL_Count_Referred__c&gt;0 ,
             $Label.RTL_Campaign_Member_Filter_Offer_Referred,
                IF( RTL_Count_Not_Interest__c &gt;0,
                $Label.RTL_Campaign_Member_Filter_Offer_NotInterest,
                &apos;N/A&apos;
                )
             )
           )
    )
  )
)</formula>
    <label>Offer Result</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Offer_Result_Eng__c.field-meta.xml
<CustomField>
    <fullName>RTL_Offer_Result_Eng__c</fullName>
    <formula>IF (TEXT(RTL_Contact_Status__c) = &apos;New&apos;, 
&apos;Pending&apos;,
IF( OR( TEXT(RTL_Contact_Status__c) = &apos;Unused&apos;, 
TEXT(RTL_Contact_Status__c) = &apos;Close&apos;, 
RTL_Count_Offer_Product__c = 0), 
&apos;N/A&apos;, 
IF( RTL_Count_Interest__c+RTL_Count_Not_Interest__c+RTL_Count_NA__c+RTL_Count_Referred__c &lt; RTL_Count_Offer_Product__c , 
&apos;Pending&apos;, 
IF( RTL_Count_Interest__c&gt;0 , 
&apos;Interested&apos;, 
IF( RTL_Count_Referred__c &gt;0 ,
&apos;Referred&apos;,
IF( RTL_Count_Not_Interest__c&gt;0, 
&apos;Not Interested&apos;, 
&apos;N/A&apos; 
) 
) 
) 
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Offer Result Eng</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_OfferResult_Product_1__c.field-meta.xml
<CustomField>
    <fullName>RTL_OfferResult_Product_1__c</fullName>
    <label>Offer Result for Product-1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RTL_OfferResultPRD</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_OfferResult_Product_2__c.field-meta.xml
<CustomField>
    <fullName>RTL_OfferResult_Product_2__c</fullName>
    <label>Offer Result for Product-2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RTL_OfferResultPRD</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_OfferResult_Product_3__c.field-meta.xml
<CustomField>
    <fullName>RTL_OfferResult_Product_3__c</fullName>
    <label>Offer Result for Product-3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RTL_OfferResultPRD</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_OfferResult_Product_4__c.field-meta.xml
<CustomField>
    <fullName>RTL_OfferResult_Product_4__c</fullName>
    <label>Offer Result for Product-4</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RTL_OfferResultPRD</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_OfferResult_Product_5__c.field-meta.xml
<CustomField>
    <fullName>RTL_OfferResult_Product_5__c</fullName>
    <label>Offer Result for Product-5</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RTL_OfferResultPRD</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Product_Group_1__c.field-meta.xml
<CustomField>
    <fullName>RTL_Product_Group_1__c</fullName>
    <label>Product Group 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BANCASSURANCE</fullName>
                <label>Bancassurance</label>
            </value>
            <value>
                <fullName>CREDIT CARD &amp; RDC</fullName>
                <label>Credit Card &amp; RDC</label>
            </value>
            <value>
                <fullName>DEPOSIT</fullName>
                <label>Deposit</label>
            </value>
            <value>
                <fullName>INVESTMENT</fullName>
                <label>Investment</label>
            </value>
            <value>
                <fullName>LOAN</fullName>
                <label>Loan</label>
            </value>
            <value>
                <fullName>OTHERS</fullName>
                <label>Others</label>
            </value>
            <value>
                <fullName>AUTO LOAN</fullName>
                <label>Auto Loan</label>
            </value>
            <value>
                <fullName>LOAN RETENTION</fullName>
                <isActive>false</isActive>
                <label>LOAN RETENTION</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Product_Group_2__c.field-meta.xml
<CustomField>
    <fullName>RTL_Product_Group_2__c</fullName>
    <label>Product Group 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BANCASSURANCE</fullName>
                <label>Bancassurance</label>
            </value>
            <value>
                <fullName>CREDIT CARD &amp; RDC</fullName>
                <label>Credit Card &amp; RDC</label>
            </value>
            <value>
                <fullName>DEPOSIT</fullName>
                <label>Deposit</label>
            </value>
            <value>
                <fullName>INVESTMENT</fullName>
                <label>Investment</label>
            </value>
            <value>
                <fullName>LOAN</fullName>
                <label>Loan</label>
            </value>
            <value>
                <fullName>OTHERS</fullName>
                <label>Others</label>
            </value>
            <value>
                <fullName>AUTO LOAN</fullName>
                <label>Auto Loan</label>
            </value>
            <value>
                <fullName>LOAN RETENTION</fullName>
                <isActive>false</isActive>
                <label>LOAN RETENTION</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Product_Group_3__c.field-meta.xml
<CustomField>
    <fullName>RTL_Product_Group_3__c</fullName>
    <label>Product Group 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BANCASSURANCE</fullName>
                <label>Bancassurance</label>
            </value>
            <value>
                <fullName>CREDIT CARD &amp; RDC</fullName>
                <label>Credit Card &amp; RDC</label>
            </value>
            <value>
                <fullName>DEPOSIT</fullName>
                <label>Deposit</label>
            </value>
            <value>
                <fullName>INVESTMENT</fullName>
                <label>Investment</label>
            </value>
            <value>
                <fullName>LOAN</fullName>
                <label>Loan</label>
            </value>
            <value>
                <fullName>OTHERS</fullName>
                <label>Others</label>
            </value>
            <value>
                <fullName>AUTO LOAN</fullName>
                <label>Auto Loan</label>
            </value>
            <value>
                <fullName>LOAN RETENTION</fullName>
                <isActive>false</isActive>
                <label>LOAN RETENTION</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Product_Group_4__c.field-meta.xml
<CustomField>
    <fullName>RTL_Product_Group_4__c</fullName>
    <label>Product Group 4</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BANCASSURANCE</fullName>
                <label>Bancassurance</label>
            </value>
            <value>
                <fullName>CREDIT CARD &amp; RDC</fullName>
                <label>Credit Card &amp; RDC</label>
            </value>
            <value>
                <fullName>DEPOSIT</fullName>
                <label>Deposit</label>
            </value>
            <value>
                <fullName>INVESTMENT</fullName>
                <label>Investment</label>
            </value>
            <value>
                <fullName>LOAN</fullName>
                <label>Loan</label>
            </value>
            <value>
                <fullName>OTHERS</fullName>
                <label>Others</label>
            </value>
            <value>
                <fullName>AUTO LOAN</fullName>
                <label>Auto Loan</label>
            </value>
            <value>
                <fullName>LOAN RETENTION</fullName>
                <isActive>false</isActive>
                <label>LOAN RETENTION</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Product_Group_5__c.field-meta.xml
<CustomField>
    <fullName>RTL_Product_Group_5__c</fullName>
    <label>Product Group 5</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BANCASSURANCE</fullName>
                <label>Bancassurance</label>
            </value>
            <value>
                <fullName>CREDIT CARD &amp; RDC</fullName>
                <label>Credit Card &amp; RDC</label>
            </value>
            <value>
                <fullName>DEPOSIT</fullName>
                <label>Deposit</label>
            </value>
            <value>
                <fullName>INVESTMENT</fullName>
                <label>Investment</label>
            </value>
            <value>
                <fullName>LOAN</fullName>
                <label>Loan</label>
            </value>
            <value>
                <fullName>OTHERS</fullName>
                <label>Others</label>
            </value>
            <value>
                <fullName>AUTO LOAN</fullName>
                <label>Auto Loan</label>
            </value>
            <value>
                <fullName>LOAN RETENTION</fullName>
                <isActive>false</isActive>
                <label>LOAN RETENTION</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/RTL_OfferResultPRD.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>Interested</fullName>
    </customValue>
    <customValue>
        <fullName>Not Interested</fullName>
    </customValue>
    <customValue>
        <fullName>Not Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Referred</fullName>
    </customValue>
    <description>List of Offer result for Campaign Product on Retail Campaign</description>
    <masterLabel>Campaign Product Offer Result</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RTL_UpdateCampaignMemberOfferResultBatch.cls
global class RTL_UpdateCampaignMemberOfferResultBatch implements Database.Batchable<sObject> {
	
	private String query;
	private List<ID> expiringCampaignId;
	static final String PENDING_TEXT = 'Pending';
	static final String CONTACT_STATUS_NEW = 'New';
	static final String CONTACT_STATUS_UNUSED = 'Unused';
	
	global RTL_UpdateCampaignMemberOfferResultBatch(List<ID> expiringCampaignIdArg) {

		expiringCampaignId = expiringCampaignIdArg;
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator([SELECT id,RTL_Offer_Result__c,RTL_OfferResult_Product_1__c,RTL_OfferResult_Product_2__c,
                        RTL_OfferResult_Product_3__c,RTL_OfferResult_Product_4__c,
                        RTL_OfferResult_Product_5__c,
                        RTL_Product_Group_1__c,RTL_Product_Group_2__c,RTL_Product_Group_3__c,
                        RTL_Product_Group_4__c,RTL_Product_Group_5__c,
                        RTL_Contact_Status__c,RTL_Offer_Result_Eng__c
                        FROM CampaignMember
                        WHERE CampaignId in :expiringCampaignId
                        AND ( RTL_Offer_Result_Eng__c = :PENDING_TEXT OR RTL_Contact_Status__c = :CONTACT_STATUS_NEW )
         ]);

		// Query to get both campaign member
	}

   	global void execute(Database.BatchableContext BC, List<CampaignMember> scope) {
	
		 for(CampaignMember cm : scope)
		 {
		 	// All camapign member that campaign expired and offer result and contact status are in scope to change data
		 	//Update for Offer Result Product to N/A if campaing offer result is pending
		 	if( cm.RTL_Offer_Result_Eng__c == PENDING_TEXT )
		 	{

			 	if( cm.RTL_Product_Group_1__c != '' && cm.RTL_Product_Group_1__c != null && cm.RTL_OfferResult_Product_1__c == null )
	            {
	                cm.RTL_OfferResult_Product_1__c = 'N/A';
	            }

	            if( cm.RTL_Product_Group_2__c != '' && cm.RTL_Product_Group_2__c != null && cm.RTL_OfferResult_Product_2__c == null )
	            {
	                cm.RTL_OfferResult_Product_2__c = 'N/A';
	            }

	            if( cm.RTL_Product_Group_3__c != '' && cm.RTL_Product_Group_3__c != null && cm.RTL_OfferResult_Product_3__c == null )
	            {
	                cm.RTL_OfferResult_Product_3__c = 'N/A';
	            }

	            if( cm.RTL_Product_Group_4__c != '' && cm.RTL_Product_Group_4__c != null && cm.RTL_OfferResult_Product_4__c == null )
	            {
	                cm.RTL_OfferResult_Product_4__c = 'N/A';
	            }
	            if( cm.RTL_Product_Group_5__c != '' && cm.RTL_Product_Group_5__c != null && cm.RTL_OfferResult_Product_5__c == null )
	            {
	                cm.RTL_OfferResult_Product_5__c = 'N/A';
	            }

	        }

	        // Update contact status to unused if contact status is new
	        if( cm.RTL_Contact_Status__c == CONTACT_STATUS_NEW )
	        {
	        	cm.RTL_Contact_Status__c = CONTACT_STATUS_UNUSED;
	        }

	        cm.RTL_isBatchUpdateCampaignMember__c = true;
		 }

		//Set Update force flag
   		//RTL_CampaignMemberUtil.setCampaignForceUpdateCampaignMemberFlag( expiringCampaignId , true );

		update scope;

		//RTL_CampaignMemberUtil.setCampaignForceUpdateCampaignMemberFlag( expiringCampaignId , false );

	}
	
	global void finish(Database.BatchableContext BC) {
		system.debug('Finish Batch update campaign member Offer Status');
	}
	
}