force-app/main/default/objects/CampaignMember/fields/RTL_Assigned_Agent__c.field-meta.xml
<CustomField>
    <fullName>RTL_Assigned_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaign_Members1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Assigned_Branch__c.field-meta.xml
<CustomField>
    <fullName>RTL_Assigned_Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Branch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Branch_and_Zone__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Branch_and_Zone__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Assigned_Channel__c.field-meta.xml
<CustomField>
    <fullName>RTL_Assigned_Channel__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Assigned Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Channel_Outbound__c.field-meta.xml
<CustomField>
    <fullName>RTL_Channel_Outbound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Assigned Outbound</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>RTL_Contact_Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Re-attempt</fullName>
            </value>
            <value>
                <fullName>Not Contact</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_Offer_Result_Eng__c.field-meta.xml
<CustomField>
    <fullName>RTL_Offer_Result_Eng__c</fullName>
    <formula>IF (TEXT(RTL_Contact_Status__c) = &apos;New&apos;, 
&apos;Pending&apos;,
IF( OR( TEXT(RTL_Contact_Status__c) = &apos;Unused&apos;, 
TEXT(RTL_Contact_Status__c) = &apos;Close&apos;, 
RTL_Count_Offer_Product__c = 0), 
&apos;N/A&apos;, 
IF( RTL_Count_Interest__c+RTL_Count_Not_Interest__c+RTL_Count_NA__c+RTL_Count_Referred__c &lt; RTL_Count_Offer_Product__c , 
&apos;Pending&apos;, 
IF( RTL_Count_Interest__c&gt;0 , 
&apos;Interested&apos;, 
IF( RTL_Count_Referred__c &gt;0 ,
&apos;Referred&apos;,
IF( RTL_Count_Not_Interest__c&gt;0, 
&apos;Not Interested&apos;, 
&apos;N/A&apos; 
) 
) 
) 
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Offer Result Eng</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/RTL_TMB_Campaign_Source__c.field-meta.xml
<CustomField>
    <fullName>RTL_TMB_Campaign_Source__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TMB Campaign Source</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/recordTypes/Retail_Campaign_Member.recordType-meta.xml
<RecordType>
    <fullName>Retail_Campaign_Member</fullName>
    <active>true</active>
    <description>Campaign Member Record Type for Retail</description>
    <label>Retail Campaign Member</label>
</RecordType>

force-app/main/default/classes/RTL_SchedulerEmailCMAssignedToAdmin.cls
global class RTL_SchedulerEmailCMAssignedToAdmin implements Schedulable {
	
	global void execute(SchedulableContext sc) {
		//String query = 'SELECT Id, Name FROM CampaignMember WHERE RTL_Assigned_Channel__c != \'Outbound\' AND RTL_Assigned_Branch__c = null AND RTL_Assigned_Agent__c = null AND RTL_TMB_Campaign_Source__c IN (\'Web\',\'ATM Request\',\'Call me now\')';
        
		String query = 'SELECT Id, Name FROM CampaignMember WHERE RTL_Assigned_Channel__c != \'Outbound\'';
		query = query + ' AND RTL_Assigned_Branch__c = null';
        query = query + ' AND RTL_Assigned_Agent__c = null';
        query = query + ' AND Campaign.Status != \'Expired\'';
       	query = query + ' AND RTL_Contact_Status__c = \'New\' ';
        query = query + ' AND RTL_Offer_Result_Eng__c  = \'Pending\'';
		query = query + ' AND RecordType.DeveloperName = \'Retail_Campaign_Member\'';
		query = query + ' AND RTL_Channel_Outbound__c = false';

        RTL_BatchEmailCMAssignAdmin emailBatch = new RTL_BatchEmailCMAssignAdmin(query);
        Id BatchProcessId = Database.ExecuteBatch(emailBatch);	
	}

	
}