force-app/main/default/objects/AsyncQueue__c/AsyncQueue__c.object-meta.xml
<CustomObject>
    <label>AsyncQueue</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>AsyncQueue Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AsyncQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commercial_Forecast_App_Config__mdt/Commercial_Forecast_App_Config__mdt.object-meta.xml
<CustomObject>
    <label>Commercial Forecast App Config</label>
    <pluralLabel>Commercial Forecast App Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Long_Term_Loan_Repayment__c/Long_Term_Loan_Repayment__c.object-meta.xml
<CustomObject>
    <label>Long Term Loan Repayment</label>
    <nameField>
        <displayFormat>LT-Loan-Repay-{0000000000}</displayFormat>
        <label>Long Term Loan Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Long Term Loan Repayments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Long_Term_Loan_Repayment__c/fields/Account_Suffix_Ref__c.field-meta.xml
<CustomField>
    <fullName>Account_Suffix_Ref__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Account/Suffix/Ref</label>
    <length>33</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Long_Term_Loan_Repayment__c/fields/AccountId_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>AccountId_Due_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>AccountId Due Date</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Long_Term_Loan_Repayment__c/fields/Next_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Due_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Next Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Long_Term_Loan_Repayment__c/fields/Repayment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Repayment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Monthly_Forecast_Input__c/Monthly_Forecast_Input__c.object-meta.xml
<CustomObject>
    <label>Monthly Forecast Input</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Monthly Forecast Input Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Forecast Inputs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Forecast_Input__c/fields/Account_Suffix_Ref__c.field-meta.xml
<CustomField>
    <fullName>Account_Suffix_Ref__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Account/Suffix/Ref</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_Forecast_Input__c/fields/Long_Term_Loan_Repayment__c.field-meta.xml
<CustomField>
    <fullName>Long_Term_Loan_Repayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Long Term Loan Repayment</label>
    <referenceTo>Long_Term_Loan_Repayment__c</referenceTo>
    <relationshipLabel>Monthly Forecast Inputs</relationshipLabel>
    <relationshipName>Monthly_Forecast_Inputs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Forecast_Input__c/fields/YearMonthAcctSuffRef__c.field-meta.xml
<CustomField>
    <fullName>YearMonthAcctSuffRef__c</fullName>
    <description>Use for backend process</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>YearMonthAcctSuffRef</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/updateLongtermRepaymentBatch.cls
public class updateLongtermRepaymentBatch implements Database.Batchable<sObject> {
    final static Boolean RunForcastNIMonthlyBatch {
        get{
            if(RunForcastNIMonthlyBatch == null){
                RunForcastNIMonthlyBatch = false;

                Commercial_Forecast_App_Config__mdt mc = Commercial_Forecast_App_Config__mdt.getInstance('Forecast_Auto_run_NI_monthly_batch');

                if(mc != null && mc.Value__c != null){
                    RunForcastNIMonthlyBatch = mc.Value__c.toLowercase() == 'true';
                }
            }
            return RunForcastNIMonthlyBatch;
        }set;
    }

    final static Integer NIMonthlyBatchSize{
        get{
            if(NIMonthlyBatchSize == null){
                NIMonthlyBatchSize = 1000;

                Commercial_Forecast_App_Config__mdt mc = Commercial_Forecast_App_Config__mdt.getInstance('Forecast_NI_Monthly_Batch_size');

                if(mc != null && mc.Value__c != null){
                    NIMonthlyBatchSize = Integer.valueOf(mc.Value__c);
                }
            }
            return NIMonthlyBatchSize;
        }set;
    }

    final static Id RTExistingRepay {
        get{
            if(RTExistingRepay == null){
                RTExistingRepay = Schema.Sobjecttype.Monthly_Forecast_Input__c.getRecordTypeInfosByName().get('Existing Repay').getRecordTypeId();
            }
            return RTExistingRepay;
        }set;
    }
    
	private String query;

    Datetime batchDate = datetime.now();
    Datetime batchEndTime;

    Integer  recordsSuccessful = 0;
    Integer  recordsFailed = 0;

    Map<String, String> mapMFIErrorMsg = new Map<String, String>();
    Map<String, Monthly_Forecast_Input__c> mapKeyErrorMFI = new Map<String, Monthly_Forecast_Input__c>();

    // public updateLongtermRepaymentBatch(String q) {
    //     query = q;
    // }

    public updateLongtermRepaymentBatch() {
        Commercial_Forecast_App_Config__mdt mc = [SELECT Id, DeveloperName, Value__c, Description__c FROM Commercial_Forecast_App_Config__mdt WHERE DeveloperName = 'Forecast_Long_Term_Batch_Query' LIMIT 1];

        if(mc != null && mc.Value__c != null){
            query = mc.Value__c;
        }else{
            query = 'SELECT Id, OwnerId, Name, Next_Due_Date__c, Repayment_Amount__c, As_of_Date__c, AccountId_Due_Date__c, Account_Suffix_Ref__c FROM Long_Term_Loan_Repayment__c WHERE LastmodifiedDate = TODAY ORDER BY AccountId_Due_Date__c';
        }
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug(':::::::::::::::start:::::::::::::::');
        batchDate = datetime.now();
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Long_Term_Loan_Repayment__c> scope){
        System.debug(':::::::::::::::execute:::::::::::::::');

        System.debug(limits.getHeapSize() + ' of ' + limits.getLimitHeapSize());
        System.debug('Query rows:' + limits.getQueryRows() + ' of ' + limits.getLimitQueryRows());

        map<String, Monthly_Forecast_Input__c> mapMFI = new map<String, Monthly_Forecast_Input__c>();

        for(Long_Term_Loan_Repayment__c LTScope : scope){
            Date dueDate = LTScope.Next_Due_Date__c;
            String year = String.valueOf(dueDate.year());
            String month = dueDate.month() < 10 ? '0' + String.valueOf(dueDate.month()) : String.valueOf(dueDate.month());
            Monthly_Forecast_Input__c MFI = new Monthly_Forecast_Input__c();

            MFI.YearMonthAcctSuffRef__c = year + month + LTScope.Account_Suffix_Ref__c;
            MFI.Long_Term_Loan_Repayment__c = LTScope.Id;

            String weekNo = GenerateForecastInputBatchUtil.getWeekNumber(dueDate);
            MFI.put('Repay_Due_Amount_Week' + weekNo + '__c', LTScope.Repayment_Amount__c);

            mapMFI.put(MFI.YearMonthAcctSuffRef__c, MFI);

            System.debug(limits.getHeapSize() + ' of ' + limits.getLimitHeapSize());
            System.debug('Query rows:' + limits.getQueryRows() + ' of ' + limits.getLimitQueryRows());
        }

        System.debug(limits.getHeapSize() + ' of ' + limits.getLimitHeapSize());
        System.debug('Query rows:' + limits.getQueryRows() + ' of ' + limits.getLimitQueryRows());

        if(mapMFI.size() > 0){
            Database.UpsertResult[] results = Database.upsert(mapMFI.values(), Monthly_Forecast_Input__c.YearMonthAcctSuffRef__c, false);
            for(Integer index = 0, size = results.size(); index < size; index++) {
                if(results[index].isSuccess()) {
                    recordsSuccessful++;
                }else{
                    recordsFailed++;
                    String errormsg = '';
                    for(Database.Error err : results[index].getErrors()) {
                        errormsg += err.getStatusCode() + ':' + err.getMessage();
                    }
                    mapMFIErrorMsg.put(mapMFI.values()[index].YearMonthAcctSuffRef__c, errormsg);
                    mapKeyErrorMFI.put(mapMFI.values()[index].YearMonthAcctSuffRef__c, mapMFI.values()[index]);
                }
            }
        }

        System.debug(limits.getHeapSize() + ' of ' + limits.getLimitHeapSize());
        System.debug('Query rows:' + limits.getQueryRows() + ' of ' + limits.getLimitQueryRows());
    }

    public void finish(Database.BatchableContext bc){
        System.debug(':::::::::::::::finish:::::::::::::::');
        batchEndTime = datetime.now();

        String filename = 'Forecast Update Long Term Loan Repayment' + String.Valueof(Datetime.now());
        String sObjectName = 'Monthly_Forecast_Input__c';
        List<String> sendToEmail = new List<String>();
        sendToEmail.add('CRM Admin 2');

        String csvHeaderStr = 'YearMonthAcctSuffRef__c, Long_Term_Loan_Repayment__c, ErrorMessage\n';
        String CSV_BODY = '';

        for (String mfikey : mapMFIErrorMsg.keySet()) {
            CSV_BODY += mapKeyErrorMFI.get(mfikey).YearMonthAcctSuffRef__c 
                        + ',' + mapKeyErrorMFI.get(mfikey).Long_Term_Loan_Repayment__c
                        + ',' + mapMFIErrorMsg.get(mfikey) + '\n';
        }

        if(recordsFailed + recordsSuccessful > 0){
            RTL_BatchEmailService.SendFinishDailyBatchSummaryEmail(batchDate, batchDate, batchEndTime, recordsSuccessful, recordsFailed, filename, sobjectName, sendToEmail, CSV_BODY, '', '', csvHeaderStr, '', '', '');
        }

        if(RunForcastNIMonthlyBatch){
            NIMonthlyPerformanceSyncBatch instance = new NIMonthlyPerformanceSyncBatch();

            AsyncQueue__c job = AsyncApexFrameworkUtil.CreateBatchQueue(instance, NIMonthlyBatchSize, 'NIMonthlyPerformanceSyncBatch', null);

            insert job;
        }
    }
}