force-app/main/default/objects/AcctPlan_Questionnaire_Template__c/AcctPlan_Questionnaire_Template__c.object-meta.xml
<CustomObject>
    <label>AcctPlan Questionnaire Template</label>
    <nameField>
        <displayFormat>QT-{000000}</displayFormat>
        <label>AcctPlan Questionnaire Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AcctPlan Questionnaire Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanCompanyProfile__c/AcctPlanCompanyProfile__c.object-meta.xml
<CustomObject>
    <description>Account Plan Company Profile</description>
    <label>Account Plan Company Profile</label>
    <nameField>
        <displayFormat>Com-{0000000}</displayFormat>
        <label>AcctPlanCompanyProfile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Company Profile</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanForeignTrans__c/AcctPlanForeignTrans__c.object-meta.xml
<CustomObject>
    <label>Account Plan Foreign Trans</label>
    <nameField>
        <displayFormat>FT-{000000}</displayFormat>
        <label>Account Plan Foreign Trans Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Foreign Trans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanForeignTrans__c/fields/AcctPlanWallet__c.field-meta.xml
<CustomField>
    <fullName>AcctPlanWallet__c</fullName>
    <label>Account Plan Wallet</label>
    <referenceTo>AcctPlanWallet__c</referenceTo>
    <relationshipLabel>Account Plan Foreign Trans</relationshipLabel>
    <relationshipName>Account_Plan_Foreign_Trans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctPlanForeignTrans__c/fields/AmtPerYear__c.field-meta.xml
<CustomField>
    <fullName>AmtPerYear__c</fullName>
    <description>Amount per year (Baht)</description>
    <inlineHelpText>Amount per year (Baht)</inlineHelpText>
    <label>Amount per year (THB)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AcctPlanForeignTrans__c/fields/FXMarginStg__c.field-meta.xml
<CustomField>
    <fullName>FXMarginStg__c</fullName>
    <description>FX margin (THB)</description>
    <inlineHelpText>FX margin (THB)</inlineHelpText>
    <label>FX margin (THB)</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AcctPlanForeignTrans__c/fields/HedgingRatio__c.field-meta.xml
<CustomField>
    <fullName>HedgingRatio__c</fullName>
    <description>Hedging ratio (%) : Actual or to be</description>
    <inlineHelpText>Hedging ratio (%) : Actual or to be</inlineHelpText>
    <label>Hedging ratio (%) : Actual or to be</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AcctPlanWallet__c/AcctPlanWallet__c.object-meta.xml
<CustomObject>
    <label>Account Plan Wallet</label>
    <nameField>
        <displayFormat>Wallet-{000000}</displayFormat>
        <label>Account Plan Wallet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Wallet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanWallet__c/fields/AcctPlanCompanyProfile__c.field-meta.xml
<CustomField>
    <fullName>AcctPlanCompanyProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Plan Company Profile of Wallet</description>
    <label>Account Plan Company Profile</label>
    <referenceTo>AcctPlanCompanyProfile__c</referenceTo>
    <relationshipLabel>Account Plan Wallet</relationshipLabel>
    <relationshipName>Account_Plan_Wallet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountPlanWalletDomainIVTest.cls
@isTest
global class AccountPlanWalletDomainIVTest {
    static{
        TestUtils.createAppConfig();
        TestUtils.createStatusCode(); 
        TestUtils.createDisqualifiedReason(); 
        TestUtils.CreateAddress();
        AccountPlanTestUtilities.getAcctPlanMode();
        AccountPlanWalletTestUtilities.createStandardFee();
        AccountPlanWalletTestUtilities.createBanks();
        AccountPlanWalletTestUtilities.createCurrencies();
         List<sObject> ls = 
            Test.loadData(AcctPlan_Questionnaire_Template__c.sObjectType /*API Name*/, 'AcctPlanQuestionnaireTemplate' /*Static Resource Name*/);
   
         }
    
    static testmethod void AccountPlanWalletDomainIVTest(){
      
         User SalesOwner = AccountPlanTestUtilities.createUsers(1, 'RM', 'PortfolioMngTest', 'portfoliomng@tmbbank.com', AccountPlanTestUtilities.TMB_RM_PROFILE_ID,false, true).get(0);
        
          List<Account> AccountList = AccountPlanTestUtilities.createAccounts(1, 'GroupPro', 'Individual', SalesOwner.id, true, true);
       List<Account> acctForCompanyProfile = new List<Account>();
        acctForCompanyProfile.add(AccountList.get(0));
        system.runAs(SalesOwner){
        List<AcctPlanCompanyProfile__c> comprofileList = AccountPlanTestUtilities.createCompanyProfileByAccount(acctForCompanyProfile, true);
         AcctPlanCompanyProfile__c comprofile = comprofileList.get(0);
                 
        AcctPlanWallet__c AcctPlanwallet = AccountPlanWalletTestUtilities.createAccountPlanWallet(comprofile.id, true);
        
        
        AccountPlanWalletTestUtilities.createWalletCurrency(AcctPlanwallet.id);
        AccountPlanWalletTestUtilities.createQuestionnaireTemplate();
        AccountPlanWalletTestUtilities.createWalletDomainITables(AcctPlanwallet.id);
                PageReference walletViewPage = Page.AccountPlanWalletDomainIIView;
               walletViewPage.getParameters().put('CompanyID',comprofile.id);
               walletViewPage.getParameters().put('GroupID',AcctPlanwallet.id);
               walletViewPage.getParameters().put('WalletID',AcctPlanwallet.id);
               walletViewPage.getParameters().put('mode','default');
               Test.setCurrentPage(walletViewPage); 
             AccountPlanWalletDomainIVViewCtrl AcctPlanwalletDoaminIV = new AccountPlanWalletDomainIVViewCtrl();
            AcctPlanwalletDoaminIV.updateSumOfWalletFXFeePerYear();
            AcctPlanwalletDoaminIV.loadCurrency();
            AcctPlanwalletDoaminIV.loadforeign();
            AcctPlanwalletDoaminIV.loadquestionnaire();
            AcctPlanwalletDoaminIV.save();
            AcctPlanwalletDoaminIV.cancel();
            AcctPlanwalletDoaminIV.EditPage();
            AcctPlanwalletDoaminIV.ExisitngLongTermLoan();
            AcctPlanwalletDoaminIV.CapitalExpenditurePlan();
            
            AcctPlanForeignTrans__c fortrans = new AcctPlanForeignTrans__c();
            fortrans.AcctPlanWallet__c = acctplanwallet.id;
            fortrans.HedgingRatio__c = 10;
            fortrans.AmtPerYear__c = 10;
            fortrans.FXMarginStg__c = 0.1;
            insert fortrans;
            AcctPlanwalletDoaminIV.loadforeign();
            
            }
        
        
        
     
        
    
    }
    
}