force-app/main/default/objects/PDPA_Activity_Log__c/PDPA_Activity_Log__c.object-meta.xml
<CustomObject>
    <label>PDPA Activity Log</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000}</displayFormat>
        <label>PDPA Activity Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PDPA Activity Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PDPA_Activity_Log__c/fields/Create_Date__c.field-meta.xml
<CustomField>
    <fullName>Create_Date__c</fullName>
    <description>Create Date will stamp date upon a click of the &quot;Print&quot; button or &quot;Email&quot; button</description>
    <encryptionScheme>None</encryptionScheme>
    <label>วันที่พนักงานให้บริการ</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/PurgePDPAActivityLogBatchTest.cls
@isTest
public class PurgePDPAActivityLogBatchTest {
    public PurgePDPAActivityLogBatchTest() {

    }

    @isTest
    public static void testExecuteBatch() {
        PDPA_Activity_Log__c activity = new PDPA_Activity_Log__c(
                Create_Date__c = Datetime.now()
            );
            
        insert activity;

        
        Test.startTest();
            Date backDate = System.Today().addDays(1);
            String q = 'SELECT Id FROM PDPA_Activity_Log__c WHERE CreatedDate <=: BACKDATE';

            database.executebatch(new PurgePDPAActivityLogBatch(q, backDate), 2000);
        Test.stopTest();
    }
}