force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Using for RMC allows to create opportunity on other&apos;s existing customer.</description>
    <label>Create Opportunity Privilege</label>
</CustomObject>

force-app/main/default/objects/AcctPlanCompanyPort__c/AcctPlanCompanyPort__c.object-meta.xml
<CustomObject>
    <label>Account Plan Company Port</label>
    <nameField>
        <displayFormat>CP-{0000000}</displayFormat>
        <label>AcctPlanCompanyPort Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Company Ports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanCompanyPort__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AcctPlanCompanyPorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctPlanCompanyPort__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctPlanCompanyPort__c/fields/Account_Plan_Company_Profile__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_Company_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan Company Profile</label>
    <referenceTo>AcctPlanCompanyProfile__c</referenceTo>
    <relationshipName>AcctPlanCompanyPorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctPlanCompanyPort__c/fields/Account_Plan_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan Portfolio</label>
    <referenceTo>AcctPlanPortfolio__c</referenceTo>
    <relationshipName>AcctPlanCompanyPorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctPlanCompanyPort__c/fields/Target_NI_By_RM__c.field-meta.xml
<CustomField>
    <fullName>Target_NI_By_RM__c</fullName>
    <label>Target NI By RM</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AcctPlanCompanyPort__c/fields/Wallet__c.field-meta.xml
<CustomField>
    <fullName>Wallet__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Snp shoot for customer wallet</description>
    <label>Wallet</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AcctPlanCompanyProfile__c/AcctPlanCompanyProfile__c.object-meta.xml
<CustomObject>
    <description>Account Plan Company Profile</description>
    <label>Account Plan Company Profile</label>
    <nameField>
        <displayFormat>Com-{0000000}</displayFormat>
        <label>AcctPlanCompanyProfile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Company Profile</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanCompanyProfile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Account</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>notEqual</operation>
            <value>Disqualified Prospect</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plan Company Profile</relationshipLabel>
    <relationshipName>Account_Plan_Company_Profile</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctPlanCompanyProfile__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <description>Name of the customer</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>Name of the customer</inlineHelpText>
    <label>Customer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctPlanCompanyProfile__c/fields/AcctPlanGroup__c.field-meta.xml
<CustomField>
    <fullName>AcctPlanGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Plan Group</description>
    <label>Account Plan Group</label>
    <referenceTo>AcctPlanGroupProfile__c</referenceTo>
    <relationshipLabel>Account Plan Company Profile</relationshipLabel>
    <relationshipName>Account_Plan_Company_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctPlanCompanyProfile__c/fields/Wallet__c.field-meta.xml
<CustomField>
    <fullName>Wallet__c</fullName>
    <description>Wallet</description>
    <label>Wallet</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AcctPlanContribution__c/AcctPlanContribution__c.object-meta.xml
<CustomObject>
    <description>Account Plan Contribution</description>
    <label>Account Plan Contribution</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>AcctPlanContribution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan Contribution</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanContribution__c/fields/Account_Plan_Company_Profile__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan_Company_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Plan Company Profile</description>
    <label>Account Plan Company Profile</label>
    <referenceTo>AcctPlanCompanyProfile__c</referenceTo>
    <relationshipLabel>Account Plan Company Profile</relationshipLabel>
    <relationshipName>Account_Plan_Company_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctPlanGroupProfile__c/AcctPlanGroupProfile__c.object-meta.xml
<CustomObject>
    <description>Account Plan Group Profile</description>
    <label>Account Plan Group Profile</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>AcctPlan Group Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan Group Profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountPlanCompanyPortSelector.cls
public without sharing class AccountPlanCompanyPortSelector {
        
    private static string  selectAllAccountInPortfolioId(){
        return  ' SELECT Id, Account__c, Account_Plan_Portfolio__c '+
                ' FROM AcctPlanCompanyPort__c '+
                ' Where  Account_Plan_Portfolio__c  IN :  acctPlanPortFolioIds ';
    } 
    
    private static string  selectCompanyPortByPortfolioIdAndAccountId(){
        return  ' SELECT Id, Account__c, Account_Plan_Portfolio__c '+
                ' FROM AcctPlanCompanyPort__c '+
                ' Where Account_Plan_Portfolio__c =: portfolioId and Account__c =: accountId ';
    }
    
    
    
    private static string selectAllCompanyProfileUnderGroupByGroupProfolioId(){
    	//groupProfileId    
    	return   'SELECT Account__c, AccountName__c, AcctPlanGroup__c , AcctPlanGroup__r.Name   '
				+'FROM AcctPlanCompanyProfile__c                                                      '
				+'WHERE AcctPlanGroup__c  IN : groupProfileId                                         ';
   
    }
    
    
    public static  List<AcctPlanCompanyProfile__c> getAllCompanyProfileUnderGroupByGroupProfolioId(Set<Id> groupProfileId){
        
        if(groupProfileId == null || groupProfileId.size() < 1 )
            throw new AccountPlanCompanyPortSelectorException('Set of groupProfileId  Cannot be null');
        string sql = selectAllCompanyProfileUnderGroupByGroupProfolioId();
        system.debug('::: sql' + sql);
        return (List<AcctPlanCompanyProfile__c>) Database.query(sql);         
    } 
    
    
    
    public static  List<AcctPlanCompanyPort__c> getAllAccountInPortfolioIds(Set<Id> acctPlanPortFolioIds){
        
        if(acctPlanPortFolioIds == null || acctPlanPortFolioIds.size() < 1 )
            throw new AccountPlanCompanyPortSelectorException('Set of acctPlanPortFolioIds  Cannot be null');
        string sql = selectAllAccountInPortfolioId();
        system.debug('::: sql' + sql);
        return (List<AcctPlanCompanyPort__c>) Database.query(sql);         
    } 
    
    public static  AcctPlanCompanyPort__c getCompanyPortByPortfolioIdAndAccountId(Id portfolioId, Id accountId){
        
        if(portfolioId == null || accountId == null )
            throw new AccountPlanCompanyPortSelectorException('Set of portfolioId or accountId Cannot be null');
        string sql = selectCompanyPortByPortfolioIdAndAccountId();
        system.debug('::: sql' + sql);
		List<AcctPlanCompanyPort__c> ret = Database.query(sql); 
		if (ret.size() > 0)
		{
			return ret[0];
		}


        return null;
    } 
    
    
    
     private static string  selectAllCompanyPortUnderGroupByGroupProfolioId(){
        return  
               '    SELECT Id, Account__c, Account_Name__c,   '
               +'    Name, Wallet__c, Target_NI_By_RM__c,  '
               +'    Account_Plan_Portfolio__c, Account_Plan_Company_Profile__c  '
               +'    FROM AcctPlanCompanyPort__c '
               +'    where Account_Plan_Company_Profile__r.AcctPlanGroup__c = : groupId ';
    } 
    
    public static  List<AcctPlanCompanyPort__c> getAllCompanyPortUnderGroupByGroupProfolioId(Id groupId){
        
        if(groupId == null  )
            throw new AccountPlanCompanyPortSelectorException('groupId Cannot be null');
        string sql = selectAllCompanyPortUnderGroupByGroupProfolioId();
        system.debug('::: sql' + sql);
        return (List<AcctPlanCompanyPort__c>) Database.query(sql);         
    } 
    
    private static string selectTargetNIByRMById(){
        return  ' Select Id, Target_NI_By_RM__c, Account_Plan_Company_Profile__c From AcctPlanCompanyPort__c Where Account_Plan_Company_Profile__c IN :  companyProfileIds ';
    } 
    public static  List<AcctPlanCompanyPort__c> getTargetNIByRMById(Set<Id> companyProfileIds){
        
        if(companyProfileIds == null || companyProfileIds.size() < 1 )
            throw new AccountPlanCompanyPortSelectorException('Set of companyProfileIds Cannot be null');
        string sql = selectTargetNIByRMById();
        system.debug('::: sql' + sql);
        return (List<AcctPlanCompanyPort__c>) Database.query(sql);
        
    } 
    
    
    
    
    // Exception
    public class AccountPlanCompanyPortSelectorException extends Exception{   
    }
}