force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Using for RMC allows to create opportunity on other&apos;s existing customer.</description>
    <label>Create Opportunity Privilege</label>
</CustomObject>

force-app/main/default/objects/Product_Fee__c/Product_Fee__c.object-meta.xml
<CustomObject>
    <description>Store Fee, Volume, No. of Transaction by Product</description>
    <label>PF Product Fee Volume</label>
    <nameField>
        <displayFormat>PFF-{0000000}</displayFormat>
        <label>PF Product Fee Volume No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PF Product Fee Volume</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Fee__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PF Product Fee Volume</relationshipLabel>
    <relationshipName>PF_Product_Fee_Volume</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Fee__c/fields/Data_Source__c.field-meta.xml
<CustomField>
    <fullName>Data_Source__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Data Source</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Fee__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Group</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_NIM__c/Product_NIM__c.object-meta.xml
<CustomObject>
    <description>Store NIMc, NIMd by Product</description>
    <label>PF Product NIM</label>
    <nameField>
        <displayFormat>PFN-{000000}</displayFormat>
        <label>PF Product NIM No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PF Product NIM</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_NIM__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PF Product NIM</relationshipLabel>
    <relationshipName>PF_Product_NIM</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Product_Performance__c/Product_Performance__c.object-meta.xml
<CustomObject>
    <description>Store Product Performance retrieve from DWH</description>
    <label>Product Performance</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>Product Performance No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Performance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Performance</relationshipLabel>
    <relationshipName>Product_Performance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Product_Performance__c/fields/As_Of_Date__c.field-meta.xml
<CustomField>
    <fullName>As_Of_Date__c</fullName>
    <description>As of Date (Monthly)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>As Of Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Performance__c/fields/Product_Domain__c.field-meta.xml
<CustomField>
    <fullName>Product_Domain__c</fullName>
    <formula>TEXT(Product_Hierachy_Code__r.Product_Domain__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Performance__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Using this group to determine Loan/Liability</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Group</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Performance__c/fields/Product_Hierachy_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Hierachy_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Hierachy Code</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Performance</relationshipLabel>
    <relationshipName>Product_Performance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Trans_Risk__c/Product_Trans_Risk__c.object-meta.xml
<CustomObject>
    <label>Product Trans Risk</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Trans Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Transaction Risk</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Trans_Risk__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Transaction Risk</relationshipLabel>
    <relationshipName>Product_Transaction_Risk</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/ProductTransactionRisk2Test.cls
@isTest
public class ProductTransactionRisk2Test {
    
    static{
        TestUtils.createAppConfig();
        TestUtils.createStatusCode(); 
        TestUtils.createDisqualifiedReason(); 
		TestUtils.createObjUserPermission();
        TestInit.createCustomSettingTriggerMsg();
    }
    public static testmethod void performanceReportTest(){
        Account acct = TestUtils.createAccounts(1, 'PerformanceRe', 'Individual', true).get(0);
        List<Product2> prodList = new List<Product2>();
        Product2 prod1 = new Product2();
        prod1.Name = 'Prod1';
        prod1.Product_Domain__c = 'Deposit';
        
        Product2 prod2 = new Product2();
        prod2.Name = 'Prod2';
        prod2.Product_Domain__c = 'Funding';
        
        Product2 prod3 = new Product2();
        prod3.Name = 'Prod3';
        prod3.Product_Domain__c = 'Risk';
        
        prodList.add(prod1);
        prodList.add(prod2);
        prodList.add(prod3);
        insert prodList;
        Date todayDate = Date.today();
        
        Product_Trans_Risk__c prodTransRisk = new Product_Trans_Risk__c();
        prodTransRisk.Account__c = acct.id;
        prodTransRisk.As_of_Date__c = todayDate;
        insert prodTransRisk;
        
        List<Product_Fee__c> pfList = new List<Product_Fee__c>();
        Product_Fee__c pf1 = new Product_Fee__c();
        pf1.customer__c = acct.id;
        pf1.Data_Source__c = 'TV';
        pf1.As_Of_Date__c = todayDate;
        
        Product_Fee__c pf2 = new Product_Fee__c();
        pf2.customer__c = acct.id;
        pf2.Data_Source__c = 'TF';
        pf2.As_Of_Date__c = todayDate;
        
        pfList.add(pf1);
        pfList.add(pf2);
        insert pfList;
        
        List<Product_NIM__c> nimList = new List<Product_NIM__c>();
        Product_NIM__c nim1 = new Product_NIM__c();
        nim1.As_Of_Date__c = todayDate;
        nim1.Customer__c = acct.id;
        Product_NIM__c nim2 = new Product_NIM__c();
        nim2.As_Of_Date__c = todayDate;
        nim2.Customer__c = acct.id;
        
        nimList.add(nim1);
        nimList.add(nim2);
        
        insert nimList;
        
        List<Product_Performance__c> perfList = new List<Product_Performance__c>();
        Product_Performance__c perf1 = new Product_Performance__c();
        perf1.Product_Hierachy_Code__c = prod1.id;
        perf1.As_Of_Date__c = todayDate;
        perf1.Account__c = acct.id;
        
        Product_Performance__c perf2 = new Product_Performance__c();
        perf2.Product_Hierachy_Code__c = prod2.id;
        perf2.As_Of_Date__c = todayDate;
        perf2.Account__c = acct.id;
        perf2.Product_Group__c = 'Loan';
        
        Product_Performance__c perf3 = new Product_Performance__c();
        perf3.Product_Hierachy_Code__c = prod2.id;
        perf3.As_Of_Date__c = todayDate;
        perf3.Account__c = acct.id;
        perf3.Product_Group__c = 'Liability';
        
        Product_Performance__c perf4 = new Product_Performance__c();
        perf4.Product_Hierachy_Code__c = prod3.id;
        perf4.As_Of_Date__c = todayDate;
        perf4.Account__c = acct.id;
        perf4.Product_Group__c = 'Loan';
        
        Product_Performance__c perf5 = new Product_Performance__c();
        perf5.Product_Hierachy_Code__c = prod3.id;
        perf5.As_Of_Date__c = todayDate;
        perf5.Account__c = acct.id;
        perf5.Product_Group__c = 'Liability';
        
        perfList.add(perf1);
        perfList.add(perf2);
        perfList.add(perf3);
        perfList.add(perf4);
        perfList.add(perf5);
        insert perfList;
        
        PageReference pr = Page.Performance_Report2;
        pr.getParameters().put('id',acct.id);
            
        Test.setCurrentPage(pr);
        
        Test.startTest();
        	ApexPages.StandardController stdController = new ApexPages.StandardController(acct);
			ProductTransactionRisk2 productTransRisk = new ProductTransactionRisk2(stdController);   
        	productTransRisk.getProductTransRisk();
        	productTransRisk.getTradeFinanceVolumn();
            productTransRisk.getTradeFinanceFee();
        	productTransRisk.getProductInfoDepositInvestment();
        	productTransRisk.getProductInfoFundingBorrowing();
        	productTransRisk.getProductInfoFundingBorrowingLiability();
        	productTransRisk.getProductInfoRiskProtectionLiability();
        	productTransRisk.getProductInfoRiskProtectionLoan();
        Test.stopTest();
    }
    
}