force-app/main/default/objects/AsyncRequest__c/AsyncRequest__c.object-meta.xml
<CustomObject>
    <description>CXM log request detail</description>
    <label>AsyncRequest</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>AsyncRequest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AsyncRequest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncRequest__c/fields/Aborted__c.field-meta.xml
<CustomField>
    <fullName>Aborted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aborted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CalloutRequest__c/CalloutRequest__c.object-meta.xml
<CustomObject>
    <description>CXM log request - response</description>
    <label>CalloutRequest</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CalloutRequest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CalloutRequest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalloutRequest__c/fields/AsyncRequest__c.field-meta.xml
<CustomField>
    <fullName>AsyncRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AsyncRequest</label>
    <referenceTo>AsyncRequest__c</referenceTo>
    <relationshipLabel>CalloutRequest</relationshipLabel>
    <relationshipName>CalloutRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CalloutRequest__c/fields/CalloutHandlerName__c.field-meta.xml
<CustomField>
    <fullName>CalloutHandlerName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CalloutHandler Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalloutRequest__c/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RequestId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalloutRequest__c/fields/Response_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Response_Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalloutRequest__c/fields/Response_Description__c.field-meta.xml
<CustomField>
    <fullName>Response_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Response_Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CalloutRequest__c/fields/Sent__c.field-meta.xml
<CustomField>
    <fullName>Sent__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CalloutRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>KO</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CXMClearLogBatchTest.cls
@isTest
public class CXMClearLogBatchTest {
    Static testmethod void CXMClearLogBatch_Test(){

        AsyncRequest__c asyncReq = new AsyncRequest__c();
        asyncReq.IsSuccess__c = false;
        asyncReq.Aborted__c = true;
        insert asyncReq;   

        CalloutRequest__c calloutReq = new CalloutRequest__c();
        calloutReq.RequestId__c = String.valueOf(datetime.now());
        calloutReq.Response_Description__c = 'MuleSoft unexpected error: Timeout exceeded';
        calloutReq.Status__c = 'Failed';
        calloutReq.Sent__c = datetime.now();
        calloutReq.Response_Code__c = '1001';
        calloutReq.CalloutHandlerName__c = 'CXMCalloutHandler';
        calloutReq.AsyncRequest__c =  asyncReq.Id;
        insert calloutReq;  

        Date lastNDay = Date.today().addDays(1) ;
        String errorLogCalloutRequestQuery = 'SELECT Id,CreatedDate  FROM CalloutRequest__c WHERE Status__c =\'Failed\' AND CreatedDate < :lastNDay ';
        database.executebatch(new CXMClearLogBatch(errorLogCalloutRequestQuery, lastNDay), 2000);

        
    }
}