force-app/main/default/objects/AsyncRequest__c/AsyncRequest__c.object-meta.xml
<CustomObject>
    <description>CXM log request detail</description>
    <label>AsyncRequest</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>AsyncRequest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AsyncRequest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalloutRequest__c/CalloutRequest__c.object-meta.xml
<CustomObject>
    <description>CXM log request - response</description>
    <label>CalloutRequest</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CalloutRequest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CalloutRequest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalloutRequest__c/fields/AsyncRequest__c.field-meta.xml
<CustomField>
    <fullName>AsyncRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AsyncRequest</label>
    <referenceTo>AsyncRequest__c</referenceTo>
    <relationshipLabel>CalloutRequest</relationshipLabel>
    <relationshipName>CalloutRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CalloutRequest__c/fields/CalloutHandlerName__c.field-meta.xml
<CustomField>
    <fullName>CalloutHandlerName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CalloutHandler Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalloutRequest__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Endpoint</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CalloutRequest__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CalloutRequest__c/fields/Sent__c.field-meta.xml
<CustomField>
    <fullName>Sent__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CalloutRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>KO</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CalloutHandlerDispatcher.cls
public without sharing class CalloutHandlerDispatcher {    
    /**
    * @author Keattisak Chinburarat
    * @date 2/21/2016
    * @description Executes Apex Callout Asynchronously
    * @param Id Id of the callout request to be made
    */
    @future(callout=true)
    public static void sendAsyncCallout(Id crId)
    {       
        // Verify kill switch is not enabled
        if (ConfigService.KillSwitchEnabled) return;
        // Query for Callout Request
        CalloutRequest__c cr = [SELECT Id, AsyncRequest__c, Endpoint__c, Method__c, Timeout__c, Status__c, Sent__c,CalloutHandlerName__c FROM CalloutRequest__c WHERE Id = :crId LIMIT 1];
        // Send Callout
        sendCallout(cr);
    }
	/**
	* @author Keattisak Chinburarat
	* @date 2/23/2016
	* @description Executes Apex Callout Synchronously
	* @param CalloutRequest__c Callout request to be made
	*/
	public static void sendCallout(CalloutRequest__c cr)
	{
        if(null == cr ) return;       
        string calloutHandler =  cr.CalloutHandlerName__c;
        Type handlerType = Type.forName(calloutHandler);   
        if(handlerType!=null) {             
            // Perform HTTP Callout           
            ICalluotSOAPHandler obj = (ICalluotSOAPHandler)handlerType.NewInstance();
            obj.execute(cr);
        }         
	}  
}