force-app/main/default/objects/RTL_Campaign_To_HQ_Callout_Log__c/RTL_Campaign_To_HQ_Callout_Log__c.object-meta.xml
<CustomObject>
    <label>Campaign To HQ Callout Log</label>
    <nameField>
        <displayFormat>CCL-{0000}</displayFormat>
        <label>RTL Campaing To HQ Callout Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign To HQ Callout Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTL_Campaign_To_HQ_Callout_Log__c/fields/RTL_Campaign__c.field-meta.xml
<CustomField>
    <fullName>RTL_Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign To HQ Callout Logs</relationshipLabel>
    <relationshipName>Campaign_To_HQ_Callout_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTL_Campaign_To_HQ_Callout_Log__c/fields/RTL_Campaign_ID__c.field-meta.xml
<CustomField>
    <fullName>RTL_Campaign_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Campaign ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTL_Campaign_To_HQ_Callout_Log__c/fields/RTL_Last_Call_Date__c.field-meta.xml
<CustomField>
    <fullName>RTL_Last_Call_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Call Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RTL_Campaign_To_HQ_Callout_Log__c/fields/RTL_Status__c.field-meta.xml
<CustomField>
    <fullName>RTL_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RTL_CampaigntoHQButtonController.cls
public class RTL_CampaigntoHQButtonController {

//	private ApexPages.StandardController standardSetController;
	public List<RTL_Campaign_To_HQ_Callout_Log__c> failLogList {get;set;}
	public RTL_Campaign_To_HQ_Callout_Log__c logObj {get;set;}
	public String PageMessage {get;set;}

	public RTL_CampaigntoHQButtonController(ApexPages.StandardSetController controller) {
		//controller.setPageSize(10);
		//this.standardSetController = standardSetController;
		DateTime today = system.now();

		logObj = new RTL_Campaign_To_HQ_Callout_Log__c();

		// Get list of failed or processing more than 1 day
		failLogList = [SELECT id,Name,RTL_Status__c  , RTL_Last_Call_Date__c,RTL_Campaign_ID__c,
					RTL_Campaign__r.Name
					FROM RTL_Campaign_To_HQ_Callout_Log__c
					WHERE RTL_Status__c = 'Fail' 
					OR ( RTL_Status__c = 'Processing' AND RTL_Last_Call_Date__c != LAST_N_DAYS:1 )
					ORDER BY RTL_Last_Call_Date__c DESC
					];

	}


	public PageReference resubmitAll()
	{


		List<Id> campaignIds = new List<Id>();

		for( RTL_Campaign_To_HQ_Callout_Log__c log : failLogList )
		{
			campaignIds.add(log.RTL_Campaign_ID__c);
		}

		RTL_CampaignToHQCalloutQueue calloutProcess = new RTL_CampaignToHQCalloutQueue();

		calloutProcess.resubmitCampaigns(campaignIds);

		//ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.CONFIRM, 'Successfully Resubmit All.'));

		PageMessage = Label.RTL_Campaign_Resubmit_All_Notice;
		return null;
	}

}