force-app/main/default/objects/AcctPlanQuestionnaire__c/AcctPlanQuestionnaire__c.object-meta.xml
<CustomObject>
    <label>Account Plan Questionnaire</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Account Plan Questionnaire Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Questionnaire</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctPlanQuestionnaire__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Collection Method</fullName>
            </value>
            <value>
                <fullName>Export Collection Method</fullName>
            </value>
            <value>
                <fullName>Collection Questionnaire</fullName>
            </value>
            <value>
                <fullName>Payment Questionnaire</fullName>
            </value>
            <value>
                <fullName>Domestic Payment Method</fullName>
            </value>
            <value>
                <fullName>Payment Method Import</fullName>
            </value>
            <value>
                <fullName>Liquidity Management</fullName>
            </value>
            <value>
                <fullName>L/G issuing</fullName>
            </value>
            <value>
                <fullName>L/G Project</fullName>
            </value>
            <value>
                <fullName>AVAL &amp; Acceptance</fullName>
            </value>
            <value>
                <fullName>International bank section1</fullName>
            </value>
            <value>
                <fullName>International bank section2</fullName>
            </value>
            <value>
                <fullName>Shipping guarantee</fullName>
            </value>
            <value>
                <fullName>Request L/G</fullName>
            </value>
            <value>
                <fullName>FX Hedging Behavior</fullName>
            </value>
            <value>
                <fullName>FX Hedging experience</fullName>
            </value>
            <value>
                <fullName>Credit protection risk</fullName>
            </value>
            <value>
                <fullName>Non credit life insurance</fullName>
            </value>
            <value>
                <fullName>Non Life insurance</fullName>
            </value>
            <value>
                <fullName>Insurance Internet Banking</fullName>
            </value>
            <value>
                <fullName>Credit life insurance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuestionnaireService.cls
global class QuestionnaireService {

	@TestVisible
	private static IQuestionnaireService mock;

	@TestVisible
	private static void setMockservice(IQuestionnaireService mockService) {
		mock = mockService;
	}

	// Factory
	@TestVisible
	private static IQuestionnaireService service() {
		if (Test.isRunningTest() && mock != null) return mock;
		return(IQuestionnaireService) new QuestionnaireServiceImpl();
	}


	global static List<BusinessOppInfo> getQuestionairByWalletId(Id walletId) {
		return service().GetQuestionairByWalletId(walletId);
	}
	/********************************************
	 *    DTO Object
	 *********************************************/
	global class BusinessOppInfo {
		public BusinessOppInfo(string name) {
			this.Domain = name;
			Sectors = new Map<string, BusinessOppInfoSector> ();
		}
		public string Domain { get; set; } /*Ex. Domain I: Transactional Banking*/

		public List<BusinessOppInfoSector> Values {
			get { return Sectors.values(); }
		}



		public Map<string, BusinessOppInfoSector> Sectors { get; set; }
	}
	global class BusinessOppInfoSector {
		public BusinessOppInfoSector(string subDomain) {
			this.SubDomain = subDomain;
			this.ProductLable = new Map<string, ProductLable> ();
		}
		public string SubDomain { get; set; } /*Ex .Domestic */

		public List<ProductLable> Values {
			get { return ProductLable.values(); }
		}

		public Map<string, ProductLable> ProductLable { get; set; }
	}
	global class ProductLable {
		public ProductLable(string label, string subDomain) {
			this.SubDomain = subDomain;
			this.Label = label;
			if (subDomain == 'International' && label == 'Collection')
			{
				System.debug(':::  HIT Change Label');
				this.Label = 'Export';
			}
			this.Questionnaires = new List<AcctPlanQuestionnaire__c> ();
		}
		public string SubDomain { get; set; }
		public string Label { get; set; } /*Ex .Domestic */
		public List<AcctPlanQuestionnaire__c> Questionnaires { get; set; }
		public String getText {
			get {
				return ToText();
			}
		}


		public string ToText() {
			Map<string, string> checkdupp = new Map<string, string> ();
			//suport special case
			integer countInternationalbanksection1 = 0;
			integer countInternationalbanksection2 = 0;
			boolean isfirst = true;
			string val = '';
			for (AcctPlanQuestionnaire__c item : Questionnaires) {
				if (item.Segment__c == 'International bank section1') countInternationalbanksection1++;
				if (item.Segment__c == 'International bank section2') countInternationalbanksection2++;
				if (item.Opportunity__c != null && item.Opportunity__c != '') {
					if (!checkdupp.containsKey(item.Opportunity__c)) {
						checkdupp.put(item.Opportunity__c, item.Opportunity__c);
						if (countInternationalbanksection1 == 2) {
							System.debug('::: >>>> countInternationalbanksection1 >>>>>>');
							if (isfirst && (item.Opportunity__c != null && item.Opportunity__c != '')) {
								isfirst = false;
								val += item.Opportunity__c;
							}
							else if (!isfirst && (item.Opportunity__c != null && item.Opportunity__c != '')) {
								val += ',<br />' + item.Opportunity__c;
							}
						}
						else if (countInternationalbanksection2 == 2) {
							System.debug('::: >>>> countInternationalbanksection2 >>>>>>');
							if (isfirst && (item.Opportunity__c != null && item.Opportunity__c != '')) {
								isfirst = false;
								val += item.Opportunity__c;
							}
							else if (!isfirst && (item.Opportunity__c != null && item.Opportunity__c != '')) {
								val += ',<br />' + item.Opportunity__c;
							}
						}
						else {
							if (isfirst && (item.Opportunity__c != null && item.Opportunity__c != '')) {
								isfirst = false;
								val += item.Opportunity__c;
							}
							else if (!isfirst && (item.Opportunity__c != null && item.Opportunity__c != '')) {
								val += ',<br />' + item.Opportunity__c;
							}
						}
					}
				}
			}
			return val;
		}
	}
}